### ISSUE TITLE
JSDocs are missing for overloaded functions

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#10012]
https://developer.enonic.com/docs/xp/stable/api/lib-node#get

Declared [here](https://github.com/enonic/xp/blob/master/modules/lib/lib-node/src/main/resources/lib/xp/node.ts#L661-L679) but is missing [here](https://developer.enonic.com/jsdoc/RepoConnection.html).

**Comment by edloidas** [comment]
Lib Auth also misses several such functions.
