### ISSUE TITLE
fragment config isn't indexed

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#10047]
https://enonic.zendesk.com/agent/tickets/6286

**Comment by vbradnitski** [comment]
There is a possibility to have a page with fragments inside of other fragments on a page. Should we index the configs of all of them for the page?

**Comment by sigdestad** [comment]
> There is a possibility to have a page with fragments inside of other fragments on a page. Should we index the configs of all of them for the page?

No

**Comment by sigdestad** [comment]
NB! We must not index config of fragments within a page, only with the fragment content itself.
