### ISSUE TITLE
Add healthcheck endpoint to XP

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#10094]
We need an endpoint to expose xp instance health state. The question is what is considered to be healthy. For now, it is the availability of particular services ( which are required by the application deployer ).

**Comment by vbradnitski** [comment]
old request: [Add healthcheck endpoint to XP #9199](https://github.com/enonic/xp/issues/9199)

**Comment by rymsha** [comment]
Endpoint `/healthz` on statistics port
It only checks that elasticsearch OSGI services are available. If they are not - XP node is definitely not healthy.
