### ISSUE TITLE
exec: "gradlew.bat": cannot run executable found relative to current directory

### ISSUE THREAD

**Issue by mousavi007** [enonic/xp#10120]
hi.
i xp version 7.12.2 windows.
i create sandbox and start it successfully.
i create demo app with this command:
`enonic project create -r app-moviedb
`
from tutorial.
it create successfully.
when i want deploy app with this command:
`enonic project deploy
`
i get this error:
exec: "gradlew.bat": cannot run executable found relative to current directory

**Comment by rymsha** [comment]
https://github.com/enonic/cli-enonic/issues/408
