### ISSUE TITLE
User.modifiedTime should be optional

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#10221]
https://github.com/enonic/xp/blob/c4b556fb79772d40e140e7a7eee9e117122f02be/modules/lib/core/index.d.ts#L32C26-L32C26

**Comment by rymsha** [comment]
It is optional on update, but not optional on read, I think

**Comment by edloidas** [comment]
Appears that we have some predefined users like ANONYMOUS who don't have a modifiedTime field.
