### ISSUE TITLE
Id Provider API

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/xp#10275]
- `/api/idprovider/...` endpoint with same behavor as described in https://developer.enonic.com/docs/xp/stable/runtime/engines/idprovider-service
- in scope of `/api` calls when idproviderUrl function is called `/api/idprovider/...` url is returned
- new context parameter `idProviderBaseUrl` to configure absoluteUrl prefix for cases when vhost is used
- https://github.com/enonic/app-standardidprovider/issues/683

**Comment by rymsha** [comment]
Id Provider API was later removed as irrelevant for `/api`.
