### ISSUE TITLE
imagePlaceholder() creates objects that remain in memory

### ISSUE THREAD

**Issue by hjelmevold** [enonic/xp#10332]
If a significant amount of calls are made to a controller code that executes the following line:
```
portalLib.imagePlaceholder({width: 1500, height: 1500})
```

…the Java Heap fills up with 9MB large objects that remain in memory, eventually causing lots of Garbage Collection and high server load.

**Comment by rymsha** [comment]
Fix is to use direct PNG creation - without creation of BufferedImage (which was 9MiB in this case). It saves memory and also a bit more performant.
