### ISSUE TITLE
403 for `/site/repo/branch` for root content

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/xp#10368]
403 for `/site/repo/branch` for root content. Must be 404.

I think the problem is here https://github.com/enonic/xp/blob/master/modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/ContentResolver.java#L50

We must use 
```
Content visibleContent = visibleContent( content );
return new ContentResolverResult( visibleContent , visibleContent != null, site, siteRelativePath, contentPath.toString() );
```

instead of

```
return new ContentResolverResult( visibleContent( content ), content != null, site, siteRelativePath, contentPath.toString() );
```

**Comment by rymsha** [comment]
root content is accessible, but only for admin users - this is why it gives 403. it is certainly a special case and should be handled separately, not generally - if we want to return 404 for root content instead of 403

**Comment by alansemenov** [comment]
The problem rooted from here: https://developer.enonic.com/docs/intro#graphql_api. The guide says that opening API endpoint in the browser should give 404, but in fact it gives 403.

**Comment by rymsha** [comment]
Probably it is a mistake in a guide. XP code responsible for 403 goes back to #10085 fix.
Although it is quite hard to explain to the end user why 403 returned. Very few know that `/content` node exists but nobody should be able to access it in rendering.

Without too much of complication it is possible to shortcut 404 for `/` content - as suggested in PR #10374

**Comment by rymsha** [comment]
The question to @anatol-sialitski why this code https://github.com/enonic/app-guillotine/blob/6.2/src/main/resources/graphql/graphql.js#L65 does not handle it.
