### ISSUE TITLE
lib-content.getSiteConfig is unable to return project config like lib-portal.getSiteConfig does

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#10431]
This is at least reproduceable inside a Guillotine 7.0.3 Extension

Keep in mind that a project can't be published, so project "siteConfig" should always be fetched from draft.

```
const libPortalSiteOrProjectConfig = libPortalGetSiteConfig();
log.info('contentMetaFieldsResolver branch:%s _path:%s libPortalSiteOrProjectConfig:%s', branch, _path, toStr(libPortalSiteOrProjectConfig));

const libContentSiteOrProjectConfig = libContentGetSiteConfig({
    applicationKey: app.name,
    key: _path
});
log.info('contentMetaFieldsResolver branch:%s _path:%s libContentSiteOrProjectConfig:%s', branch, _path, toStr(libContentSiteOrProjectConfig));
```

**Comment by rymsha** [comment]
This is by design. There is a libProject allows to rich config https://developer.enonic.com/docs/xp/stable/api/lib-project#get

**Comment by rymsha** [comment]
> Keep in mind that a project can't be published, so project "siteConfig" should always be fetched from draft.

This is also not exactly true. Project is published with any published content

**Comment by ComLock** [comment]
> There is a libProject allows to reach config https://developer.enonic.com/docs/xp/stable/api/lib-project#get

I'll have to test that. The documentation doesn't show that siteConfig is returned?

Only that you can affect it with create and modify.

BTW: Does lib-project.get read siteConfig from draft?
