### ISSUE TITLE
LoginParams password is optional, but throws Parameter 'password' is required

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#10487]
```
login({
	user: 'blablabla'
});
```

Throws:

```
2024-03-27 12:54:35,459 ERROR c.e.xp.portal.impl.main.MainExecutor - Error while executing com.acme.example.tsup Application controller
java.util.concurrent.CompletionException: com.enonic.xp.resource.ResourceProblemException: Parameter 'password' is required
```

Documentation is unclear:
https://developer.enonic.com/docs/xp/stable/api/lib-auth#login

**Comment by ComLock** [comment]
Also LoginResult message should be optional

**Comment by rymsha** [comment]
It actually might be optional - when skipAuth is true

**Comment by rymsha** [comment]
PR is very welcome


> Also LoginResult message should be optional

Fixed separately https://github.com/enonic/xp/issues/10497
