### ISSUE TITLE
applyPermissions - subtree selection

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#10485]
- apply on entire tree
- apply on entire tree excluding node itself
- apply on only on specific node

**Comment by vbradnitski** [comment]
Notes:
- We always upgrade children's permissions if parent's permissions were changed (even if 'overrideChildPermissions' is set to 'false')
- The current approach allows the "apply on entire tree excluding node itself" action only with persisted permissions of the node itself. Do we want to change that?
