### ISSUE TITLE
Limit mount to site, project, webapp, admin, global

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#10545]
```
<?xml version="1.0" encoding="UTF-8"?>
<api xmlns="urn:enonic:xp:model:1.0">
<mounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="example.xsd">
    <mount>global</mount>
    <mount>any_site_endpoint</mount>
    <mount>site_endpoint</mount>
</mounts>
</api>
```

```
<xs:simpleType name="mountType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="api"/>
            <xs:enumeration value="all_sites"/>
            <xs:enumeration value="site"/>
            <xs:enumeration value="all_webapps"/>
            <xs:enumeration value="webapp"/>
            <xs:enumeration value="admin"/>
        </xs:restriction>
    </xs:simpleType>
```

`api` - available on `/api/`
`aal_site`  - available on any site `/[admin/]site/<project>/<branch>/.../some-site/.../_/...` even if application is not set on a site. It does include project root.
`site` - available on sites (and projects) where application is set. It does not include project root. Ignored if `all_sites` is also listed.
`all_webapps` - available on all webapps `/webapp/<app-name>/.../_/...`
`webapp` - available on application's webapp. Ignored if `any_webapp_endpoint` is also listed
`admin` - available on  `/admin/tool/.../_/...` NOTE: Does not enable it on `/admin/site`, `/admin`, /admin/rest`, etc

**Comment by sigdestad** [comment]
Can we add the XML descriptor spec to this task?
