### ISSUE TITLE
Configurable ElasticSearch

### ISSUE THREAD

**Issue by oc** [enonic/xp#1449]
I'd like to be able to set ElasticSearch-settings in `system.properties`. Most importantly port and bind_host for both http and transport: 

```
[elasticsearch.]http.port
[elasticsearch.]http.bind_host
...
[elasticsearch.]transport.tcp.port
[elasticsearch.]transport.bind_host
...
```

It seems like you expect all defaults, and there doesn't seem to be extension options in NodeSettingsBuilderImpl.java (and configuration of the client dao settings). 

Thanks :+1:

**Comment by srs** [comment]
Hi.

Yes, it's planned to be able to configure Elasticsearch. It's not going to be configured into system.properties, but in a more dynamic fashion where you do not need to restart the system.

**Comment by srs** [comment]
It's now configurable in 6.1.
