### ISSUE TITLE
Task 'build' not found in root project '<my projectfolder>'.

### ISSUE THREAD

**Issue by henrikakselsen** [enonic/xp#1668]
Trying to follow instructions but getting:

>FAILURE: Build failed with an exception.
>* What went wrong:
>Task 'build' not found in root project 'enonic'.

Is some step missing in the description?

**Comment by srs** [comment]
Hi.

Which folder are you running "gradle" in? You need to run it into the checkout folder where you see build.gradle file.

**Comment by srs** [comment]
So, if you check it out with `git clone git@github.com:enonic/xp.git` then you need to cd to `xp` directory before you run `gradle build`.

**Comment by srs** [comment]
Closing this issue.
