### ISSUE TITLE
Not able to scroll when installing from Enonic Market

### ISSUE THREAD

**Issue by ljl** [enonic/xp#3166]
When trying to install from Enonic Market, the list isnt scrollable. This causes items to overflow the modal and hides items falling out of the screen. See attached image

<img width="1122" alt="screen shot 2016-04-27 at 10 24 14" src="https://cloud.githubusercontent.com/assets/414079/14846178/a95410e6-0c62-11e6-955c-2b1a570635e1.png">

**Comment by alansemenov** [comment]
Hi Lasse,

This issue was fixed in version 6.5.0 of Enonic XP which was released two weeks ago.

https://github.com/enonic/xp/releases/tag/v6.5.0

Regards,
Alan

**Comment by ljl** [comment]
Ok, is it possible for you to update the container on dockerhub?

**Comment by jsi** [comment]
Good catch.  Sorry.  I have updated latest to point to 6.5.1 now.  Should be updated within a few minutes.  Of course, you can still download 6.5.1 specifically.
