### ISSUE TITLE
Bigger text in textareas

### ISSUE THREAD

**Issue by ljl** [enonic/xp#3724]
Hi.

When creating content in the admin interface, text in TextArea is bigger than TextLine and HtmlArea text. It seems like a bug. TextArea text is 15px and all other text is 12px.

<img width="248" alt="screen shot 2016-09-16 at 13 20 20" src="https://cloud.githubusercontent.com/assets/414079/18584385/bdf551b8-7c10-11e6-9b6a-7437fd6878e9.png">

Happens in 6.6.2

**Comment by jsi** [comment]
Could you share with us the content type you have used here?

**Comment by jsi** [comment]
Oooops.  I was just informed that this is a known bug, and that is has been fixed in 6.7.0.
