### ISSUE TITLE
Layouts fail when no root element in view

### ISSUE THREAD

**Issue by ljl** [enonic/xp#3729]
If you create a layout without a root element, it will give an error and display incorrectly. This is not reflected in the documentation.

This does not work:
````
  <main data-portal-region="main">
    <div data-th-each="component : ${leftRegion.components}" data-th-remove="tag">
      <div data-portal-component="${component.path}" data-th-remove="tag" />
    </div>
  </main>

  <aside data-portal-region="side">
    <div data-th-each="component : ${rightRegion.components}" data-th-remove="tag">
      <div data-portal-component="${component.path}" data-th-remove="tag" />
    </div>
  </aside>
````
And gives this error:
<img width="792" alt="screen shot 2016-09-19 at 10 39 37" src="https://cloud.githubusercontent.com/assets/414079/18626460/78698776-7e55-11e6-8efe-8cc53cab5678.png">

This works:
````
<div>
  <main data-portal-region="main">
    <div data-th-each="component : ${leftRegion.components}" data-th-remove="tag">
      <div data-portal-component="${component.path}" data-th-remove="tag" />
    </div>
  </main>

  <aside data-portal-region="side">
    <div data-th-each="component : ${rightRegion.components}" data-th-remove="tag">
      <div data-portal-component="${component.path}" data-th-remove="tag" />
    </div>
  </aside>
</div>
````

**Comment by aro** [comment]
Thanks. I will update the documentation.

I see we only have it documented for parts: http://xp.readthedocs.io/en/stable/developer/site/part/index.html#view

**Comment by aro** [comment]
Updated in the latest doc: http://xp.readthedocs.io/en/latest/developer/site/layout/index.html
