### ISSUE TITLE
Hard to edit HTML area on mobile

### ISSUE THREAD

**Issue by ljl** [enonic/xp#3764]
Hello!

I find it hard to edit HTML areas on a mobile phone. The problem is that when selecting the HTML area the keyboard comes up and takes 50% of the screen. The rest of the screen is hidden by the HTML Area toolbar, completly hiding the field where i want to see and edit my text.

![a](https://cloud.githubusercontent.com/assets/414079/18945513/345d701e-862b-11e6-9710-5df3e8d9d394.png)

**Comment by jsi** [comment]
There have been made some improvements to this in 6.8 and some more in 6.9.
In 6.9, we have moved the tabs out of the screen, and now used system tabs.  This frees up several lines of valueable screen space.  Hope this helps!

Is it okay to close this issue, @ljl ?

**Comment by alansemenov** [comment]
We have upgraded to the latest version of TinyMCE that supports auto-switch to mobile theme specifically fit for mobile resolutions. It will come as a part of 6.15 release.
