### ISSUE TITLE
Create js function isMaster

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#4392]
The isMaster function in IndexService would be useful to expose in js-api also.

Not sure about where to place it, maybe a new "system" lib? Could also expose other stuff like "hostname" etc

**Comment by runarmyklebust** [comment]
We should prioritize this; its a simple task that would be very useful

**Comment by sigdestad** [comment]
If it is a really small thing, we don't need "PAB" Approval.
Which library would you put this in?

**Comment by ComLock** [comment]
@runarmyklebust 
I need this in app-cronjob by next wednesday! :)
So that a cronjob is only executed on the master node.

**Comment by sigdestad** [comment]
I think cronjobs are only running on master already!

**Comment by sigdestad** [comment]
It's built into the library

**Comment by ComLock** [comment]
This? https://github.com/enonic/app-cronjob/blob/7520f51750278fee4cd0653f8dbb610c439c8e1c/src/main/java/com/enonic/app/cronjob/runner/JobRunnerImpl.java#L47

**Comment by ComLock** [comment]
Documentation says otherwise? https://github.com/enonic/app-cronjob/blame/master/README.md#L8-L9

**Comment by sigdestad** [comment]
Either:
a) Sten Roger never fixed so it only runs on master (as we agreed) or
b) It is not documented correctly

**Comment by sigdestad** [comment]
Anyway, an isMaster function is useful - Im just curious how to access this information?

**Comment by ComLock** [comment]
I wonder if a workaround would be to install the app on a single node only. Aka $XP_HOME/deploy not toolbox install-app. Not very pretty in prod though?

**Comment by ComLock** [comment]
Seems to be what Sten Roger is hinting to in the doc.

**Comment by runarmyklebust** [comment]
or we can create a tiny java-lib for this as a workaround

**Comment by ComLock** [comment]
Installing an app locally is currently "not" possible from application admin.
Which means the third party OPS provider has to get involved... :(

So yes a tiny-java-lib would be lovely. (or just "inlined" in app-cronjob)

**Comment by sigdestad** [comment]
Deploying to a single node is perfectly fine if that is what you need...
‌‌
Vennlig hilsen/Best regards
Enonic AS

Thomas Sigdestad
CTO
+47 98236011

https://enonic.com <https://enonic.com/> - Your idea, one platform, any cloud

**Comment by ComLock** [comment]
@runarmyklebust will there be time to make the tiny java code snippet today or tomorrow?

**Comment by runarmyklebust** [comment]
yes

**Comment by ComLock** [comment]
@runarmyklebust I'm guessing isMaster() could be called here https://github.com/enonic/app-cronjob/blob/master/src/main/java/com/enonic/app/cronjob/runner/JobRunnerImpl.java#L30

Or maybe the sceduler should not even be running unless isMaster.

**Comment by GlennRicaud** [comment]
So @runarmyklebust, you do the snippet for @ComLock
We will create a function "isMaster" in a proper new library "cluster"

**Comment by sigdestad** [comment]
Where is this library now? How can I add it to my project?

**Comment by GlennRicaud** [comment]
The library is treated the same way as the other XP libraries.

Library in the repo: http://repo.enonic.com/public/com/enonic/xp/lib-cluster/6.15.0-RC1/
Documentation: http://repo.enonic.com/public/com/enonic/xp/docs/6.15.0-RC1/docs-6.15.0-RC1-libdoc.zip!/module-cluster.html

You include it the same way you include other libraries:
  include 'com.enonic.xp:lib-cluster:6.15.0-RC1'
