### ISSUE TITLE
Applications not installed after snapshot

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#4399]
Reproduce:

1) Start clean installation
2) Install app superhero from market
3) Move /superhero to /superhero-moved
4) Take snapshot using the toolbox, e.g /toolbox.sh snapshot -a su:password
5) Stop server, delete $XP_HOME/repo/index
6) Start server
7) Restore snapshot, e.g ./toolbox.sh restore -a su:password -s 2016-11-28t09-03-22.987z
8) Data is now restored, but the application superhero is not installed

To fix:

     When Repository.restore event is handled, install all applications again (make a public available ApplicationServiceImpl.installAllStoredApplications and move the implementation to a private (doInstall....)

Maybe the most solid solution would be to restart the nodeService and get the initialization of this and all dependants?

**Comment by runarmyklebust** [comment]
Depends on enonic/xp#4405

**Comment by jsi** [comment]
The solution will be released with 6.9.3.
