### ISSUE TITLE
Move SnapshotService to api, remove snapshot-methods from NodeService

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#4405]
We need more functionality in the SnapshotService, and the NodeService is not the correct placement for these functions.

**Comment by GlennRicaud** [comment]
nodeService.restore and snapshotService.restore were not equivalent.
Skipping the calls to nodeStorageService  and eventPublisher  will cause problems

**Comment by GlennRicaud** [comment]
Created issue #4605
