### ISSUE TITLE
Extend term-aggregation options in api

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#4407]
There are available term-aggregation parameters that could be useful to expose in JS-API's.
This should be done for both node.query and content.query

* minimumDocCount

````
 aggregations: {
        floors: {
            terms: {
                field: "data.number_floor",
                order: "_count asc",
                minimumDocCount: 10
            }
````

**Comment by anatol-sialitski** [comment]
Property should be named 'minDocCount' to be unified with the rest of the code
