### ISSUE TITLE
Move dialog - Confirmation when content is about to be moved out of its site

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4414]
If selected items contain at least one that will be moved out of its site after pressing the "Move" button, show confirmation dialog (use ConfirmationDialog class) saying "You are about to move content out of its site which might make it unreachable. Are you sure?" with two buttons Yes/No. Move content only if user pressed "Yes".

**Comment by alansemenov** [comment]
1. Whenever I get a confirmation dialog, the "Yes" button there is blinking like crazy (looks like the button is getting focused in an indefinite loop)
2. Hide "MoveContentDialog" whenever the confirmation is shown so that they are not visible at the same time.
3. Condition for showing the confirmation is incorrect. I now get the confirmation when I try to move content between folders of the same site, which is wrong. What you need to do is get the top level parent of a selected content item, check that it's a site, then check whether target item is a child of that site. Show confirmation only when source item is under a site and target item is either root or is not under the same site.

**Comment by sshklianko** [comment]
2. and 3. are fixed. And I could not reproduce 1.
