### ISSUE TITLE
Show content status as "New" when the "First Published" field is empty

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4425]
1. When content item is not in master branch (compareStatus is "NEW") and the "First Published" field is empty, show item status as "New" (instead of "Offline") everywhere in the admin UI.

2. If item is not in master branch but "First Published" field is set, that means that the item was published and then taken offline, in this case we should show "Offline".

Use color ``@admin-font-gray1 (#acacac)`` for Offline status.

![image](https://cloud.githubusercontent.com/assets/11612490/23059773/2194fc42-f4fb-11e6-948d-e3958dbc18ca.png)

**Comment by runarmyklebust** [comment]
I think this should be done in the ContentResource, since we will need to handle this status in the publish wizard anyway because of the filtering of "offline" vs "new items" in the wiz
