### ISSUE TITLE
Implement "In progress" and "Ready" workflow steps

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4447]
As a Content Manager, I want new content items to be by default marked as "In progress" and explicitly saved as "Ready" before they can be published.

Content that is valid and in progress should be visually marked with a yellow icon over the content icon (similar to how we mark invalid content with the red icon). This can be, for example, a yellow triangle icon (farther "in progress" icon).

As of now, Content Manager will be able to approve his own content for publishing (when he's done with the changes). This will be done via "Save as Ready" action in the Content Wizard (and possibly context menu of the Content Grid).

**Conditions of satisfaction:**
* All New content items that are not yet saved-as-ready are visually marked with the "in progress" icon and "New" displayed in yellow color in Content Grid, Content Wizard and Publishing Wizard.
* Invalid items that are "in progress" must show only "invalid" icon, not the "in progress" icon. 
* If the Publishing dialog contains at least one "in progress" item, the entire selection cannot be published. We should show the text in dark yellow colour on top of the Publishing dialog, just like we do when there are invalid items in the list: "The list contains item(s) not yet ready for publishing"
* In the Publishing dialog "In progress" items must be clickable and open Content Wizard (like invalid items).
* While content is in progress, the save action button should be titled "Save as In progress"
* While content is in progress, we should show the dropdown handle to the right of the save action which will expand a second option: "Save as Ready"
* "Save as Ready" action inside the dropdown must be disabled if content is in progress but invalid.
* For items in progress the entire "Publish" menu button should be disabled in the Wizard toolbar, "Publish" action should be unavailable in the grid and invisible in context menu (the action button should change state automatically on validity change).
* Clicking "Save as Ready" while the item is "In progress" should show confirmation dialog: "Mark this item as ready for publishing?" with Yes/No buttons. If user saves as ready when item is already in Ready/Approved step, we should simply save content, without the confirmation.
* "Save as Ready" action should save content and change workflow state of the item from "In progress" to the next workflow step (Ready/Approved)
* Change of workflow step from "In progress" to Ready/Approved should result in the following:
-- Publishing action should automatically become enabled (we should also track this in the grid to enable publishing of the changed item)
-- "In progress" icon should disappear
-- Color of the "New" or "Modified" status should change from yellow to black
-- "Save as In Progress" and "Save as Ready" actions will change places ("Save as Ready" will be a default action and "Save as In Progress" will be inside the dropdown)
* It's important that after the item went from "In progress" to Ready/Approved, user will still have both "Save as In Progress" and "Save as Ready" options.
* If user saves as In Progress when the item is already Ready/Approved, workflow state should go from Ready/Approved back to "In progress". This should result in return of all of the markings of the "In progress" step as described above.

**Comment by sigdestad** [comment]
We could consider placing the state inside a dropdown in "save" instead - i.e. "Save as Ready" - similar to how you change state in the zendesk application!
