### ISSUE TITLE
Implement new field for storing workflow state in content

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4450]
We need a new field "workflowState" with the following statues:

* In progress  -> The user is working on the content, it is not finished.

When user selects "save as ready", the state will either go to

* Ready 

or 

* NeedsApproval -> This content has a policy which requires that some form of approval is required

* PendingApproval -> This content is 'sent to approver' 

* Approved

**Comment by runarmyklebust** [comment]
We need a new field "workflowState" with the following statues:
* In progress -> The user is working on the content, it is not finished.

When user selects "save as ready", the state will either go to
* Ready(?) -> Ready for publishing
or
* NeedsApproval -> This content has a policy which requires that some form of approval is required
* PendingApproval -> This content is 'sent to approver'
* Approved(?) -> Ready for publishing

**Comment by alansemenov** [comment]
@runarmyklebust I think we need to combine "Ready" and "Approved" in one ("Approved"). If content requires approval based on policies, then it will go from "In progress" to "Needs approval". If not, from "In progress" directly to "Approved".
