### ISSUE TITLE
Applications - ActionMenu should not contain the 'Start' item if application is started

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4465]
@sgauruseu commented on [Thu Feb 23 2017](https://github.com/enonic/xp-ui-testing/issues/14)

1. select an started application
2. open the  ActionMenu
BUG: 
expected: 'Start' should not be displayed in the menu

But-  when a stopped application is selected  'Stop' not displayed
![menu](https://cloud.githubusercontent.com/assets/3728712/23254276/8c48aa9e-f9c8-11e6-923d-d6a012299ae5.png)
![menu2](https://cloud.githubusercontent.com/assets/3728712/23254281/8f0927ae-f9c8-11e6-9063-4f4ff50bcf80.png)

**Comment by alansemenov** [comment]
We should also collapse the menu on a click outside of it.
