### ISSUE TITLE
Adjust notifications bar to not span too high on many notifications

### ISSUE THREAD

**Issue by sshklianko** [enonic/xp#4472]
Select folder and press new button. Then switch to your file system, select a dozen of images and drop over new content dialog.
All images are loaded correctly but notifications stack looks crazy: 
![image](https://cloud.githubusercontent.com/assets/4262655/23297217/b37217b0-fa89-11e6-93e0-f64fb7119857.png)

**Comment by jsi** [comment]
The Tower of death!!!  😬
