### ISSUE TITLE
Application name indexed in fulltext-field

### ISSUE THREAD

**Issue by sshklianko** [enonic/xp#4474]
It seems that filter search gives extra results when searching.

here is my content root:
![image](https://cloud.githubusercontent.com/assets/4262655/23303848/807abd3a-faa7-11e6-930a-3683d6b3aad8.png)

and then I enter 'fea' into search panel and it gives me such results as 'S1' site or parents of contents that match 'fea' search name
![image](https://cloud.githubusercontent.com/assets/4262655/23303837/7336218c-faa7-11e6-8db9-a48f56e874ab.png)

**Comment by srs** [comment]
Maybe it has the "feature"-app on site "S1"? But this field should not be added into the `_alltext` field.

**Comment by runarmyklebust** [comment]
Its in the 

data.siteconfig.applicationkey

We index everything under data to "byType"

Should we hardcode this "data.siteConfig.applicationKey" to not to be indexed?
