### ISSUE TITLE
Outline of buttons is not visible in modal dialogs in Firefox

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4488]
In Chrome there's a blue border around buttons showing which one has focus at the moment, but in Firefox it's missing. However, in general outline works in Firefox - for example for the Publish button in the toolbar.

Seems to be general problem in all of the modal dialogs in Firefox.

Chrome:
![image](https://cloud.githubusercontent.com/assets/11612490/23397526/35a1f022-fd99-11e6-85ed-5d2b4226a605.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/11612490/23397518/2c1ed754-fd99-11e6-8400-2e37a79e546c.png)

**Comment by edloidas** [comment]
That's not actually a problem with our styles, but with Firefox defaults. Firefox has a semi-transparent dotted outline for focusable elements, while in Chrome the outline is solid blue. I've updated the behavior of focusable elements in Firefox in #4519. Though it's impossible to make it exactly like in Chrome, that do some post-processing. We can override the focus outline for each component, to look it identical, but it's not rational. Chrome will also lose the post-processing features in that case, like "outline" always on top" or "ouline tone correction, based on the background" via `outline-color: -webkit-focus-ring-color;`.
Tell me if I need do some adjustments to the outline on focus in Firefox.

**Comment by ashklianko** [comment]
Just looked at Nikita's comment; looks good in #4519
