### ISSUE TITLE
InsertImage, InsertMacro modal dialogs - Cancel Button Top are missed on the both dialogs

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4497]
![ins](https://cloud.githubusercontent.com/assets/3728712/23405917/8269254a-fdcd-11e6-9ae7-0b56ca7379f9.png)

**Comment by ashklianko** [comment]
'X' icons for both dialogs were removed intentionally, see
https://youtrack.enonic.net/issue/XP-3320 and
https://youtrack.enonic.net/issue/XP-3411
