### ISSUE TITLE
portal.attachmentUrl({download:true}) does not set Content-Disposition in 6.9.2?

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4524]
http://repo.enonic.com/public/com/enonic/xp/docs/6.9.0/docs-6.9.0-libdoc.zip!/module-lib_xp_portal.html#.attachmentUrl

So we use <a download=true> as a workaround
https://developer.mozilla.org/en/docs/Web/HTML/Element/a

However it's not supported in IE :(
http://caniuse.com/#feat=download

**Comment by srs** [comment]
We are doing this in two steps:

1. Create a URL. This will contain hints with some download=true flag.
2. The attachment service will add `Content-Disposition`-header when serving the attachment. 

The error could be in either of the two. Let's also look at why the tests did not catch this one.

**Comment by ComLock** [comment]
Hmm, it works on another part. Dunno what the difference is.

Just for reference it works on linkWithArrow and fails on pn-search.

**Comment by srs** [comment]
So it works? Do you set some other headers?

**Comment by alansemenov** [comment]
@ComLock @srs We need status report on this issue. If doesn't reproduce or is not crucial then we should move it out of then 6.10 milestone (or close)

**Comment by ComLock** [comment]
I cannot reproduce this anymore. Closing as invalid.
ref: https://github.com/bring/kp-suite/pull/234/files
