### ISSUE TITLE
Implement undo of Pending Delete flag

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4535]
Investigate how much work is involved in this, ask @runarmyklebust if unsure. 

Add a new option "Undo delete" to the context menu in TreeGrid which will only be visible for items in "Pending Delete" state.
After selecting this action and getting success response from the server, show notification: "The item has been successfully undeleted".

**Comment by sshklianko** [comment]
I took a look at this and discussed with Runar. Approximate estimate is day and a half.

**Comment by runarmyklebust** [comment]
I see that its recursively undoing deletion of all children also. It's not mentioned anything in the spec about this, but I guess that is an ok behavior? Should it be optional maybe?

**Comment by alansemenov** [comment]
We recursively delete children, so it's ok to follow the same logic when we undelete. We can add an option later on.
