### ISSUE TITLE
Adapt content modification to include publish.first

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4545]
Unpublish of an Online content item changes its state to "Offline", but if I unpublish a **Modified** item then ``publish.first`` field is cleared and the item is shown as "New" again.

**Comment by alansemenov** [comment]
There's also an error notification in admin after unpublish of a modified item (but no errors in log):

![image](https://cloud.githubusercontent.com/assets/11612490/23612103/612d2898-027a-11e7-8304-93b671514f6c.png)

**Comment by GlennRicaud** [comment]
Problem is due to the modification step. It removes the publish.first value.
I also saw that publish.first is returned as an array (When there is actually 1 value :S )
