### ISSUE TITLE
Implement handling of Publishing Issues in Content Studio

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4550]
As a Content Manager, I want to be able to send content that is ready for publishing to other users that can verify and publish the content. Content items will be grouped into issues, each issue will have id, title, description, author (the one who created it), one or more assignees, created date/time stamp, status (Open or Closed) and the list of content items. In the Publishing Wizard I should be able to choose whether I want to create a new issue or add items to one of the existing open issues. When I create or update an issue, each of the approvers I selected should receive an email notification with issue details and direct link that will open a dialog with issue details and the list of items, from which I can go directly to the Publishing Wizard. I want to be notified by email when my issues are approved or rejected. I also want to be able to access the issues I created to check their status. 

Conditions of Satisfaction:
* If user is not allowed to publish at least one of the selected items, the "Publish Button" should be replaced with the new button titled "Create Issue... (5)" where "5" is the total number of items in the list.
* The new button must always be enabled, even if the list has invalid items
* Clicking the button should open the New Issue dialog where user will enter Issue name, description and select at least one approver.
* From this dialog user can either go back to the original Publishing dialog with the list of content item or click the "Create issue" button to create the issue
* It should not be possible to create an issue with an empty name, without at least one content item or without at least one approver - via validation in the dialog
* Clicking the "Create Issue" in this new dialog should create a new issue in status "Open" with specified details, link selected content items to it and send email notification to selected approver(s) and a copy to the user
* Email notification should show issue details (id, name, description), list of content items, list of approvers and direct link to the issue dialog
* In the Content Studio toolbar there should be a new action button called "Issues"
* This action should open a new dialog showing the list of all issues in the system split in tabs by their status.
* There should be four tabs: "Assigned to me" (issues where current user is selected as an approver), "My issues" (issues that current user created), "Open" (all open issues) and "Closed" (all closed issues). Number of items should be shown in brackets after tab name (when not "0").
* The list should be sorted by created date/time (newest on top) and contain issue name, issue id, author name and date/time.

**Comment by jsi** [comment]
Putting Epic label back on this issue.  Changelog-generator will ignore it from now on.
