### ISSUE TITLE
Create Issue domain object

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#4557]
Create new domain object "Issue" in core-content.
Create a new package for this, "issue".

The Issue object should contain
* id (auto-generated, uid)
* title (string)
* name (prettified title)
* IssuePath ( new class, 'invisible' from path - just created from name but used in node-service when storing, should be prefixed with /issue"
* description (Optional)
* created date/time (auto-set)
* modified date/time (auto-set)
* status (Open, Closed) (enum)
* creator (userId)
* the list of approverId (userIds)
* the list of itemId (contentIds)

**Comment by sshklianko** [comment]
@runarmyklebust , I think that Issue class should reside in core-api module, not core-content, can u confirm?

**Comment by runarmyklebust** [comment]
yessir
