### ISSUE TITLE
*.odp (libreOffice...) files becomes media:unkown should be media:presentation?

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4578]
*.odp (libreOffice...) files becomes media:unkown should be media:presentation?

**Comment by ComLock** [comment]
Which means it's "impossible" to filter on it in content selector.

I'd rather not:
```<allowContentType>media:unkown</allowContentType>```

**Comment by ComLock** [comment]
Perhaps we could have a ```<allowExtenstion>```

**Comment by ashklianko** [comment]
https://github.com/enonic/xp/pull/4771 fixes problem
