### ISSUE TITLE
RoleWizard - list of members not refreshed, when the role has been added to a new user

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4584]
1. Open a role(do not close the wizard)
2. create a new user and the role to this user
3. navigate to the role-wizard
BUG: new added user is not displayed in 'members
![role-w](https://cloud.githubusercontent.com/assets/3728712/23752827/f6bae020-04e7-11e7-8b4a-441582c09fba.png)
'

**Comment by alansemenov** [comment]
Issue moved to [enonic/xp-apps #434](https://github.com/enonic/xp-apps/issues/434) via [**ZenHub**](https://www.zenhub.com/)
