### ISSUE TITLE
OptionSet content - incorrect validation of the content in the wizard, when all required fields are filled

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4594]
1. select "Features" and open the OptionSet wizard
2. select the option2 in the single selection
3. click on the option3 in the multi selection and select an image from the options
BUG: all required inputs are filled, but  red icon is present on the wizard page
![opt-wizard](https://cloud.githubusercontent.com/assets/3728712/23847425/4906ebd2-07e3-11e7-9017-6a9920cc390e.png)

**Comment by alansemenov** [comment]
Actually, the red icon should have disappeared already after selecting option2 in "Single selection".

Validation starts working correctly after saving new content.
