### ISSUE TITLE
Remove the cart icon

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4610]
We now visualise number of selected items with a number inside a blue circle on top of the cart icon in Grid's toolbar. Do the following changes:
1. Remove the cart icon and use only the circle with number inside as the toggler icon (make both the circle and number inside a bit bigger in size)
2. Align the toggler with SelectController checkbox (note that in mobile mode it's right aligned)
3. In "off" mode the circle should be grey. We should basically use the same styling as for the help-text toggler in the Wizard. 
4. When new items are added to selection, apply the same effect as now (when circle slightly grows for a moment). If the toggler is off, "it" should also become blue for that short moment while effect is in progress (to make the grey icon more visible).
5. Hide the toggle icon when nothing is selected
6. Add tooltips to the toggler icon: "Show X selected items" (when toggler is "off") or "Hide selection" (when "on") 

![image](https://cloud.githubusercontent.com/assets/11612490/23902499/a91155ce-08c1-11e7-9e8c-6452a3661a79.png)

![image](https://cloud.githubusercontent.com/assets/11612490/23902569/e9dd745c-08c1-11e7-8a05-1db723287b3b.png)

![image](https://cloud.githubusercontent.com/assets/11612490/23902836/c28c1bf0-08c2-11e7-91a2-5a40f17a389f.png)

**Comment by ashklianko** [comment]
Some points regarding statements 4 and 6:
-Current behaviour is that when more than 1 item is selected cart icon becomes disabled and stays active (and I left it as it is)

**Comment by alansemenov** [comment]
Correct, this behaviour is supposed to be fixed in #4611
