### ISSUE TITLE
All menu items should be disabled when 'Deleted' and 'offline' contents are selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4631]
1. Select one 'Deleted' content and one 'Offline'
Expected: 'Undo delete'  item should be enabled
Actual: 'Edit', Move, 'Delete' ... items are enabled.(See the screenshot)
The same issue with the Context menu(see the second screenshot)
![cont](https://cloud.githubusercontent.com/assets/3728712/23998304/bf6cf36e-0a65-11e7-80ea-f7d0147f9161.png)

![deleted](https://cloud.githubusercontent.com/assets/3728712/23998117/25105126-0a65-11e7-8729-39241d2107ff.png)

**Comment by alansemenov** [comment]
No longer relevant - fixed in https://github.com/enonic/xp-apps/issues/550
