### ISSUE TITLE
RepoConnection.modify converts properties to String

### ISSUE THREAD

**Issue by aro** [enonic/xp#4632]
Updating a node from the cms-repo, with the JS Node API, converts existing properties of the node that were of type Instant to type String. This happens even if the the edit callback does not touch any of those properties.

In particular this happens with properties _timestamp, createdTime and modifiedTime from Content, which then causes an exception while trying to publish the content.

It probably will happen with other non-JSON types.

**Comment by srs** [comment]
We should probably not default convert to string in `MapGeneratorBase`. But that leads to a lot of tests failing. Is it possible to create a test for this error and then we could try it out?

**Comment by runarmyklebust** [comment]
Well, it has to convert it to string for doing the output-serialization right, so it has to it differently if its coming in or out?
