### ISSUE TITLE
Upgrade Apache POI to 3.15

### ISSUE THREAD

**Issue by jsi** [enonic/xp#4633]
In September 2015, Microsoft made some additions to the DOC fileformat or more specifically the ooxml-schema and ooxml-security.  Documents created with Office 2016, which is becoming more commonplace, use this new standard, and documents using the new features will fail to parse in Enonic XP.

Enonic XP use Apache POI version 3.9 to extract text from these documents.  This version is from December 3rd, 2012.
Support for the new document standard came in version 3.14, March 2nd, 2016.
The latest stable version is 3.15, from September 19th, 2016.
The very latest version is 3.16-beta2, from February 2nd.

**Comment by rymsha** [comment]
XP 7.x doesn't depend on POI directly.
But has transitive one via Tika which also require update #7375
This issue seem obsolete.
