### ISSUE TITLE
Notification is missed, when a content was deleted in the wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4638]
case1:
1. Open a offline content
2. press the Delete button and confirm the deleting
expected - message "The item is deleted" should appear
actual - wizard closes, message was not displayed

case2:
1. Open a offline content
2. publish the content
3. press the Delete button on the wizard
4.press the Publish button 

expected - message "The item is deleted" should appear
actual - wizard closes, message was not displayed

**Comment by srs** [comment]
This will be a part of the activity log. We will not do anything about this.
