### ISSUE TITLE
Resolve dependencies with children for a selected online content

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4640]
1. Publish the entire "Features" site
2. Expand the site in the grid, select all child items and Unpublish them. They change to "Offline". The site itself is still "Online". If I select "Features" in the grid, "Publish" button is disabled because content is already published - correct.
3. Add a new child content under "Features" - it has state "New". Now all child contents under Features are "Offline" except for one that is "New".
4. Select "Features" and do "Publish tree". The dialog opens with one child item (the "New" one) shown by default - correct.
![image](https://cloud.githubusercontent.com/assets/11612490/24039267/d5ff32fa-0b04-11e7-9ced-d7819cb87199.png)

5. If I now click the toggle button next to "Features", the "New" item disappears but instead I see two "Offline" items.
![image](https://cloud.githubusercontent.com/assets/11612490/24039350/1e61e38a-0b05-11e7-928f-0b68a2824deb.png)

If these two are mandatory dependencies, then they should've been shown right away and should always be visible, independent of the checkbox state or "Include children" togglers.

**Comment by GlennRicaud** [comment]
This is actually a bug present in 6.9:
When we do not include children, the selected content is included in the initial diff (and thus its dependencies).
When we include children, the selected content is not included in the initial diff (and thus its dependencies).

After discussion with @ase and @rmy: A selected content is a content we want to publish. It is then normal to include its dependencies.

The unit tests were not seeing it this way (they consider that a content online even if selected is not published). I will update the unit tests
