### ISSUE TITLE
DetailsPanel, version history - button 'Restore version' is shifted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4641]
1. select a content with several versions
2. open the version history
BUG: button Restore is shifted, see the screenshot
![shifted](https://cloud.githubusercontent.com/assets/3728712/24043269/e8eda6c2-0b26-11e7-980e-cdcc4414fa9c.png)

**Comment by edloidas** [comment]
I could not reproduce this bug (Chrome/Firefox). I guess it was fixed already or was registered for a short period of time due to a browser engine error on one's machine.
