### ISSUE TITLE
ContentWizard - status of the content is not refreshed, when a version was restored

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4643]
1. add a HtmlArea content or ItemSet
2. publish the content
3. edit the content(do not close the wizard)
4. navigate to the grid and open the Versions view
5 restore the 'online' version of the content
BUG: 'Online' status is displayed in the grid, but 'Modified' status is displayed on the wizard-page
see on screenshots
![grid](https://cloud.githubusercontent.com/assets/3728712/24093797/c00cca52-0d66-11e7-8e97-e60aa0eaf7f6.png)
![wizard](https://cloud.githubusercontent.com/assets/3728712/24093806/c29639ac-0d66-11e7-9b51-1b668a20f1f8.png)

**Comment by alansemenov** [comment]
Pretty sure we fixed this already, don't know why it popped up again
