### ISSUE TITLE
Indirect memberships not checked when adding an application to a site

### ISSUE THREAD

**Issue by aro** [enonic/xp#4644]
To add an application to a site, the user is required to have one of the roles: "Administrator" or "Content Manager Administrator".
But currently the check does not consider indirect membership:

It allows the operation if userA has role "Content Manager Administrator". 
But it does not if userA is a member of group1 and group1 has role "Content Manager Administrator".

The user should be allowed to add an application to a site if it has indirectly one of the roles required.

This issue was reported by a customer (see support case 1870).

**Comment by GlennRicaud** [comment]
Wow. Is it just for this case or is it much bigger than this?
Are other places actually correct: REST services, Admin tools, ...
I will check

**Comment by aro** [comment]
Good idea to check. I did not see others but did not look so much.
Most other places uses the AuthenticationInfo from the context, and then the roles are already expanded.
