### ISSUE TITLE
ItemViewContextMenu does not appear when a component was clicked in the View (only MS Edge)

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4648]
1. open XP in Edge browser
2. open the Features 
3. open the PageComponent View
4.Insert an Image
5. click on the Image and try to insert anything
BUG  ItemViewContextMenu does not appear, when the item was clicked(drop down handler was clicked)
![edge](https://cloud.githubusercontent.com/assets/3728712/24097842/b2bb0884-0d78-11e7-85c3-96763eebe2d2.png)

**Comment by sgauruseu** [comment]
TreeContextMenu.ts (78,17)   Can't execute code from a freed script

**Comment by alansemenov** [comment]
I don't think this is still valid, but need to check

**Comment by sgauruseu** [comment]
It still reproducing,  checked it Today
