### ISSUE TITLE
"Upload content" dialog should be closed, when an image has been dragged to the 'New Content' dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4662]
1. Press the 'New...' button
2. drag an image and drop on the NewContent dialog's area
BUG - the image is uploaded and 'NewContent Dialog' is closed. but the "Upload content" dialog still present. (see the screenshot) Sometimes, the browser hangs, when the image was uploaded in this way.
Part2: 
1 drag an image and drop on the NewContent dialog's area
2. UploadDialog not closed, double click on the same image(try to upload the same image)
3. select the image in the grid and delete it 
BUG: BodyMask is present when the image was deleted
This bug can be linked with the  https://github.com/enonic/xp/issues/4470
![drag2](https://cloud.githubusercontent.com/assets/3728712/24140948/d520b206-0e32-11e7-9cca-0a39b2001220.png)

**Comment by alansemenov** [comment]
Possibly fixed in #4470
