### ISSUE TITLE
js authLib.addMembers() accepts non-existant member

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4666]
This works
```
addMembers('group:' + userStoreKey + ':does-exists', [
    'user:' + userStoreKey + ':non-existant'
]);
```

And then clicking the group in UserAdmin gives yellow error:
```
Principal [user:userStore:non-existant] was not found
```

Which means I now have a broken structure.

**Comment by ComLock** [comment]
Luckily I was able to use removeMembers to remove it. But I think it should not have been possible in the first place.

**Comment by rymsha** [comment]
This seems to be general case for all single value arrays, not just `authLib.addMembers` @ComLock , right?

**Comment by ComLock** [comment]
How am I supposed to remember anything about something I reported 4 years ago :)
If it is still reproduceable, take it from there?

**Comment by rymsha** [comment]
This is not a bug. There might be use cases when users are added after groups, and groups contain references prior.

**Comment by ComLock** [comment]
Broken references is a typical cause of runtime errors. It would be nice if our backend enforced consistent data. Just another case of me missing PostgreSQL :)
