### ISSUE TITLE
input type long config regexp does not work in idprovider.xml

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4672]
```
<input name="port" type="Long">
	<label>Port Number</label>
	<help-text>Proxy port to use. Between 0 and 65535.</help-text>
	<occurrences minimum="0" maximum="1"/>
	<config>
		<regexp>^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$</regexp><!-- 0 to 65535 --><!-- Does not work -->
	</config>
</input>
```

**Comment by aro** [comment]
@ComLock `regexp` is not supported on `Long` input type, only in `TextLine`.

In this case you can now use the `min` and `max` config options for Long.
Can we close this issue?

**Comment by ComLock** [comment]
I guess it's not a bug. 
And in the example above min and max can be used.
But lets say you want to dissallow some values within min and max.

I guess as a workaround I could use TextLine and parseInt.

Note: This applies to double aswell.

I guess it's such a minor issue it could be closed?

**Comment by aro** [comment]
More specific cases should be covered with custom input types, in the future. 
Closing this issue.
