### ISSUE TITLE
Publish wizard - When the toggler is on, offline child items get published  even though they are hidden

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4690]
1. add a parent folder and child
2. select the parent and  do publish both folders
3. Unpublish both folders
4. select the parent and press 'publish' on the toolbar (see the first screenshot)
5. Click on 'Include child' icon but do not check the 'Include offline items' checkbox
6. Press the 'Publish' button on the dialog
BUG: 
expected - only parent folder should be 'online', because 'Include offline items' was not checked
Actual - both folders are 'Online'
![step1](https://cloud.githubusercontent.com/assets/3728712/24242873/3c97bbd0-0fca-11e7-9cc4-d863d0891fe1.png)

**Comment by runarmyklebust** [comment]
Im not sure this will be an issue if we remove the checkbox and just add the offline that is not supposed to be published in the exclude-set

**Comment by alansemenov** [comment]
This is no longer an issue
