### ISSUE TITLE
In Publish Wizard hide "Show children" toggler when an item doesn't have any unpublished children

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4692]
Add boolean ``hasChildren`` field to object inside ``requestedContents`` of json response from ``resolvePublishContent``. If requested item doesn't have children that can be published (new, offline, modified etc.), hide the "show children" toggler.
```
"requestedContents":[  
      {  
         "id":"features",
         "hasChildren":true
      },
      {  
         "id":"my_folder",
         "hasChildren":false
      }
   ]
```

**Comment by runarmyklebust** [comment]
Dont we use hasChildren in another context as content that actually has children? I bit confusing naming there - maybe it should be 'hasChildrenToPublish'

**Comment by alansemenov** [comment]
Yeah, or ``hasUnpublishedChildren``
