### ISSUE TITLE
Unexpected scrolling behaviour when editing source code inside a text component on a page

### ISSUE THREAD

**Issue by RF0** [enonic/xp#4726]
When editing source code inside a text component on a page, and there enough lines of code to trigger scrolling, the mouse scolls the outer window with html instead of the source code window. To scroll the code one have to use keyboard arrows / page down keys.

A nice enhancement would be to scroll the active window instead, as this is expected behavior.

<img width="1087" alt="screen shot 2017-03-28 at 09 27 52" src="https://cloud.githubusercontent.com/assets/951293/24393754/94b81d3c-1399-11e7-97fb-b7a5ffa71a32.png">

Tested on:
Enonic 6.9.3
Chrome browser

**Comment by alansemenov** [comment]
Hi Rune!

We have replaced this TinyMCE dialog with our own native XP dialog, that's coming in 6.10. Behaviour is correct there.

**Comment by RF0** [comment]
A similar problem with scrolling in the component editor. When scrolling down the component editor, the scrolling stops when hovering a html-editor. One has to put the mouse pointer on the tiny space right of the html-editor and scroll to get further down using the mouse.

**Comment by RF0** [comment]
A nice feature would be to pin the table buttons in a html-area when scrolling down in a part config. It is very awkward to select content in a html-area and then scroll up to reach the buttons. For example if having a table in the bottom of a html-area, wanting to use row properties for example.

**Comment by alansemenov** [comment]
Can you post a screenshot for your last comment, Rune?

**Comment by RF0** [comment]
One screenshot shows the top of the html-area with buttons, and the other screenshot shows when I am editing lower down in the html-area, where I have marked red the area where the mouse must be hovered on the edges on the html-area to able to scroll up and reach the buttons.

<img width="1049" alt="screen shot 2017-03-28 at 10 09 39" src="https://cloud.githubusercontent.com/assets/951293/24395186/14abf720-139f-11e7-874d-4e0c7f29e349.png">
<img width="1017" alt="screen shot 2017-03-28 at 10 08 54" src="https://cloud.githubusercontent.com/assets/951293/24395187/14ac1cfa-139f-11e7-9a6c-f6ffa57cc5e3.png">

**Comment by RF0** [comment]
I tried to use the table fullscreen button which probably would have made it easy to edit, but that only results in a blank screen.

**Comment by RF0** [comment]
Whats annoying is that the body text html-area stops scrolling of the part config, and it don't scroll the content of the html-area either, so you are forced to move the mouse to left or right of the html-area to scroll further down.

**Comment by alansemenov** [comment]
Ok, we'll fix that

**Comment by alansemenov** [comment]
@RF0 Can you check if the original issue (your first comment at the top) is still valid in 6.10? I tested it now but couldn't reproduce it. We replaced the native Source dialog with our own, and I believe it might be fixed.

I created separate bugs for the two other issues you mentioned: #4877 and #4878
