### ISSUE TITLE
Applications - Installation from Market - 6.10.0 applications listed in 6.9.X

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#4728]
Applications supposed to require 6.10.0 are listed for Enonic XP installation < 6.10.0

**Comment by runarmyklebust** [comment]
It should be fixed, but the 1.5 version is not installed to prod, just QA (which doesnt work because of missing cert. for https)

**Comment by runarmyklebust** [comment]
I have not removed the hardcoded version, since its not working yet #4710
