### ISSUE TITLE
Controller mapping is not triggered for preview when the content has no matching page template for the content type

### ISSUE THREAD

**Issue by RF0** [enonic/xp#4730]
[UPDATE] The problem seems to be that site mapping is not triggered when the selected content has no matching page template for the contenttype. In the examples below, the freeform contenttype have no default page template. Is this expected behavior? [UPDATE END]

I cannot get pattern or match to work for contenttype that is included through a lib. For example the pattern /.*test.* matches the path for a landing-page that is inside my app, but not the path for my contenttype that is a incuded in my app through a library. 

![screen shot 2017-03-28 at 14 43 53](https://cloud.githubusercontent.com/assets/951293/24407648/d55ce8ea-13cb-11e7-9cde-b847fdb298dc.png)

Example: The mapping below matches the 'landing-page' content with path 'test-landing-page', but not the 'freeform' content with path 'test-freeform':

`<mapping controller="/site/controllers/freeform.js" order="1">
            <pattern>/.*test.*</pattern>
</mapping>`

Also I have tested with using match, and here I can also only match on contenttype inside app, but not contenttype included through a lib. `<match>type:'.*:landing-page'</match>` matches all landing-page content, but `<match>type:'.*:freeform'</match>` does not match the freeform content that has the contenttype inside the included library.

In the screenshot below you can se the layout of my test case. app-delphi is the app that contains the site specific code. I have a library openxp.lib.freeform that contains the contenttype openxp.lib.freeform:freeform and a separate app openxp.app.freeform-bootstrap that includes a site.xml with mappings to add a default rendering of the contenttype openxp.app.freeform:freeform.

![screen shot 2017-03-28 at 15 17 42](https://cloud.githubusercontent.com/assets/951293/24407116/480cdb22-13ca-11e7-8ee4-08f53be1f7af.png)

**Comment by RF0** [comment]
When I add a page template for the freeform contenttype, THEN the controller mapping starts working - and overrides the page template. Is a controller mapping depending on an existing page template for the matching contenttype?

**Comment by aro** [comment]
The problem is that Content Studio preview only checks if a Content has any page template supporting its content type, otherwise the preview will not be shown in admin.

We should fix the isRenderable REST method so that the controller mappings are taking into account for showing the content preview and enable the Preview button.
