### ISSUE TITLE
FF specific issue: content wizard does not always open, endless spinner is displayed 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4754]
1. open XP in FF and select a folder
2. click on the Edit button
BUG: wizard is not loaded, endless spinner displayed

TypeError: _this.formMask is undefined
Stack trace:
WizardPanel.prototype.doRenderOnDataLoaded/<@http://localhost:8080/admin/assets/1490949765393/common/js/_all.js:74381:25
Element.prototype.notifyRendered/<@http://localhost:8080/admin/assets/1490949765393/common/js/_all.js:5289:21
Element.prototype.notifyRendered@http://localhost:8080/admin/assets/1490949765393/common/js/_all.js:5288:17
Element.prototype.initChildren/<@http://localhost:8080/admin/assets/1490949765393/common/js/_all.js:4764:25
_fulfilled@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32883:54
Promise.prototype.then/</<@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32912:30
Promise/promise.promiseDispatch@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32845:13
become/</<@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32653:17
flush@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32204:17
From previous event:
Promise.prototype.then@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32877:20
Element.prototype.initChildren@http://localhost:8080/admin/assets/1490949765393/common/js/_all.js:4751:24
Element.prototype.init/<@http://localhost:8080/admin/assets/1490949765393/common/js/_all.js:4736:28
_fulfilled@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32883:54
Promise.prototype.then/</<@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32912:30
Promise/promise.promiseDispatch@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32845:13
defer/promise.promiseDispatch/<@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32605:17
flush@http://localhost:8080/admin/assets/1490949765393/common/lib/_all.js:32204:17

**Comment by alansemenov** [comment]
I don't think we can do anything about this - it's just too vague. I never experienced that and haven't heard any complaints. @sgauruseu please close it if it's no longer relevant.

**Comment by sgauruseu** [comment]
I have not reproduced this issue last month, so it can be closed
