### ISSUE TITLE
Content Wizard - 'Security Step' is not shown for users with read-only permissions

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4755]
1. Add an user and with roles : Content Manager App and Administration Console Login
2. add a folder and  set Permissions for the User:  'allow to Read permissions' and 'do not allow Write Permissions'
see the first screenshot
3. login with the user and open the folder
BUG: Security Step is not displayed despite of 'read permissions', see the second screenshot
![perm](https://cloud.githubusercontent.com/assets/3728712/24552493/5a6f9d6a-162f-11e7-8b0e-3bc5df13789e.png)
 is allowed

![perm2](https://cloud.githubusercontent.com/assets/3728712/24552510/65df07ee-162f-11e7-9266-af8e3a980933.png)

**Comment by alansemenov** [comment]
Yes, we should simply hide the "Edit permissions" button in this case, not the entire step
