### ISSUE TITLE
Better error message for: Exception processing template

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4762]
This error message is not very helpful:

```
14:01:18.194 ERROR [THYMELEAF][qtp1677813844-847] Exception processing template "bring:/site/parts/messages/part.thymeleaf.widget.html": An error happened during template parsing (template: "bring:/site/parts/messages/part.thymeleaf.widget.html")
```

The actual error was the template used a data-th-replace on a thymeleaf fragment file which where not there.

**Comment by aro** [comment]
Looks like a duplicate of this issue https://github.com/enonic/lib-thymeleaf/issues/5
Closing this issue, since Thymeleaf lib has been moved to a separate project.
