### ISSUE TITLE
Search improvments research 

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#4782]
Some suggested search-improvments:

## More info in the meta-fields #4892 
* Index / Type
* Geo-distance (if geo-pos. query type)
* Explain, for debugging queries

## Synonyms-support #4900 
* Support for supplying synonym-files for repositories. 
 * Plain synonyms: jump → (jump,leap,hop)
 * Replace: "u s a,united states,united states of america => usa"
 * Genre-mapping: 
   * "cat    => cat,pet",
   * "kitten => kitten,cat,pet",
   * "dog    => dog,pet"
   * "puppy  => puppy,dog,pet"

## Geo-shape mapping
* Introduce new geo value type; geo-shape. E.g a country 

## New query-functions
* **IndicesQuery** (query that will only take effect in defined indices, useful for multi-repo queries)
* **MLT** (MoreLikeThisQuery): Get "similar" documents
* **GeoDistance** (requires meta-field Geo-distance to be useful)
* **GeoShape** / **GeoPolygon** / **GeoHash** (requires geo-shape mapping)

**Comment by srs** [comment]
Could you create 4 epics instead of one?
