### ISSUE TITLE
BodyMask is not hidden, when dragged content was published

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4802]
1. press the 'New' button and  try to upload an image in root
2. when Upload Dialog is opened, drag an image and drop  the image on the drop-zone
3. The image is uploaded, but  Upload Dialog still opened. Do double click on the another image and upload it 
4. select the second uploaded image and publish it
BUG: Publish Wizard was closed, but 'BodyMask' still displayed and whole grid is disabled

**Comment by jsi** [comment]
Closing this issue again.  :(
