### ISSUE TITLE
Button 'Move' should be disabled when all contents are selcted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4815]
1. select all contents
BUG: button Move should be disabled
![move](https://cloud.githubusercontent.com/assets/3728712/24960575/dd4fa7fc-1f9e-11e7-9873-9a95de6749c1.png)

**Comment by alansemenov** [comment]
When fixing this we should keep in mind the selection mode in grid - in this mode even if all of the visible items are selected they can still be moved to a target which is not selected. So when disabling the "Move" action we should check **total number** of items in the grid, not just number of **visible** items.
