### ISSUE TITLE
Impossible to upload image in a page template 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4820]
Part1
1. Open a template.
2. Open the Page component View and insert Image component
3. press the Upload button and try upload an image

Part2
1. configure a template with ImageSelector
  add the " x-data mixin="select-image"  in site.xml
2. open the  template
3. navigate to Selected Image step in the wizard
4. try to upload an image, press the 'Upload' button
BUG:  Exception thrown in the server.log and notification warning appears
Expected: Upload button should be disabled?
![templ](https://cloud.githubusercontent.com/assets/3728712/25006821/0fc50cd6-2067-11e7-94db-a5b0cd14e933.png)

**Comment by alansemenov** [comment]
When we add a Text component to a page template, and then upload an image into the text area, the new image will be created under the site, not under the template. We should do the same with any attempts to add an attachment to a page template - attach to the template's site instead.
