### ISSUE TITLE
Incorrect notification message when trying to create a userstore or a role with existing name

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4827]
1. Create a User Store with the name 'store1'
2. try to create one more store with the same name
BUG: incorrect notification message appears
![notif](https://cloud.githubusercontent.com/assets/3728712/25046073/07be0854-2138-11e7-96f6-0934b42b62f1.png)

**Comment by alansemenov** [comment]
We should do the same as what we do in the Content Studio when trying to create a content item with existing path. 

Text: "Principal [name] could not be created. A principal with that name already exists"
