### ISSUE TITLE
Incorrect validation of OptionSet-content in the grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4830]
-This bug reproduced, when there is the next level of nesting of OptionSet:
content-type->mixin->item-set->item-set->option-set->mixin->option-set

1. Open the wizard and type a display name and save it 
2. required inputs are empty, so the content is not valid(in the wizard)
BUG: navigate to the grid, the content is valid
![grid](https://cloud.githubusercontent.com/assets/3728712/25121626/f4280f6a-242a-11e7-8cb0-f765cc5c1e7f.png)
![wiz](https://cloud.githubusercontent.com/assets/3728712/25121631/f7f4bad0-242a-11e7-878a-0b8b81bfe6c9.png)

**Comment by ashklianko** [comment]
@sgauruseu , please attach content-type
