### ISSUE TITLE
Fields overflow the "New issue" dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4834]
Bug #1
![image](https://cloud.githubusercontent.com/assets/11612490/25129817/f574e14e-243f-11e7-87b5-9baf154e59c6.png)

Happens only the first time this dialog opens.

Bug #2 

Current user should not be listed as approver in the dropdown

**Comment by edloidas** [comment]
Bug 1 should be fixed in PR #4905, with [commit](https://github.com/enonic/xp/pull/4905/commits/8bede5974e20df90bd05057006877fc6bf78f55b).
