### ISSUE TITLE
Applications - Installation from Market - 6.10.0 applications not listed

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#4838]
Since latest fix of the market app, the behaviour is a bit different now:
6.10.0 applications are not listed in 6.9 (which is nice) but there are not listed in 6.10 too :(

I guess it is a market issue again, but I guess 6.10 should not be released before this is fixed

**Comment by jsi** [comment]
Ooops.  No, definitely not, but if we can determine the issue can be fixed in market, then RC2 may still be released.  Please check as soon as possible.

**Comment by GlennRicaud** [comment]
You can release RC2 I think. It is clearly linked to the other bug fix that was done on the market app

**Comment by jsi** [comment]
👍

**Comment by GlennRicaud** [comment]
Checked later yesterday and this morning and it was suddenly working. It was maybe caching of this resource. I closed this issue
