### ISSUE TITLE
Improved filtering for Fragments in content studio search

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#4844]
Being able to store parts as fragments is a powerful feature in XP. But, when you end up with hundreds of different fragments (which you easily do in larger corporations) you will struggle to search for specific ones.

A good structure and naming convention will get you a few steps on the way, but if we could just add one more search filter option we could help a lot.

Add a filter for type of fragment (name of containing part/layout) - like "part: call-to-action", "layout: 2 col", "part: footer". This would show all the different "types" of fragments stored in XP and give the editor an easier way to find their needle in the haystack. They can then find a fragment called "Frontpage, click to win" made out of the part "call-to-action". Today there is no way of knowing which part/layout is running "behind" that name when you just search for fragments in Content Studio.

Note: the naming/definition of type of fragment need not be over-complicated. One part would be named with the part's name, a layout with the layout's name, more complex fragments should get names that isn't complicated to program, like "Layout with 4 parts" or "Layout with 2 regions and 3 parts" (unless listing each part is easier).

The most common scenario for end users is to create fragments out of one single part, and thus asking themselves questions like "show me all call-to-action fragments, name being something like %frontpage%". Today, and on sites with hundreds of fragments, we cannot help a user finding what they need.

**Comment by mortyeriksen** [comment]
We will add a tag field on fragments. It should not be part of _allText since it's just for administrators.

**Comment by mortyeriksen** [comment]
The fields should be below settings. Need to be searchable from admin.

**Comment by srs** [comment]
We will use a label system for this. See #4907 for real issue. Closing this.
