### ISSUE TITLE
Make the OrderExpr java-api more fluent

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#4847]
Create helpers for creating OrderExpressions
e.g
```
final FieldOrderExpr orderByPickupTime = FieldOrderExpr.create( IndexPath.from( "pickupOrDeliveryTime" ), OrderExpr.Direction.ASC );
```
->

`OrderExpr.field("pickupDevliberyTime", OrderExpr.Direction.ASC)`

**Comment by srs** [comment]
Would this break or could we do it without breaking?

**Comment by runarmyklebust** [comment]
We wont break anything, just adding helpers
