### ISSUE TITLE
First snapshot on large installations times out

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#4853]
I have seen this at customer installations;

when doing the first snapshot of an installation with a lot of data, the snapshot-operation times out and gives an exception. Try to recreate, and see if its possible to crank up the timeout for this particular operation

**Comment by rymsha** [comment]
@gbbirkisson @hjelmevold can you confirm this bug is still reproducible?
If yes, please provide a stacktrace, if no - let's close this issue.

**Comment by rymsha** [comment]
This hasn't been an issue for quite a while. closing.
