### ISSUE TITLE
Internet Explorer doesn't handle self-closing tags, typically in uploaded SVG's

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4860]
If you use utext to inline a SVG file which is uploaded to Enonic XP, it will often fail in Internet Explorer because SVG files typically have self-closing tags inside them.

For example ```<path ... />```
Rather than ```<path ...></path>```

I've made a js method to rewrite SVG files so they don't contain self-closing tags.

It would be nice if Enonic XP did this instead, automatically and by default.

**Comment by mortyeriksen** [comment]
We want to add this to lib-util. Is it possible for you to add the code you have? Is it fast enough, or should we do it differently?

**Comment by ComLock** [comment]
I don't know about the speed of it, and I'm uncertain about how good it is, it might be buggy.

It would have been cool to have access to a fully featured SVG optimizer instead.

This one is unfortunately is node based and has dependencies:
* https://github.com/svg/svgo
* https://github.com/svg/svgo/blob/master/package.json#L50-L57 Dependencies
* https://jakearchibald.github.io/svgomg/ Web interface

Maybe there exists a good java SVG optimizer?

Reference to my code:

https://github.com/bring/kp-suite/blame/master/lib-backend/src/main/resources/site/mixins/svg/index.es6#L85-L92

```
replaceSelfClosingTags() {
        // TODO: Handle / and > in attributes?
        // They should be html encoded though, but that might not be the case?
        // > --> &gt;
        // / --> &#x2F;
        this.utext = this.utext.replace(/<\s*(\S+)\s*([^\/>]*)\/\s*>/g,'<$1 $2></$1>');
        return this; // chainable
}
```
