### ISSUE TITLE
Error "404 Not Found" appears in the new-site wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4875]
Error :Admin application [com.enonic.xp.app.contentstudio:undefined] not found
1. press New and select 'site'
BUG: 
1)error appears on the wizard
2) try to add new OptionSet(Features) - see the first screenshot
3) try to add the HtmlArea content - see the second screenshot
![opt](https://cloud.githubusercontent.com/assets/3728712/25434819/82ed19c2-2a96-11e7-9919-20d756daf9f3.png)
![htmlarea](https://cloud.githubusercontent.com/assets/3728712/25435042/67d4e4ca-2a97-11e7-85bf-198352cfd32b.png)

**Comment by srs** [comment]
Ok, will check the html-area too.

**Comment by srs** [comment]
Same error. Closing.
