### ISSUE TITLE
lib task delayed execution/scheduling

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4882]
I don't know how it's handled in the cron app, but perhaps task scheduling should be available in the task API?

**Comment by ComLock** [comment]
Side-note: What should happen to tasks scheduled in the future if the Enonic XP server is restarted before that time...

I guess recurring tasks is also needed.

**Comment by srs** [comment]
We have this in our backlog. The cron-app is there for doing this right now, but in the future it will be available in the API. 

Closing this for now since we have it in our backlog.
