### ISSUE TITLE
issue with custom permissions: Read permission is denied, but the content is visible

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4884]
1. Add an User
2. login with the SU and add a folder
3. open the folder and add custom  permissions.(see the first screenshot
![perm](https://cloud.githubusercontent.com/assets/3728712/25489866/dc136528-2b73-11e7-8de9-12889b9859b6.png)

4. login with the user
ISSUE : Read permission is denied, but the content is displayed in the grid
![grid](https://cloud.githubusercontent.com/assets/3728712/25490002/3c7b0826-2b74-11e7-9a53-25bf18a13f21.png)

**Comment by ashklianko** [comment]
@sgauruseu , this is expected behaviour, content is read-only when user doesn't have modify permission and you specifically added those :)

**Comment by ashklianko** [comment]
Content remains visible because user has principal 'Content Manager app' with 'Can Read' permission; Content is not shown in grid after principal removed from content's permissions. Thus consider not an issue. @alansemenov ?

**Comment by alansemenov** [comment]
Yes, this is correct behaviour
