### ISSUE TITLE
Disable "Create Issue" button when all items are published

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4891]
When all of the items are published, the Create Issue button is still enabled. We should disable it.

![image](https://cloud.githubusercontent.com/assets/11612490/25614302/b6e631ce-2f31-11e7-865c-410c6ecd5564.png)

**Comment by edloidas** [comment]
The fix was included (committed) as part of the [PR for #4833 task](https://github.com/enonic/xp/pull/4905).
