### ISSUE TITLE
If an app is missing, one click install if on market?

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4897]
Would it be an idea to make it possible to one-click download and install and app if it is availble on market?

![screen shot 2017-05-03 at 10 10 24](https://cloud.githubusercontent.com/assets/118847/25652507/dc9ba82e-2fe8-11e7-89db-bd2e822a6f8f.png)

**Comment by mortyeriksen** [comment]
We don't want to prioritize this right now. We have some other ideas around dependencies across apps and linking between apps. We will get back to this later.
