### ISSUE TITLE
Allow issues with existing title

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4911]
Looks like we don't allow creating a new issue if another issue with the same title exists. This is wrong - we should use id and not title for uniqueness, it's not the same as with content. 

Fix it by adding postfix (-1, -2 etc.) to issue path if a duplicate exists.

![image](https://cloud.githubusercontent.com/assets/11612490/25795473/bf5cead4-33d5-11e7-9eb9-6dc297d8cbb7.png)

**Comment by srs** [comment]
Shouldn't the path be just a id - like on github? If you change the title, then the link will break or have a bad title in the link. So I think it's better just use a issue-number in path.

@sigdestad, what do you think?
