### ISSUE TITLE
Display Page Template info in the Details panel

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#4916]
In the list of "system data" for each content inside the Details Panel, it would be oh so ever handy to see the answer to a very common question on all training sessions I've held: what Template is running?

Add "Template: Xxx" (preferable with a link to select that specific template in the content grid!).

Name of template should be its DisplayName.

If no template is used, that should be displayed like "No template set up" (not linked anywhere), if automatic is used, then that should also be specified with "Template: automatic (Articles)" so that you always can find the correct info (without clicking 10 times and finding this info deep within the Page Editor).

And of course, if template is custom, "Template: Custom" is written (not linked anywhere).

![screen shot 2017-05-09 at 08 42 06](https://cloud.githubusercontent.com/assets/1465598/25838464/7cd46624-3493-11e7-95ba-9ae11741a1a1.png)
In here is a most perfect place to put this kind of data! Many have requested it.

**Comment by mortyeriksen** [comment]
Show the same way as in edit mode. Link to edit.

**Comment by alansemenov** [comment]
No template:
![image](https://cloud.githubusercontent.com/assets/11612490/26672864/0ff7c8ae-46bb-11e7-924a-1ab66fb5b07d.png)

Custom template:
![image](https://cloud.githubusercontent.com/assets/11612490/26672832/f5faeba2-46ba-11e7-992c-fcf0e0828e19.png)

Automatic template (the tooltip says "Automatic"):
![image](https://cloud.githubusercontent.com/assets/11612490/26674027/300a88d0-46bf-11e7-8332-77a2e028103f.png)

Selected template (no tooltip):
![image](https://cloud.githubusercontent.com/assets/11612490/26674112/8ac4ceca-46bf-11e7-86c0-96b0920f236a.png)

**Comment by Bellfalasch** [comment]
Nice. But didn't @mortyeriksen and @sigdestad mention that this should be added as a box of it's own? Not important for me though, but we need two lines of info. Depending on tooltips on hover is a bit annoying and not obvious, also not very accessible.

The information for a page template is two lines: 
First line being one of these: Custom / Automatic / Manual (user selected one specific template manually)
With the second line being either a template or a page controller (for "Custom" the controller is displayed). The second line is not displayed when manually selected a specific template.

This is how it looks when editing a content and inspecting what is used to display it.

![screen shot 2017-06-06 at 10 31 10](https://cloud.githubusercontent.com/assets/1465598/26820613/b2271486-4aa3-11e7-82d0-5873d421f4b0.png)
