### ISSUE TITLE
Restrict component support per regions

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#4919]
For each region defined, possibility to add restrictions as a developer. Default is to allow everything.

```
<regions>
  <region name="main">
    <allows>part:my-part</allows><!-- folder name for the part -->
    <disallows>layout:my-part-2</disallows><!-- prepend with type, default is "part:" -->
    <disallows>images:*</disallow><!-- you can disable (or enable) adding of Image Component, Fragments, and Text (and any other future built-in component) -->
  </region>
</regions>
```

Should be supported in both Page components and Layout components (any component that defines regions).

Should have allow and disallow possibilities so it is easy for developers to add only one part, or remove only one part. Example: disallow part "Menu" in the region called "Footer", or allow only part "Address" in region "Contact".

Going deeper this could use occurrences too, `<allow minimum="1" maximum="0">my-part</allow>` so that you can control amounts of each part, or even let the parts be automatically added when minimum is more than 0. This might however be very corner, but something to evaluate when designing the task as a whole. But used well it gives the developers that needs it more control. We could also add this on the `<region>` node, restricting total amount of components that can be added to it (or demanding at least X components be added.

This would be part of the validation process of the content, meaning not valid page design will not be possible to publish.

This feature would give the developers, that needs it, much more control over how the pages, templates, and parts are set up and used. It's too easy today to add for instance a full-width search part outside of the narrow `<aside>` it belongs to in Superhero, or too easy to add article-show inside the sidebar. Many many possibilities for web editors to ruin a website.

I'm well aware this might be best suited for 7.0. But it has been asked for since our very first training session, and at least restricting what part(s) per region would be very handy.

Requested by developers at Gjensidige, but also asked for on many occasions during our developer training sessions.

**Comment by mortyeriksen** [comment]
We will not implement this now. One possibility is to use the checklist to verify the content.
