### ISSUE TITLE
Show placeholder text inside the URL field of the Insert Link dialog

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#4921]
Web editors doesn't know what "http" or "https" is, less what a protocol is, or that you need to add it to all links. I've seen too many links now being added in the TinyMCE that are missing the protocol part, meaning the URL will fail on click.

If protocol is missing for any custom URL added from TinyMCE insert link (type URL) then automatically prepend it with "http://". Meaning, if user types "www.vg.no" (invalid link, will not work) just add "http://", but if they type "https://mybank.com" don't add anything, or if they type "mailto:something" or "ftp:something" or "//something", don't add anything since all these are valid ways of specifying a protocol.

Also, don't fall into the trap of just looking for "first3chars != www" since you can have infinite amount of sub domains like "member.gjensidige.no" that also is invalid since it is missing its protocol.

This functionality can be added visually in TinyMCE insert link dialog. Or in portal.processHtml.

I've had many rounds now lately with NSB around this, also common mistake during training sessions. A lot of users just don't know that the protocol is important, and we should expect them to either.

**Comment by mortyeriksen** [comment]
For insert url we will add a placeholder text (grey): https://example.com/mypage
