### ISSUE TITLE
Move dialog dropdown list doesn't expand fully if site in content studio was expanded

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#4924]
In Latest Chrome, Firefox
Appeared throughout 6.10 development, but problems reproducing. Easy to reproduce in the releases of 6.10.x.

* Go into Content Studio
* Expand your site content to see all children
* Click and select one of it's children
* Click on the Move-button
* Click the drop down arrow to the right in the Move dialog
* The drop down is only one item tall
* A few milliseconds later the content "jumps" (probably because it's first now that the actual site content is opened inside the dropdown), but still the height of the dropdown reminds one item tall
* Close it and open it again and the height is calculated properly and the dropdown is useful again

This is how the bug looks now (on first click on the arrow button - right hand side of input field):

![screen shot 2017-05-10 at 15 00 03](https://cloud.githubusercontent.com/assets/1465598/25899887/de66a1aa-3591-11e7-8f34-65e05a6ca8a2.png)

This is how it should be (even the first time):

![screen shot 2017-05-10 at 15 00 09](https://cloud.githubusercontent.com/assets/1465598/25899904/ec4b3768-3591-11e7-83d3-1fc0890b6dc8.png)

**Comment by Bellfalasch** [comment]
Looks important: you need to expand/open the site content in Content Studio, or else the list of items in the tree view inside Move dialog won't expand either.

**Comment by alansemenov** [comment]
@edloidas We should also fix the last part that Bobby mentioned - the tree inside the Move dropdown must always be collapsed by default. It should not in any way depend on whether nodes are expanded in the grid.
