### ISSUE TITLE
Auth lib - Login - Session timeout

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4934]
When a user logs in via some SSO, the SSO will typically return a expires_in property.

When implementing an idprovider I want to respect that property, so that your login to Enonic XP will expire when your SSO login expires.

Having an expiresIn parameter to login, could be a good place to support it.

One should also consider that some SSO's will update the expires_in property, for example when using oauth2.0 refresh tokens.

To support that perhaps there could be a refresh method in the idprovider which is called on every request that requires a user to be logged in. Sorta like a filter.

ref: https://discuss.enonic.com/t/auth-login-expiresin-seconds-and-idprovider-refresh-method/997

**Comment by mortyeriksen** [comment]
@GlennRicaud Can you investigate what needs to be done?

What about expire for simple id provider?

**Comment by GlennRicaud** [comment]
Okay,
Will check what has to be done in Enonic XP and Auth library.
And adapt simple ID Provider to use it as an example

**Comment by GlennRicaud** [comment]
Added parameter 'sessionTimeout' on login function of auth library
