### ISSUE TITLE
Enable showing status in Content selector

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4936]
Add an option to show content status in the selector's dropdown. This is important, for example, when adding items to a publishing issue where we want to see current status of items. 
It should work in both flat and tree structure.
Use the same styling as in the Publish dialog.
```xml
<input name="name" type="ContentSelector">
  <label>Cited In</label>
  <occurrences minimum="0" maximum="0"/>
  <config>
      <showStatus>true</showStatus>
  </config>
</input>
```
![image](https://cloud.githubusercontent.com/assets/11612490/25994037/89101282-370c-11e7-8466-583a0da4b91c.png)

When done, turn it on for the content selector inside "Create Issue" dialog.

**Comment by RF0** [comment]
It would be a nice feature for a later version to also allow this extra field in a custom selector, that could be used for status or something else entirely.
