### ISSUE TITLE
Content type icons are not properly rendered in the Dependencies widget (only MS Edge)

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4944]
Icons of some content types are not properly rendered inside the Dependencies widget on MS Edge. Folders for example:

![image](https://user-images.githubusercontent.com/11612490/30536962-36b30582-9c68-11e7-854f-607096c4db7c.png)

**Comment by vbradnitski** [comment]
Can't reproduce in MS Edge on 2 different systems
