### ISSUE TITLE
Publish Wizard - incorrect tooltip for the Remove -button

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4945]
1. select a site with some not valid child contents
2. press the Publish button
3. move cursor to the Remove button(see on the screenshot)
BUG: tooltip is 'Edit invalid content' but actually clicking on the button removes the item from the list
![tooltip](https://cloud.githubusercontent.com/assets/3728712/26095625/eedc4a50-3a26-11e7-93f2-69e73fd6df2f.png)

**Comment by alansemenov** [comment]
The problem here is that tooltip for the entire row is shown when hovering over the X icon as well. Adding own tooltip "Exclude from publishing" for the X icon should solve this.
