### ISSUE TITLE
Edge specific bug: HtmlArea, Insert Image  dialog - button insert is not available

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4949]
1. select a site and start to add a HtmlArea content(2 max 4)
2. click on the Insert image button on the toolbar and try to insert a pretty big image
BUG: Insert Image dialog appeared, but Insert button is not available
![insert_img](https://cloud.githubusercontent.com/assets/3728712/26098535/c0473484-3a30-11e7-9c64-e04e00ee4c2b.png)

**Comment by alansemenov** [comment]
@sgauruseu 
What does "is not available" mean? It's not obvious from the screenshot. Is it not rendered? Or the modal dialog is so high that the button is out of the view? In this case it might have been fixed by #5498

**Comment by alansemenov** [comment]
This looks fine now
