### ISSUE TITLE
Refresh the issue list dialog on issue server events

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#4961]
Farther improvement of #4938

We should update active (open) dialog with issue list upon receiving issue event from the server - whether a new issue was created or an existing one updated.
Mask the dialog and show the spinner while updating the dialog contents. Make sure user stays on the same tab.
Show info notification (the blue one): "The list of issues was updated" (only if the dialog is currently open).
Would be nice to add debounce of this event handling so that we don't update/notify more than once every 3 seconds, for example.

**Comment by ashklianko** [comment]
@alansemenov Please also check that #49825 is gone
