### ISSUE TITLE
Implement remove-function in cache.js

### ISSUE THREAD

**Issue by srs** [enonic/xp#4968]
Implement remove-function in cache.js. This should remove one single entry in the cache:

```js
cache.remove('key');
```

Also implement a regexp alternative that implements multiple keys. 

```js
cache.removePattern('a.+');
```

The implementation of the last one should do the following:

1. Get all keys
2. Filter the keys with regexp
3. Use cache.invalidate(keys)

**Comment by aro** [comment]
Moved to enonic/lib-cache/issues/1
