### ISSUE TITLE
Details Panel - link 'Edit permissions' should not be displayed if an user has no permissions to the content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4976]
Bug reproducing when there are contents that allowed for changing of permissions by the user
1. add an User
2. login with the user 
3. click on the content with 'Can Write' permissions for the user and open the Details Panel
   'Edit Permissions' is displayed,(Ok)
4. click on  the content with 'Can Read'
5. look at the details panel:  'Edit Permissions' is displayed, this is wrong behavior, because changing of the permissions are not allowed for this user
6. Click on 'Edit Permissions' link
7. modify permissions on the modal dialog, click on the Apply
BUG: error appears in the console
![perm](https://cloud.githubusercontent.com/assets/3728712/26311624/a541f82c-3f0d-11e7-94db-18865c9421d0.png)

**Comment by jsi** [comment]
Sorry for "testing in production" here.  I am just using this issue to verify that the latest version of the changelog-generator works correctly with all tags.  I will remove those tags above soon.

**Comment by jsi** [comment]
Removed the tags again.  Testing was successful.  :)
