### ISSUE TITLE
Exception when two layouts were swapped in the PageComponentView 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4986]
1. open a site wizard
2. open the PageCompView
3. Insert  '3-col' layout and '25/75' layout
4.  swap layouts (click on the '3-col' layout and drag it down). 
5. try to back the original order of layouts - click on the '3-col' layout and drag it up
BUG: error in the console
![swap](https://cloud.githubusercontent.com/assets/3728712/26352626/31982000-3fc5-11e7-9177-0975fa23e4cc.png)

**Comment by alansemenov** [comment]
I'm getting a different error:

![image](https://user-images.githubusercontent.com/11612490/27323015-58ff2d8c-55a0-11e7-8674-9f51bcbd9dea.png)

**Comment by ashklianko** [comment]
Was going to commit a fix, but @mta have just also made a PR that solves it: #5193
