### ISSUE TITLE
Can not set maximum="0" on options in option-set

### ISSUE THREAD

**Issue by gustafekeberg** [enonic/xp#5001]
I'm trying to create an option-set where you should be able to select all of the available options. To make this work i have to set the options maximum attribute to the number of options or greater.

When defining occurrences for inputs we can set `maximum="0"` when we want to repeat an input infinitely, could this work the same for option-sets? If `maximum="0"` is set it should be possible to select all of the options no matter how many.

It's especially when adding more options that you can forget to update the maximum allowed options.

I can't think of a case where you would present the options but not let anyone select them, which is the what happens when `maximum="0"`.

Here you can't select anything:
```xml
<option-set name="options">
	<label>Options</label>
	<expanded>false</expanded>
	<occurrences minimum="0" maximum="1"/>
	<help-text/>
	<options minimum="0" maximum="0">
		<option name="option_1">
			<label>Option 1</label>
		</option>
		<option name="option_2">
			<label>Option 2</label>
		</option>
	</options>
</option-set>
```

Here you can select everything:
```xml
<option-set name="options">
	<label>Options</label>
	<expanded>false</expanded>
	<occurrences minimum="0" maximum="1"/>
	<help-text/>
	<options minimum="0" maximum="2">
		<option name="option_1">
			<label>Option 1</label>
		</option>
		<option name="option_2">
			<label>Option 2</label>
		</option>
	</options>
</option-set>
```

**Comment by alansemenov** [comment]
Hi Gustaf

You have a valid point here. We are adding this issue to our backlog, it will be implemented in the next version of XP.
