### ISSUE TITLE
ApplicationBrowseItemPanel - Titles for id-provider are not correct

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5004]
One ui-test is failed due to this issue
1. select an application with idprovider(app-auth0-idprovider)
BUG:  titles are not correct
![prov](https://cloud.githubusercontent.com/assets/3728712/26441320/b1c3de80-4138-11e7-90d9-45724f6dcd65.png)

**Comment by alansemenov** [comment]
@srs Localisation aftermath?

**Comment by srs** [comment]
No, user-app has not been localized yet.
