### ISSUE TITLE
Single quotes are missing in the notification message when an application was installed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5005]
One test failed due to this issue
1. Open applications and install an application
BUG:
expected notification message is     "Application 'Content Viewer App' installed successfully"
but actual is "Application Content Viewer App installed successfully" 

Part2 Don't  message should be present when an application has been started or stopped?

**Comment by alansemenov** [comment]
Yes, there should be notifications when an application has been started or stopped. Not sure why that changed.

**Comment by ashklianko** [comment]
Checked through the git history of related file (ApplicationBrowsePanel.ts) and can't see any track that we've been showing that notification on start/stop.
