### ISSUE TITLE
Add icon to the issue list

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5013]
Add icon to the list of issues (all tabs) as shown below. Circle over the icon should be @admin-green if the issue is Open and @admin-red if the issue is Closed. 

![image](https://cloud.githubusercontent.com/assets/11612490/26496254/0b0aaa8e-4227-11e7-8f4e-f73b72a5b027.png)

**Comment by sigdestad** [comment]
@ase  - I was more thinking the whole icon was green. Just drop the round bubble on top :-)

**Comment by alansemenov** [comment]
Hmm... What color will the icon for Closed issues be then?

**Comment by sigdestad** [comment]
Red?
‌‌

**Comment by alansemenov** [comment]
I don't like red - red means something is wrong. Maybe it should be darkgrey then, as on the image (without the circle, of course).

**Comment by sigdestad** [comment]
Like disabled?
