### ISSUE TITLE
Mobile resolution - Don't unhighlight grid item and always open Preview Panel on click 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5019]
1. open browse panel and click on any row, preview panel and 'Show Details Panel' is appeared
2. click on the Back button,  navigate to the grid again
ISSUE:
need to click twice on the row to open the Preview Panel again
![preview_panel_mob](https://cloud.githubusercontent.com/assets/3728712/26541890/54af52da-4460-11e7-866d-e7164661e21f.png)

**Comment by alansemenov** [comment]
In mobile res we should not unhighlight an item on click, instead we should always show the preview panel on click. Another alternative is to get rid of highlighting at all in the mobile mode (its purpose is to function as a cursor which doesn't make sense on mobile), but I believe it's more work.
