### ISSUE TITLE
Mobile resolution - "Instantly delete..." checkbox is too wide

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5022]
1. Set size of browser to 480x800
2. Select a site(Online) and press the 'Delete' button
BUG: the label overlaps the button on the modal dialog

![overlap](https://cloud.githubusercontent.com/assets/3728712/26551889/5e06bf4e-448d-11e7-8624-3fd16882e6b9.png)

**Comment by alansemenov** [comment]
It's ok to shorten the label to "Instantly delete" on low-res.
