### ISSUE TITLE
Mobile resolution - ImageEditor dialog doesn't fit the viewport

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5023]
1. set 480x800 and open an image
2. click on the button-crop and try to crop the image
BUG- 'Apply' and 'Close' are not available
![imageeditor](https://cloud.githubusercontent.com/assets/3728712/26554654/0be98fb8-449a-11e7-8e11-a5b5a8ffd85f.png)

**Comment by alansemenov** [comment]
The editor toolbar and zoom control also have wrong width.
