### ISSUE TITLE
Mobile resolution - Link 'Show Results' should not be displayed when the Search input is empty

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5025]
This issue is reproducing only on 480x800
1. Navigate to users
2. click on the 'icon-search' and open the FilterPanel
BUG: 'Show Results'  should not be present because search input is empty

![search](https://cloud.githubusercontent.com/assets/3728712/26555303/178de3a2-449d-11e7-8a3c-8b721475d19c.png)

**Comment by alansemenov** [comment]
In mobile mode change text of the link depending on if the filter is applied or not.
When no filter applied: "Show all"
When the filter is applied: "Show results"
