### ISSUE TITLE
Mobile resolution - Install buttons are shown partially in the Install App dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5026]
1. open Applications on 480x800
2. Press the Install dialog
BUG: 
see the screenshot
![inst](https://cloud.githubusercontent.com/assets/3728712/26555561/48c029ac-449e-11e7-93b6-489eca2d7076.png)

**Comment by alansemenov** [comment]
We should use less padding around icons and smaller fonts in this resolution - try to use "vw" units for font size.

**Comment by ashklianko** [comment]
Adjusted scrollbar position relative to grid rows so they do not interfere, looks much better now. 
Tell me if padding and font still need to be adjusted.
