### ISSUE TITLE
Mobile resolution - ApplicationItemStatisticsPanel is not displayed when an application is selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5027]
1. set the 480x800
2. select an application
see the screenshot

![app-grid](https://cloud.githubusercontent.com/assets/3728712/26555671/e852afa8-449e-11e7-89d4-36343e2f6856.png)

**Comment by alansemenov** [comment]
The panel should slide up from the bottom like preview panel in the content grid
