### ISSUE TITLE
Feature request: REST API for deployments?

### ISSUE THREAD

**Issue by jonasws** [enonic/xp#5089]
Would it be possible to provide the same set of actions, or a subet, as the Application Manager as a REST endpoint? I would simplify the process of deploying applications originating from for example CI servers, as now one has to deploy manually to all the nodes in the clusters.

**Comment by srs** [comment]
We have an API for installing (deploying) applications via REST already. It's not documented but here's the actual code https://github.com/enonic/xp/blob/master/modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/ApplicationResource.java

You can also use the toolbox that's bundled in our distro.

**Comment by srs** [comment]
Do you need to push config too?

**Comment by jonasws** [comment]
I'm not sure, most likely this could be achieved in other ways, such as a cron polling config from an S3 bucket etc. Thank you for pointing me to the API!
