### ISSUE TITLE
Always show Back icon in the issue details dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5097]
When issue dialog was opened from the issue list there's Back icon to close the dialog and go back to the list. But when an issue was opened via direct link, we hide it (since there's no list to go back to). 

![screen shot 2017-06-14 at 13 11 34](https://user-images.githubusercontent.com/11612490/27129559-2f193e32-5103-11e7-99d1-71db2ed9176a.png)

Change it so that the Back button is always visible and it's always possible to go to the Issue list, even if the issue was opened by direct link. Also test that when we open the details dialog after creating a new issue (#5096) the Back button is also visible.

I guess that means that if we open the details dialog not from the issue list, then we should always open/load the issue list dialog (but implicitly, so that it's not visible) to be able to quickly show it when the Back button is clicked.

**Comment by ashklianko** [comment]
Done in PR #5101
