### ISSUE TITLE
Replace Back button with an icon in Create Issue and Schedule dialogs

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5098]
In the Publish wizard there are options to Create an issue or Schedule publishing, both of which open a new dialog with "Back" button in the bottom left corner. Replace this button **in both dialogs** with the icon in the top left corner like the one we have in the Issue details dialog.

![screen shot 2017-06-14 at 13 39 59](https://user-images.githubusercontent.com/11612490/27130631-61d5e312-5107-11e7-9c10-6db883ed3760.png)

**Comment by ashklianko** [comment]
Done in PR #5101
