### ISSUE TITLE
Incorrect notification message, when user or user store is deleted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5116]
1. select an existing user and delete it .
BUG: incorrect notification message appears, see the screenshot
The same issue when User Store or Role was deleted
![notification-mess](https://user-images.githubusercontent.com/3728712/27275308-7a5001d0-54df-11e7-8aee-f34a512321b7.png)

**Comment by edloidas** [comment]
@alansemenov Should be already fixed as part of the localization updates in "Localization of CSS #5077" task.
