### ISSUE TITLE
Don't close 'Edit Permissions' dialog without warning, if something is not saved

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5120]
1. click on the 'Edit Permissions' link (details  panel)
2. change permissions
3. click on the Close button
Expected:  "confirm" dialog should be present if something was not saved

**Comment by alansemenov** [comment]
Same as with SiteConfigurator dialog - show confirmation when clicking either "X" icon or outside of the dialog.

**Comment by sgauruseu** [comment]
verified on the my local machine
