### ISSUE TITLE
Feature request: Library to assist GDPR compliance.

### ISSUE THREAD

**Issue by jsi** [enonic/xp#5121]
If we are serious about helping customers with GDPR compliance, we should make a library to help with some of the tasks that GDPR compliant web-sites need to perform:
 - Simple method to retrieve all data stored about one user.
 - Pseudonymization of data that is processed statistically.
   - This could be pseudonymizing a set of data, or storing a datanode under a pseudonym.
 - Encoding of a data set.

**Comment by srs** [comment]
The first point here is problematic. I think this is a bigger issue and needs to be evaluated. Denied by PAB.
