### ISSUE TITLE
Customize CKEditor's toolbar 

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5130]
Customize the default configuration of the toolbar so that we have the same set of tools as we do now. Implement support for custom configuration via HTML Area schema. 

http://docs.ckeditor.com/#!/guide/dev_toolbar

**Comment by alansemenov** [comment]
Also, don't forget that toolbar should only become visible when the HTML Area gets focused.

**Comment by ashklianko** [comment]
Sure

**Comment by alansemenov** [comment]
@ashklianko 
There were a few small things to fix, see if you can do this in one of the next PRs:
* The footer of the area is now always visible (also in TinyMCE), we should hide it when the area is not active
* Remove the "Code" (it doesn't work because ``<code>`` tag must be placed inside a container element, btw) and "Create Div container" buttons
* Move "Block quote" inside the group of buttons to the left
* Remove 20px margin inside the HTML Area's body element
