### ISSUE TITLE
Set node-type to "Issue" for issues

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#5137]
See ContentConstants-class:

  public static final NodeType CONTENT_NODE_COLLECTION = NodeType.from( "content" );

**Comment by ashklianko** [comment]
@runarmyklebust , currently for issues we set nodeType during creation with this variable:
public static final NodeType ISSUE_NODE_COLLECTION = NodeType.from( "issue" );
Seems consistent with ContentConstants.

**Comment by runarmyklebust** [comment]
Ok, then its ok. Thanx
