### ISSUE TITLE
Handle unsupported HTTP methods

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5157]
https://enonic.zendesk.com/agent/tickets/2024

**Comment by jsi** [comment]
This bugfix has been promised to a customer, so 6.11.0 depends on this.

**Comment by GlennRicaud** [comment]
Yes, I put the milestone 6.11 when I created the issue.

So basically the problem here is that the server receives a request other than : GET, POST, HEAD, OPTIONS, PUT, DELETE, TRACE
Another point is that the customer does not want it to pollute the logs.

Proposition 1:
Since we extend HttpServlet I propose to have a canHandle method. If it is not handle, then forward to the default behaviour of HttpServlet (an error page with a status 501).
Code example: https://github.com/enonic/xp/compare/594ba59a85c25961fd559bc9cfac47bb67f62e40...issue-5157-proposition

Proposition 2:
We could also handle it the same way as a failure from a WebHandler throwing a WebException( HttpStatus.METHOD_NOT_ALLOWED, String.format( "Method %s not allowed", method )

Proposition 3:
We should handle the WebDAV headers and add these methods to com.enonic.xp.web.HttpMethod. (But we should still handle better unknown http methods)

**Comment by srs** [comment]
Hi. I committed code that implements proposition 3. But no good way to handle unknown http-method for now. We should refactor in the future so *any* http method-method could be used.
