### ISSUE TITLE
Error in the console and issues list is empty, when Issues Dialog is opened and assigned user had deleted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5167]
1. Go to Users and add new user.
2. open CS , select a content and create new issue, assign in to the user
3. Go to Users and delete the user.
4. go to the CS and try to open 'Publishing Issues' dialog
BUG: list of issues is empty and error is present in the console
![issues-d](https://user-images.githubusercontent.com/3728712/27389281-9ec7facc-56a6-11e7-9fd0-3450b91adae9.png)

**Comment by alansemenov** [comment]
We should handle this in both the list and the details dialog
