### ISSUE TITLE
Content display using a site mapping fails in edit view

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5169]
To have a display for a content:
  * You can have a template that matches the content
  * You can apply a page controller on the content.

But another possibility is that
  * You define a site mapping for this content type.

In that case
  -> The display in portal mode of the content works
  -> But the display in edit view does not work. There is a spinner that never ends
  -> There is also the fact that the preview button is not displayed in edit mode (but in is enabled in , but I am not sure we can/should do something there or if it is a consequence of the previous bug

- [ ] Fix the spinner bug

**Comment by alansemenov** [comment]
@GlennRicaud We need a bit more info here. I tried uncommenting this code in OfficeLeague's ``site.xml``

```xml
    <mapping controller="/site/pages/pwa/pwa.js">
      <match>type:'com.enonic.app.officeleague:info-page'</match>
    </mapping>
````
but when I set up an Info page it fails to render a preview because of missing pwa.html

Please provide detailed info on how we can reproduce this.

**Comment by alansemenov** [comment]
@GlennRicaud Please provide more info on how we can reproduce this.

**Comment by GlennRicaud** [comment]
Example of steps to reproduce the bug
1 - Deploy App Features

2 - Create an article under the site 'Features'

3 - Add the following mapping to the site descriptor
<mapping controller="/site/pages/no-regions/no-regions.js">
  <match>type:'com.enonic.app.features:article'</match>
</mapping>

=> The preview of the article is correct

4 - Edit the article and show the page editor
=> The page editor displays correctly the content but a spinner is present on top of it
![screen shot 2017-07-31 at 09 31 29](https://user-images.githubusercontent.com/12030113/28767238-3045e144-75d3-11e7-8cdc-3158bfbf2365.png)
