### ISSUE TITLE
Add "Save as Template" action to context menu of the page node in Page Component View

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5186]
See conditions for showing the action in #5185. Should work exactly the same as the "Save as Template" button in the Inspect panel.

![image](https://user-images.githubusercontent.com/11612490/27479733-7166d1f0-5815-11e7-8f2d-e81505824953.png)

**Comment by pmi** [comment]
Added as second commit to https://github.com/enonic/xp/pull/5307 as it depends on https://github.com/enonic/xp/issues/5185
