### ISSUE TITLE
Test: Verify that issues works on existing installations

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#5208]
Use an existing pre 6.11 version of xp with data, upgrade to 6.11 and verify that issues works as expected. Use e.g data-toolbox to verify that the /issues/ - folder is added to the cms-repo, and that the ACL is set correctly etc.

**Comment by jsi** [comment]
Looks good.  Took a back-up of Enonic from 6.9.4 and installed it.  Then did the upgrade.  No problem working with issues.  Good thing I didn't have an SMTP server, or Runar and Alex would have been spammed a lot from my testing.  :)
