### ISSUE TITLE
Support custom image scaling in HTML Area

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5216]
We now support several fixed scaling styles inside the Insert Image dialog:
![image](https://user-images.githubusercontent.com/11612490/27583560-22d867f6-5b35-11e7-98e4-026e39d23a97.png)

Applying one of these styles to an image will add ``scale`` parameter to the image url, for example "?scale=4:3".

**Part 1**: In case user sets custom value in the ``scale`` parameter, we should add a new option "Custom (X:Y)" to the bottom of predefined scaling options. It should be shown **only** if there's ``scale`` parameter and **only** if its value is not among predefined options. It should also be selected in the dropdown, of course:

![image](https://user-images.githubusercontent.com/11612490/27584139-2d7e6ece-5b37-11e7-8f9f-d78e3181d001.png)

**Part 2**: After changing scale parameter, saving and reloading there are two "size" parameters in the "src" attribute. Not a big deal, but should be fixed as well.

![image](https://user-images.githubusercontent.com/11612490/27625954-9c8c943a-5be6-11e7-9a6b-052e2e72f972.png)

**Comment by ashklianko** [comment]
@ase, if we going to switch tinymce witj CKEditor, is this task relevant?

**Comment by alansemenov** [comment]
Yes, we need this in 6.11 - @aro needs it for cms2xp. CKEditor is planned for future releases.

Good point, though :)

**Comment by ashklianko** [comment]
OK, thanks :)
