### ISSUE TITLE
Missing localized phrases in Users App

### ISSUE THREAD

**Issue by jsi** [enonic/xp#5218]
There are a number of phrases in the Users app which do not seem to have a representation in the Users app.

## App Name
- The App name is still in English (See screenshot under Action Bar).  Should it be?

## Tab title
- When creating a new user or a new group, the Tab title is "Unnamed Bruker" and "Unnamed Gruppe"  (See screenshot under Action Bar).  Bad mix of English and localized language.  Must be fixed.

## Action Bar
- The Save button (all other buttons on the action bar are localized):

![screenshot 2017-06-27 15 10 26](https://user-images.githubusercontent.com/477453/27589201-e660b6e6-5b4a-11e7-8dec-b7e68f4b6e7e.png)

## Dialogs
While the main text have an entry, none of the supporting/standardized fields seem to be localized:
- Headers/Titles have no entry (screenshot below: "Confirmation")
- Buttons like Yes/No does not either (same screenshot, "Yes/No")

![screenshot 2017-06-27 15 00 58](https://user-images.githubusercontent.com/477453/27588817-b97c2864-5b49-11e7-94b4-03b41be5af0e.png)

**Comment by jsi** [comment]
My test of this app is not very thorough.  Please check the source code for other hardcoded texts that should be localized.

**Comment by ashklianko** [comment]
@jsi, added missing phrases mentioned in issue and few more, please add norwegeian translation :)

**Comment by alansemenov** [comment]
All farther localisations will be done in #5246

**Comment by jsi** [comment]
Have reviewed the phrases_no.properties file for the user app, and it looks good now.
