### ISSUE TITLE
Support image size parameter in processHtml

### ISSUE THREAD

**Issue by aro** [enonic/xp#5223]
Support specifying a size parameter for images in an HtmlArea.
The "size" parameter if set indicates the width of the image, and should be used in the scaling done in `processHtml`.
If `"keepSize=true"` is set, then `"size"` should be ignored.
If `"keepSize" `is not set and `"size"` is set, then the size value should be used for the image width, instead of the current default value that is currently used (768).

Admin UI code should not remove or modify the "size" parameter when saving.

-----
Currently we support URLs with keepSize and scale parameters:
- image://a76ec725-b7f9-45dd-8ffd-e173476535e5?keepSize=true
- image://a76ec725-b7f9-45dd-8ffd-e173476535e5?scale=1:1&keepSize=true

The following should be supported and the size applied in processHtml when scaling:
- image://a76ec725-b7f9-45dd-8ffd-e173476535e5?size=120
- image://a76ec725-b7f9-45dd-8ffd-e173476535e5?scale=1:1&size=120

-----

This change is required for handling custom scaling in images exported from CMS.

**Comment by Bellfalasch** [comment]
"Scale width" scaling was used for this in CMS, and should be used also in XP.
http://docs.enonic.com/en/stable/reference/image-processor/scaling.html#scale-width
