### ISSUE TITLE
Incorrect confirmation about content being moved out of site

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5232]
1. Create a new site (or use existing)
2. Create a new folder under the site
3. Create some content in that folder (so that it's on the 2nd level compared to the site)
4. Select this content item in the grid
5. Click "Move" in the toolbar
6. Select the site to move the content from the folder one level up to the site
7. Click the Move button

Confirmation about content being moved out of the site pops up, but the content is not about to be moved **out** of the site, it's about to be moved **under** the site.

**Comment by ashklianko** [comment]
Not reproduced.
