### ISSUE TITLE
Edit action must be disabled when all selected items are read-only

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5241]
Both in the grid toolbar and the context menu.

![image](https://user-images.githubusercontent.com/11612490/27731224-71a9e4e6-5d8c-11e7-8151-b82cb5c731b6.png)

**Comment by ashklianko** [comment]
@alansemenov , even if we disable edit, you will still be able to open content for edit via direct link, should we do anything about it?
What if only one selected item is readonly? Is edit button supposed to be disabled?

**Comment by alansemenov** [comment]
> even if we disable edit, you will still be able to open content for edit via direct link, should we do anything about it?

It should still open the wizard via direct link and it's ok to open the wizard via double-click. It's "Edit" action that is confusing for readonly items (also in context menu).

> What if only one selected item is readonly? Is edit button supposed to be disabled?

No, but clicking the Edit action should open wizard tabs only for non-readonly items.

**Comment by ashklianko** [comment]
Ok, got it.
