### ISSUE TITLE
Event returned by eventlistener in lib-event is not formatted as a javascript object

### ISSUE THREAD

**Issue by RF0** [enonic/xp#5257]
An event returned by an eventlistener in javascript library lib-event returns a  toString() from an object. the value is not json and makes it hard to handle in javascript. the separator is = not colon.

"nodes": "[{id=13b2285c-9d57-4936-8916-c6ad908079a3, path=/content/dk/ansatte/kantinen, branch=draft, repo=cms-repo}]"

@srs suggests we should probably implement MapSerializable on the object and then handle it in the javascript bridge.

**Comment by GlennRicaud** [comment]
Was going to create this bug and just saw it at the top of the list. Perfect :+1:

**Comment by GlennRicaud** [comment]
@RF0 This will break your regexp. Your app will have to be adapted for 6.13
@GlennRicaud: Same for me for the guillotine app.

@aro: We should add something in the upgrade steps to 6.13
