### ISSUE TITLE
Issue Details dialog - Disabled Publish button should be shown when there's invalid content in the issue

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5268]
1. select invalid content and create new issue
2. open the Issue Details dialog

Problem: "no items to publish" is shown
Expected: Disabled Publish button should be shown instead of the text. "No items to publish" should be shown only when all of the issue items are Online.

![issue2](https://user-images.githubusercontent.com/3728712/27828448-f29aa168-60c4-11e7-9eac-f747f6e30650.png)

**Comment by vbradnitski** [comment]
https://github.com/enonic/xp/pull/5308
