### ISSUE TITLE
Localisation is not working in the Page Editor

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5274]
Open a site add an application and try to add controller.
Bug: localized message is not correctly displayed on the controller selector
The same issue with the Image Selector.

![controller](https://user-images.githubusercontent.com/3728712/27854601-221a85e2-6170-11e7-97db-4bb28ba07ce0.png)

![img-selector](https://user-images.githubusercontent.com/3728712/27856442-d8cbf48c-6176-11e7-9249-7443bbc500ca.png)

**Comment by alansemenov** [comment]
We have a common issue for all missing translations: #5246
Let's wait until it's done and closed - then we can start looking for things we missed.
