### ISSUE TITLE
Site Configurator dialog is not entirely masked by additional dialogs

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5275]
1. open  a site configurator dialog with a htmlArea.
2. try to insert image, link
3. BUG: when insert-modal dialog is opened, button Upload and Close should be disabled on the SiteConfigurator
![conf](https://user-images.githubusercontent.com/3728712/27854875-1580563a-6171-11e7-9c46-1d349039aa8a.png)

**Comment by alansemenov** [comment]
The upload icon should of course be masked and not clickable, as the rest of the masked dialog. 

But the "X" icon should in fact not be shown at all. It should follow the same behaviour as when you make changes in site config dialog and then click outside - a confirmation about unapplied changes will pop up and "X" of the bottom dialog will be hidden:

![image](https://user-images.githubusercontent.com/11612490/27901353-0f29028e-6232-11e7-9a6d-3e5cc8a9f384.png)

**Comment by ashklianko** [comment]
Also issue with PageComponentsView, need a separate task:
![image](https://user-images.githubusercontent.com/4255706/28011705-e49a6ffc-656b-11e7-9de1-acafa4a10bd2.png)
