### ISSUE TITLE
Control who/which privileges can use which content types

### ISSUE THREAD

**Issue by nerdegutt** [enonic/xp#5297]
With reference to [this discuss thread](https://discuss.enonic.com/t/best-practices-for-roles-and-permissions/1121), and a growing number of editors and roles in our installations, this is part two of [stuff we see a need to simplify in the content studio](https://github.com/enonic/xp/issues/5296) for users with limited privileges.

Based on informal testing, the "New" dialog confuses approximately 100% of users without XP experience. We see sites appearing here and there, and not even certified XP developers can explain what "base:unstructured" does. But most people can distinguish a "blog post" from an "office" content type.

I'd love to se a feature that would allow me as a developer, or perhaps a system.admin, to only show selected content types in the "New" dialog in content studio. Ideally, I'd also love a function that allowed me to skip this dialog entirely, if there is only a single content type allowed at a certain path for a certain principal.

I don't know enough about the inner workings of XP to see if this is possible to handle in a sensible way, but I'd be happy to drop by to discuss an implementation (seriously).

If it's extremely complex to implement a granular approach to this, an easy win would be to at least hide the "Site" and "Unstructured" content types from anyone but the expert roles.

**Comment by sigdestad** [comment]
We 100% agree that the newContentDialogue can be improved :-)
Here are some ideas:
- Add a concept of "tasks" (i.e. things user do often, such as "New blog post". Task will know content type and where to put it
- Creation of sites currently requires "content manager" role, but we should probably hide this more. 
- Unstructured can be hidden completely until further notice

We need to create a design and flow for how this could work. Any input you might have is appreciated.

**Comment by sigdestad** [comment]
Vi har nå opprettet issues for å fjerne unstructured, og skjule site for brukere uten rettigheter. #5467 and #5466

**Comment by sigdestad** [comment]
Improvements to the newContentDialog has been added to our backlog. The tasks above should be released with 6.12.
