### ISSUE TITLE
Create Issue dialog - Filter out assigness without publish permissions

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5304]
Only users of these roles should be shown in the Assignees selector:
     -Administrator
     -Content Manager Administrator
     -Content Manager Expert
     -Content Manager App
 
Note that if existing issue is assigned to a user that doesn't match this criteria, it should still be visible in the Issue details dialog (in readonly mode).

**Comment by alansemenov** [comment]
See comment in https://github.com/enonic/xp/pull/5363
