### ISSUE TITLE
Implement min and max config for Long input type

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5333]
Can be either only ``min`` or only ``max`` or both or none.

```xml
    <input name="requiredLong" type="Long">
      <label>Required Long</label>
      <indexed>true</indexed>
      <occurrences minimum="1" maximum="0"/>
      <config>
        <min>2000</min>
        <max>10000</max>
      </config>
    </input>
```

Validation messages (don't forget to transliterate them):
*The value cannot be less than ``<min>``*
*The value cannot be greater than ``<max>``*

![image](https://user-images.githubusercontent.com/11612490/28119933-d04b0ed8-6716-11e7-8ed5-1697feb60456.png)
![image](https://user-images.githubusercontent.com/11612490/28119974-f8a2aee0-6716-11e7-8891-3bc28ae92557.png)

**Comment by aro** [comment]
Shouldn't we also have some kind of backend validation?

**Comment by alansemenov** [comment]
We should.
