### ISSUE TITLE
Content Wizard has not been updated when an version of the content was restored

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5354]
Case 1:
-Add a shortcut content.(save it )
-Select a target and save it 
-Do not close the wizard and restore version without the target.
-Restore the version with target again
-click on the wizard tab
BUG: version with the target is restored, but target is not displayed(need to refresh the page for displaying of it)

Case2:
-Add a content with the ImageSelector
-Insert 2 images
-restore several version
See the screenshot
![img](https://user-images.githubusercontent.com/3728712/28306914-ceac04a0-6ba9-11e7-9fab-5155e7bdbfa2.png)

**Comment by sgauruseu** [comment]
Error in console, when NewIssueDialog was opened
_all.js:3024 TypeError: Cannot read property 'lastChild' of null
    at ensureCellNodesInRowsCache (http://localhost:8080/admin/assets/1500636996731/common/lib/_all.js:27676:45)
    at cleanUpAndRenderCells (http://localhost:8080/admin/assets/1500636996731/common/lib/_all.js:27737:9)

**Comment by vbradnitski** [comment]
fixed in master.
