### ISSUE TITLE
Image Selector content - image not displayed, when a saved content was opened

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5356]
1. add a content with the ImageSelector
2. insert an image
3. save all and close the wizard
4.open the content 
BUG: see the screenshot
![img-wizard](https://user-images.githubusercontent.com/3728712/28309487-3021bc72-6bb2-11e7-8a44-772a377761a9.png)

**Comment by vbradnitski** [comment]
fixed in #5354
