### ISSUE TITLE
ImageSelector -Error appears in the console, when an image was filtered and the option clicked

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5357]
Case1
1. open a htmlArea content
2. try to insert an image into the area : type a name in the option filter.
3. click on the image
BUG see the screenshot
![insertimg](https://user-images.githubusercontent.com/3728712/28315472-3799fea0-6bc7-11e7-9d6e-0aafd070fb73.png)

Case2:
1.Open a site, open the component view
2. try to insert an image-component
3. type a name of image, click on the option
![img2](https://user-images.githubusercontent.com/3728712/28315505-65c83b66-6bc7-11e7-90bf-d7e6447e3713.png)

**Comment by vbradnitski** [comment]
fixed in #5313

**Comment by sgauruseu** [comment]
reproducing with Features and inserting of an ImageComponent
