### ISSUE TITLE
New JS library - Read resources present on the server

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5387]
It has been asked multiple times to have the possibility to read files present on the server:
Example: A JSON config file located in /home/config

In the following link, Runar Brastad said that he implemented a library for this
https://discuss.enonic.com/t/reading-files-from-file-system-enonic-xp/1080

Should we recommend this library to people asking for this functionality or should we develop our own library (it should not be so long to implement) ?

**Comment by sigdestad** [comment]
Until further notice, we will not provide a maintained and supported version of this. People will need to use 3rd party libraries like this from Runar.
