### ISSUE TITLE
Page Template Wizard - 'Save as Template' action should not be available

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5393]
1. start to add a new page-template in the Features.
2. select a page controller .
3. open the Page Component View and show the context menu.
4. select  'Save as Template'.

BUG: 'Save as Template' should be hidden
![templ](https://user-images.githubusercontent.com/3728712/28830250-e3a8574c-76de-11e7-90ee-022793414f1a.png)

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #126](https://github.com/enonic/lib-admin-ui/issues/126) via [**ZenHub**](https://www.zenhub.com/)
