### ISSUE TITLE
Page Template widget is not refreshed after controller is reset in the Content Wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5396]
1. Add a site and add a page template(select a controller)
2. add a page template and select a controller. Do not close the template-wizard
3. select the site in the browse panel
4. go to the template-wizard and do reset the selected controller
5. go to the browse panel again
BUG:  PageTemplateWidgetItem is not updated.
Click on the another row and click on the site again- 'Page Template is not used' appears on the widget
![templ-view](https://user-images.githubusercontent.com/3728712/28866741-8d542c42-777c-11e7-89df-3581f58a84d7.png)

**Comment by ashklianko** [comment]
@alansemenov , forgot to mention, same problem for preview panel, it is not updated so separate issue needed - #5527 created
