### ISSUE TITLE
Not able to edit page-template if it was 'moved'

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5397]
1. expand templates folder in Features
2. select the 'default' template and press the Move on the toolbar(move it to the root directory)
3. try to edit  the template
BUG Error in the console and endless spinner are displayed 
![templ-edit](https://user-images.githubusercontent.com/3728712/28869360-18b4fe76-7785-11e7-9a63-bcb8eb90b17a.png)

**Comment by alansemenov** [comment]
This will no longer be relevant after we forbid moving template out of its site (#5500)
