### ISSUE TITLE
Confirmation about unsaved changes should not appear when modal dialog is closed with "X" icon

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5400]
"X" icon in modal dialogs should always act like the "Cancel" button and should not result in confirmation about changes in the dialog that were not applied. 

A dialog launching another dialog is a bad idea per se, so we should give a confirmation only when user clicks outside of the dialog to prevent him from **accidentally** losing the changes.

This should be implemented as a general behaviour in api.ui.dialog.ModalDialog.

**Comment by vbradnitski** [comment]
according to comment it's not a bug, it's a feature :)
https://github.com/enonic/xp/pull/5063#issuecomment-307353736

**Comment by sgauruseu** [comment]
Confirmation should appear only if user clicked out of the SiteConfigurator or EditPermissions
