### ISSUE TITLE
IssueListDialog - 'Open' tab should open when an issue was opened

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5413]
1. create an issue
2. click on the issue and open IssueDetails dialog
3. close the issue , and go to IssueList dialog - 'Closed' tab is active(OK)
4. click on the issue again and open it .
Expected: Open-tab should be activated
Actual: 'Closed' -tab is opend

![tabs](https://user-images.githubusercontent.com/3728712/28971237-ebc2bd3a-7933-11e7-8f02-58c1d7e490a7.png)

**Comment by pmi** [comment]
Here's the abstract responsible for choosing tab
`private getTabToOpen(issues?: Issue[]): IssuesPanel {
        if (!issues) {
            return this.getFirstNonEmptyTab();
        }

        if (issues[0].getModifier()) {
            if (this.isIssueModifiedByCurrentUser(issues[0])) {
                if (issues[0].getIssueStatus() === IssueStatus.CLOSED) {
                    return this.closedIssuesPanel;
                }
            }

            return <IssuesPanel>this.dockedPanel.getDeck().getPanelShown();
        }

        if (this.isIssueCreatedByCurrentUser(issues[0])) {
            return this.openIssuesPanel;
        }

        return <IssuesPanel>this.dockedPanel.getDeck().getPanelShown();
    }`
It currently opens closed issues tab if an issue was closed by the current user.
Should we switch to open issues if the last issue in the list was reopened ?

**Comment by pmi** [comment]
Issue moved to [enonic/xp-apps #412](https://github.com/enonic/xp-apps/issues/412) via [**ZenHub**](https://www.zenhub.com/)
