### ISSUE TITLE
Give exception when installing global app in Read-only mode

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#5421]
If trying to install an application when server is in read-only mode, an exception should be thrown. 

Now, when installing an global app when in read-only mode, the application seems to be installed and set to "stopped" mode.

If turning off read-only mode, the application can be started, but the application will disappear after a restart since there is no entry written to the repo

Read-only mode: 
http://xp.readthedocs.io/en/latest/reference/toolbox/set-read-only.html

**Comment by rymsha** [comment]
#8022 explains a more generic case.
Closing it as duplicate.
