### ISSUE TITLE
Layout's region should not have "Insert Layout" option in its context menu

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5425]
1. start to add a new site, select Features in the applications
2. select the Page Controller and save the site
3. open the Page Component view and insert the 25/75 layout
3. click on the left region, open the context menu  and select  Insert/Layout
BUG: error in the console
![nested-layout](https://user-images.githubusercontent.com/3728712/29026311-c911770c-7b83-11e7-9298-afea1510b7a1.png)

**Comment by alansemenov** [comment]
We should fix the console error of course, but it's equally important to hide "Insert -> Layout" option in the context menu of Layout component.
