### ISSUE TITLE
PageTemplate wizard - Refresh options inside component selectors when a new application was added

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5433]
1. Open a site-wizard , type data, select an application
2. open template-wizard, type data, select a controller,(support is site)
3. insert a part-component  on the template-wizard 
4. go to the site-wizard and add one more application, press Save
5. go to template-wizard, click on the dropdown handler(part-component)
ISSUE: parts from the second application should be present in the PartComponentView

![parts](https://user-images.githubusercontent.com/3728712/29065047-8ab1671e-7c33-11e7-8a10-9eb82145f982.png)

BUT these parts are available on the site-wizard
![site-parts](https://user-images.githubusercontent.com/3728712/29065132-cc0044c4-7c33-11e7-8d6b-baecb01e8bd7.png)

**Comment by alansemenov** [comment]
Same for layouts, of course.

**Comment by ashklianko** [comment]
https://github.com/enonic/xp-apps/pull/31
https://github.com/enonic/lib-admin-ui/pull/11
