### ISSUE TITLE
Custom Selector is not working in ID provider

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5438]
Original discuss page: https://discuss.enonic.com/t/custom-selector-in-id-provider/1131/3

Steps to reproduce:
1 - Git clone an existing ID Provider:  git clone https://github.com/enonic/app-simple-idprovider.git
2 - Deploy the application
3 - Create a user store and assign the ID Provider 'simpleidprovider'
=> It works. 

4 - Add a custom selector inside the ID Provider config
  4.1 - Modify "/idprovider/idprovider.xml": Add the following config input:
```xml
<input name="my-custom-selector" type="CustomSelector">
  <label>My Custom Selector</label>
  <occurrences minimum="0" maximum="0"/>
  <config>
    <service>my-custom-selector-service</service>
  </config>
</input>
```
  4.2 - Add "/services/my-custom-selector-service/my-custom-selector-service.js" with the following content:
```javascript
exports.get = function () {
    return {
        contentType: 'application/json',
        body: {
            "total": 2,
            "count": 2,
            "hits": [
                {
                    "id": 1,
                    "displayName": "Option number 1"
                },
                {
                    "id": 2,
                    "displayName": "Option number 2"
                }
            ]
        }
    };
};
```
5 - Redeploy the application
6 - Refresh the new user store page and reassign the ID Provider 'simpleidprovider'

=> The configuration button is not displayed and we get in the console the following error:

_all.js:70497 Uncaught TypeError: Cannot read property 'toString' of undefined
    at CustomSelector.readConfig (_all.js:70497)
    at new CustomSelector (_all.js:70492)
    at Class.newInstance (_all.js:1955)
    at Function.InputTypeManager.createView (_all.js:41806)
    at InputView.createInputTypeView (_all.js:40994)
    at InputView.layout (_all.js:40921)
    at _all.js:40766
    at Array.forEach (<anonymous>)
    at FormItemLayer.doLayoutPropertySet (_all.js:40721)
    at FormItemLayer.layout (_all.js:40712)

**Comment by pmi** [comment]
There are 2 PRs here: to master and 6.11

**Comment by GlennRicaud** [comment]
I am trying to test it but I get the following error when I create a new User store:

![screen shot 2017-08-21 at 14 11 45](https://user-images.githubusercontent.com/12030113/29518736-cef2efaa-867a-11e7-8db0-2698cecebf20.png)

**Comment by pmi** [comment]
Sorry, overlooked that default userstore is needed for new wizard. 
Should work now.

**Comment by GlennRicaud** [comment]
Works well now :+1:

I saw the following error because of missing messages in CONFIG.messages. But it is not linked to this issue so I will create a separate issue (and I guess it is a known error).
![screen shot 2017-08-22 at 10 38 09](https://user-images.githubusercontent.com/12030113/29557155-6fab0c04-8728-11e7-8fb5-cbc3b40f3093.png)
