### ISSUE TITLE
Edge specific - context menu in the Page Component View is getting not available after a inserting of 2 components

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5442]
1. Open Features and open the PageComponentView
2. Insert the first ImageComponent and select an image. (context-menu on the component is available 
  OK)
2. Insert one more ImageComponent  and select an image

BUG: the context menu is getting not available
![edge1](https://user-images.githubusercontent.com/3728712/33545635-dd838120-d8ef-11e7-9871-76a96a3a8e5f.png)

**Comment by alansemenov** [comment]
@sgauruseu Please verify that this is still relevant

**Comment by alansemenov** [comment]
I couldn't reproduce this one on latest Edge, most likely fixed in #5441.

**Comment by sgauruseu** [comment]
Issue moved to [enonic/xp-apps #378](https://github.com/enonic/xp-apps/issues/378) via [**ZenHub**](https://www.zenhub.com/)
