### ISSUE TITLE
Inspection Panel - Fragment selector is not refreshed when fragments are added or removed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5454]
Part 1:
1. Open Features, open PageComponentView and insert 2 images, create 2 new fragments from images
2. click on any fragment and inspect it 
BUG: new fragments are not present in the list of options:
![refresh](https://user-images.githubusercontent.com/3728712/29159677-17da6cf0-7db8-11e7-951a-7c026b85785a.png)

Close the wizard and open the site again, open the Inspect Panel, options are present now:

![expected1](https://user-images.githubusercontent.com/3728712/29159709-4056bbca-7db8-11e7-97d1-c5523c0f6882.png)

Part 2: options in the 'Page Template'- dropdown list are not updated, when a page-template was removed
  - open a site, navigate to the browse panel and remove one of the templates
 - go to site-wizard and open the 'Page Template'- dropdown and select the template, that was removed 
BUG: 404 error appears on the LiveEdit

![templ-removed](https://user-images.githubusercontent.com/3728712/29309826-02d3e76e-81b4-11e7-84ee-e1da0d7d20e2.png)

**Comment by alansemenov** [comment]
I believe part 2 from this is being fixed in #5488, so we should focus on refresh of the fragment selector
