### ISSUE TITLE
StackOverflowError extracting metadata from excel media

### ISSUE THREAD

**Issue by aro** [enonic/xp#5462]
Creating an attachment from the Excel .xlsx below, triggers a StackOverflow exception and the content is not created. 

Attached source file and stack trace:
[VolumPrisIndeksar2016.xlsx](https://github.com/enonic/xp/files/1217129/VolumPrisIndeksar2016.xlsx)
[fileError.txt](https://github.com/enonic/xp/files/1217130/fileError.txt)

It seems to be some recursive call in Java Pattern, but the call comes from Tika ```org.apache.tika.parser.AutoDetectParser```.

This issue was reported in the Discuss forum: https://discuss.enonic.com/t/xlsx-file-upload-error/1157

**Comment by aro** [comment]
It's not related to Tika. 
The exception happens in the replaceAll using a regex  in ```ExtractedTextCleaner.cleanLineBreaks()```

**Comment by alansemenov** [comment]
@aro what is the status on this? is it really in progress?

**Comment by aro** [comment]
It was in progress, I started working on it before holidays. I will continue working on it today.
