### ISSUE TITLE
Handle circular principal memberships

### ISSUE THREAD

**Issue by aro** [enonic/xp#5474]
Currently it is possible to have 2 groups being a member of each other:
- Group A added as member of Group B
- Group B added as member of Group A

This is not logical and causes issues when resolving memberships in different parts of the application.

We should handle this when trying to resolve the memberships.

**Comment by rymsha** [comment]
We experienced this issue at least once. Moving to development pipeline

**Comment by sigdestad** [comment]
I don't see why this is an issue, don't we already have a group resolver that will handle circular references? If not, this is what we should implement - not a blocker from creating the circular membership.

**Comment by rymsha** [comment]
> don't we already have a group resolver that will handle circular references

No we don't. At least in CS there is no check for circular references.

> If not, this is what we should implement - not a blocker from creating the circular membership.

Resolving group circular dependencies requires to store all groups in a set. It is better to do once when stored.

The real concern is that we may need to support sync from external groups (AD, LDAP). They don't have prevention of circular references, and we have to support them, too.

Perhaps it is better, as you say, to implement permissions resolver in XP available via API, so applications won't need to reinvent the wheel.

**Comment by rymsha** [comment]
https://github.com/enonic/app-contentstudio/issues/5509 fixes it in CS.

Generic XP solution for this is not required as there might be different needs/requirements.
