### ISSUE TITLE
Fragment Wizard - LiveEdit is not available, when a fragment was moved from the site

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5478]
Probably this issue is similar to 
XP #5397 Not able to edit page-template if it was 'moved

Steps:
1. open Features, insert a part
2. create a fragment from the part
3. move the fragment to the root directory
4. open the fragment in wizard
Issue: LiveEdit is not available. How to edit the fragment?

![fragm-moved](https://user-images.githubusercontent.com/3728712/29218793-99ea35ca-7ebe-11e7-908a-59073607f257.png)

**Comment by jsi** [comment]
This issue is obsolete because of #5500 
After #5500 is implemented, the situation described in this bug will never happen.
