### ISSUE TITLE
UserItemStatisticsPanel - Information about an user-item is not cleared, when switch between rows in the grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5482]
1. Open Users app
2. click on row and select on any existing user.
3. click on another user or role 
BUG:  when new item is selected, information about the previous item still displayed
![statistic](https://user-images.githubusercontent.com/3728712/29269948-f656b366-80fc-11e7-8185-b1dc6067fca8.png)

**Comment by alansemenov** [comment]
This was fixed a while ago.

**Comment by sgauruseu** [comment]
verified on my local machine
