### ISSUE TITLE
Page Editor shows an error after selected page template is deleted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5488]
1. start to add a new site, select Features in the apps. close the wizard
2. expand the site and add a new page-template, select the 'main-page' in controller
3. insert an Image(for example) in the page-template, save it and close the wizard
4. open  the site-wizard again. open InspectPanel and select the just created template in the dropdown options. See the first screenshot

![step1](https://user-images.githubusercontent.com/3728712/29365704-9e861988-82a0-11e7-8f5d-de0bf6d98325.png)

5. go to the browse panel, select and remove the template
![step2](https://user-images.githubusercontent.com/3728712/29365732-b3852e00-82a0-11e7-92f9-5c91a2095a36.png)

6. open the site;
BUG: 404 error is displayed and impossible to select another controller

![result](https://user-images.githubusercontent.com/3728712/29365776-ce29e264-82a0-11e7-9ba6-696f9d8b6ccc.png)

**Comment by alansemenov** [comment]
Just a quick note - in this case we should reset selected page template Id in the content and the page editor should show the controller selector:
![image](https://user-images.githubusercontent.com/11612490/29630658-2fd75e8c-883d-11e7-8cf8-ab07d8ef4e72.png)

**Comment by vbradnitski** [comment]
@alansemenov What if the current template is gone, but we still have 'automatic' template? Should we reset to it?

**Comment by alansemenov** [comment]
Here are possible scenarios:

1. The page is using Automatic page template.
If the page is automatically using the template that was deleted, then the page will simply switch to the next one. If no other templates exist, then it should show the controller selector (see above)

2. The page is using specific page template.
In this case we should show the controller selector right away to let user know that his template is no longer available. Don't switch to Automatic.

3. The page is using custom template (the page was customized).
Nothing should change, the page remains the same.

Also note that in all these cases we should refresh the template selector in the Inspect panel after the list of templates was modified in any way (added, deleted or updated).
