### ISSUE TITLE
Image Editor should store custom orientation data in data.media

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5491]
We should store custom orientation data in ``data.media``, like we do with cropping and focal point. Now we overwrite default orientation value in ``media.cameraInfo`` and after that there's no way to roll back to the original value.

Commit to branch issue-5328

**Comment by alansemenov** [comment]
And another bug to be fixed:
1) Open an image
2) Zoom in to some detail in the image
3) Save (everything looks fine on the client)
4) Click rotate twice (everything still looks fine)
5) Save

Zoomed part of the image is repositioned.

**Comment by pmi** [comment]
Done, pushed to issue-5328 branch
