### ISSUE TITLE
ItemSet content - HtmlArea stops working after DnD of an item

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5499]
[item-set0_0.txt](https://github.com/enonic/xp/files/1234028/item-set0_0.txt)
1. start to add a content with type(in attachments)
2.  click on 'Add Item Set' and add 2 sets
![step1](https://user-images.githubusercontent.com/3728712/29454110-a5e5ff0c-8414-11e7-9780-b7a6e8eecd40.png)

3. click on the second set and try to drag it to up(swap sets)

BUG: when sets have been swapped, htmlarea in the second set is getting disabled and text has been lost. There are no any errors in the console
![result](https://user-images.githubusercontent.com/3728712/29454261-2c03d9f6-8415-11e7-92db-43529c0e4ced.png)

**Comment by vbradnitski** [comment]
enonic/xp#5508 is for 6.11
