### ISSUE TITLE
A fragment should be allowed to be moved out of its site

### ISSUE THREAD

**Issue by jsi** [enonic/xp#5500]
If a Fragment is moved out of it's site, a lot of strange errors may appear, so we need to disallow this.  It should still be possible to move a Fragment around inside the same site.

If an attempt is made to move the Fragment out of the site, an error-message (in red), should appear across the bottom, saying "A Fragment is not allowed to be moved out of its site."  -  The Fragment should not be changed in any way.

Currently, a confirmation message, asking if the user really want to move the Content out of the site is displayed.  This is okay, since there may be other content that should be moved.  If several content are moved, including a Fragment, only the Fragment should be blocked with the error message, and left as is.  All the other content should be moved ask requested.

In Norwegian, the error message should read: "Et fragment kan ikke flyttes ut av sitt nettsted."

**Comment by sigdestad** [comment]
Why on should I not be allowed to move a fragment out of a site (if I absolutely want to)? 

We already have an error message that says: Moving content out of a site may cause shit to happen. A fragment is not different from other content in that sense.

@ase Let's make a task to reverse this issue

@jsi please consult me before creating tasks that change or limit behaviour of XP. The solution for this case would simply be better error-handling in portal/admin when trying to render the specific fragment.

@ComLock hope this fixes your problem.

**Comment by alansemenov** [comment]
@vbradnitski Let's roll back this limitation (keep the confirmation about moving content out of site, of course)
