### ISSUE TITLE
Array returned from Java object not converted to JavaScript array

### ISSUE THREAD

**Issue by aro** [enonic/xp#5501]
When a JavaScript function calls a Java method that returns e.g. an array of String, it is not correctly converted to a JavaScript array of strings.
Research if we can improve the handling for arrays, in ```toNativeObject``` function.

**Comment by alansemenov** [comment]
Another request to fix this:
https://discuss.enonic.com/t/event-lib-json-without-quotes-in-data-nodes/1192

**Comment by alansemenov** [comment]
@aro @srs Isn't this the same as #5257?

**Comment by aro** [comment]
It's not the same issue. This one is related to general conversion of objects from Java to JS.
For #5257 we probably need a custom serializer (mapper) for Event objects in java.

**Comment by alansemenov** [comment]
Do we want this in 6.12? How complicated/time-consuming is this?

**Comment by aro** [comment]
It's a minor improvement for people creating libs. There are workarounds, by using List instead of array, which is more common in Java anyway. 
It's not a big change but I would prefer to make it after 6.12 so we get time to test it and make sure there is no unexpected behavior with the conversion.
