### ISSUE TITLE
Implement download of distro file from the list of installed applications

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#5542]
Lets say "Person X" has installed "App A" in QA environment using upload in Applications.

Some time later "Person Y" is supposed to deploy the very same app to Production.

Since "Person X" is on vacation no one has access to the original jar file.

There might be some jar files around, but can you be sure it's the exact same file as in QA...

Therefore it would be nice it one could download apps directly from Applications.

**Comment by ComLock** [comment]
Current workaround is do an export using data-toolbox app, dowload, unzip, find the binary, which no longer has it original name, but is called "applicationFile"

**Comment by sigdestad** [comment]
Solution here is actually to clean up current deployment practice. Use code repositories and enable developers to compile new versions when needed. We won't spend time on this.
