### ISSUE TITLE
Enable selecting an app version to install in the Install Application dialog

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#5559]
Sometimes a new release of a market apps breaks something, and you need to "rollback" to the previous version. It is currently not possible to select which version of an app you want to have installed in the Applications admin page.

It would be nice if that was possible.

Current workaround is going to the market web page and downloading the old version of the app, uninstalling the newest version and uploading the version you want from your harddrive.

**Comment by sigdestad** [comment]
We cannot guarantee that an older version will work, however at least if it is a major version it should not be possible. We think your workaround is ok for now.
