### ISSUE TITLE
Move Content dialog - Incorrect confirmation about moving out of site

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5561]
Looks like this confirmation always comes up now, no matter if you are trying to move the content out of its site or not.

Example:
1. Expand Features site in the grid
2. Select "media" folder (or any other content item, really)
3. Try to move it to "Features" (which is the same parent "media" already has)

Bug #1: The confirmation dialog comes up while it shouldn't
Bug #2: Notification says "media was moved" although nothing has changed

**Comment by vbradnitski** [comment]
need to translate notify.item.nothingToMove
