### ISSUE TITLE
Refresh Launcher panel when the list of tools changes

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5571]
Whenever a new tool is deployed or an existing one is removed or updated, we should refresh the Launcher panel, similar to how we do it with widgets in the Details panel.

It's important that we refresh the list only when there's a change that affects **tools**, not any other type of application.

![image](https://user-images.githubusercontent.com/11612490/29959764-33954cba-8ef9-11e7-9687-c0cf54e1f81b.png)

**Comment by GlennRicaud** [comment]
OMG YES !!!!
