### ISSUE TITLE
Incorrect label for the New-button on the toolbar, when several items was selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5604]
1. open Users
2. select several folders in the grid(Users, Groups, Store folders)
Expected: New button should be present on the toolbar and NewPrincipal dialog should appear, when New button has been pressed
![1](https://user-images.githubusercontent.com/3728712/30205215-e9d45cc2-9490-11e7-83b1-8980db42768e.png)

**Comment by alansemenov** [comment]
Moved to enonic/xp-apps#3
