### ISSUE TITLE
TextArea with input values longer than max-length should not be sent to backend

### ISSUE THREAD

**Issue by aro** [enonic/xp#5633]
If there are values in TextLine or TextArea input types, with the length of the text value longer than max-length config, the value should not be stored.

```
    <input name="textarea" type="TextArea">
      <label>Text Area</label>
      <occurrences minimum="0" maximum="1"/>
      <config>
        <max-length>3</max-length>
      </config>
    </input>
```

Currently if the user types a text longer than max-length and then click Save, the value is sent to the server in the update request, even though is marked as invalid. The server checks the validation and throws an exception.

It should work in the same way as TextLine with regexp config, or Long/Double with man/min config. The value should not be set internally if it is not valid according to the config. If the value typed is invalid it should be sent as empty when clicking on Save. This is what happens now for regexp, max, min config.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #16](https://github.com/enonic/lib-admin-ui/issues/16) via [**ZenHub**](https://www.zenhub.com/)
