### ISSUE TITLE
Images missing in SuperHero app.

### ISSUE THREAD

**Issue by jsi** [enonic/xp#5635]
Using a clean installation of 6.12.0-B1 and installing the SuperHero app, no images are displayed:
![screenshot 2017-09-19 09 22 42](https://user-images.githubusercontent.com/477453/30580341-7c48a408-9d1c-11e7-8304-aa2e1b9eeff9.png)

**Comment by alansemenov** [comment]
Fixed in https://github.com/enonic/app-superhero-blog/issues/14

**Comment by jsi** [comment]
This was not an XP bug, but a bug in the superhero app.
