### ISSUE TITLE
Improve UX for installing apps from market

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#5642]
This one comes from the last round of training sessions at Enonic.

Watching the developers and editors trying to install an app (without instructions on how to, only saying they should do it from the Application admin tool) showed many minor hurdles for newcomers.

No one was able to install an app from market on their own. I had to help everyone of them, believe it or not. I'm very certain this is something we can fix, and that we should fix.

What happened was they most of the time opened up a new tab and went to Market, and then tried clicking the "Free" button (but a lot of them asked here about "where's the download button?"). Basically they went to the wrong place first of all.

Others at least opened the "Install" dialog, but instead of clicking the tiny "install" text, they clicked the name of the app (because that is what you might assume when someone tell you "install the X app").

My suggestion to improve app installation UX in XP is:
* Remove link from all App titles/names
* Add a gray (weak color) link under (or to the side) of the description saying "Read more on Market" (or similar). This improves UX by actually telling the user what the link does! Newcomers will not need to think twice, or try first to find out.
* Make the "install"-link look more like a button to emphasis it. Also, installing things or performing a task as such, is more often started from the click of a button than the click on a link. Using a button design will be more obvious for newcomers.

These three tiny changes will greatly improve installation UX in the Application admin tool.

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-applications #36](https://github.com/enonic/app-applications/issues/36) via [**ZenHub**](https://www.zenhub.com/)
