### ISSUE TITLE
Wrong property-name used for service in portal.serviceUrl-example on docs.enonic.com 

### ISSUE THREAD

**Issue by cfenzo** [enonic/xp#5646]
The property used to identify the service was changed in 6.7.0, from `name` to `service`, but [docs.enonic.com](http://docs.enonic.com/en/stable/developer/services/index.html#access) is using the `name` property.

But the change isn't mentioned in [the changelog for 6.7](https://github.com/enonic/xp/releases/tag/v6.7.0), the [docs.enonic.com changelogs](http://xp.readthedocs.io/en/6.7/appendix/release-notes/index.html), or the [upgrade notes](http://xp.readthedocs.io/en/6.7/appendix/upgrade/index.html).

6.6.0 js docs, using `name`:
http://repo.enonic.com/public/com/enonic/xp/docs/6.6.0/docs-6.6.0-libdoc.zip!/module-lib_xp_portal.html#.serviceUrl
6.7.0 js docs, using `service`:
http://repo.enonic.com/public/com/enonic/xp/docs/6.7.0/docs-6.7.0-libdoc.zip!/module-lib_xp_portal.html#.serviceUrl

**Comment by jsi** [comment]
This was actually done on September 25th.
@cfenzo : Can you approve of the current state, or do you still find errors?
