### ISSUE TITLE
Support all function to handle all method requests in controllers

### ISSUE THREAD

**Issue by aro** [enonic/xp#5648]
Currently for handling an HTTP request in a JS controller, we export a function with the name of the HTTP method:

Example:
```javascript
exports.get = function (req) {

}
```

It would be useful to be able to export a function to handle all and any method, as in PurpleJS:
```javascript
exports.all = function (req) {

}
```

We need this to use [lib-router](https://enonic-docs.s3.amazonaws.com/com.enonic.lib/lib-router/index.html) in a general way, not depending on the HTTP method.

**Comment by sigdestad** [comment]
Seems reasonable. Is it a quick fix?

**Comment by srs** [comment]
That should be a quick fix in XP. It's wise to check existence like this (in this order):

* hasMethod(req.getMethod().toLowerCase()) == true ---> execute the method specific.
* hasMethod('service') == true ---> execute the service method.

**Comment by GlennRicaud** [comment]
I think that the equivalent in PurpleJS is `exports.service`
We should use the same naming for both

Or are exports.service and exports.all two different things?

**Comment by sigdestad** [comment]
We should go for "all", and get rid of "service"

**Comment by GlennRicaud** [comment]
I agree. And routers in NodeJs world also use "all". So it makes sense.
We will have to adapt PurpleJS then.

Merged.
