### ISSUE TITLE
ElasticSearch 1.5.Z - EngineCreationFailureException

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5660]
Users keep getting:
org.elasticsearch.indices.cluster - [local-node] [[storage-system-repo][0]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.index.engine.EngineCreationFailureException: [storage-system-repo][0] failed to upgrade 3x segments
java.io.EOFException: read past EOF: NIOFSIndexInput(path="/Users/a731597/workspace/kp/enonic/home/repo/index/data/mycluster/nodes/0/indices/storage-system-repo/0/index/segments_3b"

https://discuss.enonic.com/t/cluster-health-in-state-red/455
https://discuss.enonic.com/t/data-import-bug/902
https://discuss.enonic.com/t/elasticsearch-broken-after-restart/1197
https://enonic.zendesk.com/agent/tickets/2148

It seems to be a bug in ElasticSearch 1.5.Z and fixed in 1.6.0.
We should upgrade as soon  as possible

**Comment by alansemenov** [comment]
Discuss upgrade with @runarmyklebust
