### ISSUE TITLE
Rendering of images with legacy media property fails

### ISSUE THREAD

**Issue by aro** [enonic/xp#5664]
Rendering of images created in older versions of XP fail while trying to obtain the image orientation.

The problem is that originally the images had a property with name `media` of type **String**. But later it was extended making it of type **PropertySet** with more complex data. So the code accessing this property must always handle both cases.

This bug was introduced in changes done for 6.12.

**Comment by jsi** [comment]
Set "Not in Changelog", since it has been introduced since 6.11.
