### ISSUE TITLE
Restrict access to services based on site context

### ISSUE THREAD

**Issue by aro** [enonic/xp#5668]
Requests to portal services (using a service URL) must be restricted so that only the services in the apps configured for a site can be accessed under the site's context.

Example: 
- If there are 2 apps in an Enonic installation: _app1_, _app2_.
- _app2_ has a service _svc42_
- There is a site in `/my-site` for which the _app1_ has been added
- `/portal/draft/my-site/_/service/app2/svc42` should return 403 Forbidden (consider 404 Not found)

In addition to this, service URLs accessed for a main.js controller should also be allowed for services included in the main.js application.
Example:

- the service `/app/com.enonic.myapp/_/service/com.enonic.myapp/ok-svc`  should be allowed
- the service `/app/com.enonic.myapp/_/service/org.otherapp/secret-svc`  should be forbidden

**Comment by GlennRicaud** [comment]
To be discussed in depth. Services are used at multiple places other than sites: admin tools, widgets, id providers, apps (/app), ...
