### ISSUE TITLE
Portal lib - Application URL

### ISSUE THREAD

**Issue by aro** [enonic/xp#5673]
We have portal functions to generate URLs for everything that is accessible (services, pages, parts, assets...) except for the `main.js` controller (e.g. "/app/com.enonic.features").

Add a new function `applicationUrl(...)` to portal-lib and expose it for the views (Thymeleaf function).
```javascript
var url = portalLib.applicationUrl({
  application: app.name, // optional, by default current app
  type: 'absolute', // optional
  path: '/person/list', // optional (appended to the app url path)
  params: {foo: 'bar'} // optional
});
```

Allow calling it without any parameter also, and take default values.

**Comment by GlennRicaud** [comment]
Closing issue. We will create a resourceUrl.
More generic
