### ISSUE TITLE
Add contextPath field to PortalRequest

### ISSUE THREAD

**Issue by aro** [enonic/xp#5678]
Add `contextPath` field of type String to `PortalRequest` .
It should return the value of the base URL matched, when a request is handled by portal.

When a request  is processed by any of the following handlers, it should set the appropriate context path:

* AppHandler
* AssetHandler
* AttachmentHandler
* ComponentHandler
* IdentityHandler
* ImageHandler
* MappingHandler
* PageHandler
* ServiceHandler
* WidgetHandler

For controller mappings it will return the same as for a request to the Site where the mapping is based on.

Examples:

App main request: `/app/com.myapp/some/path`
App request: `/app/com.myapp`

Page request: `/portal/draft/site/portal?a=1&b=1&b=2`
Page contextPath: `/portal/draft/site/portal`

Component request: `/portal/draft/site/portal/_/component/main/0`
Component contextPath: `/portal/draft/site/portal/_/component/main/0`

Service request: `/portal/draft/site/portal/_/service/com.myapp/test/sub-path`
Service contextPath: `/portal/draft/site/portal/_/service/com.myapp/test`

Mapping request: `/portal/draft/my-site/rest/customer/123`
Mapping contextPath: `/portal/draft/my-site`

The class `PortalRequestMapper` also needs to be updated to expose the field to JavaScript.

**Comment by GlennRicaud** [comment]
After discussion with aro, the context path is:

For webapp requests: /app/[applicationKey]
For admin tool requests: /admin/tool/[applicationKey]/[adminToolName]
For mappings: [pathMatchingTheCurrentSite]
For service endpoints:    [preEndpointPath]/_/applicationKey]/[serviceName]
For idprovider endpoints: [preEndpointPath]/_/applicationKey]/[userStoreKey]

Context path for routing does not make sense in the case of a page, asset, component. This still need to be discussed.
For now we will focus on the 5 mentioned above
