### ISSUE TITLE
Improved session timeout handling in XP admin

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#5683]
User story about how logout is enforced when sessions timeout:

For I guy handling 10+ different client installments weekly, the admin of XP is my second home. Many windows and tabs open with the admin interface, for each client. This is all good.

However, when my session times out, all my tabs will force the URL to the login screen, and I will loose any track of where I was. If I have one tab with Content Studio grid, one with Application admin tool, one with another admin tool, two tabs where I edit specific contents, all will return to the login screen. This is beyond annoying. When I sign in again, I always end up on the Home Screen. No other tab is updated to reflect that I just signed in another tab. I can live with the last part, as long as each tab could remember where I was before logging out.

It is often X days since I worked on the project, so I don't remember which URLs or tools these tabs used. Or even if I leave some tabs open during the night, next day I need to start all over again.

**Basically:**
* Remember the page I was on when you redirect me to the login screen on timeouts. This is very important.

**Or better yet:**
* Or just stop force-redirecting me out of admin when session times out or server restarts. I know there are many many working with XP that hates this behavior.
_Suggested solution:_ Don't force me to sign out this way, just overlay a login modal over the page, signing in would close that modal. Might be conflicting with other ID providers, so I'm not expecting this to be easy. If the modal thing is too hard, just overlay a modal saying "lost connection" that will disappear when I'm back online. The modal could link to the configured login URL.

**Bonus:**
* Also make login-screen smarter by making them see if you signed into XP from another tab, then automagically refresh these tabs. So if I have 5 tabs in admin, and are logged out of them all, but then sign in to one of them, also sign in to the other tabs.

**Comment by alansemenov** [comment]
That's a great proposal and we should definitely fix that. However, I'm not so sure about the modal window (the "better yet" part). Standard practice is what you originally suggested - show the login page once the session expired but keep original url. Once user logs back in, we'll open the original page.

The bonus part should also be done, and that's actually how it already works now - except that now you have to refresh the page after you logged in in another tab. But we should detect the restored session and refresh the page automatically.

@GlennRicaud this sounds like something you could do - any input?

**Comment by sigdestad** [comment]
I believe we should investigate a modal approach anyway - thing is that an ID-provider could be configured to run in "one-pager" mode for a particular site, and traditional mode for others, similar to how auth0 works. For the admin we should definetly use a modal approach as this means we could load parts of the "dashboard" in the background, and then launch the Idprovider on top. This way we would not have to "replicate" the background image and it would work more or less like a mac :-)

**Comment by rolfrb** [comment]
I was about to add a feature request for login to preserve the current URL. Would this issue also solve this?

For instance, if I open a URL to a content item in content editor, and I'm not authenticated, the current URL will still be visible on the username and password page. Let's say: 
http://domain/admin/tool/com.enonic.xp.admin.ui/content-studio#/edit/some-id-here

But after adding my credentials and clicking "Log In", the URL changes to
http://domain/admin/tool/com.enonic.xp.admin.ui/content-studio#/browse

**Comment by alansemenov** [comment]
Yes, this is mostly to fix the issue you are describing.

**Comment by sigdestad** [comment]
We have added a task to make the system idprovider work as a "modal" rather than take over everything.

Will rise again as a separate task
