### ISSUE TITLE
Latest Market apps are not retrieved by name from getMarketApplications REST API

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5720]
None of the latest apps on the Market can be retrieved by passing ``id`` parameter to ``getMarketApplications`` REST API, although they are returned when getting the full list of apps (when ``id`` parameter is not used). 

Example: com.enonic.app.officeleague, com.enonic.app.guillotine, com.enonic.app.corporate.theme etc. Looks like there's ``count`` sitting somewhere in the code which limits the list somehow.

![image](https://user-images.githubusercontent.com/11612490/31914679-eb779a42-b84b-11e7-9720-20e562bc894a.png)

**Comment by sigdestad** [comment]
Is this related to the missing apps? Why is there paging / count involved here?

**Comment by GlennRicaud** [comment]
Fixed in: https://github.com/enonic/market.enonic.com/issues/4
