### ISSUE TITLE
EXP vhost does not work with IP addresses

### ISSUE THREAD

**Issue by z127545** [enonic/xp#5736]
When I launch an instance of XP in the public clouds I have to disable XP vhosts for XP to work at the moment is launched.

If not I have to wait for the instance to be created then point a DNS service to it before XP can be used.

**Comment by sigdestad** [comment]
We want standard initial deployments to work without using virtual hosts. Virtual hosts should only be used for more production style deployments.

What do you mean vhosts does not work with ip-addresses?

**Comment by sigdestad** [comment]
Pinging this. Do you want vhosts to work for IP-addresses? How is this useful?

**Comment by z127545** [comment]
This is not needed anymore. The workaround you mentioned is a good solution. Closing this.
