### ISSUE TITLE
Index visualization widget/library

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#5750]
It would be very nice with a widget showing how the data is indexed:

* Fulltext / Minimal etc marked e.g with colors
* Processors applied

This should be pretty easy by using the stored index data.

**Comment by sigdestad** [comment]
Maybe better as an improvement for @gri dataToolBox :-)

**Comment by runarmyklebust** [comment]
Its almost done as a content-widget. Some UI tuning maybe?

https://github.com/runarmyklebust/indexInspector
