### ISSUE TITLE
Temporarily disable Duplicate action in the toolbar

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5760]
After Duplicate action in the toolbar is clicked, it should instantly become disabled until the DuplicateContentDialog is up (if the duplicate task takes over X ms) or the task is finished (if less than X ms). This should eliminate the possibility of accidental double-clicking.

**Comment by edloidas** [comment]
Issue moved to [enonic/xp-apps #293](https://github.com/enonic/xp-apps/issues/293) via [**ZenHub**](https://www.zenhub.com/)
