### ISSUE TITLE
Errors during ScrollExecutors are not caught properly

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#5766]
If e.g a timeout occurs during a scroll executor execution, the result is returned with a wrong number of total hits. See issue @ posten: 

https://enonic.zendesk.com/agent/tickets/2192

**Comment by alansemenov** [comment]
@runarmyklebust do we still want to fix this? how can this be reproduced?

**Comment by GlennRicaud** [comment]
Duplicated #7139
