### ISSUE TITLE
Index X-Data 

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#5775]
Same as the other stuff; ByType and html-stripper for html-areas.

Protip: use the mighty indexInspector to get an overview of the indexed fields:
https://github.com/runarmyklebust/indexInspector

**Comment by alansemenov** [comment]
@runarmyklebust Should this really be an epic? An epic usually has subtasks. Anyway, we need to assign it some labels if we want it in the changelog.

**Comment by runarmyklebust** [comment]
Tried to remove the epic-label, but its still an epic?

**Comment by alansemenov** [comment]
![image](https://user-images.githubusercontent.com/11612490/32783850-6cc00e9c-c94d-11e7-9ed3-4edeb665b56f.png)

"Convert to Issue" button
