### ISSUE TITLE
Applications - Check for updates

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5791]
In the future we will have the applications "Content Studio" and "Users" installed independently from the runtime.

The problem is that after an upgrade of Enonic XP, we will end up with applications that will be probably incompatible (especially once we start to move java code to these 2 apps, that is guaranteed breaking changes).
This problem is already present today. For example Google analytics needed to be upgraded because of breaking changes in 6.8.0

- Feature request: When listing applications in the admin tool "Applications", we should request from the market if there are any application more up to date and show it to the user. 
  - That will reduce the impact of this problem
  - It will also push the user to install patches of "Content Studio" and "Users".
- Alternative solution: An icon in the launcher panel indicating that an application is not up to date
- Documentation adaptation request: Add a step that is to check for application upgrades after an Enonic XP upgrade.

**Comment by jsi** [comment]
Some thoughts and questions:
 * In Market, we have a field to state which version of XP a version of an App works for, but this is only a from field.  It says for instance "Compatibility: 6.7.0", meaning it needs 6.7.0 to work, and indirectly saying that it works for all versions after that.  See screenshot from ContentHive.  Do we need a "to field" as well, that may be used to make XP understand that an app is no longer runnable in the latest version?  If a customer upgrades the runtime to a new version and finds installed apps that are no longer compatible, Administrator users could then get a special alert to tell them to upgrade.
![screenshot 2017-11-16 09 42 39](https://user-images.githubusercontent.com/477453/32881764-8cf0308c-cab2-11e7-98f1-5471688906e7.png)
 * Should ContentStudio, The Users App and the other admin apps be put on Market?  It could be a good place to keep version info, so we don't have to reinvent something we allready have, but maybe we should have a checkbox for "hidden", "secret", "admin", or something like that, indicating that it will not be displayed on market.enonic.com, while we still have the data in one place.

**Comment by mortyeriksen** [comment]
The plan is to create a new market tool where this will be available. The current application tool will be detached from the market and just lists the installed apps.

The plan is to make sure bundled apps are upgraded with XP releases.
