### ISSUE TITLE
Content cannot be deleted if content type is missing

### ISSUE THREAD

**Issue by aro** [enonic/xp#5792]
If the content type of some created content is deleted, the "Delete" button in Content Studio is disabled. This makes not possible to delete content when a content type has been deleted or an app has been uninstalled.

Also, in the case the content type is not found, the "New" button is enabled, but it should not be.

This issue was reported in a support case (2204)

**Comment by jsi** [comment]
This bug has been promised for 6.13 to a customer.  Must be fixed ASAP!

**Comment by alansemenov** [comment]
@jsi We have a bug testing phase after feature-freeze when we focus on bugs. I'm aware of this one and it will be fixed by the time of release.

**Comment by jsi** [comment]
Okay, @alansemenov !  I trust you!  😉

**Comment by alansemenov** [comment]
Issue moved to [enonic/xp-apps #302](https://github.com/enonic/xp-apps/issues/302) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alansemenov** [comment]
Fixed in https://github.com/enonic/xp-apps/issues/302
