### ISSUE TITLE
NodeJS compatibility

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5794]
A lot of users and even ourselves often expect to be able to run some JS code that reveals to be NodeJS code, very often not compatible with Nashorn/Enonic XP.

I don't know it there has been a task and what is the status on the matter

But if not done before, we should dedicate some time to see if it feasible to make them more compatible and how much work that would be

If Enonic XP can reuse all Java libraries + all NodeJS libraries, there will not be much not doable/usable from Enonic XP.

**Comment by sigdestad** [comment]
We have invested time to support more node stuff in PurpleJS. Let us focus on merging in PurplejS and then see what more we can do!

**Comment by sigdestad** [comment]
Also, the webpack controller compiler can actually "merge" nodeJS modules functionality directly into our serverside compilers. This actually solves some interesting compatibility issues.
