### ISSUE TITLE
Add meta-data to contentLib query

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#5801]
It would be nice to include search meta-data to the content query results, ref this thread:

https://discuss.enonic.com/t/global-search-orderby-most-matches/404/8

**Comment by rymsha** [comment]
#8167 exposes `_sort` meta field

To help solving issue described in "discuss" we need to expose `_score` in content as well.

Use case 1: Based on `_score` field don't discard less relevant results (for instance hide them under spoiler to save screen space)
Use case 2: If none of returned result `_score` reach certain threshold - redo the query with different criteria automatically.
