### ISSUE TITLE
Not possible to move pages under a shortcut

### ISSUE THREAD

**Issue by aro** [enonic/xp#5809]
- Create a shortcut in Content Studio
- Select another existing content and click Move
- Expand the dropdown tree selector to find the shortcut
- It is disabled so it cannot be selected to move under

There is no reason why it should not be allowed, "base:shortcut" ctype has allowChildContent=true.

Reported in Discuss:  https://discuss.enonic.com/t/not-possible-to-move-pages-under-a-shortcut/1288

**Comment by alansemenov** [comment]
Issue moved to [enonic/xp-apps #288](https://github.com/enonic/xp-apps/issues/288) via [**ZenHub**](https://www.zenhub.com/)
