### ISSUE TITLE
Store scroll position in Page Editor and scroll to it when saving

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#5821]
When editing any content, you can scroll inside the Page Editor. If your page is long, and your form too, it is handy to scroll the Page Editor down to the place you are currently editing in the form.

When saving, the form is not reloaded, but the Page Editor is, and the scroll position is reset to the top. This is very annoying on larger content types (ref writing articles on Webagility blog).

Could we on save (and publish) make sure scroll position in Page Editor is saved, and after the page is reloaded, instantly scroll down to that position after the page editor is reloaded.

**Comment by alansemenov** [comment]
Issue moved to [enonic/xp-apps #332](https://github.com/enonic/xp-apps/issues/332) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alansemenov** [comment]
Done in https://github.com/enonic/xp-apps/issues/332
