### ISSUE TITLE
Add readonly state of the repo to the 'status' REST response

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5831]
We have 'status' REST service which we poll from the client every X seconds to check connection status. Add state of the repo (``readonly: true/false``) so that we could show user a warning when repo is readonly and hide the warning when it becomes editable again (see https://github.com/enonic/lib-admin-ui/issues/134).

![image](https://user-images.githubusercontent.com/11612490/33421946-27c05e3c-d5b4-11e7-967f-218193b5323c.png)

**Comment by runarmyklebust** [comment]
Ok, to implement this rest-service, a couple of things will be necessary:

The readOnly-settings is set from the toolbox-command SetReadOnlyCommand. It sets a setting on es: index.settings.blocks.write = false to enable read-only.

1) Extend IndexServiceInternal with a method to get and return IndexSettings (I guess all settings, or maybe an optional value / filter - check the api this.client.admin().indices().getSettings() to see whats possible. It will probably be useful to be able to fetch all index settings for other usages, keep that in mind

2) Extend IndexService with method to getIndexSettings

3) Get settings, check if the index.settings.blocls.write = false. If so -> readOnly
