### ISSUE TITLE
Component Viewer - issues with collapsed segments of the tree

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#5837]
*CV = Component Viewer.*

Bug is in 6.12 and 6.13, except it behaves slightly different.
Discovered and reported by multiple students during class.

* Open up any content and go into the Page Editor.
* Open the CV
* Collapse one of the branches that contains Parts
* Locate one of those Parts in the Page Editor and left-click it.

Expected behavior:
* Part is highlighted in CV and in Page Editor, if CV branch is collapsed it should open.

What happens instead:
* 6.12: Part is selected but no highlight is shown in CV
* 6.13: The page is selected instead, in CV and Page Editor.

<img width="565" alt="screen shot 2017-12-01 at 13 52 49" src="https://user-images.githubusercontent.com/1465598/33483622-f33d4152-d69e-11e7-86d8-a03cb105a240.png">

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #234](https://github.com/enonic/lib-admin-ui/issues/234) via [**ZenHub**](https://www.zenhub.com/)
