### ISSUE TITLE
Portal Lib - URL Generation - Context path parameter

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5845]
In portal lib URL functions, add a flag to specify if we want the URL to be generated at the rootest (like assetsUrl or idProviderUrl today) or under the current content path.
The default value of this flag would be the current behaviour (false for assets, true for service, ...)

Add this flag to the following functions:
- assetUrl
- imageUrl
- serviceUrl
- idProviderUrl
- loginUrl
- logoutUrl

**Comment by GlennRicaud** [comment]
Note to self: Adapt documentation for view functions

**Comment by sigdestad** [comment]
This was a bit unclear to me? What is "the rootest"? Do you have some examples of how this would work?

**Comment by GlennRicaud** [comment]
Not sure what word to use to describe the way asset URLs are generated.
Ideally after the base uri ("/portal/draft" for example), but could contain some content path because of the vhosting

Assets on superhero have a URL like this:
  /portal/draft/_/asset/com.enonic.app.superhero:1514451089/css/style.css"
Images have a URL like this 
  /portal/draft/superhero/_/image/81b1e3cd-575f-4565-a618-3c85d56224f6:666fcc4247e015ab6878f91fd7502f3b882ace10/block-1024-355/superhero_featured_4.jpg

After this improvement, by setting the flag contentPath to "false" when calling imageUrl, we could have the following URL:
  /portal/draft/_/image/81b1e3cd-575f-4565-a618-3c85d56224f6:666fcc4247e015ab6878f91fd7502f3b882ace10/block-1024-355/superhero_featured_4.jpg

**Comment by sigdestad** [comment]
But why would we need this?

**Comment by GlennRicaud** [comment]
I proposed this feature for idProviderUrl. So that they could be generated for the current content path.
You validated and asked me to make it generic for all the URL functions. Especially for imageUrl (which could be interesting if the caching headers are also set).

For assetUrl, I do not see any interest in doing this.
For serviceUrl, it could be useful in some very specific cases if you need a fixed service URL.

**Comment by sigdestad** [comment]
I start remembering.. So what do you propose calling the parameter?
We already have types right? Absolute and relative right?

**Comment by GlennRicaud** [comment]
Yes

**Comment by sigdestad** [comment]
What do you want to call the parameter? This parameter seems to make no sense for content or url I guess?

**Comment by GlennRicaud** [comment]
I called it "contentPath".
And yes I did not add it to the functions attachmentUrl, componentUrl, pageUrl or url

**Comment by sigdestad** [comment]
ContentPath is not a good name, as this could also be used outside of sites? Any other suggestions?

**Comment by GlennRicaud** [comment]
No better suggestion. I close the pull request and put this issue back to backlog until the finalisation of the specs

**Comment by GlennRicaud** [comment]
After discussion with tsi:

Flag will be renamed to "contextPath" and will have the following possible values. "vhost" and "relative"

Create another issue to make sure that URL functions generated inside an app conserve the context path the same way the content path is conserved in portal.

**Comment by aro** [comment]
Looks good 👍  
Remember to update view functions documentation.
