### ISSUE TITLE
Hot link to edit-mode for Fragments in the Inspect Panel

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#5878]
When editing a page with Fragments, it might sometimes be a bit unclear that you have Fragments on the page. Sure, it says "Fragment" in the Inspect Panel, but since all the forms are gone (they're edited on the Fragment itself, not the current page using the Fragment) it takes a few minutes until you're made aware that "oh, it's a Fragment, I need to edit it somewhere else".

Adding a button saying something like "Edit Fragment" and then opening that in a new tab would greatly improve the UX here.

Consider the following screen. Opening a page and clicking a fragment. It uses a part that I know have settings. But the form doesn't show up here (obviously). Took me some poking around until I noticed it was a fragment and not a part.
![screen shot 2017-12-14 at 08 11 11](https://user-images.githubusercontent.com/1465598/33979898-bbcc927e-e0a6-11e7-8760-8d84385c5415.png)

**NB!** When user clicks the edit button and a new wizard tab opens for the fragment, we should auto-select the fragment in the page editor (which should also expand the Inspect panel). This should be done via new argument(s) of the ``EditContentEvent`` class.

**Comment by sigdestad** [comment]
Sounds like a simple and good improvement to add a link/button to edit the fragment in a new tab!

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-contentstudio #55](https://github.com/enonic/app-contentstudio/issues/55) via [**ZenHub**](https://www.zenhub.com/)
