### ISSUE TITLE
Cache properties in LocaleServiceImpl

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#5896]
Now the localization-resource is fetched for every invocation of localize. This seems to make off-heap memory grow on certain customer installations using the localize-lib. 

Cache properties on applicationKey+bundleName.
Make sure reloaded application invalidates entry.

**Comment by sigdestad** [comment]
I just remembered, aren't all resources loaded from file on every request? I.e. serving an asset, or fetching a controller? Maybe the controllers are cached already?

**Comment by aro** [comment]
The app resources loaded from file are cached. But the i18n bundles are recomputed everytime. The i18n bundles is not just the file, the resources are merged based on the locale requested, and filling the blank with the default bundle values.

We will now cache this result bundle based on locales parameters and bundle names. The cache will be invalidated when an app is updated.

**Comment by runarmyklebust** [comment]
3x(+) performance on the localize-function
