### ISSUE TITLE
Unable to get past '401 Unauthorized' on fresh installation

### ISSUE THREAD

**Issue by jvskriubakken** [enonic/xp#5923]
After installing XP i keep on getting an error page saying I'm unauthorized when I try to access the admin console on http://localhost:8080/admin
401 Unauthorized You don't have permission to access this resource
`com.enonic.xp.web.WebException.forbidden(WebException.java:42)
com.enonic.xp.portal.handler.WebHandlerHelper.checkAdminAccess(WebHandlerHelper.java:15)
com.enonic.xp.admin.impl.portal.AdminToolHandler.doHandle(AdminToolHandler.java:55)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:71)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
com.enonic.xp.web.impl.handler.WebDispatcherImpl.dispatch(WebDispatcherImpl.java:50)
com.enonic.xp.web.impl.handler.WebDispatcherServlet.doHandle(WebDispatcherServlet.java:135)
com.enonic.xp.web.impl.handler.WebDispatcherServlet.service(WebDispatcherServlet.java:63)
javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
com.enonic.xp.web.impl.dispatch.mapping.ServletDefinitionImpl.service(ServletDefinitionImpl.java:39)
com.enonic.xp.web.impl.dispatch.pipeline.ServletPipelineImpl.service(ServletPipelineImpl.java:30)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:45)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
com.enonic.xp.portal.impl.auth.AuthFilter.doHandle(AuthFilter.java:45)
com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
com.enonic.xp.web.impl.auth.BasicAuthFilter.doHandle(BasicAuthFilter.java:33)
com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
com.enonic.xp.web.impl.context.ContextFilter.lambda$doHandle$0(ContextFilter.java:33)
com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:101)
com.enonic.xp.web.impl.context.ContextFilter.doHandle(ContextFilter.java:32)
com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
com.enonic.xp.web.vhost.impl.VirtualHostFilter.doHandle(VirtualHostFilter.java:57)
com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
com.enonic.xp.web.impl.dos.DosFilterWrapper.doFilter(DosFilterWrapper.java:64)
com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
com.enonic.xp.web.impl.dispatch.pipeline.FilterPipelineImpl.filter(FilterPipelineImpl.java:29)
com.enonic.xp.web.impl.dispatch.DispatchServletImpl.service(DispatchServletImpl.java:35)
javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
org.eclipse.jetty.server.Server.handle(Server.java:517)
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
java.lang.Thread.run(Thread.java:745)`

I've tried to follow the installation instructions in README.md, which are pretty simple. I've successfully built the project using gradle build. 
Then I've started XP using several ways:
- Running gradle dist/run
- Running server.sh in the distributed build in modules/runtime/build/distributions/runtime....zip
but both without same result.

The only thing that works is downloading XP installation for MAC, but I would like run XP in development mode (from my IntelliJ) for better debugging. 

Thanks for help bringing my past this.

Jørund

**Comment by sigdestad** [comment]
You are probably running XP core without the apps included in the distro. As such no admin console or idprovider is installed. This was changed for 6.12 and the readme is likely not up2date.

**Comment by jsi** [comment]
Hei Jørund!

Alt vel?  Hyggelig at du fortsetter å følge med på oss!  ;)

Jeg har oppdatert README-filene.  Kan du se om det gir mening nå?  Kom gjerne med forslag til videre forbedringer.
