### ISSUE TITLE
Macro is not found when name contains hyphen "-" in name

### ISSUE THREAD

**Issue by RF0** [enonic/xp#5929]
A macro with a hyphen in its folder / file name are not found / processed. For example I had to rename the macro linked-image/[linked-image.xml | linked-image.js] to linkedImage/[linkedImage.xml | linkedImage.js] for it to work.

Tested in XP 6.11.0, 6.13.0.

**Comment by aro** [comment]
I reproduced this. It should be a small fix.
We will include it in the next minor release.
