### ISSUE TITLE
Admin lib - Change location of common and phrases resource bundles

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5931]
``getPhrases`` method in admin lib (``/lib/xp/admin``) currently looks for resource bundle (``i18n``) under ``admin`` folder (see below). Change it so that it looks directly in the ``resources`` folder. 
````
/**
 * Returns all i18n phrases.
 *
 * @returns {string} Current locale.
 */
exports.getPhrases = function () {
    return JSON.stringify(i18n.getPhrases(exports.getLocales(), ['admin/i18n/common', 'admin/i18n/phrases']));
};

**Comment by vbradnitski** [comment]
https://github.com/enonic/xp/pull/5949 contains commit for it.
