### ISSUE TITLE
Change email subject for the case when an issue gets assigned to a user

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5956]
If I first create an issue with no assignees and then assign it to a user, then he will get an email with the subject saying "Issue <blabla> was updated...". It comes as a surprise because he doesn't even know what this is about and why he got this email at all.

So, **in this case** the subject should be "You were assigned a new issue..." - same as the one we send when a new issue is created and assigned to the user at the same time. With the following updates the subject should be as now ("...was updated..."), it's only when the user was added to the list of assignees that the subject should be different.

**Comment by sigdestad** [comment]
Lets prioritize the other "issue" tasks first, and deal with optimizing the mail when they are completed..
