### ISSUE TITLE
Lock library

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5957]
We need a way to synchronize code in our controllers

**Comment by sigdestad** [comment]
How do you want this to work Glenn, what is the use-case? I thought the controllers were executing in their own threads?

**Comment by GlennRicaud** [comment]
Their exports.get/post/... are executed in their own threads yes. But they might access something declared outside of the function. And that is shared

Example:
```
var count = 0;

exports.get = function() {
  count = count + 1;
}
```
