### ISSUE TITLE
Implement update of a comment in an issue

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5965]

**Comment by sigdestad** [comment]
We need to provide a design for this before we start this task!

**Comment by alansemenov** [comment]
@sigdestad 

![image](https://user-images.githubusercontent.com/11612490/35045319-bb76c1b6-fb93-11e7-9654-aca239c73539.png)

![image](https://user-images.githubusercontent.com/11612490/35046193-985894f4-fb96-11e7-8bb1-dc35d1d49656.png)

**Comment by sigdestad** [comment]
Then pencil is ok, but the edit does not look good. Lets work on this together!
