### ISSUE TITLE
Implement delete of a comment in an issue

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5966]
![image](https://user-images.githubusercontent.com/11612490/35046964-d4447102-fb98-11e7-8a2b-afb8bdadfd9f.png)

* Ask for confirmation before deleting a comment: "Are you sure you want to delete this comment? This cannot be undone."
* Instantly update the number of comments inside the tab after deleting a comment

**Comment by sigdestad** [comment]
We need a design for this one too!

**Comment by alansemenov** [comment]
@sigdestad 

Alt.1: Delete button in edit mode

![image](https://user-images.githubusercontent.com/11612490/35046394-27c3b1aa-fb97-11e7-8196-3032e3955d1f.png)

Alt.2: Delete link in edit mode

![image](https://user-images.githubusercontent.com/11612490/35046507-758f7a54-fb97-11e7-8954-1ce55af166be.png)

Alt.3: Delete icon in edit mode

![image](https://user-images.githubusercontent.com/11612490/35046680-fc7e0b16-fb97-11e7-8699-214acd2b72c0.png)

Alt.4: Delete icon in regular mode

![image](https://user-images.githubusercontent.com/11612490/35046964-d4447102-fb98-11e7-8a2b-afb8bdadfd9f.png)

**Comment by alansemenov** [comment]
Deleted comment:
![image](https://user-images.githubusercontent.com/11612490/35047552-9761b360-fb9a-11e7-9495-92c71a925bcc.png)

**Comment by alansemenov** [comment]
Because it might be a part of the discussion which will stop making sense with comments removed from the middle. So it's more like hide, not delete.

Also, Github (which we are trying to copycat, I guess) is doing it like that :)

**Comment by sigdestad** [comment]
No, when I delete a comment in github it goes away...

**Comment by sigdestad** [comment]
I will delete this one!

**Comment by sigdestad** [comment]
And this one
