### ISSUE TITLE
When two contents are selected and one of  those is  'Deleted',  all buttons on the toolbar should be disabled

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5996]
1. Select(click on the checkbox) a content with the 'Deleted' status
2. Click on checkbox and select a content with New status

All buttons(except for 'Undo Delete' should be disabled(not displayed)

<img width="722" alt="grid" src="https://user-images.githubusercontent.com/3728712/35279127-301f2a08-005d-11e8-9649-1f2a8774317a.png">

**Comment by vbradnitski** [comment]
Issue moved to [enonic/xp-apps #550](https://github.com/enonic/xp-apps/issues/550) via [**ZenHub**](https://www.zenhub.com/)
