### ISSUE TITLE
Investigate problem Gradle 4.3 - Grunt

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6005]
A problem has been reported when using gradle wrappers 4.3 with grunt.
Worked when downgrading to 4.0.
Check kopinor repo to reproduce

**Comment by Bellfalasch** [comment]
Details, but it is the **kopinor-fabelaktig** repo to be specific. (they have 4 apps, it was on **-fabelaktig** it was found)

**Comment by GlennRicaud** [comment]
Closing this issue as we are now using Gradle 5.6
