### ISSUE TITLE
Item set is collapsed when clicking on help text

### ISSUE THREAD

**Issue by aro** [enonic/xp#6006]
- Create a content of type "shortcut"
- Click on "Add Parameters"
- If you click on the ? button next to "Parameters", the help text is shown but also the item set is collapsed and its fields hidden.

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #355](https://github.com/enonic/lib-admin-ui/issues/355) via [**ZenHub**](https://www.zenhub.com/)
