### ISSUE TITLE
Create WebSesssionFilter-implementation

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#6017]

**Comment by sigdestad** [comment]
I think rather than implementing a filter, we should use the explicit session replication support within Jetty: https://www.eclipse.org/jetty/documentation/9.3.x/session-management.html

With filters we have way less control I would assume?

**Comment by runarmyklebust** [comment]
We need to maintain full control of the replication engine, including lifecycle. I dont think that is possible by using this? Ignite also has a premade WebSessionsFilter, which is about the same thing as we must implement.

**Comment by sigdestad** [comment]
Ok.. I just tought jetty knew when to replicate what and invalidate better than any filter would?

**Comment by runarmyklebust** [comment]
It may be worth having a look, Ill add a task to investigate the upside of doing it as a SessionHandler - it means that we cannot use the built-in Ignite Filter but will have to implement our own.
