### ISSUE TITLE
Vhost config - Mapping for all hosts

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6024]
Today we need to define mappings for all the possible hostnames.

- Solution 1: A default mapping that will apply if no mapping is found for the host
- Solution 2: The possibility to use a wildcard character for the host name property value
  - Conflict resolution to be discussed

**Comment by sigdestad** [comment]
Glenn, what is the problem you are trying to solve?

**Comment by GlennRicaud** [comment]
If you use virtual hosting, you need to define mappings for all the hostnames that could potentially be used to access the installation.
I noticed that the vhost mappings are very often duplicated with for only difference, the hostname.

So not really a problem to solve.
More of a feature proposal if the PAB thinks it is interesting to implement.

**Comment by sigdestad** [comment]
vhost wildcards could be interesting, but can you come up with an example?
