### ISSUE TITLE
Images with invalid date metadata cannot be edited in Content Studio

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6036]
Upload an image with invalid dates in their metadata (exif) and that image is impossible to open up for editing in Content Studio. The image will work otherwise (able to be displayed with code, preview works, and so on). Edit screen will open, but be totally blank.

This is one image that has that problem.

This error occurred during Content 101 training. It's been reproduced on Mac, Windows, Chrome and Firefox.

Guess some checks needs to be made on all metadata on images so Content Studio doesn't fail just because the data was wrong, like negative dimensions or similar.

This is the image: 
![giraffe_standing](https://user-images.githubusercontent.com/1465598/36029451-8a661b5e-0da3-11e8-8bbf-c19d23a9d018.jpg)

This is how CS looks when trying to edit that image:
![screen shot 2018-02-09 at 14 14 52](https://user-images.githubusercontent.com/1465598/36029481-a3a1f372-0da3-11e8-86d9-b71244c73cb8.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #337](https://github.com/enonic/lib-admin-ui/issues/337) via [**ZenHub**](https://www.zenhub.com/)
