### ISSUE TITLE
HtmlArea: Editing existing links on images deletes the image

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6037]
Error happened for multiple students during training. Basically they wanted to link a smaller thumbnail images in a news article to the full width image, or to external website on a logo image. It's been reproduced on Windows and Mac, in Chrome and Firefox. All running XP *6.13*.

Do this:

* Edit any HtmlArea on a content
* Insert an image (new or old, doesn't matter)
* Click it and create a link anywhere

You now have a clickable image, that's nice.

Now you see that the URL (or content) target is wrong. And you try to edit it. That looks good, so you correct your target and clicks "insert" again. The image disappears. It is actually removed from code, leaving only the empty link, meaning that when you save the image is gone.

Source HTML looks like this.
```
<figure class="justify"><a href="content://9379cf99-24ae-4ef5-bbd4-ff5167b16267"></a>
<figcaption style="text-align: left;"></figcaption>
</figure>
```

Linked image - error happens when you Edit the link and "insert" those changes.
![screen shot 2018-02-09 at 14 20 02](https://user-images.githubusercontent.com/1465598/36029762-d734f058-0da4-11e8-9470-5ba60cded9fd.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #350](https://github.com/enonic/lib-admin-ui/issues/350) via [**ZenHub**](https://www.zenhub.com/)
