### ISSUE TITLE
HtmlArea saved content lagging behind what is shown in the form

### ISSUE THREAD

**Issue by hjelmevold** [enonic/xp#6045]
To reproduce:
* Clean install of XP v6.13.1
* Install Superhero app (but this occurs inside other apps as well)
* Create a new content of type Post
* _Quickly_ move focus to the Post text field, and _quickly_ type something, in my case this was "Ingen stillinger tilgjengelig."
* Save using keyboard shortcut command-s on Mac

The saved result in the content will then either:
* not be registered at all, and the surrounding input field being marked as required
* be truncated to a shorter value, such as ```</p>I</p>```

You then cannot "re-save" the content that is shown in the browser, since no changes seem to have been made since the last time you saved. But if you _slowly_ make a new change, you can save and then revert.

**Comment by alansemenov** [comment]
@hjelmevold Bjørnar, can you try this on 6.14 snapshot? I couldn't reproduce it.

**Comment by hjelmevold** [comment]
I haven't been able to reproduce this on any other computer than my own, so I think this must be a very rare race condition caused by something in my OS. I've tried different browsers and with all browser extensions disabled, but the problem is still there, also on 6.14. But since I'm the only one experiencing this on my computer and not on other computers, this issue can be closed.
