### ISSUE TITLE
Upgrade TinyMCE to 4.6.7 at least

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6063]
We might be abandoning TinyMCE, but we're still many many months away from that being ready to ship. In the meanwhile we run an outdated TinyMCE (4.6.1 as far as I can see). This has had [many releases since](https://www.tinymce.com/docs/changelog/), close to hundred bugs fixed, and have now reached 4.6.7.

Also 4.7.x is released, with 4.7.6 being the latest stable released. It too fixing multiple issues with the editor. Upgrading to this might be more complicated I guess, so not the most important thing to do.

So, while we're waiting for a brand new experience, why not make our life's a little more enjoyable by keeping TinyMCE up to date. Plz upgrade to 4.6.7 (latest 4.6-version). So we all can benefit from the many bugfixes they've made since the version XP runs.

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #414](https://github.com/enonic/lib-admin-ui/issues/414) via [**ZenHub**](https://www.zenhub.com/)
