### ISSUE TITLE
ContentResource - getVersionsForView should not filter on modifiedTime

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6066]
https://enonic.zendesk.com/agent/tickets/2343

The filtering (if it really must be done) should be instead on the _timestamp

**Comment by runarmyklebust** [comment]
On the question on whether it should be filtered or not, @sigdestad must chime in.
If we are going to use the _timestamp-property instead, we must change the ContentVersion in the api, and its also debatable if this is the correct approach (instead of making sure the content-domain property is set correctly instead) )

**Comment by GlennRicaud** [comment]
I did not know we had a concept of ContentVersion. I only knew about the NodeVersion.
Then I guess it is not a bug. We need a NodeVersion viewer then :)

**Comment by runarmyklebust** [comment]
Filtering of versions in the content-resoruce; If a version's modifiedTime is within 500ms of a version already added to the view, its not displayed.

**Comment by sigdestad** [comment]
Still makes no sense to me? When is this use, and if this is a list of contentVersions, why is it filtered?

**Comment by runarmyklebust** [comment]
I think it is done to prevent flooding the Version-view in ContentStudion with lots of versions that where created simultanious. It must have been required by you, I wasn't involved.

**Comment by GlennRicaud** [comment]
If I understood well: The Widget is a Content version widget and not a Node version widget. The filtering is done on modifiedTime on purpose and there is no bug
I close this issue
