### ISSUE TITLE
Log user actions in admin tools

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6067]
It was asked by a customer and it would be a useful feature when doing support.
But it might also be heavy to leave this feature turned on and will increase the complexity of the code.

I let the PAB discuss the interest of the proposition.

In our case, the problem is that it is very easy to follow the modifications of a content using the "Version history" widget, but we have no possibility to know what happened to a deleted content for example.

**Comment by sigdestad** [comment]
This will be handled by audit logging. Already existing PAB backlog issue
