### ISSUE TITLE
Searching for content types in the Template "supports" field doesn't match DisplayName

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6069]
Ref: this issue - https://discuss.enonic.com/t/cant-search-by-display-name/1418

You can search for the content type's name (like 'article') but not the Display Name it has. These two may often differ, so it's expected to be able to search in both. Also, an editor will have a relation to the Display Name, never the actual name only used in code.

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #353](https://github.com/enonic/lib-admin-ui/issues/353) via [**ZenHub**](https://www.zenhub.com/)
