### ISSUE TITLE
Scrollbar covers part of "status" text in Chrome when grid has many items

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6072]
**6.14 B2**

With the contents of The Grid fully expanded, we'll get a vertical scrollbar. In Chrome, this scrollbar is painted on top of the grid area making it cover parts of the status text on each content. Looks "off" even if one can still understand what it says.

![screen shot 2018-02-22 at 11 33 06](https://user-images.githubusercontent.com/1465598/36533607-4f1ff634-17c4-11e8-9d9f-8ce012fca974.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #356](https://github.com/enonic/lib-admin-ui/issues/356) via [**ZenHub**](https://www.zenhub.com/)
