### ISSUE TITLE
Editing permissions - the context menu with different capabilities gets stuck inside its container

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6073]
**6.14 B2**
**Chrome**

* Open Detail Panel for any content
* Click "Edit Permissions"
* Make sure "Inherit..." is not checked
* Click to edit any of the permissions

When you open the Detail Panel and click Edit Permissions, then try to edit one of the rights, the box popping up will be cut because it doesn't popup outside of the container but inside of it. One can scroll inside the container, but that just feels odd.

![screen shot 2018-02-22 at 11 37 02](https://user-images.githubusercontent.com/1465598/36533757-dbad1c76-17c4-11e8-983e-08d105f7a6c9.png)

The scrollbar is not in the area before clicking, but appears when you click and the context menu appears.

![screen shot 2018-02-22 at 11 38 13](https://user-images.githubusercontent.com/1465598/36533794-f68af70c-17c4-11e8-9da0-904bafd3450b.png)
![screen shot 2018-02-22 at 11 38 21](https://user-images.githubusercontent.com/1465598/36533795-f6a36710-17c4-11e8-93db-e20561d38bc3.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #405](https://github.com/enonic/lib-admin-ui/issues/405) via [**ZenHub**](https://www.zenhub.com/)
