### ISSUE TITLE
The "expand all help-text" displayed even when no help-texts exists

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6077]
For content without any help-text I believe we previously hid the toggle for "display all help text". In 6.14 B2 it is always shown, and possible to click.

![screen shot 2018-02-22 at 15 12 38](https://user-images.githubusercontent.com/1465598/36543046-e1f2acb8-17e2-11e8-970c-6ea04723bc9a.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #372](https://github.com/enonic/lib-admin-ui/issues/372) via [**ZenHub**](https://www.zenhub.com/)
