### ISSUE TITLE
Increase test coverage for low coverage classes

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#6082]
Hypothesis; there are a lot of classes that with low test coverage that is easily tested with a minor effort. Identify and create tasks.

**Comment by alansemenov** [comment]
@aro please make the list of classes that are missing tests, either entirely or for the most part

**Comment by aro** [comment]
Test classes in server-rest module. 
Resource classes in package `com.enonic.xp.impl.server.rest`:
- ApplicationResource
- ContentResource
- ExportResource
- IndexResource
- SnapshotResource
- SystemResource
