### ISSUE TITLE
Opening multiple contents for editing will make the last one freeze

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6085]
*6.14 B2*
*Chrome*

* Open Content Studio
* Expand a site, for example Corporate Theme
* Select 3 items

![screen shot 2018-02-23 at 12 52 14](https://user-images.githubusercontent.com/1465598/36593156-e5407858-1898-11e8-8df3-df2706fd74ee.png)

* Click Edit
* They'll open in new tabs - happy days
* However, the last tab will get frontend errors and never load, requiring full reload of page.

![screen shot 2018-02-23 at 12 52 06](https://user-images.githubusercontent.com/1465598/36593081-a28829ca-1898-11e8-92f2-7ec628853f8f.png)

This happens for the last item (no matter if you select 2, 3, 4, etc of items. It looks, in Chrome, like this is the tab that gets auto focus. The other tabs will start to load when focused, just like expected.

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #417](https://github.com/enonic/lib-admin-ui/issues/417) via [**ZenHub**](https://www.zenhub.com/)
