### ISSUE TITLE
Make it possible to filter on score range

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6094]
Apply to these:
- lib-content.query (currently no score)
- repoconnection.query
- multirepoconnection.query

**Comment by ComLock** [comment]
Range is perhaps a little overkill, min is what I need.

Usecase:

On a normal search results page showing a bunch of hits is fine.
However when doing the same query, but using it as autocomplete for a search input box you may only want to show the best results.

Workaround:
Use repo- or multirepo- connection.query and filter on score in js.
Problem with workaround is counts, aggregation, etc will be wrong.

**Comment by runarmyklebust** [comment]
Its possible (but not implemented) to limit the results based on the score, e.g a min_score parameter, but this will only affect the result-list - e.g the same as filtering in js afterwards (except for the payoff received by not fetching the content at all after query-time)

**Comment by ComLock** [comment]
Not certain it's the best thing to filter on either since the score depends a lot on the query.

**Comment by runarmyklebust** [comment]
Using the min_score will not influence the score, only filter the final result. Same applies when doing the filtering afterwards?

Only query and query-filter affects the score / aggregations.

**Comment by ComLock** [comment]
Yes as I said: "on the query"

**Comment by runarmyklebust** [comment]
As discussed; too complex and very difficult to use since the score will change based on both data and query
