### ISSUE TITLE
Change or remove questionmark in navigation bar in Content Studio

### ISSUE THREAD

**Issue by rolfrb** [enonic/xp#6095]
Version 6.13.1   

The questionmark in the navigation bar in the edit view in Content Studio should either

- show an explanation of what navigation bar does 
- toggle all questionmarks in all the subsections
- be removed

Currently, if I navigate to another subsection, it will still only toggle (the now invisible) questionmarks in the first section. And if you have a question about the second field of the first section, you will click on the querstion mark next to it, not the one in the navigation bar.

This is very confusing and an issue for all content I've tried this in.

Steps to reproduce: 

1. Create a site with acme wireframe
2. Edit the page
3. Click the question mark in the editor navigation bar
4. Click on "Publiseringsplan" and click the questionmark in the navigation bar, the questionmark will seem to do nothing. 

![image](https://user-images.githubusercontent.com/1007261/36779707-23f52fcc-1c71-11e8-89a0-e52c79872dcd.png)

**Comment by alansemenov** [comment]
Hi @rolfrb and thank you for the bug report. We have investigated this and help text icons inside the Publiseringsplan section are in fact not affected by the main help text toggler. The main toggler itself works as it should, it's the Publiseringsplan section that has a problem. We will fix this.

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #373](https://github.com/enonic/lib-admin-ui/issues/373) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alansemenov** [comment]
@rolfrb The fix will be released in version 6.14 next week
