### ISSUE TITLE
Admin User Creation - Real user check removal

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6105]
After discussion with tsi, was decided to remove the check that there is no real user. The check is now only
  1) Currently on the user store 'system'
  2) Flag 'adminUserCreationEnabled' existing and set to true

**Comment by jsi** [comment]
This will not be included in the release.  The change came in too late, so we can not release it with approved quality controls.  The alternative is to postpone 6.14.0 for a week, or somebody else executes the release this coming Tuesday.

**Comment by GlennRicaud** [comment]
Okay

**Comment by GlennRicaud** [comment]
The commit has not been included in the branch 6.14 so it was not included in 6.14.1.
Will merge now in branch 6.14 so that it is included if a 6.14.2 is released
