### ISSUE TITLE
Fragments can't be moved or imported to another site?

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6116]
I have a fragment which I want to move to another site.
I just get the error message in a green box: "Content can't be moved".

I also tried exporting it. Which worked.
But when I try importing it to the other site. I get the imported content box as expected.
But no content appears in the site.

**Comment by sigdestad** [comment]
See #5500

**Comment by alansemenov** [comment]
Will be fixed in https://github.com/enonic/xp/issues/5500
