### ISSUE TITLE
Support inline preview mode

### ISSUE THREAD

**Issue by RF0** [enonic/xp#6120]
Sometimes it is nice to know if a controller is rendered in preview mode inside Content Studio or in a separate window. Today we can only see if the user is req.mode=preview|edit|live, there is no way to distinguish if the preview is in separate window or inside Content Studio.

Feature request: Add a new parameter to the request object so that it is possible to check if the request is done from inside Content Studio or in a separate preview window. req.isInsideContentStudio = true|false

Example where this is useful:

I have a link contenttype that redirects the user to an external link by using a controller mapping, I use this f.x. to create a external link that can be included in the menu via menu-item mixin. Problem is that if I select the content ('Login') inside Content Studio, I don't want to do a redirect to the external login url, but I want to redirect if preview is in a separate window. I want to do the redirect directly in the controller, but I cannot, because I have no way of knowing if user is in separate window or inside content studio, therefore I have to do the redirect in the view like below.

[Code example on github](https://github.com/storebrand/delphi.ny/blob/6d4538f45280ab53255faa8a5eabc3466d759229/src/main/resources/site/controllers/optionlink.html#L24)

Inside view:
```
if (window.self === window.top){//check if preview is in own window, if so, do redirect
  window.location.replace(url);
}
```

Feature request:

I want to do something like this inside controller:
```
if (!req.isInsideContentStudio){
  return {
    redirect: url
  }
}
```

**Comment by Bellfalasch** [comment]
+100
I have multiple apps that could benefit from this. Today I deactive code on mode `preview`, but that is confusing if you use the full screen preview mode (the one without Content Studio wrapped around the page). Optimally I would want to add my code in that mode, but not when previewing inside Content Studio.

**Comment by alansemenov** [comment]
Implement an alternative preview url: ``admin/portal/inline/<branch>/<path>`` that will only be used for preview in the Content grid's preview panel. In this mode ``req.mode`` will be ``"inline"`` (as opposite to ``"preview"`` that will be used only for preview in a separate tab)
