### ISSUE TITLE
Default log configuration - Asynchronous logging

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6121]
Our default console and file logging is synchronous.
We would gain in speed, especially for verbose applications, by making this asynchronous.

It will not require much time since it is only configuration.
But it would be useful to have some before/after metrics

**Comment by sigdestad** [comment]
I vote a BIG+ on this one. I was under the assumption logging was already async?
Can we fix this for 6.14.2?

**Comment by aro** [comment]
I would not change this in a minor version. Most probably we won't notice so much in performance.

And it is not for free. When you turn in async, there is a queue and a thread involved. 
Maybe there is a reason why it's not async by default. At least I would measure it during a release cycle before making changes.

https://stackoverflow.com/questions/46411704/configuration-and-performance-of-the-asyncappender-in-logback-framework

**Comment by sigdestad** [comment]
Hmm.. wouldn't that writer thread be reused across all other requests? How can even writing to the same file from 100 parallell threads be threadsafe? Or is is in a synchronized block?

**Comment by rymsha** [comment]
Async logging usually not good especially for verbose applications, because it starts loosing log messages. So, price for speed may be too high.

https://logback.qos.ch/manual/appenders.html#AsyncAppender

**Comment by rymsha** [comment]
More details https://logging.apache.org/log4j/2.x/manual/async.html#Performance

One may think that log4j 2 is "the best" but there are alternatives on for logback as well https://github.com/logstash/logstash-logback-encoder

**Comment by sigdestad** [comment]
This is apparently a fairly complex topic. I suggest we dont spend (waste) time on logging. IMHO logging is working pretty good right now. A properly written app will not be logging much anyway!
