### ISSUE TITLE
Send (temporary) password to user on creation of user

### ISSUE THREAD

**Issue by diegopasten** [enonic/xp#6125]
It is a cumbersome and error prone to have to copy the generated/set password for a user to my own email and send it to a user. Especially when I have to make more than one user at once.

For any organisation with more than 10 users this has to be quite annoying.
I think this is a easy to implement but quite huge quality of life improvement.

**Comment by sigdestad** [comment]
Are you thinking of how this works inside "users" app?

**Comment by diegopasten** [comment]
Yes.

**Comment by sigdestad** [comment]
We are "shutting down" user creation directly from Admin, so this will have to be implemented in the idProvider (or elsewhere)
