### ISSUE TITLE
Group and roles are placed incoherently in Users

### ISSUE THREAD

**Issue by diegopasten** [enonic/xp#6127]
When looking at a user in the users tools Roles is to the left (or first) and groups is to the right (second), but when in user creation window its opposite Groups on top (first) and Roles below (second). 

Seems like a small thing but since I can't duplicate a user this is a bit annoying, when "copying" a user.

**Comment by alansemenov** [comment]
Issue moved to [enonic/xp-apps #741](https://github.com/enonic/xp-apps/issues/741) via [**ZenHub**](https://www.zenhub.com/)
