### ISSUE TITLE
Put standard XP apps on top of dashboard menu.

### ISSUE THREAD

**Issue by jsi** [enonic/xp#6128]
The dashboard menu always have the home screen on top.  (When on the Home Screen, this is sort of unnecessary, but not a big deal.)  -  Below the home screen, all the other apps come alphabetically sorted.  With many apps, this can easily cause the Users app to be moved off the screen, and while the Applications app and Content Studio come early in the alphabet in English, this is not the case in other languages.  So:

Please split the menu in three sections:
1. The Home button.
2. The standard apps (Content Studio, Users and Applications)
3. All the other apps in alphabetical order.

- There need not be any visible split between the sections, it is just there to make sure the apps come in a well defined order.

**Comment by sigdestad** [comment]
We will not do this - In upcoming releases, there is no difference between a "standard" app or any other apps.
