### ISSUE TITLE
Implement a setting in config file of Content Studio to switch HtmlArea to CKEditor

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6137]
We need to have a transition phase during which we will support both TinyMCE and CKEditor. This will allow users to a) test the new editor and b) try switching their content types from one to another and see how that works out.

To do that we will implement a new setting in the config file of Content Studio (``com.enonic.xp.contentstudio.cfg``):

``
htmlarea=ckeditor
``

When this setting is present in the file with this value, we will use CKEditor instead of TinyMCE in the HtmlArea.

We can pass value of the config setting from the controller via ``CONFIG`` object, like we do with ``tourDisabled`` setting in ``app-admin-home``.

**Comment by sigdestad** [comment]
Hmm.. could we try using a property to switch instead? Then we can test all of our existing content types and data?

**Comment by alansemenov** [comment]
Good idea, let's do this via config property of HtmlArea input type:
```xml
<config>
  <new>true</new>
</config>
```

**Comment by ashklianko** [comment]
Ok, will update

**Comment by sigdestad** [comment]
Still not a good solution, then we need to modify apps. I was thinking of a config file i.e. com.enonic.xp.contentstudio.cfg
htmlarea=ckeditor

**Comment by alansemenov** [comment]
Not sure if that’s a good idea - will make it impossible to test both editors side by side with the same content

**Comment by sigdestad** [comment]
Do we need that? Much more important to be able to test it at scale... We could even let partners test it with this property, and say it is beta mode.

**Comment by alansemenov** [comment]
Issue moved to [enonic/xp-apps #743](https://github.com/enonic/xp-apps/issues/743) via [**ZenHub**](https://www.zenhub.com/)
