### ISSUE TITLE
Folder URLs under assets default to index.html if it exists

### ISSUE THREAD

**Issue by espen42** [enonic/xp#6152]
It's currently possible to serve static files from /assets/ by referring to them directly in html files (with no need to resolve assetUrl). But index.html files can't be referred to by the URL to their parent folder - doing that just produces an error. 

I suggest adding a check for whether index.html exists in a folder, and defaulting to that if it does. 

Advantage: makes it possible to add independent static pages to an app (e.g. a self-contained and externally-built react client), without having to add a controller in main.js or a page/template/controller combo.

**Comment by sigdestad** [comment]
Need some more input on this espen? An example of how you do this in your application code etc?

**Comment by espen42** [comment]
Well, the use case I'm looking at now: 

I once made a simple scoring react webapp for a game. Apart from missing an API backend (and a reference to it), it's completely selfcontained and webpack builds static JS and CSS files that can run in the browser. Point the browser to file:// (...) /index.html, and it will work as an offline app, since all the references to the static files are relative. 

So it would be neat to be able to easily insert that app as a sub-app page in an XP app, among other XP pages. Intuitively/naively, I'd like to be able to just copy the built `dist` folder from the scoring app right into some place in the `<xpapp>/build` structure with gradle, and be able to reference that folder and display the static content as a page. Webpack also handles hashing of the file names, so the sub-app should be ready to be served when built.

There seems to be several ways of doing this now, all of them require a little bit of workarounding. Right now gradle copies my sub-app files into `/assets/client`, then moves the `index.html` from there and over to `site/pages/play`, and then regex-changes the relative resource file references in the html file to insert a `${clientAssetsUri}` prefix (for example, `src="./js/app_ca44e635bd.js"` is expanded to `data-th-src="|${clientAssetsUri}/js/app_ca44e635bd.js|"`), and then `clientAssetsUri` is supplied in the model by a controller in `site/pages/play`. Basically, the pre-built html file is inserted as a view during build. This works, but it's a bit cumbersome, the gradle tasks get really specific and ideosyncratic, and it needs both an added page controller and a template added in content studio. Not at all the generalizability I wanted.

I'm looking into improving this by using a router in main.js to point to the html file directly under assets, and hopefully that can serve the resources it needs directly by relative url instead of inserting the `${clientAssetsUri}` part. But the idea was that if referencing to a folder and defaulting to index.html was possible out of the box, there wouldn't even be a need for that controller/router - it could be done really easy in vhost, just by referencing the folder under assets.

Disclaimer: I'm a total XP noob. :) There may be other good and easy ways of doing this, I'm open to suggestions.

**Comment by rymsha** [comment]
Use lib-static instead. it supports index.html fallback
