### ISSUE TITLE
Controller Mapping - URL pattern not matching for non-root sites

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6158]
https://enonic.zendesk.com/agent/tickets/2406

**Comment by sigdestad** [comment]
6.14.3?

**Comment by GlennRicaud** [comment]
6.14.2

**Comment by sigdestad** [comment]
Why do you write it will be included in 6.15 then? If it is already live?

**Comment by GlennRicaud** [comment]
??
Written the 13th of april: "The bug has also been fixed in Enonic XP and will be present in Enonic XP 6.14.2 and 6.15."

**Comment by GlennRicaud** [comment]
Yes, that was the 17th of april. 6.14.2 was not released back then and not even planned.
So no it was not live yet.
