### ISSUE TITLE
pageContributions on form post (search page)

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6167]
According to @aro: Page contributions are only enabled for GET requests, and seem to remember that @sigdestad had a good argument for why that is the case.

On a typical search results page it would be nice not to populate the url field with a ton of query parameters. Using method POST is a common way to solve that.

Now since I pageContribute all styling, the search results page ends up without styling.

Programming everything dynamically (ajax) is a workaround, but is quite a bit of work.

**Comment by sigdestad** [comment]
Posts should in general not return HTML pages imho, and typically have side-effects. 
Simply hiding your parameters is not a good reason for doing this, and also trashes possibility for sending the search result as a link to someone else.

I suggest you go back to using  GET for this requirement.

**Comment by ComLock** [comment]
Good point.
