### ISSUE TITLE
Display inside edit of fragment where fragment is being used

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6170]
Requested by TINE editors.

Often, when you edit Fragments you're not aware of where it is actually being used. Yes, you could open up the Content Studio grid overview, scroll around for some time and find this fragment in the grid somewhere, and then open the widget panel, and then open the dependency widget, and then get this info.

This is obviously a waste of time, and clunky UX. Could we rather use the form-area for the fragment edit view (which is not used, since it's a fragment) and add a list there over where the fragment is being used (this list should be links, so one could go there directly to edit that page).

![screen shot 2018-04-16 at 08 32 01](https://user-images.githubusercontent.com/1465598/38793466-b024a658-4151-11e8-87ce-4725a414fd84.png)

**Comment by sigdestad** [comment]
Using form area for a different behaviour just for fragments is a no-go imho. However, introducing widgets in edit mode has long been in our plans. We should be able to do this quite easily.

Lets focus on this solution and make a design for it.

**Comment by alansemenov** [comment]
We're adding the detail panel to the Wizard which will enable seeing fragment dependencies, so I'm closing this.
