### ISSUE TITLE
PDF preview image

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6175]
It would be nice to have access to preview images of pdfs.

Something like previewUrl() similar to imageUrl().
Or perhaps just extend imageUrl?

Some questions: when should the preview get generated, and should it be cached/stored.

I'd use this on a search results page. So there might be many previews on the same page.

Useful code example:
https://stackoverflow.com/questions/4392640/thumbnail-of-a-pdf-page-java
https://pdfbox.apache.org/

**Comment by ComLock** [comment]
I guess the same would be nice for other files, such as word documents etc. Similar to what an operating system file explorer does. That might be difficult for file types that are not of an open standard like PDF is.

**Comment by alansemenov** [comment]
This is done
