### ISSUE TITLE
Edit-button for each content in the Publishing Wizard

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6184]
Improvement suggested by TINE editors during training.

When publishing any content, any related contents will also be included. It would be extremely handy to have a edit-link on each of these related contents so that I can open it up for editing in a new tab before finally clicking publish. It would improve the workflow around publishing (today you need to close the wizard, navigate to these items in the grid or in the form, and then edit them).

Today it looks like this. To be consistent with UI a pen-icon would be added next to the "x"-icon on the far right side.
<img width="686" alt="screen shot 2018-04-19 at 13 01 42" src="https://user-images.githubusercontent.com/1465598/38989778-46b30b5e-43d8-11e8-98de-9664fe848862.png">

**Comment by alansemenov** [comment]
@pmi
We already support opening content from that dialog but only for invalid items. Let's always open content wizard on click (there's not much space there for another icon). Also, get rid of "Edit invalid content" tooltip that we show for invalid items - always show tooltip with full path (see https://github.com/enonic/xp/issues/6185)

Do the same for the "main" content above the dependency list - both link and tooltip.

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-contentstudio #49](https://github.com/enonic/app-contentstudio/issues/49) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sigdestad** [comment]
But how will we visualize that you can click on the content to edit? We don't have this concept anywhere except grid? How about just supporting doubleclick then?

**Comment by alansemenov** [comment]
We change the mouse cursor to "hand". It's very obvious.

**Comment by sigdestad** [comment]
Also on a touch device?

**Comment by alansemenov** [comment]
On touch we could change text color to blue. We really don't have space for another icon there. And having edit and remove icons next to each will be challenging, especially on mobile devices.

**Comment by sigdestad** [comment]
Color blue? That indicates it is selected? Should all items be blue?

Suggestion: Lets try using "click anywhere except X" == edit, test it out.
