### ISSUE TITLE
Hover/click to display full URL for each content in Publishing Wizard

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6185]
Improvement suggested by TINE editors during training.

On hover, show the full URL for each content in the publishing wizard (main content(s) and its dependencies). For complex sites, one only sees a part of the URL, the left part, not the rest.

Today it looks like this. Not easy to see which image this is since only part of URL is displayed. With hover, or click, that information could be available to you if needed.
<img width="686" alt="screen shot 2018-04-19 at 13 01 42" src="https://user-images.githubusercontent.com/1465598/38989879-8a2a0ac2-43d8-11e8-92ac-3f9c93c16547.png">

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-contentstudio #50](https://github.com/enonic/app-contentstudio/issues/50) via [**ZenHub**](https://www.zenhub.com/)
