### ISSUE TITLE
Upload files from the Link dialog in HtmlArea fields

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6186]
I was certain I've added this before, but cannot find it. But the request popped up yet again. Improvement suggested by TINE editors during training.

Working in XP you really enjoy drag-n-drop to upload new images or files. However, when inserting links in the HtmlArea (using Cmd + K) you can link to Downloads (through a ContentSelector, I believe) but drag-n-drop/upload is not available there.

We wish for the same upload functionality to be added here (click to upload + drag-n-drop) that ImageSelectors have in general. (on the field Target at the bottom of this screenshot)
![screen shot 2018-04-19 at 13 54 05](https://user-images.githubusercontent.com/1465598/38990060-2cb95194-43d9-11e8-9acf-ba8c371807aa.png)

**Comment by sigdestad** [comment]
Hi.. We are actually making the "media selector" for 6.15.. when that is finished, we could probably fix this too.

**Comment by alansemenov** [comment]
As @sigdestad said, we will replace this selector with the new Media Selector which will have the upload button.
