### ISSUE TITLE
Keyboard shortcut to open content(s) in Preview

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6187]
Improvement suggested by TINE editors during training.

We have loads of keyboard shortcuts, and that's great. However, opening contents in fullscreen preview is something we do a lot, but there's no shortcut on the keyboard for that.

Could we have a key combo for that? Both in the grid and from edit mode would be great.

(be sure not to overwrite system-wide shortcuts, like Ctrl+P)

**Comment by mortyeriksen** [comment]
We decided on "Alt + Space" in PAB.

**Comment by edloidas** [comment]
Issue moved to [enonic/app-contentstudio #240](https://github.com/enonic/app-contentstudio/issues/240) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alansemenov** [comment]
Alt-Space is reserved in Windows for window's context menu so it will be Mod-Alt-Space
