### ISSUE TITLE
Keyboard shortcut to publish content(s)

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6188]
Improvement suggested by TINE editors during training.

We have loads of keyboard shortcuts, and that's great. However, publishing content(s) is something we do a lot, but there's no shortcut on the keyboard for that.

So, could we have a key combo for opening the Publishing Wizard? Both from the grid and from edit mode would be great.

(be sure not to overwrite system-wide shortcuts, like Ctrl+P)

**Comment by sigdestad** [comment]
Yes. Dette var en bra ide! cmd-P på mac da?

**Comment by alansemenov** [comment]
`Ctrl-Alt-P` doesn't seem to be reserved in either Chrome or FF, so we can go for that. I'm usually a bit reluctant to use first letter of a word in keyboard shortcuts due to localisation reasons, but in case of Publishing it's the same letter in both English and Norwegian so that's probably fine.

**Comment by Bellfalasch** [comment]
Good point Alan, translations might make the shortcuts tricky. But looks ok this time.

I would prefer using the `P` key for Publishing, and then rather skip shortcut for Preview in that case (because we more often click publish-button). `Ctrl/Cmd + Enter` is my favorite shortcut, I teach it during all training sessions and people love it (it seriously gets "WOW" reactions every time). So changing that would not be good. Also, `Cmd+Enter` usually works similar in emails or chat, you "send" (save and close) the text you're writing. It is the most natural choice to have Ctrl+Enter for this in Content Studio. So let's not change that one.

I'm all for Ctrl+Alt+P or any other three-key combo, or even Cmd+P.

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-contentstudio #72](https://github.com/enonic/app-contentstudio/issues/72) via [**ZenHub**](https://www.zenhub.com/)
