### ISSUE TITLE
Templates: display all contents using a specific template

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6189]
Improvement suggested by TINE editors during training.

If you need to quickly see which contents is using a specific template, there's no way for that in XP. Using the Dependency widget will not display contents using the template (through Automatic mode). And as far as I know, there's no other way.

There are a few times you might need to know "which contents will look differently after I change this Template here). If we somewhere could get a list over all contents using Automatic and/or this template directly, that would be very nice.

See, the empty Dependency widget attached.
![screen shot 2018-04-19 at 14 00 43](https://user-images.githubusercontent.com/1465598/38990321-17ef966e-43da-11e8-9081-391973cc1361.png)

**Comment by mortyeriksen** [comment]
We will add listing of content using the template on the detail panel.

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-contentstudio #332](https://github.com/enonic/app-contentstudio/issues/332) via [**ZenHub**](https://www.zenhub.com/)
