### ISSUE TITLE
Range query function does not work with ISO8601 instant parameter

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6190]
Given a content with publish.from = 2018-04-09T05:15:08.490Z

This works:
"(publish.from >= '2018-04-09T00:00:00.000Z' AND publish.from <= '2018-04-09T23:59:59.999Z')"

This fails:
"range('publish.from', '2018-04-09T00:00:00.000Z', '2018-04-09T23:59:59.999Z', 'true', 'true')"

**Comment by alansemenov** [comment]
@ComLock did you try with ``instant()``, as described in the [docs](http://xp.readthedocs.io/en/stable/developer/search/query-functions/range.html)?

**Comment by ComLock** [comment]
I did try dateTime and instant earlier, but not that exact example above. Since I've made my own workaround with the => <= I stopped digging deeper. Still think it's a bug though. The above should work even without instant() or dateTime()

**Comment by ComLock** [comment]
And it might still fail with eiter instant() or dateTime()

**Comment by ComLock** [comment]
no hits

**Comment by aro** [comment]
I tested it and it works using the instant function, as in the documentation. 
But it's a simple change to make it work for strings with the timestamp format.
