### ISSUE TITLE
filter on _references

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6191]
```
must: {
    references: [
        id1,
        id2
    ]
}
```

**Comment by alansemenov** [comment]
@Comlock you need to write a more elaborate description. Is it about query filter? inbound references? outbound? I'm also not sure how this might affect performance. @runarmyklebust ?

**Comment by runarmyklebust** [comment]
Dont think we will create a special filter for this, use
`hasValues: {
field: "_references",
values: [id1, id2...]`

**Comment by ComLock** [comment]
```
hasValue: {
	field: '_references',
	values: [
		'id1'
	]
}
```
