### ISSUE TITLE
Enable upload of new media files in HTMLArea's Insert Link dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6195]
On the Downloads tab of the HTMLArea's Insert Link modal dialog we now use Content Selector filtered by media content types. When MediaSelector is ready, we should use it there instead of Content Selector.

![image](https://user-images.githubusercontent.com/11612490/39129179-1b8fa47a-470a-11e8-98ab-7448b73b6266.png)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #457](https://github.com/enonic/lib-admin-ui/issues/457) via [**ZenHub**](https://www.zenhub.com/)
