### ISSUE TITLE
Publishing a content changes value in modifiedTime

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6200]
When a content item is published we create a new version and set `publish.first`. This also causes  modifiedTime to be updated with current date/time. We need to avoid modifiedTime being updated. It's common to have content sorted by modifiedTime and publishing should not affect this order.

**Comment by GlennRicaud** [comment]
We are modifying the content, so the modifiedTime should be updated.
The problem here is the original solution: Setting a value on a content on a publish. It is not only wrong but makes the initial publish 4 times slower.

**Comment by GlennRicaud** [comment]
I will close this issue.

IMHO, we should fix the way we do the publish and scheduled publish in 7.0.
Use the createdTime of the master version (instead of publish.first) and have scheduled task for the future for scheduled publish (instead of publish.from and publish.to)

**Comment by sigdestad** [comment]
So, logically the modifiedTime value is wrong, and must not be set as part of the publish process.

**Comment by sigdestad** [comment]
It actually breaks a lot of things when this value is changed as part of the publishing process.

**Comment by GlennRicaud** [comment]
Yes. I thought about it after and I definitely talked too fast here.
You are right about timestamp/modifiedTime and I also take back the solution proposed for 7.0 which is also wrong.

modifiedTime is not only about the content/data though. It is also modified on modifications on all the other properties: language, owner,… (which makes sense).
But I agree about making an exception for publish.first in this specific case.
