### ISSUE TITLE
Item set label - First input value displayed

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6212]
While editing an ID Provider config, I noticed that the value of the first input was displayed at the place where the item set label should be.
If I delete the item set and recreate it, I get the correct value.
If I click on help, the bug reappears.

Wrong item set label. It should be "User mappings"
![Screen Shot 2018-04-30 at 10.13.12.png](https://images.zenhubusercontent.com/58a5657151aa2c3057749a34/7f896c3e-fe2d-498b-aeed-2398bc2873ec)

When deleted, it uses "User mappings"
![Screen Shot 2018-04-30 at 10.13.20.png](https://images.zenhubusercontent.com/58a5657151aa2c3057749a34/a367b158-523f-47a9-a5a5-2e2c524bf13e)

If I add a new item, it uses "User mappings"
![Screen Shot 2018-04-30 at 10.13.27.png](https://images.zenhubusercontent.com/58a5657151aa2c3057749a34/491b8767-550f-4849-bbe3-deb908552aee)

If I click on help, the first input value is displayed
![Screen Shot 2018-04-30 at 10.13.33.png](https://images.zenhubusercontent.com/58a5657151aa2c3057749a34/76b5fcd3-dbe1-4499-a39b-e1c99f58b53a)

**Comment by sigdestad** [comment]
Glenn, this is actually intentional. In order to separate when you have a bunch of itemSets. Just looks a bit strange with this value - but still makes sense.

**Comment by GlennRicaud** [comment]
Okay. I close the issue

**Comment by alansemenov** [comment]
We already have a to-do bug/improvement to not use a value from input field when there's just one item-set: https://github.com/enonic/lib-admin-ui/issues/381. It will help for this case.
