### ISSUE TITLE
Enable manually plugging in x-data in the Content Wizard

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6216]
**As a Content Editor**, I want to be able to specify what x-data I want to fill out in the Content Wizard.

X-data 1  (+)
X-data 2  (+)
X-data 3   X
  Field 1
  [        ]
  Field 2
  [        ]
X-data 4  (+)

**Conditions of satisfaction:**
* x-data that match content type but are not explicitly added via site.xml or content type schema should be rendered inside the Content Wizard as collapsed step forms
* Only title with display name and "enable" button should be shown for a collapsed x-data 
* Clicking on the "enable" button should "inject/expand" the whole x-data step form, and add it to the list of steps.
* When content is saved with x-data step form expanded, we should save x-data object in the content json, even when no fields inside the form are filled out:
```xml
 "x": {
    "com-enonic-app-features": {
      "menu-item": {
      }
    }
  }
```
* Clicking on the "Disable" icon of an expanded x-data should collapse its step form. It's ok to keep field values inside a collapsed form (in case user closed it accidentally and wants to reopen it before saving)
* Before the content is saved, collapsed x-data object(s) should be removed from content JSON 
* After content is saved, fields inside collapsed x-data step form must be cleared
* When opening a content, those x-data step forms that have JSON object inside X-data object of content JSON must be expanded (even if x-data object is empty)

If x-data is explicitly specified in site.xml or in content type:
* Content wizard step navigator should always treat it as "enabled", and remove/hide the "disable" button (just like things work today)

<img width="537" alt="screen shot 2018-05-02 at 16 25 19" src="https://user-images.githubusercontent.com/482228/39528822-76f39386-4e25-11e8-84f5-99f761688eb6.png">

**Comment by sigdestad** [comment]
Question about the sorting order of x-data? What is it based on today? order of the apps?
