### ISSUE TITLE
Add request context info to Tracing 

### ISSUE THREAD

**Issue by aro** [enonic/xp#6217]
Add information from the current request and response to the Trace object.

**Comment by jsi** [comment]
Hmmmm.  I do not like this!  It was done in a way that reduce the code coverage with 0.02%  Is it possible to bring the code coverage back up in some way?  Please consider adding tests!

**Comment by GlennRicaud** [comment]
This modification should not require a new test.

What could be done to increase the coverage, and was proposed in the sprint meeting, is to dedicate time to write tests of portion of code not tested.
