### ISSUE TITLE
Render step forms in Content Wizard for x-data that match content type pattern

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6220]
x-data that is directly plugged in via schema from site.xml or content type schema should be rendered first (like now).

After these, render the list of x-data that match current content type (based on ``allowContentType``, remember that no ``allowContentType`` means that it matches all content types).

If x-data has corresponding data object in content JSON's "x" object, its form should be rendered as "expanded", with title and all of the form fields.
Otherwise, the form should be rendered as "collapsed" - with only form title.

![image](https://user-images.githubusercontent.com/11612490/39627115-f8e96e08-4fa4-11e8-9c1a-18965255d988.png)

**Comment by vbradnitski** [comment]
pushed to #6245
