### ISSUE TITLE
When saving content, toggle x-data in content JSON based on whether the x-data is enabled or not

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6222]
* When saving the content, add or remove data object of that x-data inside content JSON's "x" object based on whether the form of that x-data is expanded or collapsed. 
* If x-data is inside JSON but is no longer rendered in the Wizard (for example, x-data was added to content and then it was deleted from the app or its schema was changed), then it's removed from JSON upon save
* Clear the fields inside collapsed x-data forms after successful save.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #134](https://github.com/enonic/app-contentstudio/issues/134) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #133](https://github.com/enonic/app-contentstudio/issues/133) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #135](https://github.com/enonic/app-contentstudio/issues/135) via [**ZenHub**](https://www.zenhub.com/)
