### ISSUE TITLE
Implement toggle icon to expand/collapse x-data step form

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6224]
Implement icons that will expand and collapse x-data step forms. NB! Explicitly included x-data should not have these icons - their forms are always expanded, just like now.

Use "+" icon (tooltip: "Enable <mixin display name>", localise) to expand the form and "x" icon (tooltip: "Disable <mixin display name>", localise) to collapse the form.

Do not clear form fields after the form is collapsed.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #516](https://github.com/enonic/lib-admin-ui/issues/516) via [**ZenHub**](https://www.zenhub.com/)
