### ISSUE TITLE
Show/hide step in the step navigator toolbar on x-data form expand/collapse

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6225]
Dynamically show (in correct order) or hide step of x-data step form in the wizard step navigator whenever x-data form is expanded or collapsed.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #130](https://github.com/enonic/app-contentstudio/issues/130) via [**ZenHub**](https://www.zenhub.com/)
