### ISSUE TITLE
Toolbox init-project command does not set project name for library

### ISSUE THREAD

**Issue by aro** [enonic/xp#6226]
Using the init-project command with the starter-lib, does not set the artifact name correctly in the gradle build. 

This is because the maven plugin works different than the app plugin. It seems that the settings.gradle file should be handled.

**Comment by aro** [comment]
Looks like it works by creating a file``settings.gradle`` at the project root with:
```rootProject.name = projectName```

And setting the `projectName` variable in `gradle.properties`

Init-project is replacing the name in gradle.properties, so it should already work.

**Comment by GlennRicaud** [comment]
Toolbox removed. Closing this issue
