### ISSUE TITLE
Check why we provide vary-headers 

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#6231]
When we sends response, we provide the headers:  

`Vary: Accept-Encoding, User-Agent`

These headers makes the apache cache very ineffective. 

We should  not include "User-Agent", check out best-practice for this.

**Comment by rymsha** [comment]
Most obvious reason would be a support cashing redirects to mobile version of the site. (Vary: User-Agent) which we should stop using by default.
Accept-Encoding is still more-or-less needed to be there by default

**Comment by sigdestad** [comment]
Vary user agent should endeed be removed as a default setting.
