### ISSUE TITLE
Updating related contents in other tabs, should force refresh on main tabs Page Editor

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6240]
Confused many during training Content 101.

If you edit a content, like an Article, and this has related contents (like images, authors, etc) you can easily change these too, in another tab. Cool thing here is that if you change Display Name in another tab, the main tab's form will be updated with this info automatically. People love this little feature.

However, confusing for them is that the Page Editor is not refreshed. It still shows the old data. So even if the form looks ok and you see that an author has a new name, the Page Editor shows the old name. To us devs this makes sense - you didn't save. But the save button is not possible to click in 6.14 when only a related content is saved. Better would be if Page Editor could trigger a refresh in Page Editor based on changes to related content as well.

This would add for killer demo when you can edit related images (autofocus, cropping), authors and articles in another tab, and when you get back to the main tab, its Page Editor is refreshed automatically!

I see many users edit get confused here, they edit that related content, close that tab, and then check the Page Editor - huh, still old name, I should edit again, new name shows in edit mode of that content but not in Page Editor, cannot click Save either, let's just reload the entire browser ... and they get an experience we could improve.

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-contentstudio #243](https://github.com/enonic/app-contentstudio/issues/243) via [**ZenHub**](https://www.zenhub.com/)
