### ISSUE TITLE
Change related contents name in an ContentSelector and selector flat list not updated

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6242]
Reproduced in Firefox and Chrome with Corporate Theme app from market. But goes for all contents with a ContentSelector.

* Use the ContentSelector to add a related Content.
* Click the pen-icon to edit this content.
* Change the Display Name.
* Ctrl+Enter to save and close tab.
* _Super exciting, the changed name shows in the list under the ContentSelector._
* Open the flat list again using the arrow icon on the ContentSelector and the old name shows  there.

It would be expected to see the new name - Emma - everywhere, not only just underneath the list.

Underneath the ContentSelector we see updated content names:
![screen shot 2018-05-09 at 16 05 23](https://user-images.githubusercontent.com/1465598/39819091-d8d629ce-53a2-11e8-8ec9-b32a817f963f.png)

In the list we only see old names, never changes:
![screen shot 2018-05-09 at 16 05 20](https://user-images.githubusercontent.com/1465598/39819090-d8be4f02-53a2-11e8-824e-61d9924b9a9e.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #550](https://github.com/enonic/lib-admin-ui/issues/550) via [**ZenHub**](https://www.zenhub.com/)
