### ISSUE TITLE
Fetch dragged URLs from the ImageSelector

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6243]
Drag-and-drop support is great in XP. But anytime I talk about it during Content training, many will try to open a webpage, left-click an image from the page (not downloading it) and then drag this back to the Content Studio-tab and the ImageSelector. This will active the "Drop here" dialog, indicating that the image will be uploaded. But since in reality what you are dragging is just the URL of the image (even if Chrome and other browsers shows the image while you drag) the upload will not begin and you will be a bit confused. No messages either. It just disappears.

It would be pretty bad-ass if we could support also such dragging. If dropped data is text, and looks like an URL, we could try and fetch it and then upload in the background. Since I see this behavior repeat each and every training session, it suggest to me that this is how people would expect it to behave. Is it possible and not too complicated to improve this?

**Comment by mortyeriksen** [comment]
This should be fixed.

**Comment by alansemenov** [comment]
Yes, master.

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #606](https://github.com/enonic/lib-admin-ui/issues/606) via [**ZenHub**](https://www.zenhub.com/)
