### ISSUE TITLE
Never disappearing tooltips on the command line in Content Studio

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6244]
I get this all the time in Chrome (and have for some time) but cannot really reproduce it in a step-by-step way. But what happens is I demonstrate editing of a content so I save a lot. And after a while (sometimes sooner than later) the tooltop for "Save"-button opens and gets stuck. It never disappears (until tab is reloaded).

Could we clean this up? The mouse is nowhere near it so I'm not sure why it still shows. Maybe it is because it pops up and I save at the same time? Anyways, it should be possible to fix and make sure tooltips doesn't get stuck like that for ever.

There's no way in Chrome to get it to go away, except reload the tab:
![screen shot 2018-05-09 at 16 21 24](https://user-images.githubusercontent.com/1465598/39820025-1d070e86-53a5-11e8-8ada-5079d2157df8.png)
![screen shot 2018-05-09 at 16 21 30](https://user-images.githubusercontent.com/1465598/39820026-1d26576e-53a5-11e8-90f6-0e0fbe643b5a.png)

**Comment by alansemenov** [comment]
@Bellfalasch this is difficult to test, but most likely it was fixed in https://github.com/enonic/app-contentstudio/issues/163. I'll close it but please reopen it if you experience the same behaviour on the snapshot again.
