### ISSUE TITLE
Removed or changed keyboard shortcuts in CKEditor implementation

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6249]
For editors, the keyboard shortcuts we have in TinyMCE are well established and well used. We write about them in our docs, and teach them extensively through our Content 101 training. With CKEditor some of them are removed/not working, and some changed keyboard shortcut, this is not so fortunate unless well motivated.

Findings:
* No longer possible to use `Cmd+Alt+1-6` to change headings on text.
* No longer possible to open Insert Image dialog via keyboard shortcut (was `Cmd+L`).
* Keyboard shortcut for inserting links changed from Cmd+K to Cmd+L, using `K` looks odd but we have used it for many versions now, Google Docs uses it, and many other. If there is no direct reason behind this change, I'd suggest we leave this shortcut at `Cmd+K`.

Here's a list of all our established rich text shortcuts. Maybe more are changed/removed?
http://docs.enonic.com/en/stable/admin/contentstudio/shortcuts.html

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #505](https://github.com/enonic/lib-admin-ui/issues/505) via [**ZenHub**](https://www.zenhub.com/)
