### ISSUE TITLE
CKEditor: Improve UX on drag-n-drop uploading of images by giving visual queues when dragging

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6250]
When dragging images into any ImageSelector in Content Studio, we get that blue ring that pulsates indicating you can drop to upload. This ring would be very handy to also use in the new CKEditor that now supports very epic drag-n-drop of images. At first I wasn't sure the function would work, as other drag-n-drop supported elements in Content Studio use that blue circle. Could we also have that in the CKEditor (in a way that is not stopping the user from still placing that image at any location of choice).

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #616](https://github.com/enonic/lib-admin-ui/issues/616) via [**ZenHub**](https://www.zenhub.com/)
