### ISSUE TITLE
CKEditor: improved notice when same images is uploaded multiple times in same HtmlArea

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6251]
This is not a big one, but the feedback when I try to use the same images many times in the same HtmlArea (by uploading multiple versions of the same image), is a bit odd. I first get the "uploading" message, then quickly a "success" message and then a "404 couldn't find image" message. Pretty weird for the user, what actually happened.

I understand that image upload is blocked the second time because of it having a name that already exists on the same level, but could we present that to the user with a better message instead of 3 contradicting ones?

Again, this is not the most common thing to do, but nice to clean up if possible.

![screen shot 2018-05-15 at 13 37 00](https://user-images.githubusercontent.com/1465598/40054647-ea98d5ce-5845-11e8-8612-2c3afe8f0cef.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #558](https://github.com/enonic/lib-admin-ui/issues/558) via [**ZenHub**](https://www.zenhub.com/)
