### ISSUE TITLE
CKEditor: inconsistent padding on images with or without figcaption

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6252]
1. Add an image inside CKEditor
2. Float the image to left side
3. Add a caption

If an image has a caption, the padding around it will be massive inside the CKEditor when the image is floated (left/right aligned). Without caption, the image will look more normal and padding is not so big.

It would be nice if padding behaves the same, with or without figcaption.

With caption - massive padding:
![screen shot 2018-05-15 at 13 40 15](https://user-images.githubusercontent.com/1465598/40054753-3db90242-5846-11e8-9dbf-dba80cb0d93d.png)

Without caption - good padding:
![screen shot 2018-05-15 at 13 40 23](https://user-images.githubusercontent.com/1465598/40054759-3f5465e2-5846-11e8-8e05-bc8695b634e7.png)

Using Firefox Developer Edition.

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #506](https://github.com/enonic/lib-admin-ui/issues/506) via [**ZenHub**](https://www.zenhub.com/)
