### ISSUE TITLE
Implement modal dialog for duplicating content

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6260]
As a web editor I want to be able to specify when creating a duplicate of selected content whether I want to duplicate the entire tree (with children recursively included) or only the selected content itself, without the children.

**Conditions of satisfaction:**
* When I click Duplicate button in the toolbar from the Wizard or Content grid, the modal dialog opens
* Title of the dialog should be "_Duplicate content_" (localised to all of the supported languages), no subheader
* Each of the selected items should have a toggle icon for recursively including/excluding child items
* The "include children" toggle icon should be "on" by default, meaning that children will be by default included, representing current behaviour
* If selected item doesn't have any children, the toggle icon should not be visible (but the space occupied by it should still be vacant to preserve the layout), just like in the Publish dialog
* I can remove items from the list of selected content with **x** icon as long as there's more than one item (same as in the Delete dialog)
* Child items should not be removable (same as in the Delete dialog)
* When there's just one item selected, the **x** icon should be disabled
* Text of the link expanding/collapsing the list of child items should say "Show _child_ items"/"Hide _child_ items" (as opposed to "Show/Hide _dependent_ items" in other dialogs)
* Subheader of the child items list should be "_Other items that will be duplicated_" (localise)
* There should be no expand/collapse link and subheader if the list of child items is empty
* Number on the "**Duplicate**" button should represent the number of items that will be duplicated
* Any change in the list of content (exclusion of selected content, toggle of child items) should update the number on the "**Duplicate**" button
* For the time-consuming duplicate operation the progress bar should be shown inside the dialog
* REST API for duplicating content should be changed to support a new property indicating for each content item Id whether its children should be duplicated or not

Approximate look of the dialog:
![image](https://user-images.githubusercontent.com/11612490/40107551-db00debe-58f8-11e8-9d69-63c02e5d1498.png)

**Comment by sigdestad** [comment]
This is looking nice. remember that "hide child items" should be the default

**Comment by alansemenov** [comment]
It's default in all of the dialogs with sole exception of the Delete dialog.
