### ISSUE TITLE
Change Duplicate operation to take into account includeChildren property

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6267]
``content/duplicate`` API now takes an array of ``contentIds`` and duplicates them, always duplicating the child content as well. 

After https://github.com/enonic/xp/issues/6259 and https://github.com/enonic/lib-admin-ui/issues/508 request to API contains boolean property ``includeChildren`` indicating whether child items should be duplicated for this item or not. Change the code of duplicate operations to take this value into account.

**Comment by vbradnitski** [comment]
pushed to #6260
