### ISSUE TITLE
Status servlet down when ES/Ignite are down

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6292]

**Comment by GlennRicaud** [comment]
The problem is the following dependency of services: StatusServlet -> JettyService -> IgniteDataStore -> Ignite which is unregistered.

The question is should jetty be available without the sessions data store and  is it possible to plug it dynamically

**Comment by sigdestad** [comment]
Hmm.. Initially it feels like it makes sense that Ignite should be running before Jetty can start. Today jetty starts at the "end" of the boot process.
