### ISSUE TITLE
Content library - findVersions, getActiveVersions & setActiveVersion

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6345]
Asked by 2 two developers from Bouvet and Tine on Slack.
Then asked again, the day after, by the same developer on Discuss: https://discuss.enonic.com/t/programmatically-work-with-versioning/1542

It should not take too much time. The methods are already there. We just have to expose them in the content library

**Comment by sigdestad** [comment]
6.15?

**Comment by alansemenov** [comment]
Ok

**Comment by Bellfalasch** [comment]
Request for this feature dates all the way back into 2016 =)
https://discuss.enonic.com/search?q=version

**Comment by Bellfalasch** [comment]
Request for this feature dates all the way back into *2016* =)
https://discuss.enonic.com/search?q=version 

Or this, from Sept *2015* where we said "It will come with 7.0 that we plan to release Q1 2016", fun dive into history. https://discuss.enonic.com/t/content-versions/217/2

**Comment by sigdestad** [comment]
If there are no objectsion, lets just put this into 6.15.
@GlennRicaud , I would love to see the signature of the methods before you commit them? Also, I belive they want this for both content and node API's

**Comment by GlennRicaud** [comment]
I was thinking 6.16 or 7.0 but if it is a priority I will work on it today.
Please adapt the version though. We cannot be in RC1 and at the same time not be in feature freeze.

**Comment by GlennRicaud** [comment]
Been asked to stop the development for now.

For future development, start from work done in:
XP branch: issue-6345
App-features branch: issue-56

**Comment by GlennRicaud** [comment]
Closing this issue. See last comment in PR for more info: https://github.com/enonic/xp/pull/6454
