### ISSUE TITLE
Security Resource - Retrieve users with role filtering

### ISSUE THREAD

**Issue by pmi** [enonic/xp#6348]
@sgauruseu commented on [Wed May 23 2018](https://github.com/enonic/app-contentstudio/issues/145)

1. Open IssueDetailsDialog, go to Assignee tab and add a user **without roles**

![image](https://user-images.githubusercontent.com/3728712/40421722-824f3e76-5e95-11e8-99da-dad8556752aa.png)

2. Issue is updated and  `1` appears in  `Assignees`
3. Close the modal dialog
4. Open the issue in IssueDetailsDialog again
Bug : no any users are present in `Assignees`

**Comment by GlennRicaud** [comment]
I remove the milestone 6.15 since it has been removed in the other related issues in other repositories
