### ISSUE TITLE
Detach session from context for separated threads

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6350]
Depending on https://github.com/enonic/xp/pull/6346

* Go through the list of context creations and detach the session if the context was created for a different thread than the HTTP request thread

**Comment by aro** [comment]
I didn't find any other places. We only create threads explicitly, using ExecutorService, in a few places:
- IssueNotificationsSenderImpl: for sending emails in the background
- ApplicationListenerHub: sending application state change events
- TraceEventDispatcherImpl: sending tracing events to TraceListeners
- ContentServiceImpl: applying permissions recursively

Only in the last case it uses the Context.

The other place is TaskManagerImpl. But the tasks set up the branch, repo and AuthInfo from the context of the task submitter. No need to fix it here.

**Comment by GlennRicaud** [comment]
Perfect
