### ISSUE TITLE
ContentNodeHelper:translateContentParentToNodeParentPath impact check

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6351]
The method now return absolute paths (https://github.com/enonic/xp/issues/5699)
Go through the list of caller of ContentNodeHelper:translateNodePathToContentPath and check the impact.

ContentQueryWithChildren.java has been adapted in https://github.com/enonic/xp/pull/6344

**Comment by aro** [comment]
The relative path in both NodePath and ContentPath was overdesigning. And in my opinion should be removed in 7.0

If there was any place where it was relying in relative path then it was in some URL genereted by concatenating strings. I could not find any other code that shoud be affected by the fix.
