### ISSUE TITLE
Fully deleted images still visible in the HtmlArea

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6360]
Grabbed 6.15-SNAPSHOT just now and repeated this bug. It surfaced yesterday during Content training when a lot of editors got to try the CKEditor.

To repeat, do this:
* Open a Content Type with a HtmlArea
* Upload an image inside the text here
* Publish content and image
* Go back and delete (and publish) the image.
* Image is still visible in the HtmlArea, and output on page is a broken URL.
* Double clicking image will say image cannot be found, but still somehow it is visible

![screen shot 2018-06-20 at 09 49 04](https://user-images.githubusercontent.com/1465598/41644897-c0c2b63e-746f-11e8-93c4-af091ff8fdab.png)
![screen shot 2018-06-20 at 09 49 13](https://user-images.githubusercontent.com/1465598/41644899-c0dc64ee-746f-11e8-8259-42e3b8e9a9ca.png)
![screen shot 2018-06-20 at 09 49 30](https://user-images.githubusercontent.com/1465598/41644900-c0f8385e-746f-11e8-96ba-53ac21ee1427.png)

Could other references also be shown this way? It's only for admins, but I would take for granted that if an image is unpublished or deleted, it would not be in the resulting HTML from a HtmlArea.

**Comment by ashklianko** [comment]
I'll check!

**Comment by alansemenov** [comment]
Fixed in https://github.com/enonic/lib-admin-ui/issues/649
