### ISSUE TITLE
Wrong tooltips for keyboard shortcut issues in CKEditor

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6361]
Two minor things in 6.15:

* The keyboard shortcut for inserting links has always been Ctrl/Cmd + K (a lot of other systems use this too). The tooltip displayed, however, shows another shortcut. **This should be corrected to Ctrl/Cmd + K**.
![screen shot 2018-06-20 at 10 00 49](https://user-images.githubusercontent.com/1465598/41645371-16eb11cc-7471-11e8-95d9-7a701124d00e.png)

* The keyboard shortcut for inserting images has always been Ctrl/Cmd + L. This is not displayed in the tooltip. **Add shortcut in tooltip**.
![screen shot 2018-06-20 at 10 00 55](https://user-images.githubusercontent.com/1465598/41645374-1b6dacc8-7471-11e8-9eed-176f5921f7ad.png)

**Comment by alansemenov** [comment]
@ashklianko check if we can override tooltips

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #696](https://github.com/enonic/lib-admin-ui/issues/696) via [**ZenHub**](https://www.zenhub.com/)
