### ISSUE TITLE
Possibility to open images in HtmlArea in edit mode

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6363]
When inserting images in the HtmlArea, you can change the image alignment and such. But, if you want to edit the source image (for cropping, flipping etc) there is no handy shortcut in the UI of the image dialog for getting there. Why not a little link somewhere, or a pen-icon? That would open the source in a new tab so that it can be edited.

The insert image dialog then needs to refresh image if any changes are made to the image.

![screen shot 2018-06-20 at 10 55 41](https://user-images.githubusercontent.com/1465598/41648286-c1dbde48-7478-11e8-89da-404c2fa12539.png)

Today I need to find this image manually from the grid instead.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #629](https://github.com/enonic/lib-admin-ui/issues/629) via [**ZenHub**](https://www.zenhub.com/)
