### ISSUE TITLE
"View in Master"-button/toggle

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6369]
Now with 6.15 additional info in the interface, I'd love a button to just toggle what is displayed in the preview window. Many agree with me (based on feedback during training, etc) that it is not very easy to know "how does this article look in production/master" without actually publishing it and then locate that page in production (which is a pretty boring click-job when deep down in the content tree).

If we could add a button that could toggle "view in draft" and "view in master" for the preview panel, it would be extremely handy. Then you could easier explore the website and compare changes. Like, "what are actually changed in this article compared to what is published from before" when content have status "modified".

I find this taking more time than needed in XP when I use it as an editor, a button/toggle would greatly improve this experience.

![screen shot 2018-06-21 at 10 55 10](https://user-images.githubusercontent.com/1465598/41708898-2172843c-7542-11e8-9451-c58d766bd7d8.png)

If that button/toggle was here, on the screen above (to the very right, in the row that says "Publisert etter su") I could instantly see how the page looks without the unpublished service. Today this requires me to go to the live site and locate that page and refresh it.

**Comment by alansemenov** [comment]
but... but... we already have this feature request here: https://github.com/enonic/xp/issues/6239. it's coming :)

**Comment by Bellfalasch** [comment]
Haha LOL, already forgot. Closing this. Sorry
