### ISSUE TITLE
Change notification messages in Users and Applications

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#6385]
1. Install an application 
Actual : ` Application 'Chucknorris' installed successfully`
Expected: `Application 'Chucknorris'  is installed.`

2. Uninstall an application
Actual : ` Application '%s' is uninstalled`
Expected: `Application '%s'  is uninstalled.`

3. Create a new **userStore**
Actual - `User store was created`
Expected - `User store is created`

4. Update a userStore
Actual- `User store was updated`
Expected - `User store is saved`

5. Create an user:
Actual- `User was created`
Expected - `User is created`
when Updated - Expected - `User is saved`

6. Create a group
Actual- `Group was created`
Expected - `Group is created`
when Updated - Expected - `Group is saved`

7. Create a Role
Actual- `Role was created`
Expected - `Role is created`

8. Role updated:
Actual- `Role was updated`
Expected - `Role is saved`

**Comment by sigdestad** [comment]
We should drop all the is and was stuff. Role created - is good enough
