### ISSUE TITLE
Session storage - Save on each logged-in request

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6398]
Current situation: For logged in user, the session is stored for every request.

FI: There is a savePeriod config property (set by default 0ms => always save).
Investigate if there is a better alternative

**Comment by aro** [comment]
https://www.eclipse.org/jetty/documentation/9.4.x/configuring-sessions-file-system.html

`jetty.session.savePeriod.seconds=0`

> By default whenever the last concurrent request leaves a session, that session is always persisted via the SessionDataStore, even if the only thing that changed on the session is its updated last access time. A non-zero value means that the SessionDataStore will skip persisting the session if only the access time changed, and it has been less than savePeriod seconds since the last time the session was written.
