### ISSUE TITLE
Rest services missing in Jaxrs registry

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6400]
Screenshots: [osgi-resources.zip](https://github.com/enonic/xp/files/2155183/osgi-resources.zip)

Existing random problem that was mentioned multiple times and fixed with a restart.

Now reproduced 2 times (may be more frequent due to 6.15 changes):
All the OSGI services are correctly started but some are missing from the JaxRs registry.
Last time it was reproduced, on the 22 usual admin resources, the 5 following were missing: 
* ContentResource
* SecurityResource
* Tasks
* Macro
* Application

For testing, try to reproduce systematically by delaying the initialization of a resource.
Fix the recording in JaxRsServlet

**Comment by GlennRicaud** [comment]
I do not manage to reproduce for now. The thing noticed though is that these 5 problematic resources are the 5 last admin resource services started:

```
addComponent: class com.enonic.xp.admin.impl.rest.resource.auth.AuthResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.content.ContentIconResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.content.ContentImageResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.content.ContentMediaResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.content.page.PageDescriptorResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.content.page.PageResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.content.page.PageTemplateResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.content.page.fragment.FragmentResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.content.page.layout.LayoutDescriptorResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.content.page.part.PartDescriptorResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.issue.IssueResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.schema.content.ContentTypeResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.schema.mixin.MixinResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.schema.relationship.RelationshipTypeResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.status.StatusResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.widget.WidgetDescriptorResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.security.SecurityResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.content.ContentResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.task.TaskResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.application.ApplicationResource
addComponent: class com.enonic.xp.admin.impl.rest.resource.macro.MacroResource
```

**Comment by sgauruseu** [comment]
I also sometimes reproduced this bug - when I built new XP locally and start it, I saw the notification message : "Could not find resource for full path ....."
I thought, the cause of this issue was  that I updated the XP,  but did not delete  resources in 'repo' 
Because XP works good again, when I stopped server, cleared the repo and restarted XP.

**Comment by GlennRicaud** [comment]
Duplicated https://github.com/enonic/xp/issues/6517#issuecomment-591389680
