### ISSUE TITLE
Permissions report in Users app

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6403]
Item Statistics panel should have a new section to generate a report on permissions.

* The report will include both direct memberships set for a principal and transitive memberships
* List only items where principle has effective permissions
* The report will have a flat list of node path, id and permissions (Read, Write, Push etc.) for each in CSV format
* First line should be a header with column headings
* Each permission should have its own column
* Only system.admin should be able to generate the report
* User should be able to select the repos he wants the report on
* Have a dropdown with the repo list; when user clicks Generate for selected repo we'll add a line with a report generation task underneath and a progress bar. When the task is done, the progress bar will be replaced with the Download button.
* system.admin will have all of the nodes in the report

**Comment by GlennRicaud** [comment]
Note to self:
app-users: branch issue-92
lib-admin-ui: 3b160ecdd5faa9ae9fceca443dbf03b5bdb3a750

**Comment by pmi** [comment]
PRs: 
lib-admin-ui: https://github.com/enonic/lib-admin-ui/pull/777
app-users: https://github.com/enonic/app-users/pull/116
