### ISSUE TITLE
Blobstore/Version/IndexConfig 7.0 refactoring

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6406]
* One root folder by repository: /data/cms-repo/blobs/aa/bb/cc/aabbccxxx
* Remove IndexConfig from versions and replace with an ID. Extract the IndexConfig to a folder in the data blobstore: data/cms-repo/index/aa/bb/cc/aabbccxx (the ID would be the md5 of the file)
* node will now be stored by Node ID, with versions as subfolder/files (the versions will not be md5 anymore but a random ID) to allow upgrading of version files.
* (Lower prio)Binary counter in the index to keep track of number of nodes using the Binary
* Rewrite Vacuum (Example: Repositories can be deleted in an easier way)
* Rewrite versions table (only need to hold versions that are in branches), and nodes that are/ have not yet been deleted
* Fix "Hack" for detecting changed nodes (related to metadata - ask @runarmyklebust )
* Look at dump/export format

**Comment by sigdestad** [comment]
Will maybe be safer to use a generated ID per repo than name?
