### ISSUE TITLE
Server not restarted properly after config change

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6411]
Change a value in com.enonic.xp.cluster.cfg
For example, set cluster.enabled=true

The server does not restart properly and keeps logging the following:
WARN  c.e.x.c.impl.ClusterManagerImpl - Waiting for cluster providers

**Comment by rymsha** [comment]
I work in this in #7511 
It happens when several clusters available, but Elasticsearch does not come first to be configured
