### ISSUE TITLE
Treat contents of HTML Area as a property value instead of a string

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6453]
* The input type "HtmlArea" should now be property set.
  * It contains a property "value" of type string.
  * It contains a property "references" of type reference.

* Adapt com.enonic.xp.inputtype.HtmlAreaType
* Adapt the usage of HtmlStripper to that it is used on the property "value" instead

**Comment by sigdestad** [comment]
Hmm, how about shredding everything into element and attributes instead? What would this look like, isit good or bad?

**Comment by GlennRicaud** [comment]
Not sure if I understand correctly: You want to split the value between normal text and the content links.
Why do you prefer this solution?
How do you want to store these values?
