### ISSUE TITLE
JsonExceptionMapper - label is required

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6461]
https://discuss.enonic.com/t/enonic-version-6-15-0-has-been-released/1595

Apparently some mixin schemas are breaking with 6.15. The label is now mandatory.
Find out why and fix

**Comment by GlennRicaud** [comment]
https://enonic.zendesk.com/agent/tickets/2518

**Comment by aro** [comment]
Pending of pull request to master
