### ISSUE TITLE
Extract references from HTML Area by parsing its contents 

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6470]
There are three cases when HTML Area can reference content items:

1. When inserting an image via "Insert image" modal dialog (example: ``<img src="image://<contentId>">``)
2. When inserting a link via "Content" tab of the "Insert Link" modal dialog (example: ``<a href="content://<contentId>">``)
3. When inserting a link via "Download" tab of the "Insert Link" modal dialog (example: ``<a href="media://download/<contentId>">``)

When saving contents of HTML Area, we should parse it and extract/store references to contentId.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #721](https://github.com/enonic/lib-admin-ui/issues/721) via [**ZenHub**](https://www.zenhub.com/)
