### ISSUE TITLE
Clean up HTML Area classes/code

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6471]
1. Remove TinyMCE lib
2. Remove old classes working with TinyMCE
3. Rename all classes ending with "_CKE_" (for example, _HTMLAreaBuilderCKE_ -> _HTMLAreaBuilder_)
4. Clean up code for all of the "``if ... then``" where we check if TinyMCE or CKE classes should be instantiated
5. Remove the check for config option that defines whether TinyMCE or CKE is used
6. Clean up ``html-area.less`` so that only CKE styles remain
7. Remove TinyMCE assets from the build files

**Comment by ashklianko** [comment]
Moved to lib-admin ui
