### ISSUE TITLE
Corporate Internal Market (nexus)

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6474]
It would be nice if it was easy to install (few mouse clicks) a bunch of apps a company has which should not be available on the internet (our market).

Typically a company will have their own nexus to uploadArchives and download libs using gradle.

Would it be possible to make some integration with nexus to make an corporate internal market?

**Comment by ComLock** [comment]
Or just provide a market app.

If I could have my own "personal" market for the bunch of apps I have made which perhaps does not belong on the official Enonic market, that would be nice too. Simply pointing to a folder of jar files on the local HD could work too.

**Comment by alansemenov** [comment]
Yes, we need a market app which you can configure to point to your own apps (at github, repo or wherever) and then they will be shown on a separate tab inside the Install app dialog.

**Comment by sigdestad** [comment]
I suggest we fokus on making it easy to create and add apps in Enonic Cloud. Here is a screenshot of what it might look like
![screen shot 2018-09-07 at 11 43 46](https://user-images.githubusercontent.com/482228/45211724-4f968000-b293-11e8-8035-010c9ef79b2e.png)
