### ISSUE TITLE
customselector is calling service with request.params.ids as JSON string rather than Array of Strings

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6479]
Fixing this might break api, so perhaps this should be included in 7.0

Documentation states:
"Array of item ids already selected in the CustomSelector. The service is expected to return the items with the specified ids."
ref: http://docs.enonic.com/en/stable/developer/schema/input-types/custom-selector.html

Lets say occurences maximum is 1.
Then the list of ids will only ever contain 1 entry.

So if it was an array is should be this simple:
```javascript
const id = req.params.ids[0];
```

But since its a string, one have to do something like this???

```js
const id = req.params.ids.substring(2, req.params.ids.length - 2);
```

Or if one is rather stupid:

```js
const ids = eval(req.params.ids);
const id = ids[0];
```

**Comment by ComLock** [comment]
The documentation: http://docs.enonic.com/en/stable/developer/schema/input-types/custom-selector.html mentions a tutorial: http://docs.enonic.com/en/stable/tutorials/custom-selector/index.html#custom-selector-tutorial

Which shows even weirder ways of converting the req.params.
Am I just tired or something. I thought req.params handling where easier than this?

```js
try {
        ids = JSON.parse(params['ids']) || []
    } catch (e) {
        log.warning('Invalid parameter ids: %s, using []', params['ids']);
        ids = [];
    }

    try {
        start = Math.max(parseInt(params['start']) || 0, 0);
    } catch (e) {
        log.warning('Invalid parameter start: %s, using 0', params['start']);
        start = 0;
    }

    try {
        count = Math.max(parseInt(params['count']) || 15, 0);
    } catch (e) {
        log.warning('Invalid parameter count: %s, using 15', params['count']);
        count = 15;
    }
```

**Comment by ComLock** [comment]
I'm tired ;)

**Comment by ComLock** [comment]
Perhaps the correct fix for this is to make clear in the documentation that the request parameters are passed as strings, or a list of strings (when a property has multiple values), or as a JSON string.

I think it would be nice if the thingy calling the service used a list of strings instead of a JSON string to list ids?

**Comment by ComLock** [comment]
ref: https://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request

**Comment by alansemenov** [comment]
@ComLock we will change it to pass comma-delimited list of strings (ie "``?ids=1,2,3``") which will then should be formatted to array via ``params['ids'].split(',')``

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #803](https://github.com/enonic/lib-admin-ui/issues/803) via [**ZenHub**](https://www.zenhub.com/)
