### ISSUE TITLE
Get a node/content for a specific version

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6498]
Feature request from a Seeds employee.

After the completion of the following tasks
  https://github.com/enonic/xp/issues/6345
  https://github.com/enonic/xp/issues/6459

... it will be possible to list the content versions and node versions and restore them (medata)
This feature is about retrieving the entire node/content for a specific version (metadata+data)

**Comment by sigdestad** [comment]
Hmm.. is this not exposed in the API already? If not we must do it.

**Comment by GlennRicaud** [comment]
Done in issue https://github.com/enonic/xp/issues/7319
