### ISSUE TITLE
Check why regex for excluding x-data for a content type stopped working

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6500]
This used to work for enabling x-data for all content types except folders, but not anymore:
  ``<allowContentType>((?!base:folder).)*$</allowContentType>``

Here's the schema in app-features: https://github.com/enonic/app-features/blob/master/src/main/resources/site/x-data/all-except-folders/all-except-folders.xml

**Comment by vbradnitski** [comment]
regex should be ^(?!base:folder$).*
