### ISSUE TITLE
User-agent vary header removal

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6502]
Task description: XP by default uses a VARY header that includes User-Agent - this is not good as it means cache is not re-used when user agent string is different.However it also includes a vary header based on Accept-Encoding (which is fine). Remove User-Agent from the standard header produced by XP

**Comment by sigdestad** [comment]
Can we get this fixed for 6.15.1 instead?

**Comment by GlennRicaud** [comment]
6.15.1 is already being released. But I will fix it for 6.15.2 (and merge in 7.0 of course).

**Comment by GlennRicaud** [comment]
Modify GZipConfigurator. Extend GzipHandler:getVaryField
Check if set at different places
