### ISSUE TITLE
correct horse battery staple should be a legal password (allow users to create password with space)

### ISSUE THREAD

**Issue by RF0** [enonic/xp#6515]
Through 20 years of effort we've successfully trained everyone to use passwords that are hard for humans to remember but easy for computers to guess. Enonic XP should allow the user to create good passwords despite this fact.

<img width="672" alt="screen shot 2018-08-22 at 10 35 49" src="https://user-images.githubusercontent.com/951293/44452604-3b962180-a5f7-11e8-8603-0d73a47885c0.png">

<img width="678" alt="password strength" src="https://user-images.githubusercontent.com/951293/44452472-e9ed9700-a5f6-11e8-9f1d-ba42f057bb76.png">

**Comment by alansemenov** [comment]
this is very related to #6516 and should be fixed there.
