### ISSUE TITLE
password is not a good password - work is needed on the algorithm that decides what is a good password

### ISSUE THREAD

**Issue by RF0** [enonic/xp#6516]
Since we have restrictions on which passwords to use, we should not allow the worst possible passwords available.

![screen shot 2018-08-22 at 11 57 38](https://user-images.githubusercontent.com/951293/44457135-abf67000-a602-11e8-97ca-9233daff592b.png)

![screen shot 2018-08-22 at 11 59 29](https://user-images.githubusercontent.com/951293/44457183-db0ce180-a602-11e8-9763-dd5ae6020e4d.png)
-http://time.com/5071176/worst-passwords-2017/

**Comment by alansemenov** [comment]
See also https://github.com/enonic/xp/issues/6515

**Comment by sigdestad** [comment]
Lets see if there are any libs that kill off stupid password, and embed this in the back-end of the standard idprovider!

**Comment by ahmedelkassas52** [comment]
Need more information to use it

**Comment by alansemenov** [comment]
Will be fixed in https://github.com/enonic/app-users/issues/34
