### ISSUE TITLE
Satisfied WebDispatcherServlet

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6517]
Happened when restarting one node of a 3nodes cluster in RED state. The 12 following OSGI services were 'SATISFIED':
  com.enonic.xp.web.impl.exception.ExceptionMapperImpl
  com.enonic.xp.web.impl.handler.WebDispatcherServlet
  com.enonic.xp.admin.impl.portal.AdminPortalHandler 
  com.enonic.xp.portal.impl.app.AppHandler
  com.enonic.xp.portal.impl.error.ErrorHandlerScriptFactoryImpl
  com.enonic.xp.portal.impl.exception.ExceptionRendererImpl 
  com.enonic.xp.portal.impl.handler.attachment.AttachmentHandler
  com.enonic.xp.portal.impl.handler.identity.IdentityHandler
  com.enonic.xp.portal.impl.handler.mapping.MappingHandler
  com.enonic.xp.portal.impl.handler.portal.PortalHandler
  com.enonic.xp.portal.impl.handler.service.ServiceHandler
  com.enonic.xp.portal.impl.websocket.WebSocketManagerImpl

Also to note. There was an exception on startup for this node:
```
23:45:17.473 ERROR c.e.x.c.i.app.ApplicationServiceImpl - Cannot install application [no.gjensidige.intra.redirect]
java.lang.NullPointerException: null
	at com.enonic.xp.core.impl.app.ApplicationServiceImpl.storedApplicationIsStarted(ApplicationServiceImpl.java:448)
	at com.enonic.xp.core.impl.app.ApplicationServiceImpl.doInstallStoredApplications(ApplicationServiceImpl.java:212)
```

The Enonic XP version (<6.15) is to be confirmed. It matters when trying to reproduce since the startup has been changed with the new cluster behaviour in 6.15

**Comment by GlennRicaud** [comment]
The problem I have noticed is when admin rest services are created while being queried.

TO reproduce: Restart a node and and bombard of requests the admin rest endpoints

**Comment by rymsha** [comment]
@sgauruseu @jsi @alansemenov have you ben able to reproduce it recently?

> Could not find resource for full path http://localhost:8080/admin/rest ...

**Comment by alansemenov** [comment]
Not for a long while. Can be closed, I think

**Comment by rymsha** [comment]
Let's wait for @sgauruseu comment

**Comment by sgauruseu** [comment]
This problem did not reproduce for me when I used clusters with two nodes, I think that this does not reproduce with three nodes also

**Comment by rymsha** [comment]
Problem not reproduced, does't mean it disappeared :)
By looking closer on affected components I could see that they are either non-immediate (so they stay SATISFIED until other components request them), or they depend (sometimes indirectly) on ContentService.
So this is definitely same as #8173
