### ISSUE TITLE
Content lib doesn't support new format of x-data when creating content

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6534]
```Javascript
  var contentLib = require('/lib/xp/content');
  contentLib.create({
    name: 'mycontent',
    data: {},
    x: {
        "com-enonic-app-features": {
            "menu-item": {
                "menuItem": true
            }
        }
    }
```

When x-data is passed as a part of content object when creating a content via ``create`` method of the content lib, the operation will fail with an exception:

_ERROR c.e.x.p.i.e.ExceptionRendererImpl - Mixin not found [com.enonic.app.features:menu-item]
com.enonic.xp.web.WebException: Mixin not found [com.enonic.app.features:menu-item]_

Can be easily reproduced with _JS Libraries/Content_ helper in ``app-features``.

**Comment by GlennRicaud** [comment]
@alansemenov: Not sure if this was a support ticket, but tell them they will have to rebuild their application with the 6.15.3 libraries also
