### ISSUE TITLE
Wrong behaviour for "Enter"-button when inside Move-dialog

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6544]
**6.15.1**

When moving a content you'll be presented with the "Move dialog". Here you'll find a ContentSelector for selecting a new parent. After you have selected that parent, you might hit the Enter-key to perform the move. This doesn't work, instead the selected item in the background (current item) will be opened for editing. This is a confusing behaviour, expected is that either 1. don't support enter key and don't do anything, or 2. let enter key be the same as clicking the "Move" confirmation button and perform the move. Now, the enter-key "leaks" downwards through the dialog and is used as it would be if you just clicked something in the grid and hit enter (open for edit).

Reported by Norsk Tipping during training.

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-contentstudio #408](https://github.com/enonic/app-contentstudio/issues/408) via [**ZenHub**](https://www.zenhub.com/)
