### ISSUE TITLE
"Compact mode" of the Component Viewer in Page Editor

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6545]
On normal desktops (like in our training facilities) the resolution is not very high. This means when inside the Page Editor, things gets rather crowded. Storebrand requested specifically for the Component Viewer to add a "compact mode" to be more useful. Today we print "part" and "layout" and other details for each "segment" of the page. This is also reflected by the icons. On pages with 1-2 layouts and 8-10 parts, or more - the component viewer will present vertical scrolling to be able to see everything. This makes moving things around difficult, and you don't get a good overview by scrolling.

Could we introduce a little link in the top right corner saying "Toggle compact mode" or similar (like Google does it in many of their web apps). This would remove redundant information, like type of component. It could also make icons smaller, and basically make each row half the height. This would help editors working a lot with page setup on large pages.

Today this is how it looks. This page contains only 6 parts, 1 text component, and one layout with two regions - already making the overview crowded.

![screen shot 2018-09-06 at 12 12 38](https://user-images.githubusercontent.com/1465598/45151505-d170a580-b1ce-11e8-924e-407e0fa752ae.png)

**Comment by sigdestad** [comment]
We need to make a design suggestion for this @Bellfalasch will handle

**Comment by Bellfalasch** [comment]
<img width="421" alt="screen shot 2018-09-07 at 12 09 21" src="https://user-images.githubusercontent.com/1465598/45213116-f16b9c00-b296-11e8-965e-9a7902b26a70.png">
I just changed the CSS in the Inspect Tool of DevTools in Chrome. I didn't adjust the paddings, but items would need to be fitted a bit tighter than this. Other than that:
* Half size of icon.
* Hover icon to display type of component
* Slightly bigger text (name of component)
* Reposition arrows etc.

Bonus would be to find a better icon for opening context menu as the downward facing arrow more looks like it indicates movement.

**Comment by Bellfalasch** [comment]
Google uses three horizontal dots for things like opening context menus (...).

**Comment by sigdestad** [comment]
Three dots is a good solution for this. Regarding the design, we could probably make the icon/text a bit bigger. Now it looks a bit too spacy?

**Comment by Bellfalasch** [comment]
Space was something I just skipped to adjust for the screenshot I sent, to save some time (too many places to adjust to get it right). So yeah, make it even tighter.

**Comment by alansemenov** [comment]
Let's skip the toggle button for now and automatically switch to compact mode on resolutions < 960px.
The context menu icon (arrow) should be replaced with the triple dots icon in both modes.

**Comment by sigdestad** [comment]
Didn't we agree to only have the compact mode? Not two different modes?

**Comment by sigdestad** [comment]
Also, dnd is not working on mobile phones anyway? or am I wrong? DnD with the small fields is going to be hard.

**Comment by alansemenov** [comment]
Yes, if we will always have compact mode then we'll get a problem with DnD. Current look feels natural on high resolution, so I think we should make it responsive.

**Comment by pmi** [comment]
Issue moved to [enonic/app-contentstudio #435](https://github.com/enonic/app-contentstudio/issues/435) via [**ZenHub**](https://www.zenhub.com/)
