### ISSUE TITLE
Not possible to see full description for ID Providers in User admin tool

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6549]
6.15, 6.14, etc.

Description for an ID Provider in XP might need to be a bit longer than the limited with of the modal we have in User admin tool. If installing the ADFS ID Provider, the text will not fit, and will be cut. It is not possible to read it in any way (hover, break row, read more-toggle, etc). Could this be handled better?

![screen shot 2018-09-06 at 14 59 13](https://user-images.githubusercontent.com/1465598/45158919-b0677f00-b1e5-11e8-918c-898088ee75cb.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-users #130](https://github.com/enonic/app-users/issues/130) via [**ZenHub**](https://www.zenhub.com/)
