### ISSUE TITLE
applyFilters and postProcess in error handler

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6580]
I have made an app which adds tealium tracking to a site.
It does this with pageContributions in a filter.

However filters and pageContributions does not work in error handlers.

I think it's a good idea that applyFilters and postProcess is set to false by default for error handlers.
However when I explicitly set true in my response, I would like it to do what I tell it to :)

You see, tracking 404 etc is rather important for most customers.

It would be nice if simply adding the tracking app would be enough, rather than to have to change the error handling code to much...

**Comment by sigdestad** [comment]
As commented by alex, error handler executes after the filtering in the pipeline, so it is not possible to do.. with good intensions too!
