### ISSUE TITLE
Re-deploying app will close Inspect Panel in Page Editor

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6590]
The panel where you edit config for components is closed the moment XP detects the app is gone (actually when it is being reloaded because of changes to the app source and `gradle deploy -t` is active). This is very annoying when testing things out locally and the panel keeps closing itself all the time.

Happens at least in *6.15*

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #588](https://github.com/enonic/app-contentstudio/issues/588) via [**ZenHub**](https://www.zenhub.com/)
