### ISSUE TITLE
Set up Jacoco for Code Coverage with Codacy

### ISSUE THREAD

**Issue by jsi** [enonic/xp#6598]

**Comment by jsi** [comment]
Also look for Code Coverage tools for JavaScript and TypeScript.

**Comment by rymsha** [comment]
https://github.com/codacy/codacy-coverage-reporter/blob/master/README.md#travis-ci

**Comment by rymsha** [comment]
now even better https://github.com/codacy/codacy-coverage-reporter-action

**Comment by rymsha** [comment]
this didn't work well, so it got removed https://github.com/enonic/xp/issues/8767
