### ISSUE TITLE
Modal dialog - Fix delay after task progress bar is 100% complete

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6599]
When for example duplicating lots (1000+) of content items there's a 3-5 seconds gap between the moment when the progress bar is 100% complete and the moment when the dialog is closed. Adding verbose logging shows that this it's the ``FINISHED`` task status that comes from server with delay. Find out why this happens and try to fix.

**Comment by pmi** [comment]
The reason of the delay is the following recursive code:
`
    private void updateChildReferences( final Node duplicatedParent, final NodeReferenceUpdatesHolder nodeReferenceUpdatesHolder )
    {
        final FindNodesByParentResult findNodesByParentResult = doFindNodesByParent( FindNodesByParentParams.create().
            parentPath( duplicatedParent.path() ).
            from( 0 ).
            size( NodeSearchService.GET_ALL_SIZE_FLAG ).
            build() );

        final Nodes children = GetNodesByIdsCommand.create( this ).
            ids( findNodesByParentResult.getNodeIds() ).
            build().
            execute();

        for ( final Node node : children )
        {
            updateNodeReferences( node, nodeReferenceUpdatesHolder );
            updateChildReferences( node, nodeReferenceUpdatesHolder );
        }
    }

    private void updateNodeReferences( final Node node, final NodeReferenceUpdatesHolder nodeReferenceUpdatesHolder )
    {
        final PropertyTree data = node.data();

        boolean changes = false;

        for ( final Property property : node.data().getProperties( ValueTypes.REFERENCE ) )
        {
            final Reference reference = property.getReference();
            if ( reference != null && nodeReferenceUpdatesHolder.mustUpdate( reference ) )
            {
                changes = true;
                data.setReference( property.getPath(), nodeReferenceUpdatesHolder.getNewReference( reference ) );
            }
        }

        if ( changes )
        {
            UpdateNodeCommand.create( this ).
                params( UpdateNodeParams.create().
                    id( node.id() ).
                    editor( toBeEdited -> toBeEdited.data = data ).
                    build() ).
                binaryService( this.binaryService ).
                build().
                execute();
        }
    }
`
