### ISSUE TITLE
Connection reset when attempting to download

### ISSUE THREAD

**Issue by kyma** [enonic/xp#6602]
I can't download the development distribution. Get a network error via browser, and via wget, it fails:
curl: (56) Recv failure: Connection reset by peer
Failed to download distribution : status = 56

This is happening every time

**Comment by alansemenov** [comment]
Hi, can you give us a bit more information? Are you clicking Download button [on this page](https://enonic.com/downloads#download-other)? Do you get an error when accessing our repo [directly](http://repo.enonic.com/public/com/enonic/xp/distro/6.15.3/)?

**Comment by alansemenov** [comment]
If you still experience errors trying to access the distro, please report it on [our forum](http://discuss.enonic.com). We are using the github repo only for development issues.
