### ISSUE TITLE
Only first app with controller mappings work. All other apps mappings gets ignored.

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6611]
App WHATEVER:
```xml
<mapping controller="/unversionedAssetsWHATEVER.js" order="10">
            <pattern>/assets/WHATEVER/.*</pattern>
</mapping>
```

App SOMETHING:
```xml
<mapping controller="/unversionedAssetsSOMETHING.js" order="10">
            <pattern>/assets/SOMETHING/.*</pattern>
</mapping>
```

If app WHATEVER is first in site, its mapping work and not app SOMETHING  mappings. 

If app SOMETHING is first in site, its mapping work and not app WHATEVER  mappings.

**Comment by ComLock** [comment]
Hmm, perhaps I can work around this using lib-router.

**Comment by ComLock** [comment]
Hmm nah I don't know how to use lib-router on a site app. Would probably require vhost mapping etc.

**Comment by ComLock** [comment]
I gotta double check this one. There was some wrong regexp in my patterns.

**Comment by aro** [comment]
I have just tested having mappings in 2 different apps and it works for me.

Can you double check that the script in those 2 apps are in the path specified?

**Comment by ComLock** [comment]
I'm not gonna work with than code anymore, and you are probably correct. So closing it down.
