### ISSUE TITLE
Implement REST endpoint for fetching the list of image styles

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6619]
We need an admin REST endpoint which will be used to fetch the list of image styles (https://github.com/enonic/xp/issues/6617, https://github.com/enonic/xp/issues/6618).

* The list should contain a combined list of styles from predefined **styles.xml** and custom-defined **styles.xml** from all apps of the site
* Only styles for ``<image>`` elements
* Fields needed in response:
-- _name_ (string)
-- _display-name_ (string)
-- _type_ (string)
-- _requires_ (array of objects with two fields: ``name`` and ``displayName`` (optional))
-- _params_ (object)
* Style _name_ must be unique in the list
* CSS path must include app name, and be unique
* Order of priority is from the first to last app, predefined styles in the end. If there's a style called "my-style" in an app and in predefined **styles.xml**, it's the app's style that should be fetched. This way users can override predefined styles by defining a style of the same name.

**Comment by alansemenov** [comment]
Expected format:

```json
{
    "css": "assets/styles/styles.css",
    "styles": [{
        "name": "editor-style-raw",
        "type": "style",
        "displayName": "Unprocessed raw image"
    }, {
        "name": "editor-align-justify",
        "type": "alignment",
        "displayName": "Justify",
        "requires": {
            "name": "editor-width-auto",
            "displayName": "Auto (100%)"
        }
    }, {
        "name": "editor-align-left",
        "type": "alignment",
        "displayName": "Align Left",
        "requires": {
            "name": "editor-width-auto",
            "displayName": "Auto (40%)"
        }
    }, {
        "name": "editor-align-center",
        "type": "alignment",
        "displayName": "Center",
        "requires": {
            "name": "editor-width-auto",
            "displayName": "Auto (60%)"
        }
    }, {
        "name": "editor-align-right",
        "type": "alignment",
        "displayName": "Align Right",
        "requires": {
            "name": "editor-width-auto",
            "displayName": "Auto (40%)"
        }
    }, {
        "name": "editor-width-auto",
        "type": "width",
        "displayName": "Auto"
    }, {
        "name": "editor-width-actual",
        "type": "width",
        "displayName": "Actual"
    }, {
        "name": "editor-width-custom",
        "type": "width",
        "displayName": "Custom"
    }, {
        "name": "editor-style-cinema",
        "type": "style",
        "displayName": "Cinema",
        "params": {
            "scale": "21:9"
        }
    }]
}
```

**Comment by aro** [comment]
Moved to Content Studio, to be implemented as a service.

https://github.com/enonic/app-contentstudio/issues/485
