### ISSUE TITLE
Mixin's inlining works only through ContentTypeResource

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#6634]
As I can see, we use Mixin just for inlining it's fields in form after splitting XData and Mixin in 7.0.

But it doesn't work properly: 

We store InlineMixin like a form item during \<form\> xml parsing in backend. And then inline it's content only for ContentTypeResource response. So "inlining" doesn't work if we get our form not through ContentTypeResource, for macros e.g.

I see 2 variants to make mixins work for all forms:

1. Inline it during all FormJson creations. 
  I can't find any place where we don't actually need to inline mixins in form in frontend, and it shouldn't work anyway, because we don't have InlineMixin form item class in frontend, it should throw an error.

2. Just inline mixin content during \<form\> parsing, skip storing InlineMixin in form items.
This one will let us to remove a big piece of code and looks better for me but are there any pitfalls?

For both cases it looks we don't need Mixin code in frontend, so it can be removed.

**Comment by alansemenov** [comment]
@GlennRicaud what do you think? This is needed for https://github.com/enonic/xp/issues/6600

**Comment by GlennRicaud** [comment]
I did not see I was assigned to this.

Well I love the idea of the 2nd proposition. That would remove a lot of unnecessary complexity.

Possible problem #1: Caching
- Well there is caching of resource like descriptors in XP, but there is invalidation by application key and you cannot reference a mixin from another application.
But I am thinking about DEV mode and I would like to be sure that descriptors using mixins are correctly invalidated when a mixin is modified in DEV mode.

Possible problem #2: Mixin service
To be able to do this, you need to access MixinService in all XmlFormMapper.
We need to sure that there will not be any cyclic dependency. Like ResourceService needs MixinService that needs ResourceService.

Possible problem #3: We really need to keep them for a reason that I do not see yet. @aro any reason why we should not? 

If there is something problematic in any of the above then let's do proposition #1 (less risky)
