### ISSUE TITLE
Applying permissions in the Content Wizard should not require saving the content

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6636]
"Edit permissions" dialog behaves differently when used from the Content grid (when opened via info widget) and from the Content Wizard. In the first case permissions will be applied right after the Apply button is clicked, in the second case user has to save the content to apply the permission changes. 

This is confusing, and we should change the behaviour to always apply permissions with the Apply button, without having to save. Other changes done in the Wizard should not be a part of this permission change operation - if user changed some data in the Content Wizard and then changed permissions, he will have to save the changes.

See also https://github.com/enonic/xp/issues/6635 - this must work in exactly the same way when changing permissions from the Content Wizard, and user must get the same notification ("_Permissions applied to content..._") after the task is completed.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #509](https://github.com/enonic/app-contentstudio/issues/509) via [**ZenHub**](https://www.zenhub.com/)
