### ISSUE TITLE
Update indexing of page for flattened page

### ISSUE THREAD

**Issue by aro** [enonic/xp#6651]
Update the index configuration in `PageRegionsConfigProcessor` according to the changes in the page components structure.

Remove the double wild cards "**" since it is not necessary anymore with the flat structure.

Set the following index paths

- Image components:
  - `"components.image.id"`

- Fragment components:
  - `"components.fragment.id"`

- Text components:
  - `"components.text.value"`

- Layout components:
  - `"components.layout.descriptor"`
  - `"components.layout.config.<app-key>.*"`

- Part components:
  - `"components.part.descriptor"`
  - `"components.part.config.<app-key>.*"`

- Page:
  - `"components.page.descriptor"`
  - `"components.page.template"`
  - `"components.page.customized"`
  - `"components.page.config.<app-key>.*"`

**Comment by sigdestad** [comment]
This one is particularily interesting, as we had to do some special tricks to index page content in 6.x. Is there any logical improvement we can do to how we store data to optimize indexing/search of pages?
