### ISSUE TITLE
Flattened page structure - Dump migration

### ISSUE THREAD

**Issue by aro** [enonic/xp#6653]
Create an upgrade script to upgrade content nodes created with 6.x that used the tree structure for the page. They should be converted to the new flattened page structure.

TODO: Describe how to do this @GlennRicaud

**Comment by GlennRicaud** [comment]
Explanations in: https://github.com/enonic/xp/issues/6697
Code present both in epic-6649 and issue-6697

**Comment by GlennRicaud** [comment]
For the following page
![screen shot 2018-11-28 at 10 10 48](https://user-images.githubusercontent.com/12030113/49143815-24548780-f2fc-11e8-82aa-a84d7eb030ea.png)

Here is the Node data part of the VersionNode
[nodedata-aftermod.json.txt](https://github.com/enonic/xp/files/2623837/nodedata-aftermod.json.txt)
[nodedata-beforemod.json.txt](https://github.com/enonic/xp/files/2623838/nodedata-beforemod.json.txt)

**Comment by GlennRicaud** [comment]
@aro:
Some question regarding the new serialization:

1) The property "config" of Image components has been dropped. It has been replaced by a property "caption". Is that on purpose?
2) The property "config" of Image components has been dropped. Is that on purpose?

**Comment by GlennRicaud** [comment]
If all of this is on purpose, then I will start the dump migration tomorrow.
But we will not be able to merge all of this before https://github.com/enonic/xp/pull/6781 is merged, since dump migration is sequential.

![screen shot 2018-11-28 at 16 28 13](https://user-images.githubusercontent.com/12030113/49162252-c2f7dd00-f32a-11e8-8bdc-af67894a2c88.png)
![screen shot 2018-11-28 at 16 28 19](https://user-images.githubusercontent.com/12030113/49162249-c2f7dd00-f32a-11e8-9723-f3edbcaf932c.png)

**Comment by ashklianko** [comment]
> @aro, @ashklianko :
> Some question regarding the new serialization:
> 
> 1. The property "config" of Image components has been dropped. Is that on purpose?
>    It has been replaced by a property "caption" with as value the property "caption" of the Image component config.
> 2. The property "config" of Fragment components has been dropped. Is that on purpose?

Hi Glenn, I removed it on a purpose in spite of it is not mentioned in a task; Config is not needed neither for fragment or image, it is used with components that have a descriptor (layout and part) and a page itself;

**Comment by sigdestad** [comment]
What happens if the fragment is a part or layout?

**Comment by aro** [comment]
@GlennRicaud Agree with @ashklianko , image and fragment don't have config.
I'm not sure about storing the caption. I guess you could say that caption is part of the image config? If we want to keep it. Not sure if it is actually used.

Fragment just points to the content of type "portal:fragment" that contains the fragment components. It doesn't matter if it is part, layout, image or text.

**Comment by GlennRicaud** [comment]
@aro: https://github.com/enonic/xp/blob/52101771ae9dff847ffc62e58abc473607b1930f/modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/upgrade/flattenedpage/FlattenedPageDataUpgrader.java
