### ISSUE TITLE
Implement node create indexValueProcessors htmlStripper

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6659]
Documented here: http://repo.enonic.com/public/com/enonic/xp/docs/6.15.4/docs-6.15.4-libdoc.zip!/module-node-RepoConnection.html#create

But according to @runarmyklebust not implemented yet.

Future example:

```javascript
_indexConfig: {
  default: 'byType',
  configs: [{
    path: 'data.response.body',
    config: 'fulltext',
    indexValueProcessors: ['htmlStripper']
  }]
}
```

**Comment by vbradnitski** [comment]
@ComLock I'm not sure about provided example, what would you expect in next case:
```javascript
_indexConfig: {
  default: 'byType',
  configs: [{
    path: 'data.response.body',
    config: {
                        "decideByType": false,
                        "enabled": true,
                        "nGram": true,
                        "fulltext": true,
                        "includeInAllText": true,
                        "path": false,
                        "indexValueProcessors": ['processor1']
                    },
    indexValueProcessors: ['processor2']
  }]
}
```

@GlennRicaud what do you think?

**Comment by ComLock** [comment]
@vbradnitski I really don't know about indexValueProcessors. The fact there was one called 'htmlStripper' is something @runarmyklebust told me about.

**Comment by GlennRicaud** [comment]
From what I see the behaviour to use a custom index config is already there. Just not documented.
Instead of passing a string 'fulltext', you pass an object.
For example for a fulltext with htmlStripper:

```
_indexConfig: {
  default: 'byType',
  configs: [{
    path: 'data.response.body',
    config:  {
      "decideByType": false,
       "enabled": true,
       "nGram": true,
       "fulltext": true,
       "includeInAllText": true,
       "path": false,
       "indexValueProcessors": ['htmlStripper']
    }
  }]
}
```

**Comment by GlennRicaud** [comment]
@ComLock Could you try. We will close this issue then
