### ISSUE TITLE
autoLogin should be called even for /admin/rest

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6678]
workaround for now is use handle403

**Comment by alansemenov** [comment]
@ComLock  from the description I have no idea what this is about, but you shouldn't use admin API from outside of the admin, it's not a public API.

**Comment by ComLock** [comment]
@alansemenov This is regarding idprovider implementation.

**Comment by ComLock** [comment]
@GlennRicaud Asked me to make the issue, I guess I was a bit sloppy with context.

**Comment by rymsha** [comment]
Cannot reproduce. It is called.
