### ISSUE TITLE
toolbox import progress and slow listing in terminal

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6679]
When importing huge exports like 14.24GB I have no idea whether an import is frozen or still working except looking at the server log.

Also when it finishes the listing of imported content is sooooo long that the terminal take a long time to list, just because of the "baud" rate of the terminal... Which makes the import seem even slower.

So logging to a file and then reporting where that file is could be a log quicker?

**Comment by ComLock** [comment]
Just as an example:

This takes 3 minutes:
time $XP_INSTALL/toolbox/toolbox.sh import -a su:password -t cms-repo:draft:/content -s cms_content/content 2>&1 > import.log

This also takes 3 minutes:
time cat import.log

**Comment by ComLock** [comment]
import.log is 40MB and looks like a very long line, so less and tail really don't work on it.
And atom freezes.

**Comment by alansemenov** [comment]
We're replacing toolbox with Enonic CLI in 7.0 which will have progress update on time-consuming tasks
