### ISSUE TITLE
lib-http-client should handle cookies

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6680]
For example if you get this page http://lvh.no/naar_det_haster/drukningsulykker

It will redirect to an error page if you don't handle cookies.

Current workaround:

1. Send a head request
2. Process "Set-Cookie" headers
3. Send a get request with cookie

**Comment by ComLock** [comment]
ref: https://github.com/enonic/lib-http-client/issues/10

**Comment by alansemenov** [comment]
Alex, I don't think we need another task in addition to enonic/lib-http-client#10. Close this if you agree

**Comment by ComLock** [comment]
Yeah, I did not know about the other task when creating this one.
