### ISSUE TITLE
lib-ua lib-user-agent User Agent Library Redirects Session Cookie

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6683]
If https://github.com/enonic/lib-http-client/issues/13 is implemented, it gives me the possibility to implement my own user agent with support for redirects and session cookies etc. It would be even nicer if we delivered a library.

For example lets say I need to fetch 1000 articles from http://lvh.no
Since there are 3 redirects it currently it takes 4000 requests to fetch the 1000 articles.

Using a lib-ua only the first request would trigger the redirects and then the cookie would be reused so you would only need 1003 requests.

I think it would be useful to avoid sending 2997 useless requests.

Workaround: Hardcode the cookie.

**Comment by alansemenov** [comment]
@ComLock https://github.com/enonic/lib-http-client/issues/13 is implemented. can this be closed?

**Comment by ComLock** [comment]
@alansemenov Yes it's now possible to implement ones own UA in JS. However what I'm asking for here is for Enonic to provide one. (possibly implemented in Java). So this task should be closed if Enonic decides its not feasible to provide such a lib within a reasonable timeframe.
