### ISSUE TITLE
built in pagination

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6691]
We have a bunch of methods in our js api and in guilotine that returns a list of content or nodes with count and total. It would be nice if it also returned page and pages. In addition the api functions should take a page parameter which one could use instead of offset.

This way there would be no need to "reimplement pagination math" everywhere you need it.

I luv this idea, hope ye do too. 🙏

**Comment by sigdestad** [comment]
There is pagination in Guillotine, it returns a "connection" if you want to do pagination.

**Comment by ComLock** [comment]
Yes there is cursor and offset pagination, not human readable page number pagination. So in order to show the people visiting the site how many pages there are you have to do math.

Implementing this math all over the place is cumbersome.

**Comment by sigdestad** [comment]
How does this relate to XP core?

**Comment by sigdestad** [comment]
lib-pagination?

**Comment by sigdestad** [comment]
I suggest you make such a library during labs @ComLock. Closing issue
