### ISSUE TITLE
Content - processedReferences field & ContentProcessor

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6692]
The goal is that the links present in HtmlAreas should be handled as references.
The chosen solution is to have a new Content field "processedReferences" that will be translated to Reference at node level. This field will be populated by a ContentProcessor that will visit the HtmlArea properties and add references to processedReferences

* Create a new field "processedReferences" of type ContentIds in com.enonic.xp.content.Content
  * This field will not be transmitted to the rest api or the controllers (Do not add this to ContentMapper or ContentSummaryJson)
* Create a new ContentProcessor (in portal-impl), that will
  * Visit the HtmlArea properties of the content
  * Retrieve the references contained (A regexp exist in HtmlLinkProcessor.CONTENT_PATTERN) 
  * Add the references to "processedReferences"

**Comment by sigdestad** [comment]
Do we have a single field, or one per editor? Is the name processedReferences good? 

Also, are there any problems related to updating content with this approach?
