### ISSUE TITLE
ClusterHealth-implementation returns status RED if cluster-health message fails

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#6700]
We have seen that cluster issues happens if a node does not respond in time due to prolonged cluster health requests.

This code in the ElasticsearchCluster:

` try
        {
            final ClusterHealthResponse healthResponse = doGetHealth();
            return toClusterHealth( healthResponse.getStatus() );
        }
        catch ( Exception e )
        {
            return ClusterHealth.create().
                status( ClusterHealthStatus.RED ).
                errorMessage( e.getClass().getSimpleName() + "[" + e.getMessage() + "]" ).
                build();
        }
`

If the clsuter-health message failes to be delivered due to GC-pauses on one of the nodes, the cluster will set itself into state RED even if the current node is not in state error. The catch exception part is too strict,. it should NOT return RED.

**Comment by rymsha** [comment]
after #8219 there is no such check.
