### ISSUE TITLE
content-display-name-script with hardcoded strings

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6705]
This:
https://xp.readthedocs.io/en/stable/developer/site/content-types/custom-types.html

Contains the following example:
```xml
<content-display-name-script>$('firstName', ' ', 'lastName')</content-display-name-script>
```

Which seems to indicate a space character is inserted between the firstName and lastName.

However if you try:
```xml
<content-display-name-script>$('Hardcoded text ', 'fieldName')</content-display-name-script>
```
The 'Hardcoded text ' disappears and only the content of the field with the name fieldName is added.

The syntax is rather bad in terms of what is a variable and whats not.

Tried this too without any luck:
```xml
<content-display-name-script>Hardcoded text $('fieldName')</content-display-name-script>
```

**Comment by alansemenov** [comment]
Docs are wrong - you cannot use empty string or space or hardcoded string or anything but a field name. However, in 7.0 we will support ES [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) - you will be able to write something like 

``<content-display-name-script>Hardcoded ${firstName} ${lastName} string</content-display-name-script>``

**Comment by sigdestad** [comment]
Alan, need to have a talk with you about this template literal thing, if it is not good I propose we discontinue the whole display-name-script thing.

**Comment by alansemenov** [comment]
Sure, let's discuss it. But if you worry about security then it's not a problem - the value is always wrapped as a string.

**Comment by alansemenov** [comment]
Fixed in https://github.com/enonic/app-contentstudio/issues/536 and https://github.com/enonic/app-contentstudio/issues/557, also updated the 7.0 docs
