### ISSUE TITLE
Communicating between cluster nodes (specifically the master node)

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6712]
What is the best way to send and verify that the message was received, between cluster nodes?

We have event listeners and sending event. In which you can broadcast an event to all cluster nodes.
Then you could have a listener on every node and all but the master node could ignore the event.

But lets say triggering the event is a manually clicked button, it would be nice then to actually verify that the master node received the event. And so dispatching an event into a non responding black box which could potentially respond over another channel, seems not like the way to go.

So perhaps when the button is clicked, one would have to figure out the network address for a service running on the master node and call it server to server and then pass on the response back to the browser.

Or perhaps using a web-socket is the way to go.

Please leave your thoughts and suggestions below.

**Comment by sigdestad** [comment]
Events are not message message ques with guaranteed delivery.
Have you experienced that events get lost?

Also, it would be better to take this on #tech channel on slack or similar
