### ISSUE TITLE
Task manager

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6713]
Hi

It would be nice to have a task manager. To list, see progress, start and stop tasks.
It could be cluster wide.

Perhaps this could be implemented in JS server-side and client-side react, by the consultants (team lab?) but might require some more libTask features.

**Comment by Bellfalasch** [comment]
If I'm not mistaken this is the planned Job Scheduler tool, right? @sigdestad @alansemenov

**Comment by ComLock** [comment]
Are jobs and tasks the same thing? In code they are not. They each have their own folder in src/main/resource. ASFAIK Jobs only exist in the cron app.

**Comment by sigdestad** [comment]
Already in our backlog, but not prioritized at the moment. 
Also, see this feature request: https://discuss.enonic.com/t/api-to-list-all-available-tasks/1793/2
