### ISSUE TITLE
Repoconnection.exists()

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6736]
So I'm currently using Repoconnection.query({count:0}) and returning result.total. to figure out whether a node exists. Perhaps using Repoconnection.get() would be quicker, but I don't need the data. I'm thinking a Repoconnection.exists() which only returns a boolean (nodeId or false) would be nice to have and could perhaps be more efficient.

**Comment by sigdestad** [comment]
if passing "nodeKey" to exists, this makes sense: i.e. connection.exists(key).

**Comment by GlennRicaud** [comment]
Done in issue https://github.com/enonic/xp/issues/7212
