### ISSUE TITLE
Inspect (multi)repoconnection sources/repoId/branch property

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6738]
In order to (in theory) avoid wasting precious time reconnecting to a repo I pass the connection around.

To make sure I have the correct connection I would like to be able to inspect the connection.

Thus I propose that a connection have two properties:
- repoId
- branch

**Comment by ComLock** [comment]
Hmm one must take into account multirepoconnection. So perhaps an array of sources.

http://repo.enonic.com/public/com/enonic/xp/docs/6.15.5/docs-6.15.5-libdoc.zip!/module-node.html#.multiRepoConnect

**Comment by sigdestad** [comment]
So, what are you looking for, like a connection.info()?

**Comment by ComLock** [comment]
Yes. You could provide a function called info, but JS object can haz properties too. Not everything needs to be functions.

**Comment by sigdestad** [comment]
Sure, Any input on what it could it look like?

**Comment by ComLock** [comment]
const connection = connect({branch: 'master'});
log.info(connection.branch); // --> 'master'

**Comment by sigdestad** [comment]
Having discussed this, there is actually no time spent here - since this "connection" is just a simple object. There are no pools etc. 

I think this invalidates your initial problem?

Re-open if we are wrong
