### ISSUE TITLE
multiRepoConnection.query aggregation bucket repoId

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6757]
When you do a multiRepoConnection.query you will get repoId in the hits, so that is it possible to repoConnection.get the actual hit node. However when you aggregate on terms and you will only get node.key and you have no idea which repo that node exists in.

Ugly workaround is to get a list of all repos and loop through them until you find the node :(

**Comment by alansemenov** [comment]
@ComLock hmm.... what if you have the same key value in several repos?

**Comment by ComLock** [comment]
@alansemenov Exactly! If that is possible then current aggregation is broken.
