### ISSUE TITLE
API -  Progress 

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6762]
All toolbox operations are synchronous.
It can be problematic for operations taking a long time: dump creation, vacuum, ...
Depending on your setup, you could have timeouts. But most importantly you do not have any progress information.

The purpose of this epic is to make the following toolbox operations display a progress:
* ``dump``
* ``export``
* ``import``
* ``load``
* ``upgrade``
* ``vacuum``

The solution is to execute these operations inside tasks and return the task ID.
The toolbox will then pull information about the task and display its progress.

## TaskResource
* Create a new JaxRsComponent "TaskResource" with @Path("/api/task")
  * This resource will have an endpoint "info" taking a task ID as parameter and returning the task information

## Operations as tasks
Adapt the following endpoints:
``/api/system/dump``
``/api/system/load``
``/api/system/vacuum``
``/api/system/upgrade``
``/api/repo/export``
``/api/repo/import``

* Execute them inside tasks and return the task ID.
* Use the listener mechanisms available to report the progress

**Comment by sigdestad** [comment]
Hi!
Why are we still "fixing toolbox"? The toolbox should be dropped and the code removed completely from XP/distro for 7.0. The CLI replaces toolbox and will enable us to communicate with XP. As far as I am concerned the API could be completely rewritten if needed.

**Comment by GlennRicaud** [comment]
I will try to gather here the questions mentioned at multiple places:
1 - https://github.com/enonic/xp/issues/6763#issuecomment-440703792
2 - https://github.com/enonic/xp/issues/6762#issuecomment-440702692

1 - Safety:
There is an admin endpoint /admin/rest/tasks/{taskId} doing exactly the same thing.
The admin endpoint only requires Admin login rights, while /api requires Admin rights....
I was not involved in the design of the tasks, but I guess this was discussed.
Question 1: What was the result of this discussion?

1 - Task result:
I totally agree with you there and it is something I complained about before: The tasks do not have a result field.
Again I was not involved in the design of the tasks, but I guess this was discussed.
Question 2: How was this planned to be handled? How are we case suppose to return a task result?
Until now, the only way I found is by stringifying the result inside the info field...

1 - Better solution:
There may be a better approach. I took this way because it is simple and it is an already used and common solution in admin.
Again I thought this was the intended purpose of the task progress mechanism but I might have been wrong.
Question 3: What do you have in mind to retrieve progress?

2 - Toolbox:
Toolbox has never been planned to be removed.
The way the CLI was described orally is as a tool intended for developers.
In that case, it makes sense to keep toolbox and that is is still shipped with the runtime. You definitely need to manage Enonic XP.
Question 4: Has the purpose of CLI changed? What is the goal of the CLI now?

Let's put this epic on hold untill we solve these problems.
