### ISSUE TITLE
Editable/recycled header and footer on error pages

### ISSUE THREAD

**Issue by espen42** [enonic/xp#6778]
Feature requested at dev 101/201 at SmartLabs. And I've also seen code at Gjensidige that seemed to try to accomplish it (see also the header on an error page at gouda.no (just provoke a 404 below it), with a complex menu):

A way to make a header and/or footer on error pages that is editable in content studio, or even better: recycles/syncs with existing headers/footers from other pages, so they're always identical. This would improve user experience for end users and developers.

**Comment by sigdestad** [comment]
Enonic XP actually does not limit people from building "rich" error pages. You can produce the text for instance via x-data only available on the site content. However, making such error pages is severly stupid as it may cause the errorpage to crash.

Any comments before we close this?
