### ISSUE TITLE
repo.create/connect should force the developer to think about security

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6790]
The default permission settings for a repo is read for **authenticated** and all permissions for **system.admin**

When developing one is typically **authenticated** as a user with the **system.admin** role.

Which means per default a developer will have **full access** to read and write data without really thinking about security.

When things are in production and a bunch of data has been written it will suddenly become apparent that the public (**everyone**) cannot read from the repos.

The goto solution for that is wrapping the whole code in **context.run** as super user. I feel like that is a really **bad practice**.

Now if you want to do it the right way you will have to **modify all the nodes** in a repo to have proper principals for reading and writing data. Which can be a bunch of work you don't have time for when things are already in production, so this rarely happens.

If there at some point is human interaction in configuring the app that writes data to repos, then since everything is now running in a super user context it could happen that data is written or **deleted** from cms or even system-repo.

Perhaps when you spin up a new server without users the default "admin" user (which does not require login) should only have access to read and write content, not repos.

I feel like the super user is to exposed, it becomes the default in all circumstances.

**Comment by ComLock** [comment]
I'm also noticing that context.run user parameter is optional and defaults to the current user. In a cronjob "context" there is no current user. Does that mean you will be able to connect to a repo without a user? Since there is no node._owner perhaps that makes sence.

I feel like the usecase for context.run is to run something in a context where the user is NOT the current user. As such I feel like the user parameter to context run should be **required**, but should you be able to run anything in a context without a user? Perhaps.

Should you be able to run anything in a context with neither a user nor a principal? Does context run throw immediately in such a case?

Should we force the developer to think about security with regards to context.run too?

**Comment by ComLock** [comment]
When I'm doing connect with

`user: {
	login: 'non-existant-user',
	userStore: 'non-existent-userStore'
}`

And some role with write permissions in additional principals, I will get the error message: 

> Cannot modify node with key

So connecting without a user does not work.

This means that if you are developing code and submitting a named task "manually" during development, it can stop working when submitted in a cronjob context, since there is no user.

**Comment by ComLock** [comment]
So rather than context.run having user as required, it think repo.connect having user as a required parameter would make more sense.

**Comment by ComLock** [comment]
Also giving authenticated read access by default does not force the developer to think, read docs and learn about security.

**Comment by sigdestad** [comment]
Good input, context run is now default also for contentAPI (7.0).
These changes will be more interesting in the future i.e. xp 9+.

closing issue for now.
