### ISSUE TITLE
Avoid reloading the form after applying changes inside the Inspect Panel

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6798]
*XP 6.15.5*
*Firefox Developer Edition*

When you have a huge config for a component, like a Part, the list of fields in the Inspect Panel in the Page Editor requires some scrolling. When editing settings at the bottom and clicking "Apply" button you will actually have the form scroll back to the top (it also looks like the form reloads as well?!). Could this behavior be deactivated? Keep my scroll position within the Inspect Panel and the form within when I click "Apply".

Before save:
![screenshot 2018-12-05 at 12 08 37](https://user-images.githubusercontent.com/1465598/49509866-e4a31800-f886-11e8-9f21-f2acc5121686.png)

After save:
![screenshot 2018-12-05 at 12 08 44](https://user-images.githubusercontent.com/1465598/49509875-e8cf3580-f886-11e8-8b37-43dd5fcbdcfd.png)

And I lost track of where I am =(

**Comment by alansemenov** [comment]
@edloidas It's the same in XP7 as well. We should obviously reload the iframe when the config changes, but can we skip the reload of the Inspect's panel form somehow? The only reason to reload it would be when the app is reinstalled but that's not the case here.

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio #995](https://github.com/enonic/app-contentstudio/issues/995) via [**ZenHub**](https://www.zenhub.com/)
