### ISSUE TITLE
By default restrict content inside content selector to current site

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6802]
Content selectors (base Content selector, Media selector and Image selector) by default allow content from the root.
Change it only for Content selector (not Media or Image) to by default allow content only inside the current site (what can now be done by setting ``allowPath="${site}/*"``). If needed, user can change it to allow all content by setting "``allowPath="*"``".

NB! Check that current behaviour remains the same for Media and Image selectors.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #601](https://github.com/enonic/app-contentstudio/issues/601) via [**ZenHub**](https://www.zenhub.com/)
