### ISSUE TITLE
API - Status Resource

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6804]
Create a new JaxRsComponent "StatusResource" with @path("/api/status")
This resource will have an endpoint "server" returning the server information (Same information as what ServerReporter is returning)

**Comment by sigdestad** [comment]
I think this might be a misunderstanding?
Plan was for status to run on a separate port, @runarmyklebust ?

**Comment by GlennRicaud** [comment]
This is not about the separate port at all.
This is about the CLI getting the server version while allowing to extend in the future.

We can change the name "status" for something else of course
