### ISSUE TITLE
Support allowPath config for Tag input

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6811]
Implement support for ``<config><allowPath></allowPath></config>`` in the Tag input type. By default it should search inside contents of the current site (currently it looks inside all contents), but this can be changed by setting ``<allowPath>*</allowPath>`` (same behaviour as for content selector).

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #643](https://github.com/enonic/app-contentstudio/issues/643) via [**ZenHub**](https://www.zenhub.com/)
