### ISSUE TITLE
CustomSelector from non site app does not work

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6826]
I have made a custom selector service in a pure admin tool app.

I'm trying to use that service from via a custom selector in a site app.

Looking at Inspect and the Network tab I can see that is only tries to access the service on the site.

Now since the admin tool app is not a site app it cannot be added to the site and the service should not exist on the site...

So is this a bug, I think not. 

If the custom selector first try a site service url and then fallback to app service url. It could work. However the app url may not have a vhost.  Soo...

I think my workaround will have to be make lib so that the custom selector service can be present in the app that uses it.

Perhaps the custom selector doc should point out it only works across site apps?
https://xp.readthedocs.io/en/stable/developer/schema/input-types/custom-selector.html?highlight=site

**Comment by sigdestad** [comment]
A service is essentially available "everywhere", in admin, webapps and sites - however - in webapp context, only services made in that app should be available, in site context, only services for apps installed on site are available. In admin, every service is available.

As such, you might worry that your service should only be available for admin, not the site?
This is easily solved by adding a role check in the service.xml file, that will effectively prevent unauthorized use of the service.

**Comment by ComLock** [comment]
I now consider this a feature rather than a bug.

If one wants to make a service available both in an admin tool and a site application create a lib and include the lib in both the admin tool and the site app.
