### ISSUE TITLE
Require for modules

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6828]
To be validated and researched first.

I had a ticket where a customer was using moment-timezone that was requiring another module: https://enonic.zendesk.com/agent/tickets/2704

In short. Our ``require`` works to refer to relative paths and absolute paths.
But not to reference "modules".

We should maybe add a default case if not found, to search for a matching module

**Comment by alansemenov** [comment]
NB! Should probably be a part of the backwards compatibility fix we're going to do for ``require`` in 7.0
