### ISSUE TITLE
i18n defaulting to language

### ISSUE THREAD

**Issue by poi33** [enonic/xp#6843]
# Country and langauge code does not fallback to language code.

If the langauge code is set to `en-GB` it should default to `en`.

This does not resolve when using [localize](http://repo.enonic.com/public/com/enonic/xp/docs/6.15.4/docs-6.15.4-libdoc.zip!/module-i18n.html#.localize) 
With the file being: phrases_en.properties

**Comment by alansemenov** [comment]
You have to first get current locale code via [admin.getLocale()](http://repo.enonic.com/public/com/enonic/xp/docs/6.15.5/docs-6.15.5-libdoc.zip!/module-admin.html#.getLocale) (which will return "en" for "en-GB", "en-US" etc.) and then use this code in ``i18n.localize()``.

**Comment by poi33** [comment]
When using `adminLib.getLocale()` it returns "en" even if i set my page language to "norsk (no)". 
Does adminLib.getLocale() just return the language the server is set to?
There must be something I'm doing wrong here...
![ScreenShot](https://user-images.githubusercontent.com/3340349/50775267-fa489a80-1295-11e9-9ee0-caef76fce7b8.png)

**Comment by poi33** [comment]
`portal.getContent().language` returns the langauge code the page is set to.
The issue for me is that i18n does not fallback to `en` value when given the `en-gb` value.

    i18nLib.localize({
        key: "newComment",
        locale: langCode,
    }),

Its not intended to use the page language in this way?

**Comment by sigdestad** [comment]
It will return the language of the site - the language of your content is not considered as it would cause massive inconsistency if localization changed for every content within a site.

**Comment by alansemenov** [comment]
As Thomas says, this has nothing to do with content language. Locale code is taken from the request header:

![image](https://user-images.githubusercontent.com/11612490/50819085-57416080-1329-11e9-9654-7f72c055be7a.png)
