### ISSUE TITLE
Allow blockquote tag by default in CKEditor

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6846]
In TinyMCE we had the possibility to add `Blockquote` blocks for text as a default option. When upgrading to CKEditor this functionality is lost, and must be added manually everywhere HtmlAreas are used. Could this Blockquote button be added as standard in CKEditor? (while properly handle content types that now manually re-adds them?).

The reason this function fell out is that TinyMCE added it as an option in the `styleselect` whereas CKEditor adds it as a separate button.

**Comment by alansemenov** [comment]
@Bellfalasch not sure if this should really be a default option... it doesn't look like something that is used often and it can easily be added via config. have you received many complaints about it being missing?

**Comment by Bellfalasch** [comment]
Problem is that if you do not have this button, the editor will remove any `<blockquote>` when saving. So basically breaking/ruining articles created with TinyMCE. When button is added the html tag is kept. Pretty annoying yes.

**Comment by ashklianko** [comment]
We can adjust editor filter to not strip `blockquote`

**Comment by alansemenov** [comment]
Oh, I see. Yes, let's not add the button by default but make sure the tag is passed by the filter.

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio #671](https://github.com/enonic/app-contentstudio/issues/671) via [**ZenHub**](https://www.zenhub.com/)
