### ISSUE TITLE
Improve table features in the HTML Editor

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6847]
In TinyMCE one could perform many changes and custom edits on tables, rows and cells. In CKEditor all those possibilities are lost. You cannot customize size of table or cells, you cannot "promote" a row to a table header or footer, and so on. Loads of features you need when working with tables now forces you to go into HTML source code, which is okay only for a few elite editors.

Is it possible to add more functionality to the table feature in CKEditor? =( Working with tables is rather painful in CKEditor now.

**Comment by ashklianko** [comment]
Hi Bobby! We can add at least column resizing, will investigate more.

**Comment by Bellfalasch** [comment]
"Promoting" table rows to header (`thead` + `th`) and footer (`tfoot`) was the most important feature missing. But any improvements are welcome.

**Comment by alansemenov** [comment]
@ashklianko Enable these plugins: ``tableresize``, ``tableselection``, ``tabletools``. Also enable ``table`` to enable Table Properties context menu.

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio #59](https://github.com/enonic/app-contentstudio/issues/59) via [**ZenHub**](https://www.zenhub.com/)
