### ISSUE TITLE
No error message in Content Studio when the Content Studio app is stopped

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#6859]
1. Open `Content Studio` in browser.
2. Open Applications and stop the `Content Studio` app
3. Go to `Content Studio` again and select any content in the grid

Issue :  Delete, Move, Duplicate are available for the content
Expected :  Message should be displayed in the browser page : "Admin application [com.enonic.app.contentstudio:main] not found"

**Comment by sigdestad** [comment]
Shouldn't this be the same as "unable to connect to server" somehow?

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #345](https://github.com/enonic/app-contentstudio/issues/345) via [**ZenHub**](https://www.zenhub.com/)
