### ISSUE TITLE
Handle trailing spaces in content names

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6863]
https://enonic.zendesk.com/agent/tickets/2731

We get multiple problems with trailing spaces in content names
Either forbid it or handle it correctly

**Comment by sigdestad** [comment]
It should be forbidden.. Guess clients should automatically remove it when possible.

**Comment by GlennRicaud** [comment]
Duplicated. Two existing issues about this subject.
Closing this issue
