### ISSUE TITLE
Remove name from FieldSet

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6865]
The main purpose is to remove the name from FieldSet.

But even if it is not used by the UI, used for storage and the JSON representation of a Form does not seem to require the name (to be confirmed), this might have impact.
Today all FormItems have a name.

Search for the implications and impacts.
If this seems correct, apply the necessary refactoring.

**Comment by GlennRicaud** [comment]
Not sure why it was "posponed due to apps needing to be fixed" if it is a non-breaking change.

**Comment by GlennRicaud** [comment]
Thanks for the information.

The situation today:
Form items have a name
Field set is a form item
=> Field set has a name

If I understand correctly the new rule is:
Form items do not have necessarily a name
Form items other than schema layouts have a name

About the check:
Luckily, in Java and JSON (both admin rest and content lib) form items are not represented as a map with a key being the name of the form item.
So it is true it should not be too much breaking change.

I want to point out that I disagree with this issue.
It makes sense and it is useful to have an identifier for a form item.

I will close this issue and create an epic since it has impact on content-studio

**Comment by sigdestad** [comment]
Hmm.. My problem here is simply that all form-items that create and persist data meaninfully need a name. However, fieldSets have turned out not to have any effect on storing data at all. So, maybe it simply is not a formItem then? Just think of it as a decorator.

**Comment by GlennRicaud** [comment]
I know the reason and understand the idea. But I still disagree.
Because I am not talking about the data here but about the form as a tree where each node (form item) has a name.
Example: You have places in the code where form items or layouts are mapped by name. To allow to go through the form as a tree.

But we will refactor and find solutions. I will create the epic.

**Comment by sigdestad** [comment]
You are free to create a name for it, as long as the author of the schema does not have to (should not be able to) :-)
