### ISSUE TITLE
Support multiple CMS repositories - Adapt Portal URLs

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6877]
- Rename "/portal" and "/admin/portal" to "/site" and "/admin/site" respectively
- Add the name of the CMS repo in the url before the branch (Adapt the WebHandlers and the URL generation)
- Adapt code in Admin apps and lib (Create an issue in the Git repo that need modification)

Example: "/portal/master/mysite" becomes "/site/default/master/mysite"
Example: "/admin/portal/preview/draft/mysite" becomes "/admin/site/preview/default/draft/mysite"

**Comment by vbradnitski** [comment]
pushed to #6890
