### ISSUE TITLE
"Save" button doesn't get disabled after assigning a template with no regions to a site

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6899]
1. Make sure the Features app is installed.
2. Create a new site in CS, select Features, save. "Save" button is disabled now.
3. In the controller selector select "No regions".

The site is saved, but "Save" button is still enabled (pressing "Save" manually won't help). If you add a region to the template (``pages/no-regions/no-regions.xml``) in the Features app, it starts working as it should.

It shouldn't matter if the template has regions or not.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #210](https://github.com/enonic/app-contentstudio/issues/210) via [**ZenHub**](https://www.zenhub.com/)
