### ISSUE TITLE
phrases.properties in lib gets overridden by phrases.properties in app making it impossible to use i18n

### ISSUE THREAD

**Issue by RF0** [enonic/xp#6904]
I am building a library that I want to internationalize. Problem is that the app that wants to use the library already is internationalized, and when packaging the app with gradle, the i18n/phrases.properties inside the app gets priority, and the phrases for the library gets ignored. Is it any way of getting around this today, or are changes needed for this to work?

**Comment by alansemenov** [comment]
@RF0 When you write that you want to "internationalize the lib", what do you mean exactly? If you internationalise directly via i18n lib then both ``getPhrases`` and ``localize`` methods have ``bundles`` parameter where you can specify a different bundle name than ``phrases``.

Also, let's use Slack (@tech channel) and Discuss for such questions. Github issues are for tasks.
