### ISSUE TITLE
lib-content query() filter: unable to exclude by _id values in array

### ISSUE THREAD

**Issue by hjelmevold** [enonic/xp#6912]
XP version: 6.15.5

Why can I exclude content from a query by using a NOT IN query constraint, but if I use filters instead, I still get the undesired content in my query result?

```javascript
// Works
var result = contentLib.query({
    query: '_path LIKE "/content/mysite/*" AND _id NOT IN ("04e749e0-f621-4304-9f48-22cfce29606a","44af8a7e-496c-4031-b940-43f69fd23430")'
});

// Doesn't work:
var result = contentLib.query({
    query: '_path LIKE "/content/mysite/*"',
    filters: {
        boolean: {
            mustNot: {
                hasValue: {
                    field: '_id',
                    values: ['04e749e0-f621-4304-9f48-22cfce29606a','44af8a7e-496c-4031-b940-43f69fd23430']
                }
            }
        }
    }
});
```

The documentation recommends using filters whenever possible, since the results are then are not scored and thus faster.

I have also tried using the ids filter
```javascript
mustNot: {
   ids: {
           values: ['04e749e0-f621-4304-9f48-22cfce29606a','44af8a7e-496c-4031-b940-43f69fd23430']
       }
}
```
…which also doesn't seem to work - the undesired content is still included in the results.

**Comment by vbradnitski** [comment]
hmm, tried it both for 6.15.5 and master and it works for me with :
            boolean: {
                mustNot: {
                    hasValue: {
                        field: '_id',
                        values: ['77c23a78-569c-4b6c-a764-b9004c47886c']
                    }
                }
            }
@hjelmevold Could you try in again?

**Comment by hjelmevold** [comment]
@vbradnitski I created an app from scratch that tests this, and it works just like it is supposed to. So it must have been something strange in the enonic.com app (old libraries?) that caused this behavior.

The issue can be closed.
