### ISSUE TITLE
Management API - Add repository listing endpoint

### ISSUE THREAD

**Issue by pmi** [enonic/xp#6941]
@sigdestad commented on [Thu Feb 07 2019](https://github.com/enonic/enonic-cli/issues/95)

To make things, I suggest the following change to our structure

New command structure then looks like this:

* app (no change)
* cms (no change)
* export
** create (renamed from new)
** list
** remove
** import (renamed from load?)
* snapshot
** create (rename from new)
** list
** remove
** restore
* repo
** list (new command to list available repos)
** reindex
** readonly
** replicas (moved from cluster)
* dump
** create (renamed from new)
** list (new command to list dumps)
** upgrade
** load
* system
** info (new command to show info about XP, should get this from request to :4848/

---

@pmi commented on [Mon Feb 11 2019](https://github.com/enonic/enonic-cli/issues/95#issuecomment-462300471)

@tsi Where can I get list of available repos ? Should I create new API endpoint for that ?

---

@sigdestad commented on [Mon Feb 11 2019](https://github.com/enonic/enonic-cli/issues/95#issuecomment-462337423)

We are working on the endpoint now Pavel.. Hopefully live tomorrow!

---

@pmi commented on [Mon Feb 11 2019](https://github.com/enonic/enonic-cli/issues/95#issuecomment-462345144)

Cool ! Waiting for it then, the rest is ready !

**Comment by sigdestad** [comment]
Looks like we'll do the endpoint improvement for 7.1 - so lets drop the system command for now, and do that in next versino of CLI

**Comment by pmi** [comment]
@sigdestad This is not for the system info, but rather for repo list
