### ISSUE TITLE
DecideByType - Too many types indexed as allText

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6950]
References and Boolean are indexed in _allText (Check for other types)

Investigate and fix

**Comment by vbradnitski** [comment]
IndexConfig.BY_TYPE config is used by default for all unspecified properties. And we add all values of properties with '_decideByType_' or '_includeInAllText_' flags to __allText_ field (AllTextTypeFactory.java:18). 
Not sure why '_decideByType_' is allowed, but it was like this from the very start.
 Should it be only 'includeInAllText' here @GlennRicaud ?

**Comment by GlennRicaud** [comment]
The idea is to have in AllTextTypeFactory something similar to the double check in FulltextTypeFactory.
The test should be: (indexConfig.isDecideByType && value.isText) || indexConfig.isIncludeInAllText.

I will double check with Rmy first.

**Comment by sigdestad** [comment]
Lets not release B4 until this fix is merged...
