### ISSUE TITLE
Less logging in xp boot sequence

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#6979]
When booting XP7, we output a _very_ noisy log compared to XP6 - especially the creation of repo's is unbearable.

See if we can improve on this:
`08:30:31.794 INFO  c.e.x.r.i.e.IndexServiceInternalImpl - Index search-system-repo created with status true, settings {"index":{"number_of_shards":1,"number_of_replicas":1},"analysis":{"char_filter":{"zero_width_spaces":{"type":"mapping","mappings":["\\u200C=> "]}},"filter":{"front_ngram":{"side":"front","max_gram":12,"min_gram":1,"type":"edgeNGram"},"ngram":{"type":"nGram","min_gram":"2","max_gram":"12","token_chars":["letter","digit"]},"arabic_stemmer":{"type":"stemmer","language":"arabic"},"armenian_stemmer":{"type":"stemmer","language":"armenian"},"basque_stemmer":{"type":"stemmer","language":"basque"},"bengali_stemmer":{"type":"stemmer","language":"bengali"},"brazilian_stemmer":{"type":"stemmer","language":"brazilian"},"bulgarian_stemmer":{"type":"stemmer","language":"bulgarian"},"catalan_elision":{"type":"elision","articles":["d","l","m","n","s","t"],"articles_case":true},"catalan_stemmer":{"type":"stemmer","language":"catalan"},"english_stemmer":{"type":"stemmer","language":"english"},"english_possessive_stemmer":{"type":"stemmer","language":"possessive_english"},"czech_stemmer":{"type":"stemmer","language":"czech"},"danish_stemmer":{"type":"stemmer","language":"danish"},"dutch_stemmer":{"type":"stemmer","language":"dutch"},"dutch_override":{"type":"stemmer_override","rules":["fiets=>fiets","bromfiets=>bromfiets","ei=>eier","kind=>kinder"]},"finnish_stemmer":{"type":"stemmer","language":"finnish"},"french_elision":{"type":"elision","articles_case":true,"articles":["l","m","t","qu","n","s","j","d","c","jusqu","quoiqu","lorsqu","puisqu"]},"french_stemmer":{"type":"stemmer","language":"light_french"},"galician_stemmer":{"type":"stemmer","language":"galician"},"german_stemmer":{"type":"stemmer","language":"light_german"},"greek_lowercase":{"type":"lowercase","language":"greek"},"greek_stemmer":{"type":"stemmer","language":"greek"},"hindi_stemmer":{"type":"stemmer","language":"hindi"},"hungarian_stemmer":{"type":"stemmer","language":"hungarian"},"indonesian_stemmer":{"type":"stemmer","language":"indonesian"},"irish_hyphenation":{"type":"stop","stopwords":["h","n","t"],"ignore_case":true},"irish_elision":{"type":"elision","articles":["d","m","b"],"articles_case":true},"irish_lowercase":{"type":"lowercase","language":"irish"},"irish_stemmer":{"type":"stemmer","language":"irish"},"italian_elision":{"type":"elision","articles":["c","l","all","dall","dell","nell","sull","coll","pell","gl","agl","dagl","degl","negl","sugl","un","m","t","s","v","d"],"articles_case":true},"italian_stemmer":{"type":"stemmer","language":"light_italian"},"latvian_stemmer":{"type":"stemmer","language":"latvian"},"lithuanian_stemmer":{"type":"stemmer","language":"lithuanian"},"norwegian_stemmer":{"type":"stemmer","language":"norwegian"},"portuguese_stemmer":{"type":"stemmer","language":"light_portuguese"},"romanian_stemmer":{"type":"stemmer","language":"romanian"},"russian_stemmer":{"type":"stemmer","language":"russian"},"spanish_stemmer":{"type":"stemmer","language":"light_spanish"},"swedish_stemmer":{"type":"stemmer","language":"swedish"},"turkish_lowercase":{"type":"lowercase","language":"turkish"},"turkish_stemmer":{"type":"stemmer","language":"turkish"}},"tokenizer":{"path-tokenizer":{"type":"path_hierarchy","delimiter":"/"}},"analyzer":{"default_search":{"tokenizer":"keyword","filter":["lowercase","asciifolding"]},"keywordlowercase":{"type":"custom","tokenizer":"keyword","filter":["lowercase"]},"keywordasciilowercase":{"type":"custom","tokenizer":"keyword","filter":["lowercase","asciifolding"]},"ngram_index_front":{"type":"custom","filter":["standard","lowercase","asciifolding","word_delimiter","front_ngram"],"tokenizer":"standard"},"ngram_index":{"type":"custom","filter":["standard","lowercase","asciifolding","word_delimiter","ngram"],"tokenizer":"standard"},"ngram_search_default":{"type":"custom","filter":["standard","lowercase","asciifolding","word_delimiter"],"tokenizer":"standard"},"fulltext_search_default":{"type":"custom","filter":["standard","lowercase","asciifolding","word_delimiter"],"tokenizer":"standard"},"document_index_default":{"type":"custom","filter":["standard","lowercase","asciifolding","word_delimiter"],"tokenizer":"standard"},"all_field_analyzer":{"type":"custom","filter":["standard","lowercase","asciifolding","front_ngram"],"tokenizer":"standard"},"path_analyzer":{"type":"custom","tokenizer":"path-tokenizer","filter":["standard","lowercase","asciifolding"]},"language_analyzer_ar":{"tokenizer":"standard","filter":["lowercase","decimal_digit","arabic_normalization","arabic_stemmer"]},"language_analyzer_hy":{"tokenizer":"standard","filter":["lowercase","armenian_stemmer"]},"language_analyzer_eu":{"tokenizer":"standard","filter":["lowercase","basque_stemmer"]},"language_analyzer_bn":{"tokenizer":"standard","filter":["lowercase","decimal_digit","indic_normalization","bengali_stemmer"]},"language_analyzer_pt-br":{"tokenizer":"standard","filter":["lowercase","brazilian_stemmer"]},"language_analyzer_bg":{"tokenizer":"standard","filter":["lowercase","bulgarian_stemmer"]},"language_analyzer_ca":{"tokenizer":"standard","filter":["catalan_elision","lowercase","catalan_stemmer"]},"language_analyzer_cs":{"tokenizer":"standard","filter":["lowercase","czech_stemmer"]},"language_analyzer_danish":{"tokenizer":"standard","filter":["lowercase","danish_stemmer"]},"language_analyzer_nl":{"tokenizer":"standard","filter":["lowercase","dutch_override","dutch_stemmer"]},"language_analyzer_en":{"tokenizer":"standard","filter":["english_possessive_stemmer","lowercase","english_stemmer"]},"language_analyzer_fih":{"tokenizer":"standard","filter":["lowercase","finnish_stemmer"]},"language_analyzer_fr":{"tokenizer":"standard","filter":["french_elision","lowercase","french_stemmer"]},"language_analyzer_gl":{"tokenizer":"standard","filter":["lowercase","galician_stemmer"]},"language_analyzer_de":{"tokenizer":"standard","filter":["lowercase","german_normalization","german_stemmer"]},"language_analyzer_el":{"tokenizer":"standard","filter":["greek_lowercase","greek_stemmer"]},"language_analyzer_hi":{"tokenizer":"standard","filter":["lowercase","decimal_digit","indic_normalization","hindi_normalization","hindi_stemmer"]},"language_analyzer_hu":{"tokenizer":"standard","filter":["lowercase","hungarian_stemmer"]},"language_analyzer_in":{"tokenizer":"standard","filter":["lowercase","indonesian_stemmer"]},"language_analyzer_ga":{"tokenizer":"standard","filter":["irish_hyphenation","irish_elision","irish_lowercase","irish_stemmer"]},"language_analyzer_it":{"tokenizer":"standard","filter":["italian_elision","lowercase","italian_stemmer"]},"language_analyzer_lv":{"tokenizer":"standard","filter":["lowercase","latvian_stemmer"]},"language_analyzer_lt":{"tokenizer":"standard","filter":["lowercase","lithuanian_stemmer"]},"language_analyzer_no":{"tokenizer":"standard","filter":["lowercase","norwegian_stemmer"]},"language_analyzer_fa":{"tokenizer":"standard","char_filter":["zero_width_spaces"],"filter":["lowercase","decimal_digit","arabic_normalization","persian_normalization"]},"language_analyzer_pt":{"tokenizer":"standard","filter":["lowercase","portuguese_stemmer"]},"language_analyzer_ro":{"tokenizer":"standard","filter":["lowercase","romanian_stemmer"]},"language_analyzer_ru":{"tokenizer":"standard","filter":["lowercase","russian_stemmer"]},"language_analyzer_es":{"tokenizer":"standard","filter":["lowercase","spanish_stemmer"]},"language_analyzer_sv":{"tokenizer":"standard","filter":["lowercase","swedish_stemmer"]},"language_analyzer_tr":{"tokenizer":"standard","filter":["apostrophe","turkish_lowercase","turkish_stemmer"]},"language_analyzer_th":{"tokenizer":"thai","filter":["lowercase","decimal_digit"]}}}}
`

**Comment by GlennRicaud** [comment]
Fixed in 7.0
