### ISSUE TITLE
Set default value for the "Caption" field in ImageInspectionPanel

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6986]
When an image is selected in the image component's image selector, fetch value of the ``data.caption`` field and use it in the Inspect panel's Caption field. If ``data.caption`` doesn't exist or is empty, use value from `x.media.imageInfo.description`.

![image](https://user-images.githubusercontent.com/11612490/53961401-c698be00-40e8-11e9-90c4-4099899de82e.png)

NB! We should do it only once, after image is selected. If user manually deletes value in the Caption field and saves, the default value should not reappear.

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio #304](https://github.com/enonic/app-contentstudio/issues/304) via [**ZenHub**](https://www.zenhub.com/)
