### ISSUE TITLE
Xp ascii logo breaks in windows terminals.

### ISSUE THREAD

**Issue by poi33** [enonic/xp#6991]
The logo looks like this on windows terminals:
![image](https://user-images.githubusercontent.com/3340349/54037435-6d02c300-41be-11e9-9ca9-39e61e248d96.png)

Tried out all of this:
Checked if the banner.txt file has the wrong encoding. (Does not utf-8)
Checked if it was terminal specific. (Is not same output in CMD, powershell)
Checked to see if we did not handle propper print out in out bannerPrinter:
 `xp/modules/launcher/launcher-impl/src/main/java/com/enonic/xp/launcher/impl/util/BannerPrinter.java`
 Looks like we have proper printing (utf-8)

The consoles do have utf-8 support: 

![image](https://user-images.githubusercontent.com/3340349/54038857-d46e4200-41c1-11e9-987d-15a8f302c67d.png)

So i do not think its the terminals encoding causing the problem.

Here is a workaround:
[Banner_2.txt](https://github.com/enonic/xp/files/2946532/Banner_2.txt)
Using latin1 supported characters (even if the file is utf-8 encoded) seems to nok get the java utf-8 print confused in windows.

Here is my tiny java program that recreated the same print in windows terminal: 
[BannerPrint.txt](https://github.com/enonic/xp/files/2946550/BannerPrint.txt)

**Comment by sigdestad** [comment]
Awesome

**Comment by pmi** [comment]
@poi33 Are you running Windows 10 prior to October 2018 Update (build 1809) ?

According to [this article](https://devblogs.microsoft.com/commandline/windows-command-line-unicode-and-utf-8-output-text-buffer/) microsoft fixed that in build 1809.

This is what it looks on my pc (Version 10.0.17763 Build 17763)
![enonic-ascii](https://user-images.githubusercontent.com/754221/54363424-f7926900-467b-11e9-878d-3aee6dc00069.jpg)

**Comment by poi33** [comment]
Wow, yes i do...
I have the 1803 version. 
I'll update it tomorrow and see if i still have the issue.

**Comment by poi33** [comment]
This still breaks for me in Windwos 1809.
Just using the normal CMD (command prompt).
Running the windows-sdk-7.0.0-B5
enonic cli 1.0.1

**Comment by sigdestad** [comment]
Did you try this in powershell @poi33 ?

**Comment by poi33** [comment]
![image](https://user-images.githubusercontent.com/3340349/55537825-5700f900-56bd-11e9-8af6-f1ea70a859dd.png)
This is how my powershell looks now.
