### ISSUE TITLE
Attachment binary is not deleted after the attachment was removed from content

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7000]
1. Create a new content of type "Attachments" under the Features site
2. Upload an attachment to both Attachment Uploaders in the Wizard.
3. Open the "Details" widget and note that both attachments are listed at the bottom of the panel

![image](https://user-images.githubusercontent.com/11612490/54126119-1b994480-4407-11e9-922c-e84aabe56da2.png)

4. Now delete both attachments using the "X" icon.
5. They are deleted from the content but still available on the node layer (still listed in the Details widget and can be accessed via Data Toolbox)

![image](https://user-images.githubusercontent.com/11612490/54126246-6a46de80-4407-11e9-8554-26f6d28ebf72.png)

![image](https://user-images.githubusercontent.com/11612490/54126322-89457080-4407-11e9-8bee-b4f2186fc09e.png)

What's even worse is that attachmentUrl to such attachments are still available online after they are deleted from the content.
 
https://enonic.zendesk.com/agent/filters/56419022

**Comment by pmi** [comment]
Issue moved to [enonic/app-contentstudio #310](https://github.com/enonic/app-contentstudio/issues/310) via [**ZenHub**](https://www.zenhub.com/)
