### ISSUE TITLE
Social sharing icons not sharing correct URL

### ISSUE THREAD

**Issue by vot-enonic** [enonic/xp#7011]
When I'm trying to share [this article](https://enonic.com/blog/boost-your-digital-experiences-with-siteimprove) on social media with the icons in the bottom, I only get Enonic.com and not the actual blog post URL. This is the case on LinkedIn and Facebook, but not Twitter. BHJ mentioned that it might have something to do with the SEO meta fields app not being set up correctly.

**Comment by alansemenov** [comment]
Issue moved to [enonic/site-market #21](https://github.com/enonic/site-market/issues/21) via [**ZenHub**](https://www.zenhub.com/)
