### ISSUE TITLE
Add functions for boosting queries

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#7020]
We need to expose the boost-query functionality to let users easily boost queries without creating very complex expressions.

Some suggestions to look at:
* Boosting query: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-boosting-query.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html
* Support boost-parameter for boolean queries

Eg, see support-issue: https://enonic.zendesk.com/agent/tickets/2824, here there are no easy, intuitive and predictable way of boosting based on e.g content-type without resorting to pretty complex and slow boolean statements.

**Comment by sigdestad** [comment]
Ok, we need to support this, but need a design/spec before it can be implemented.

**Comment by runarmyklebust** [comment]
Lets not forget this, we really saw the need for this in the yase-project

**Comment by runarmyklebust** [comment]
Any plans on this? Chiming in with a really useful real-life example, user to boost newer results:

```
"functions": [
     {"filter": { 
         "range" : { "post_date.date": { "gte" : "now-1y", "lte" : "now" } }} ,
         "weight": 5
     },
     {"filter": { 
        "range" : { "post_date.date": { "gte" : "now-4y", "lt" : "now-1y" } }} ,
        "weight": 2
      }
   ],
  "boost_mode": "multiply"
```

Also interesting the decay-function: https://www.elastic.co/blog/found-function-scoring#decay-functions-in-elasticsearch

**Comment by sigdestad** [comment]
This is definetly an interesting use of filter boosting

**Comment by sigdestad** [comment]
Feature request on Forum sure would help raise attention for this one!

**Comment by alansemenov** [comment]
https://discuss.enonic.com/t/improved-control-of-search-scoring/2313

**Comment by vbradnitski** [comment]
"boost" float param has been added for every expression type.

**Comment by rymsha** [comment]
This is a part of #8936 
We haven't implemented boost_mode/weight . If needed - submit a new feature request.
