### ISSUE TITLE
Print notifications in console

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7032]
A customer complained about the notifications not being visible more than some seconds (https://enonic.zendesk.com/agent/tickets/2816).

I personally think notifications are supposed to go away like it is today.
But could we have the message at least printed in the console?

**Comment by sigdestad** [comment]
What do you mean printed in console? Like browser console? How will that help users?
I suggest we test out gmail, and delete an item or similar. I believe they have a notification. Lets see how long it is there, and use the same time for our notifs

**Comment by GlennRicaud** [comment]
Yes I meant the browser console.
And it will help the user by making him able to read the messages when there are too many / they are too long. Even better, he will be able to copy them to us.

**Comment by alansemenov** [comment]
In case of UI error messages they always output either a server-side error (in which case the actual error will be in the XP log) or a client-side error like a Javascript exception (will be shown in the browser console) or a missing resource (will be shown in the Network panel).

We cannot keep them opened forever - they will fill up the entire screen.

**Comment by GlennRicaud** [comment]
> server-side error

We are talking about the UI here, not the backend (I do not think XP logs are accessible by all content editors and they should not be)
> Javascript exception

Not talking about exceptions here. I am talking about notifications in general
> We cannot keep them opened forever

Exactly my point in my first comment...

It seemed to me like an obvious and quick improvement but I was apparently wrong. I will close this issue.
