### ISSUE TITLE
Regexp for HtmlArea links doesn't allow same-page anchors

### ISSUE THREAD

**Issue by hjelmevold** [enonic/xp#7035]
Version: 7.0.0-B4
In a part config with an input of type HtmlArea, I tried to create a link with a URL pointing to an anchor on the same page. This was not allowed.
<img width="597" alt="Screenshot 2019-03-27 at 17 01 19" src="https://user-images.githubusercontent.com/354917/55092317-aee2a300-50b2-11e9-9206-86bff40c9a1b.png">

**Comment by hjelmevold** [comment]
Hmm… it seems that I can only create such anchor links if it points to an anchor within the same HtmlArea.

I think it would be nice to allow linking to anchors that are on the same page but outside the same HtmlArea, but I'll leave it up to the Dev team to decide if this should be supported or if this issue should be closed.

**Comment by sigdestad** [comment]
You have No way of knowing about other anchors on a resulting Page, ref headless

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-contentstudio #1458](https://github.com/enonic/app-contentstudio/issues/1458) via [**ZenHub**](https://www.zenhub.com/)
