### ISSUE TITLE
ES mappings and settings cleanup

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7042]
- Set "stored" attribute to no
- Commit: Remove keywordlowercase
- Remove displayname._ngram mapping
- Check why template_fulltext.analyzer was added
- Remove ngram filter
- Set max_gram of front_ngram to 25

**Comment by sigdestad** [comment]
Why remove displayname ngram?!
What happens to aggs when store = No?

**Comment by GlennRicaud** [comment]
> Check why template_fulltext.analyzer was added

Default analyzers

ES 1.5

"default", "default_index" and "default_search"
https://www.elastic.co/guide/en/elasticsearch/reference/1.5/analysis-analyzers.html
We have "default_search":
{
  "tokenizer": "keyword",
  "filter": [
    "lowercase",
    "asciifolding"
  ]
}
For indexing, my guess is that the standard analyzer is used


"_analyzer"
https://www.elastic.co/guide/en/elasticsearch/reference/1.5/mapping-analyzer-field.html
In search mappings, we have
"_analyzer": {
  "path": "_document_analyzer"
}

And in documents, we store the value for _document_analyzer based on the analyzer of the IndexConfig of the document
If no custom IndexConfig, it will be the following: _document_analyzer": "document_index_default"

Bug: If no document analyzer, the analyzer at search and index will be different (default_search and standard).
It happens for fulltext for nodes created with the node lib.
Workaround: Specify the analyzer in the fulltext search function


ES 2.4
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_mapping_changes.html#_analyzer_mappings
_analyzer has been removed
New way to specify analyzer for mapping. First an analyzer for both index/search and then possibility to specify a different analyzer for search.
For all places where the document analyzer was used (_analyzed and search of ngram), document_index_default is used
This also fixes the bug above.

Cleanup: We do not need an analyzer on the indexconfig document. -> Create specific issue
