### ISSUE TITLE
Rollback region name removal

### ISSUE THREAD

**Issue by hjelmevold** [enonic/xp#7046]
When calling portal.getComponent() from inside a layout controller, the result in 7.0.0-B4 no longer outputs "name" (which should have had the layout display name) on the root level. This was present in all versions of 6.x

```
2019-04-02 09:17:59,948 INFO  com.enonic.web.enonic.com - (/site/layouts/layout-bg-color/layout-bg-color.js) {
    "path": "/main/0",
    "type": "layout",
    "descriptor": "com.enonic.web.enonic.com:layout-bg-color",
    "config": {
        "paddingTop": false
    },
    "regions": {
        "main": {
            "components": []
        }
    }
}
```

**Comment by alansemenov** [comment]
We'll document this as a breaking change

**Comment by sigdestad** [comment]
Hold on a se ond as we need to conclude best practice / what does the alternativ look like

**Comment by sigdestad** [comment]
From investingating, I think we should rollback this breaking change in particular. Was changed by mistake.

**Comment by GlennRicaud** [comment]
So to sum up we rollback the removal of name for regions.
Details of changes here: https://github.com/enonic/xp/issues/7041
