### ISSUE TITLE
Rollback banner modifications

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7051]
The banner picked in https://github.com/enonic/xp/issues/6872 is not displayed properly on Windows
Not sure why https://github.com/enonic/xp/issues/6991 has been closed since this is still a problem
Still no fix 2 months after implementation

Rolling back modifications.

Please involve backend developers in the future before modifying the backend.

**Comment by sigdestad** [comment]
Lets go for this:
http://patorjk.com/software/taag/#p=display&f=Speed&t=enonic%20xp
