### ISSUE TITLE
Dump load - Global application uninstallation before load

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7058]
* All non-system applications should be uninstalled before loading a dump
  * If local, keep installed and started. But the uninstall event should be spread to other cluster nodes.
* After load, keep the code as it is today (the code under doInstallStoredApplications already checks the presence of a local application)

The behaviour of ApplicationService is a bit complex and should be refactored in the future.

**Comment by sigdestad** [comment]
Hmm. Why should we do this? It means that dumping data will trash an installation big time?

**Comment by GlennRicaud** [comment]
I do not understand your comment.
How is dumping data having an impact on the installation and what is the link with uninstalling applications before loading a dump

**Comment by sigdestad** [comment]
Ah.. I did not read, so it says uninstall before loading. I was thinking uninstall before dumping :-)
Sorry..
