### ISSUE TITLE
Images inserted as original in 6.15 are now scaled in 7.0

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/xp#7062]
![Screenshot 2019-04-08 at 13 43 52](https://user-images.githubusercontent.com/702065/55721751-70c77680-5a04-11e9-9fc2-2b4e26310d2d.png)

7.0:
https://enonic-xpqa-cluster-lb-t0ljuwx9.enonic.cloud/blog/enonic-help-save-time-daily-tasks

Should be:
https://enonic.com/blog/enonic-help-save-time-daily-tasks

Also, the top image is not showing correctly on 7.0, but works on 6.15.

**Comment by mortyeriksen** [comment]
Blocker...

**Comment by alansemenov** [comment]
@mortyeriksen have you tested this after upgrade of enonic.com?

**Comment by alansemenov** [comment]
Will be fixed in 7.1
