### ISSUE TITLE
Application icon: PNG doesn't work

### ISSUE THREAD

**Issue by espen42** [enonic/xp#7072]
When putting Application.SVG in /resources/, the icon appears in Application admin as it should. However, PNG images don't work (fallback to the standard A icon).

Version XP7.0.0-RC1

**Comment by alansemenov** [comment]
Actually, the docs [explicitly say](https://xp.readthedocs.io/en/stable/developer/admin/tools/index.html#icon) that the icon must be in SVG format... We'll check how fast this can be changed to support PNG as well.

**Comment by sigdestad** [comment]
We don't want to support PNG for app icons, as we will not allow apps on market without SVG.

**Comment by edloidas** [comment]
I guess, the task should be closed then.

**Comment by alansemenov** [comment]
Not insisting on doing this but this limitation seems a bit strange. Are all of the apps ever made on XP going to be released on the Market? Tine made 20+ internal apps which will never be on our Market, for example. So why limit the app icon to only SVG? If someone wants his app to be on our Market then yes, they should provide an SVG icon but we shouldn't have this as a general requirement, I think.
