### ISSUE TITLE
Implement QueryDSL filter

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7081]
To filter on dateRanges you currently have to build range queries using instant('...').

It would probably be much more efficient to have a dateRange filter instead.

Also it would make implementing dataRange facets much easier codewise.

- [ ] support `filter` in query
- [ ] support `exists` expression

**Comment by sigdestad** [comment]
Do you have a specific example of what you want this too look like?

**Comment by sigdestad** [comment]
Ping?

**Comment by ComLock** [comment]
How to aggregate:
https://developer.enonic.com/docs/xp/stable/storage/aggregations#daterange

How to filter?

It looks like I've attempted something here and given up:
https://github.com/enonic/app-explorer/blob/master/src/main/resources/services/journals/journals.es#L42

**Comment by alansemenov** [comment]
Have to be researched and spec'ed.

**Comment by rymsha** [comment]
lib is simply missing range filters. We had a sort discussion about it recently, and it is not that hard to implement (I see not challenges) and it allows users to fetch data in portions. 

We use range filters extensively in internal XP methods.

**Comment by ComLock** [comment]
Doc: https://developer.enonic.com/docs/xp/stable/api/lib-content#query

From the top of my head

filters: {
  boolean: {
    must: [{
      dateRange: {
        field: 'created',
        ranges: [{
          from: 'now-1D',
          to: 'now'
        }]
      }
    }]
  }
}

**Comment by rymsha** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-range-query.html#ranges-on-dates

**Comment by rymsha** [comment]
We made an experiment with range filter and it didn't go very well.

filters are made as json-type structures, and this makes them more attractive for use, but unfortunately it makes them more hard/impossible to use as well in cases where data type knowledge is required.
One cannot proper date range on 'created' field as this filed has `term` index, not datetime. 
Instead one would have to use `created._datetime` "implementation detail" field - that would be a disaster.
Query Language has an extensive set of functions to deal with it, but an opposite request exists #4980 because, as you mentioned, it is hard to construct query string properly.

**Comment by sigdestad** [comment]
when using a date filter, shouldn't we implicitly use the _datetime value in ES? Just like we do in other scenarios?

**Comment by sigdestad** [comment]
Does anyone know the status of this issue? Will we support this?

**Comment by vbradnitski** [comment]
We can do date range queries in the new Query DSL epic. One of the next steps - to rewrite current filters to the same code base. So it potentially can be done in the same syntax for filters.

**Comment by rymsha** [comment]
Renamed task to "query filter" because date range in automatically implemented as filters are implemented.

In addition we need to implement `exists` expression https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-exists-query.html

**Comment by rymsha** [comment]
Renamed task to "query filter" because date range in automatically implemented as filters are implemented.

In addition we need to implement `exists` expression https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-exists-query.html

**Comment by rymsha** [comment]
exists is a separate feature https://github.com/enonic/xp/issues/9603
