### ISSUE TITLE
Sandbox start/stop trouble

### ISSUE THREAD

**Issue by Slideshow776** [enonic/xp#7083]
Created sandbox did not know that it had stopped (as by my command).
I solved this problem by creating a new sandbox, possibly could also be solved by ```$enonic sandbox stop```
I'm not sure how to replicate this problem.

**Comment by alansemenov** [comment]
@Slideshow776 can you describe the sequence of steps? did you run some command that assumed the sandbox was running while it was in fact stopped?

**Comment by sigdestad** [comment]
This issue has a poor description, and is placed in wrong repo. Closing it
