### ISSUE TITLE
Default values not set on sub components

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#7085]
@alansemenov commented on [Thu Apr 11 2019](https://github.com/enonic/app-contentstudio/issues/424)

1. Open a site / Page Editor
2. Open the Page Components view
3. Add a part inside the Page Components view (via context menu)
4. Select descriptor for this part (inside the Inspect panel)

The page auto-saves, the part remains selected on the page and inside the Inspect panel but it's no longer selected inside the Page Components view

**Comment by GlennRicaud** [comment]
I do not reproduce the issue.
Was it rather a content studio bug that has been fixed and this is just a refactoring/fixing something else?

**Comment by vbradnitski** [comment]
Problem is reproduced only with parts contained inputs with default values inside layouts. Also reproduced it for default values of layouts, pr is updated.
