### ISSUE TITLE
lib-cache stale-while-revalidate

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7094]
It would be nice if our lib-cache could provide more caching strategies.

In particular I would like "stale-while-revalidate".

For example lets say you have some data which need to be updated approx once an hour, but fetching it could take some seconds.

In stead of having to make a lot of code to fetch and store the data in a repo simply using 'stale-while-revalidate' would be enough.

Then only the first request after installing a new version of the app would be "slow".

Side note:
I guess letting a cache live between app versions would be hazardous.
Then only the first request on the first install would be slow.
One would need to have some kind of cache version or something.
I guess PWA does something like that.

**Comment by sigdestad** [comment]
This can be handled by product dept. Need to look at a proper spec before we implement anything. I'm closing this issue, and it must be re-created on the lib-cache repo.
