### ISSUE TITLE
lib-cron

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7095]
I need to schedule some code to run at certain times.

The API should look something like this:
https://github.com/ComLock/cron-example/blob/master/cron-example.es

The actual callback should be executed syncronously. And the responsibility for how long a callback runs is the developer using the cron libabry and not the lib itself.
(what if a callback takes longer to execute than it's next calling, will a queue grow until memory issues)

According to @sigdestad Timers should run in their on thread:
https://stackoverflow.com/questions/28886584/stop-a-timer-in-an-osgi-bundle

**Comment by ComLock** [comment]
I don't know wether we should support "second" resolution. https://en.wikipedia.org/wiki/Cron

**Comment by ComLock** [comment]
It might take more than a second to spin up a task, but a minute shouldn't be a problem.

**Comment by ComLock** [comment]
Timers should run in their on thread:
https://stackoverflow.com/questions/28886584/stop-a-timer-in-an-osgi-bundle

**Comment by ComLock** [comment]
After talking with @sigdestad we have a change of mind. The callback should not be wrapped in a task, and simply run syncronously. Then the responsibility to not let long running code overlap belongs to the developer using the API. In my case my callbacks would simple start a named task and return right away. Within my named task I have code which checks wether another named task is already running and does nothing if that is the case.

**Comment by alansemenov** [comment]
See [tasks in the repo](https://github.com/enonic/lib-cron/issues)
