### ISSUE TITLE
No error handler available for webapps

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#7104]
We need to support error handling for webapps.
Preferably on src/resources/main/error/error.js

Alternatively, we could support exports.handleError etc directly in webapp.js, but this would complicate reuse of code between webapps and sites.

NB! Needs to support backward compatibility so site handler will also look for error.js within site/ folder. But this should only occur after trying resources/error/error.js first.

**Comment by GlennRicaud** [comment]
Paragraph 1 and 3 are contradictory.

Will be done in https://github.com/enonic/xp/issues/7404
