### ISSUE TITLE
ImageContentProcessor deletes existing custom extra data

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7108]
Ticket https://enonic.zendesk.com/agent/tickets/2901

- Create an image with custom extra data 
Example:
```
"x": { 
  "com-enonic-myapp": { 
    "relatedFile": "41331350-8387-4ad6-9cd6-a8b7897c07bd" 
  } 
}
```
- Reprocess the branch 
``toolbox reprocess -a su:password -s draft:/``
- The custom extra data has been deleted (ImageContentProcessor)

=> To be fixed in 6.15 and 7.0

**Comment by alansemenov** [comment]
@vbradnitski @GlennRicaud what's going on with this one? still in progress?
