### ISSUE TITLE
task.xml should contain allow principals like services

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7111]
Currently a task may fail somewhere deep inside the code because the programmer didn't think too much about permissions.

In order to avoid the programmer to write a bunch of boilerplate code at the beginning of each task in order to check permissions. I would be nice if this was handled similarly to services such that a task will fail immediately with missing permissions, rather than somewhere deep in the task code.

**Comment by sigdestad** [comment]
End users cannot start tasks themselves today. Why whould this make any difference? Do you want to prevent programmers from running a task with wrong users? 

PS! You may also specify role directly in the context when running a task if this is what you need.
