### ISSUE TITLE
Permission indexing - Anonymous/Everyone mixup

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7117]
Reported by @espen42 
Nodes with READ permission for "role:system:anonymous" are index with "_permissions.read = 'role:system.everyone'"

Try to reproduce and fix

**Comment by sigdestad** [comment]
I think this is a workaround. We should be careful to change, as it might break instances...

**Comment by GlennRicaud** [comment]
I set the milestone to 8.0.

Do you remember what it was "fixing"?
Because this cannot be a proper fix. We have a wrong indexing but also inconsistency with the data. If a search was searching for 'role:system.everyone', that should have been changed instead.

**Comment by GlennRicaud** [comment]
Not reproduced
