### ISSUE TITLE
package com.enonic.xp.testing.script does not exist

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7136]
When trying to upgrade to Enonic XP I get the following error:

```
bitbucket/openxp/lib-filesystem/src/test/java/openxp/lib/file-system/FileSystemLibTest.java:3: error: package com.enonic.xp.testing.script does not exist
import com.enonic.xp.testing.script.ScriptRunnerSupport;
```

Is this caused by API changes to:
https://repo.enonic.com/public/com/enonic/xp/testing/7.0.0/

Not finding anything here:
https://developer.enonic.com/docs/xp/stable/release/upgrade#requirements
https://developer.enonic.com/docs/xp/stable/release/apps-upgrade
http://wiki.enonic.com/display/dev/7.0+breaking+changes
http://wiki.enonic.com/display/dev/7.0+app+upgrade+guide

**Comment by alansemenov** [comment]
In build.gradle:
```
dependencies {
    testCompile "com.enonic.xp:testing:${xpVersion}"
}
````
In your Java test class:
```
import com.enonic.xp.testing.ScriptRunnerSupport;
```
In your Javascript test class:
```
var assert = require('/lib/xp/testing');
```

Added new section [here](https://developer.enonic.com/docs/xp/stable/release/apps-upgrade#12_testing_api)
