### ISSUE TITLE
Don't use deep pagination to fetch all entries

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7139]
* Use ES 'Search Request Scroll' instead of Deep Pagination for processes like dump and export
Linked to https://github.com/enonic/xp/issues/7124

**Comment by rymsha** [comment]
I rebranded it to a bug. There are certain issues with quickfix.

**Comment by rymsha** [comment]
"Search Request Scroll" is still not the best approach in cases when data must be temporary stored in memory (for extra processing - like in Vacuum).

Next best algorithm candidate batching with sort by unique value and extra range filtering.
