### ISSUE TITLE
Skip creating extra cache files for gif images

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#7143]
New cache image is created for any new combination of read params, but it contains exact original source, so it can be skipped.

**Comment by vbradnitski** [comment]
New cache image is created for any new combination of read params, but it contains exact original source, so it can be skipped.

**Comment by GlennRicaud** [comment]
Closing issue
See comment in https://github.com/enonic/xp/pull/7145#issuecomment-501616099
