### ISSUE TITLE
Project Lombok

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7155]
Proposed by @gbbirkisson: Use lombok to reduce Java boilerplate code in our classes

I am agreeing with this. What I did not know is that it also has Builder generation that creates code very similar to what we have.
It would make reading and future development faster.

Not proposing to refactor everything now but slowly and at least for new developments.

Not sure what will be the impact for code coverage metrics.
We might have to configure to not take generated methods into account.

Under MIT License (Well it is not really included in the product anyway, it is used at compile time)

**Comment by ashklianko** [comment]
Won't it complicate debugging of Java code?

**Comment by GlennRicaud** [comment]
Well I was thinking to use it in classes like our Params classes that do not have any logic inside and should not need to debug.
But yes you are right

**Comment by gbbirkisson** [comment]
Here are the things I can think of to consider:
* How will codacy handle it?
* Inheritance and Lombok do not play nice, so we should not extend lombok classes.
* The methods generated are just getters, setters, equals, hashCode and toString. If we trust that they are generated correctly, you never need to step through those methods.
* Other custom methods you add work fine with the IntelliJ debugger.
* Classes generated are shown normally in the debuggers variable browser, just like any other class.
* I am not sure about remote debugging, should be the same right?
* When in doubt you can always "delombok" the class with the IntelliJ plugin.
* We can remove so much boiler plate. And generally more code means more bugs.

I think it is definitely worth trying out, so I would like to suggest a "standard" on how we use it. These suggestions cover the cases for data class usage that I have seen so far. If you can think of more cases, let me know what they would be.

### In general

* Use it on classes that are meant to be data classes, so use `@Data` or `@Value` (if the class is immutable)
* Always create inner builder class with the name `Builder`, so use: `@Builder(builderClassName = "Builder")`
* Annotate all required fields with `@NonNull` or `@lombok.Builder.Default`
* Annotate all collections with `@Singular`

Example:

```java
@Value
@Builder(builderClassName = "Builder")
public class ImmutableDataClass
{
    String someString;
    @NonNull Double someDouble;
    @lombok.Builder.Default boolean somePrimitive = false;
    @Singular ImmutableMap<String, Integer> items;

}
```

### Validation of data classes on build

* Only needed when annotations `@NonNull` and `@lombok.Builder.Default` are not enough
* Create a private method  `validate` in your data class that validates and returns the class
* Create a protected class `ValidationBuilder` that extends `YourClass.Builder`
  * Override `build` method in ValidationBuilder and call `validate` in that method
* Return new `ValidationBuilder` in the static `build` method.

Example:

```java
@Value
@Builder(builderClassName = "Builder")
public class ImmutableDataClass
{
    String someString;
    @NonNull Double someDouble;
    @lombok.Builder.Default boolean somePrimitive = false;
    @Singular ImmutableMap<String, Integer> items;

    private ImmutableDataClass validate()
    {
        if (someDouble < 0) {
            throw new IllegalArgumentException( "someDouble cannot be less than 0" );
        }
        return this;
    }

    protected static class ValidationBuilder extends ImmutableDataClass.Builder
    {
        @Override
        public ImmutableDataClass build()
        {
            return super.build().validate();
        }
    }

    public static ImmutableDataClass.Builder builder()
    {
        return new ValidationBuilder();
    }
}
```

### With jackson

* Annotate class with `@JsonDeserialize(builder = YourClass.Builder.class)`
* Annotate inner builder class with `@JsonPOJOBuilder(withPrefix = "")`

Example:

```java
@Value
@Builder(builderClassName = "Builder")
@JsonDeserialize(builder = ImmutableDataClass.Builder.class)
public class ImmutableDataClass
{
    String someString;
    @NonNull Double someDouble;
    @lombok.Builder.Default boolean somePrimitive = false;
    @Singular ImmutableMap<String, Integer> items;

    @JsonPOJOBuilder(withPrefix = "")
    public static class Builder
    {
    }
}
```

### All put together

Example class of all of the above:

```java
@Value
@Builder(builderClassName = "Builder")
@JsonDeserialize(builder = ImmutableDataClass.ValidationBuilder.class)
public class ImmutableDataClass
{
    String someString;
    @NonNull Double someDouble;
    @lombok.Builder.Default boolean somePrimitive = false;
    @Singular ImmutableMap<String, Integer> items;

    private ImmutableDataClass validate()
    {
        if (someDouble < 0) {
            throw new MalformedParametersException( "someDouble cannot be less than 0" );
        }
        return this;
    }
    
    @JsonPOJOBuilder(withPrefix = "")
    protected static class ValidationBuilder extends ImmutableDataClass.Builder
    {
        @Override
        public ImmutableDataClass build()
        {
            return super.build().validate();
        }
    }

    public static ImmutableDataClass.Builder builder()
    {
        return new ValidationBuilder();
    }
}
```

**Comment by sigdestad** [comment]
This sounds interesting

However, we need to do more research before we move on this

* We have a massive Java API, are there any impacts on this?
* What are the alternatives to Lombok (there typically are - many..)
* How does this relate to our tests?
* How does it relate to OSGi?
* If we like it, how do we try it out
etc..

Also I see there is serialization stuff here.  I remember we have tried a lot of "generated" JSON/XML stuff in the past, and I know this has not always produced the results we wanted. I'm not sure what state is now, but we need to have 100% control over how these things work due to our API's etc.

To me this sounds like a PAB level thing once the basic research is concluded.

**Comment by gbbirkisson** [comment]
> Also I see there is serialization stuff here. I remember we have tried a lot of "generated" JSON/XML stuff in the past, and I know this has not always produced the results we wanted. I'm not sure what state is now, but we need to have 100% control over how these things work due to our API's etc.

The serialization is completely optional. We could still do things as we do them today. But it is an option if we see that it can work out of the box.

**Comment by gbbirkisson** [comment]
Apparently there seems to be a more powerful alternative called [immutables](https://immutables.github.io/) when it comes to generation of Immutable data classes and builders for them. At first glance it seems to:
* Be more mature
* Make more sence. You define interfaces and abstract classes and the generator implements them.
* Handle inheritence very well

To be honest then I like this approach better then Lombok.

### Simple example

```java
@Value.Immutable
public interface DataClass
{
    Optional<String> getSomeString();

    Double getSomeDouble();

    boolean getSomePrimitive();

    ImmutableMap<String, Integer> getItems();
}
```

### Example with default values, validation and Jackson

```java
@Value.Immutable
@JsonSerialize(as = ImmutableDataClass.class)
@JsonDeserialize(as = ImmutableDataClass.class)
public abstract class DataClass
{
    public abstract Optional<String> getSomeString();

    public abstract Double getSomeDouble();

    @Value.Default
    public boolean getSomePrimitive()
    {
        return false;
    }

    public abstract ImmutableMap<String, Integer> getItems();

    @Value.Check
    protected void check()
    {
        if ( getSomeDouble() < 0 )
        {
            throw new IllegalStateException( "someDouble cannot be less than 0" );
        }
    }
}
```

### Usage of the generated classes

```java
DataClass dataClass = ImmutableDataClass.builder().
    somePrimitive( true ).
    someDouble( 7.0 ).
    build();
```

**Comment by sigdestad** [comment]
We need to to some basic testing of this to conclude.
I.e. could we use Kotlin instead? What about next gen Java etc?
