### ISSUE TITLE
js cluster api for statistics endpoint

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7163]
web endpoints are nice, but if server config and firewall openings are not in place they might not be reachable, and using lib-filesystem to figure out which port/url the endpoint is on and doing http client request to localhost with faked session does not sound reasonable.

I would like something like:
lib-cluster.get()
lib-cluster.getInfo()
lib-cluster.getClusterName()

To return some useful information.

ref: https://github.com/enonic/doc-xp/issues/33

**Comment by sigdestad** [comment]
We want to minimize the need for XP devs to know about/deal with clustering. We should rather focus on making the cluster transparent for developers.

Closing issue for now.
