### ISSUE TITLE
Updating the app name installs two applications

### ISSUE THREAD

**Issue by poi33** [enonic/xp#7167]
Renaming an app will create two apps and only one can be deleted (Delete from deploy folder)

Reproduce:
1. Deploy app
2. Rename the appName (gradle.properties)
3. Re deploy app

Creates two applications 
Can only uninstall one

![image](https://user-images.githubusercontent.com/3340349/59605208-9660b280-910e-11e9-966a-8741381ad7cc.png)

**Comment by sigdestad** [comment]
This is fully intentional as you have now created two different apps.
To remove the first app, you need to remove the file.

I'm closing the issue
