### ISSUE TITLE
i18n support in <default> fields in input type schemas

### ISSUE THREAD

**Issue by espen42** [enonic/xp#7177]
`<label>` and `<help-text>` support `i18n="key"` attributes that kan look up values from phrases_xx.properties. `<default>` does not, it would  be handy if it did.

**Comment by sigdestad** [comment]
This is probably a "no-go" as I see it. Why would one use the default language of the admin console as the default value of content produced (likely in another language)

**Comment by alansemenov** [comment]
Why admin console? The app containing input schemas can have its own localisation resources. Makes total sense to me.

**Comment by sigdestad** [comment]
So, If I have spanish UI, and I'm editing some English content, why a spanish default text be any good?

**Comment by sigdestad** [comment]
Strictly speaking, you should have a default text for the chosen language.

**Comment by sigdestad** [comment]
In the content you are editing
