### ISSUE TITLE
repoConnection.getActiveVersion is slow

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7180]
getActiveVersion() is cool and can be used to keep a cache fresh.

However it's slow. On my development laptop it takes 1ms, while in a cluster environment is averages about 10ms.

Perhaps that doesn't sound like a lot, but if you wanted to keep a fresh cache of 100 nodes, then that would make every request 1 second slower, which is simply too much.

I got some help from @gbbirkisson to look at the Java code.
It looks like nodeService behind the scenes does a lot more than necessary.
Getting all branches and all versions, etc.

@alansemenov says that we cannot add a repoConnection.getActiveVersionId which would only return the versionId string, because it's a core library and would trigger a feature release.

Could someone make a temporary micro lib which only that function? And later include it in Enonic XP 7.1?

Or improve the behind the scenes code to do as little as possible.

**Comment by rymsha** [comment]
node-lib `getActiveVersion` 
- may have to convert key to id if key is path.
- it does not iterate over all branches! Just current branch is examined
- it does two queries to ES: to branch index to find current version id and to version index to get version metadata.

if key is path - then yes, extra latency is added.

**Comment by rymsha** [comment]
#7913 introduced Node cache. There is no need for extra layer of cache
