### ISSUE TITLE
Modifying content should change state to IN_PROGRESS 

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7182]
When content is modified, state should change to "IN_PROGRESS".

State should not change when only content permissions are updated or a version is rolled back or when content is saved in the Content Studio before opening the publish dialog.

**Comment by alansemenov** [comment]
I'm still not 100% convinced this logic should be a part of content modify API... should probably be discussed.

**Comment by GlennRicaud** [comment]
Will be solved through https://github.com/enonic/xp/issues/7185
