### ISSUE TITLE
Workflow - Check readiness on publish

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7185]
* Make it so that the default is WorkflowInfo.ready() and not WorkflowInfo.inProgress() in Content constructor
* Adapt PublishContentCommand (and maybe PushContentCommand) to check that contents to be published have a workflow state in READY state
  * There is already a very similar check that check that the contents to be published are valid (CheckContentsValidCommand)

**Comment by sigdestad** [comment]
I guess we should not need to check for valid anymore, as ready should required valid?
