### ISSUE TITLE
Session expire event

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7188]
We now have sessionTimeout parameter to the login function:
- https://repo.enonic.com/public/com/enonic/xp/docs/7.0.1/docs-7.0.1-libdoc.zip!/module-auth.html#.login
- https://github.com/enonic/xp/issues/4934

However there might be some stored data to delete when a session expire.

Is it possible to send an session expire event?

**Comment by rymsha** [comment]
Sessions can be distributed and their expiration moment is not well defined - they are kept in memory much longer and may even resurrect (if expiration just happened, but there was an inflight request for another instance)

Short: no session expire event possible.
