### ISSUE TITLE
Repo specific snapshot?

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7190]
Lets say a nightly sync has corrupted a specific repo. And after that multiple content editors has made important changes to a site. Now rolling back to yesterdays snapshot would "loose" all those important changes, but "repair" the nightly corruption.

Typically nighly syncs doesn't write to the content repo, but rather its own repo.
Wouldn't it be nice if I could roll back only a single repo?

**Comment by ComLock** [comment]
@sigdestad When the versions garbage collector is implemented what happens if on restores an old snapshot whose versions has been deleted?
I guess the correct answer is something like: Versions that belong to a snapshot cannot be deleted.

Thus one would need to delete old snapshots.

Will it be possible to configure what stays and what gets deleted?

**Comment by sigdestad** [comment]
So, we will investigate support for restoring a single repo from a snapshot. For simplicity, we will still snapshot the entire system for now.

**Comment by rymsha** [comment]
https://developer.enonic.com/docs/enonic-cli/master/snapshot#snapshots
says there is an `--repo`  to do a specific repository snapshot

https://developer.enonic.com/docs/enonic-cli/master/snapshot#restore
Restore also has `--repo` to restore specific repository

Isn't that it?

**Comment by rymsha** [comment]
Possible and documented since CMS times
