### ISSUE TITLE
Header names - Case sensitivity

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7211]
Starting from September 30th, header names will be lowercased by GCP
Check impact and adapt if required
Fix in master and 6.15 branch

**Comment by sigdestad** [comment]
NB, so the expiration only applies to the Google load balanser. Thing is that headers are actually case insensitive

**Comment by sigdestad** [comment]
We can not and must not do any breaking changes

**Comment by GlennRicaud** [comment]
- I know. By "Check impact and adapt if required" I mean check that we handle case variation
- I know. I put 7.1.0

**Comment by GlennRicaud** [comment]
Request Headers used by Enonic XP:

From the HttpServletRequest:
Headers like "Range" or "Referer" used by AttachmentHandler or IssueResource are camel cased by Jetty -> OK
"X-Forwarded-*"" headers are not but the getHeader is case insensitive -> OK

WebRequest/PortalRequest:
Only specific header usage found is for "Range" and it is camel cased as mentioned above -> OK

Only impact found would then be for the Applications for the headers that are note renamed by Jetty.
