### ISSUE TITLE
uri normalize parse resolve serialize

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7217]
There are a bunch of node modules to handle uri's.
All of them have various problems requiring numerous build hacks and polyfills to the level of giving up!

Now there must be some kinda Java library that does this?

Can somebody please make a java lib to handle uris?

It should also be possible to get the various parts of the uri, like host and query.

See https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Definition

**Comment by sigdestad** [comment]
Could this be used? http://galimatias.mola.io/

**Comment by ComLock** [comment]
Perhaps, it doesn't contain any function/method to resolve though.

**Comment by ComLock** [comment]
Looks like I can use java.net.URL directly.
