### ISSUE TITLE
Node lib - Modify method runs supplied editor function twice

### ISSUE THREAD

**Issue by arneroen** [enonic/xp#7220]
Hi,

I think I've found an error in node-lib. The .modify-method seems to run the provided editor-function twice. 

XP version: 7.0.1

Calling the following function
```
const testFunction = (someNodeId) => {
  log.info("This is printed once");
  const repo = nodeLib.connect({
    repoId: config.repoId,
    branch: config.branch,
  });
  repo.modify({
    key: someNodeId,
    editor: function(node){
      log.info("This is printed twice, but should be printed only once!")
      return node;
    }
  })
}
```

Results in the following output:
```
[pathstuff] This is printed once
[pathstuff] This is printed twice, but should be printed only once!
[pathstuff] This is printed twice, but should be printed only once!
```

... meaning that the supplied editor function is run twice, when (as far as I can tell) it should only get run once!

In the interest of reproduction the function is being  run from the context of the controller of an admin-tool. I have not tested if the behavior is present in other contexts.

**Comment by GlennRicaud** [comment]
Reproduced.

Wow. I think this problem has been present since its creation.
Thank you for reporting this. :+1:
