### ISSUE TITLE
Tests results for more than one test per class

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7231]
The Tests Results located here: 
file:///<SNIPPED>/build/reports/tests/test/packages/default-package.html

Gives an impression that you can get more than one test  result per class:

![Skjermbilde 2019-07-11 kl  12 58 10](https://user-images.githubusercontent.com/118847/61045739-b9177b80-a3db-11e9-9de7-282d9ca307a2.png)

Following
https://developer.enonic.com/guides/writing-unit-tests

That doesn't seem possible.

Are there any plans to improve the testing framework?

**Comment by anatol-sialitski** [comment]
According to the documentation https://developer.enonic.com/guides/writing-unit-tests
```
Every exported function that is prefixed with test is executed as a separate test. 
```
