### ISSUE TITLE
Content Layer - Deletion of node on local/children branches

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7234]
Decide what happens on deletion of nodes (when some are inherited or local copies).

**Comment by GlennRicaud** [comment]
What would be an interesting solution (not in prototype but in final solution) is to be able to delete inherited nodes by storing information on children branches that a node has been deleted.

Proposition for prototype:

On current branch:
- Ignore inherited nodes
- Inherit nodes from parent branch for the ones deleted

**Comment by sigdestad** [comment]
This is a very interesting idea!
What needs to be concluded is how to deal with this in terms of branch path's. I.e. what if you create a brand new item with same path (etc.) A solution could be to store the "inhetitance" data as branch metadata in a list or similar. So, this would be used during the inheritance calculation process.
