### ISSUE TITLE
Fragment Resource - Add workflow info parameter

### ISSUE THREAD

**Issue by ashklianko** [enonic/xp#7244]
@sgauruseu commented on [Mon Jul 15 2019](https://github.com/enonic/app-contentstudio/issues/642)

1. Open new site wizard, select Features, select Page-controller.
2. Insert new text component(for example) then select `Save as Fragment` menu item:

![image](https://user-images.githubusercontent.com/3728712/61215572-fe0d1c00-a713-11e9-9fb3-b78a95cfeba4.png)

3. New fragment wizard is opened.

BUG: Workflow state of the fragment should `In Progress`, because parent site is 'In Progress'

![image](https://user-images.githubusercontent.com/3728712/61215739-59d7a500-a714-11e9-99b8-0bb224570165.png)

**Comment by GlennRicaud** [comment]
Why not in progress anymore.
What is the status?

**Comment by ashklianko** [comment]
Had to switch to Content Layers epic, so postponed for now
