### ISSUE TITLE
Error after loading dump: "Cannot get blob with blobKey... blob is null"

### ISSUE THREAD

**Issue by espen42** [enonic/xp#7274]
Context: large-ish (1.6 GB) content dump from XP 6.11.0, uploading with datatoolbox app to XP 6.15.5 running on docker in Azure. Afterwards, all contact with XP - even datatoolbox - shows the stack trace. 

Sharing the stack trace tomorrow, dump file should also be available.

**Comment by chriwest** [comment]
Probably not the best stack trace, but this is the gist of our error.  
![image](https://user-images.githubusercontent.com/45593962/62295897-55c6b980-b46e-11e9-8b12-875de4a25039.png)

When tried today it just gave a blank 500 screen. 

Understood it was in Enonic 6.11 when the system dump had an overhaul, so Will try to avoid the system dump in the next attempt and go for node exports instead.

**Comment by GlennRicaud** [comment]
Hei,

I just made a dump with XP 6.11.0 and loaded it in 6.15.5 and I cannot load it yes.
Something has changed in the dumps between 6.11.0 and 6.15.5.
I will make a fix for Data Toolbox tonight and release a new version.

But it is not exactly your error here. This "Cannot get blob with blobKey" might be linked something else.

I will write here when the new version is available.
You can try it and then if you still have the problem, maybe i could take a look at your system dump somehow.

**Comment by GlennRicaud** [comment]
Data Toolbox version 2.2.6 has been released on the market.
Can you upgrade the application and retry the load of the dump?

**Comment by GlennRicaud** [comment]
Closing the issue
