### ISSUE TITLE
Default config of Content Selector doesn't allow selecting site content

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7276]
By default Content Selector allows child items of the site, but not the site itself. This should be fixed so that the site itself can also be selected. If user wants to disable selecting the site, he can do it by specifiying regex in `allowContentType`.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/app-contentstudio #850](https://github.com/enonic/app-contentstudio/issues/850) via [**ZenHub**](https://www.zenhub.com/)
