### ISSUE TITLE
Can't nest inline mixin(s) in x-data 

### ISSUE THREAD

**Issue by espen42** [enonic/xp#7277]
XP version: 6.15.6

When I try to add `<inline mixin=... >` inside the `<items>` node inside x-data, the inline mixin doesn't appear for editing in Content Studio - even though the same inline mixin works in a direct context or even added inside another inline mixin.

**Comment by alansemenov** [comment]
Confirmed. On a side note, including a mixin inside an x-data works fine in XP7.

**Comment by alansemenov** [comment]
@espen42 The conclusion is that the changes we made to support this in XP7 were so big that we won't risk doing this in 6.15. Please find a workaround.
