### ISSUE TITLE
Set default layer language for a new content

### ISSUE THREAD

**Issue by ashklianko** [enonic/xp#7286]
@alansemenov commented on [Mon Jul 22 2019](https://github.com/enonic/app-contentstudio/issues/673)

When a new content is created, set `language` property of the new content to default language of the current layer (now it's set to `null`).

**Comment by GlennRicaud** [comment]
Modification done in PR #7287 is not correct.

This new behaviour is overriding the param (not behaving as a default value).
Also the place to do this kind of thing already exists: Please adapt CreateContentCommand::getDefaultLanguage instead

Moving this issue back to InProgress

**Comment by GlennRicaud** [comment]
Pass back to done. Will be fixed in https://github.com/enonic/xp/issues/7305
