### ISSUE TITLE
Different behaviour when deleting local content from a layer

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7292]
In the screenshot below the "Features" site exists as a local copy (`inherited` is set to `false`) in the layer while all of its children are inherited from its parent layer (`inherited` is set to `true`).

![image](https://user-images.githubusercontent.com/11612490/62878319-24c96d00-bd29-11e9-8b7b-4b84cb6560c0.png)

If user deletes the site, it will delete the site itself and all of its inherited dependencies. Can we change it so that in this case we don't physically delete the content but update `inherited` property from `false` to `true`, so that local content becomes inherited again? This also means that we need to change the resolution of dependencies/children as well, to only include items that are not inherited.

The challenge is to only do this for content that used to be inherited but then was turned into local. If the content was originally created as local, then deletion should go as usual.

**Comment by sigdestad** [comment]
Remember, this is low prioritity...

**Comment by GlennRicaud** [comment]
Not reproduced. Can we discuss it together Alan
