### ISSUE TITLE
Potential problem with localization file resolution

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#7316]
Ref: https://discuss.enonic.com/t/localization-trouble/1952/7

Seems, the country extension of language is not resolved correctly?

**Comment by GlennRicaud** [comment]
Tried quickly without any issue except the lowercasr yhing.

Will wait for an answer in discuss

**Comment by sigdestad** [comment]
So, it "converts" da-DK to da_DK when looking in the props file? How can that be? I thought we were using standard Java approach for this all the way through? Are we changing Java's representation of langauge when storing it as "da-DK"?

**Comment by GlennRicaud** [comment]
Closing this issue as the documentation has been updated and there is still no answer
