### ISSUE TITLE
read-only mode killed my cluster

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#7328]
Indices where closed, but never opened, had to run manual open of indices.

Message from toolbox:

```
Source docker-functions
XP-Container found: [a4f8480f2e96]
Response error: {
 "status" : 500,
 "message" : "[helsenett-xpprod-cluster-master-1][inet[/10.223.113.162:9300]][indices:admin/close] request_id [10607381] timed out after [5000ms]",
 "context" : {
  "authenticated" : true,
  "principals" : [ "role:system.admin", "role:system.admin.login", "role:system.authenticated", "role:system.everyone", "user:system:su" ]
 }
}
```

Ask rmy for server-log.

**Comment by sigdestad** [comment]
Shit hit the fan again. We need to look into this. Same version of XP 6.15.8, cluster goes black after issuing readonly mode.

**Comment by sigdestad** [comment]
We need to a) fix this or b) drop the read only instruction in upgrade notes

**Comment by sigdestad** [comment]
Quick fix when this happens: https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-open-close.html

curl -XPOST 'localhost:9200/_all/_open'

**Comment by rymsha** [comment]
According to the initial error message `index/close` method timed out. this should not happen on healthy cluster.
#8219 (only applicable to 7.x) verifies that XP nodes don't try to fade away when cluster is unhealthy. It should help this case as well.
But if cluster is really doomed - all bets are off. Admins should use low level tools to restore it (easiest to try to reopen indices as described)
