### ISSUE TITLE
Named placeholders with {} in phrases.properties used in x-data freezes CS editor 

### ISSUE THREAD

**Issue by espen42** [enonic/xp#7332]
XP 6.15.6

When a help-text in an x-data XML is localized from phrases.properties, and the phrase contains non-numeric dynamic placeholders (e.g. `{phoneNumber}` instead of `{0}`), content items where that x-data is used (in my case a site) can’t be edited in content studio. Opening the edit window makes the window lock with visible spinners in both the forms tab and the edit preview, without ever proceeding. 

Only this hanging behavior happens, I can't see any error message / exception stack trace anywhere (server log or client console).

**Comment by alansemenov** [comment]
Will be fixed in https://github.com/enonic/xp/issues/7333
