### ISSUE TITLE
Repository Data - Data field

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7362]
To be PRed to branch "next"

* Add field on com.enonic.xp.repository.Repository
  * private final PropertyTree data;
* Adapt serialization/unserialization

**Comment by sigdestad** [comment]
Question:
Why do we need to serialize the propertyTree? Aren't we storing this data in the system repo?

**Comment by rymsha** [comment]
Yes we will do store `data` in system-repo.

Your initial questions will remain unanswered for now... I need to talk to Glenn.

**Comment by rymsha** [comment]
Questions to Glenn:
- What does "Adapt serialization/unserialization"  mean?
- How do we deal with Dump/Restore. Especially if we plan to save an Attachment it this repo?

**Comment by GlennRicaud** [comment]
By serialization/deserialization, I meant the translation to/from node.
These classes are often suffixed with Serializer in the code: ContentDataSerializer, IssueDataSerializer, ...
But in this case RepositoryNodeTranslator as you found out.
So no problem here.

And yes we will have to change again in a second issue by including BinaryAttachments to CreateRepositoryParams.
Will review and create a second issue.
