### ISSUE TITLE
Research migration from _type mapping

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#7389]
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

- [ ] find and link in comments other projects experience (actually we are interested only in bad experience) with migration to new mapping
- [ ] find out the reasons we use parent/child and _type mappings. Maybe we can use something else instead.

**Comment by sigdestad** [comment]
Some input here.
The _reason_ why we use parent child mapping does not need to be researched, this is to be able to "diff" versions between branches. Runar (and probably Glenn) can explain this if one needs details.

I suggest limiting this task to the _type part, and then we can have a different task if we need to research parent/child thing. Ok?

**Comment by rymsha** [comment]
Well, no. ;-)
parent/child needs _type.
With _type removal parent/child functionality was removed as well.
Reasons behind use of _type in Enonic XP ARE to be able to use parent/child mapping. After talks with Runar and Glenn I got an impression that there are no other reasons. 

Now there is `join` functionality. (Starting from ES 6.x) but there is still a small hope we can live without it: by implementing `diff` somehow else. 
If not - can `join` be used, and how.

**Comment by sigdestad** [comment]
Ok :-)

**Comment by sigdestad** [comment]
Join could solve this issue i guess...

**Comment by runarmyklebust** [comment]
I dont think join would solve this? That is between docs in the same index, isnt it? I think the version and branch should be sepated into different indices, there is no other good explanation (just bad stuff) of keeping them in the same index

**Comment by runarmyklebust** [comment]
You are right about that the only reason @rymsha is to facilitate this search, else it only cause issues. I think the full rework of this is the way to go rather than try to path this even further.

**Comment by vbradnitski** [comment]
Won't we get performance issue after splitting it? `Branch` contains copied blobkeys from it's `Version` and we use it to construct a node. After splitting we will have to get `versionkey` from branch instance and then get full version data from `Version` index.

**Comment by vbradnitski** [comment]
_type in `search` index can be easily replaced by custom field I think.

**Comment by rymsha** [comment]
> 1. Won't we get performance issue after splitting it? `Branch` contains copied blobkeys from it's `Version` and we use it to construct a node. After splitting we will have to get `versionkey` from branch indice and then get full version data from `Version` indice.
this sounds like an extra roundtrip, so performance may become worse. But there are lots of factors, so it may end up being unnoticed performance hit.

> 2. With new internationalization functionallity we create 2 new branches(master, draft) for every new language layer. In case of creating new indices for each branch: are we going create 6 indices (draft/master-version, draft/master-branch, draft/master-commit) for every new language layer?
This I don't get yet. So, maybe I will ask stupid question: Why "new" branches require new indices? cant they live in the same index for branches.

**Comment by rymsha** [comment]
>  I would also think that two different branches should live in different indices to make it easy to create and delete branches

ES now provides a new feature "delete by query" https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html 
which can offload long-running deletions to internal ES task. So cleaning up process can be done in the background. (similar to what Git does)
Giving the fact that branches are rarely removed it would be correct to complicate structure just to make deletion of branches fast. What do you think?  @runarmyklebust
