### ISSUE TITLE
Translate missing phrases to Swedish

### ISSUE THREAD

**Issue by jsi** [enonic/xp#7399]
The following phrases are missing Swedish translations:
 - base.folder.description
 - base.shortcut.description
 - portal.page-template.description
 - portal.template-folder.description

**Comment by Bellfalasch** [comment]
Hmm not familiar with this app structure. Where's the phrases files?

**Comment by alansemenov** [comment]
https://github.com/enonic/xp/blob/master/modules/app/app-system/src/main/resources/i18n/phrases_sv.properties

**Comment by Bellfalasch** [comment]
Thx, done
