### ISSUE TITLE
Audit Log Usage - Content API

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7424]
To be PRed to master

At ContentService level, use the AuditLogService to log for each call of the following methods (the methods updating the state):
```
    create
    update
    rename
    delete
    deleteWithoutFetch
    undoPendingDelete
    publish
    unpublishContent
    duplicate
    move
    setChildOrder
    reorderChildren
    applyPermissions
    setActiveContentVersion
    reprocess
```

**Comment by GlennRicaud** [comment]
* Source: com.enonic.xp.core-content
* Time, User: They are set automatically
* Data: Put the parameters there (at least the relevant ones)
* Message: Message describing the action. If it is a list of IDS bigger than 1, use the number of IDS rather than listing the entire list I think. Like Publish X contents or something
* objectUris: The idea is to have an identifier for the objects of the action. For example for a content identified by its content ID. I would like the format [repoId]:[branch]:[contentId]
Example:     com.enonic.cms.default:draft:0123-4567-7890-1234
For a content identified by its content path, I would like the format [repoId]:[branch]:/content[contentPath]
Example:      com.enonic.cms.default:draft:/content/features

**Comment by sigdestad** [comment]
Hi.
I have had a look at the actions to log, and have some questions/input:

- reprocess - We do not need to audit this one, as it does not affect any state
- create - Ok
- update - Ok
- rename - Ok
- delete - Is this "delete now", or "mark as deleted"?
- deleteWithoutFetch
- undoPendingDelete (potentially we don't have to log this?)
- publish - Ok, but what do we log? All items and what happened? Or do we log the items as created/deleted in the master branch?
- unpublishContent (same as above)
- duplicate - Ok
- move - Ok
- setChildOrder
- reorderChildren (what is the difference between this and the one above?)
- applyPermissions - Ok
- setActiveContentVersion - Ok

**Comment by GlennRicaud** [comment]
reprocess - It does.
delete - Both
undoPendingDelete - Why not?
publish/unpublish - I thought the idea was to log the usage of the API and not the results of the actions
setChildOrder/reorderChildren: One is changing the childOrder on a nodem the other one is reordering the children of a node

**Comment by GlennRicaud** [comment]
@sigdestad: But we need to agree on the messages format though
