### ISSUE TITLE
Portal - Content path count limit

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7439]
To be PRed to 6.15, 7.0, 7.1 and master

Set a limit for the number of content path elements handled by Portal
Add a check of contentPath.elementCount() in BaseSiteHandler.doCreatePortalRequest

@runarmyklebust @sigdestad: Unsure about the exact limit. We could make it configurable in future version. But what should be the default? 256 (takes about 0.2s on my machine)?

**Comment by sigdestad** [comment]
I dont know what is being limited? Number of sub-folders? Character??

**Comment by GlennRicaud** [comment]
Closing this issue. Original problem got handled differently: https://github.com/enonic/xp/issues/7466
