### ISSUE TITLE
Vacuum - Endpoint

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7446]
Add possibiity to specify
- The tasks to execute
  - In the future, the possibility to extend with a configuration for each task
- A global configuration

Defaults values:
- By default, all vacuum tasks will be executed
- By default the time threshold is 1hour

**Comment by sigdestad** [comment]
What is this threshold about?

**Comment by GlennRicaud** [comment]
Same as in Enonic XP 6. There is an age threshold

**Comment by sigdestad** [comment]
For what?
