### ISSUE TITLE
All unit tests fail on app-users

### ISSUE THREAD

**Issue by jsi** [enonic/xp#7467]
On Concourse (https://ci.enonic.io/teams/dev/pipelines/xp-all-master/jobs/build-app-users/builds/721) and locally on my Mac, all the unit tests in app-users fail.  Strangely enought, this does not seem to happen on Travis.  Please investigate and fix the tests.

**Comment by rymsha** [comment]
it is a regression after #7318 
testing framework is Junit4 dependent.
