### ISSUE TITLE
Error after scheduled publishing of content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#7486]
1. Open new folder wizard, type a name., save it. (open existing folder)
2. Open Publish menu and click on Publish menu item.
3. Add Schedule Form and select correct date: 

![image](https://user-images.githubusercontent.com/3728712/65948317-b0ff3300-e442-11e9-9f7c-2de028546772.png)

4. Click on Schedule button.

BUG - The content is not published, error message appears after clicking on Schedule button.

![image](https://user-images.githubusercontent.com/3728712/65948591-37b41000-e443-11e9-8ec1-cd3be3669f09.png)

**Comment by GlennRicaud** [comment]
Due to https://github.com/enonic/xp/issues/7424
