### ISSUE TITLE
Fix remote debugging for JAVA 9+

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#7499]
Since Java 9.0 JDWP supports only local connections by default: http://www.oracle.com/technetwork/java/javase/9-notes-3745703.html#JDK-8041435

So remote debugging does not work on Java 11 unless you are doing it on the same machine. To enable remote machine debugging we have to change `address=5005` to `address=*:5005` in [server.sh](https://github.com/enonic/xp/blob/19eb2ecae8de14422b22d62b09a0a926db181588/modules/runtime/src/bin/server.sh#L54).

**Comment by rymsha** [comment]
Local is usually sufficient. If remove is required (for instance in docker) tunnel can be made.
What you suggest  "is not secure and not recommended" according to Oracle

**Comment by rymsha** [comment]
Alternative would be to let users themselves provide jdwp parameters (for instance to change port 5005), but I believe this is already possible.

**Comment by gbbirkisson** [comment]
Sergey is right. It is less secure. Maybe we only want it to work on `localhost`. Then we can just close this issue.

If we need to do remote debugging in the future we would just use the `JAVA_OPTS` variable to set the required flags to make that work. I will let you guys decide if you want to close this issue or not (@rymsha and @GlennRicaud).

**Comment by rymsha** [comment]
One can do `export JAVA_DEBUG_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=10.0.1.8:8000"` before calling `server debug` where `10.0.1.8:8000` - are desired ip and port to listen on.

https://fr.m.wikisource.org/wiki/L%E2%80%99Ours_et_l%E2%80%99Amateur_des_Jardins

**Comment by rymsha** [comment]
on Windows one can do `SET JAVA_DEBUG_OPTS=-agentlib:jdwp=transport=dt_socket,server=n,address=192.168.0.100:5005,suspend=y`

**Comment by GlennRicaud** [comment]
Closing the issue
Just tested and it is true that the default behaviour is to deny remote connection (and not based on hostname check). Better to let user define if they want to enable remote debugging and keep is disabled by default
