### ISSUE TITLE
Add flag to enable profiling for VisualVM on startup

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#7500]
It would be nice to be able to start the server with jxmremote enabled to be able to connect to the server with VisualVM for profiling.

Similar to the `server.sh` `debug` flag, it would be nice to have a `profile` flag. The flags that need to be set are:

```bash
-Dcom.sun.management.jmxremote 
-Dcom.sun.management.jmxremote.port=3000
-Dcom.sun.management.jmxremote.rmi.port=3001
-Dcom.sun.management.jmxremote.ssl=false 
-Dcom.sun.management.jmxremote.authenticate=false 
-Djava.rmi.server.hostname=127.0.0.1
```

In the case you for some reason want to do both, that should also work, i.e all these should work:

```bash
server.sh debug
server.sh profile
server.sh debug profile
server.sh profile debug
```

Then you could run `visualvm --openjmx localhost:3000` to do profiling.

**Comment by rymsha** [comment]
Suggested parameters are highly insecure. I don't agree that turning on insecure should be so easy.

And VisualVM can access local VMs without jmxremote

**Comment by gbbirkisson** [comment]
You are right, this is maybe not such a good idea. If people want to enable this they can just add these flags them self. Closing this issue.
