### ISSUE TITLE
Improve error handling on self-referencing js data model

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#7515]
This was posted by customer regarding an error in production that has proved to be difficult to find the source, it may be  nicer to wrap it in a sensible exception

https://discuss.enonic.com/t/improve-error-description-of-self-reference-for-js-data-model-object/1998

**Comment by sigdestad** [comment]
@runarmyklebust - Why was this issue closed? No info avaialble here?

**Comment by rymsha** [comment]
probably due to this fixed issue #7488
