### ISSUE TITLE
Missing local-preference for getByIds

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#7572]
Testing cluster failover has discovered that the `getByIds`-command asks in a "round-robin" fashion instead of using the "local" preference. This means that even if a node is rejected from the LB, until the cluster kicks the node out of the cluster it will be served requests from `getByIds` slowing down the performance considerably. 

The kick-node-from-cluster operation is more brutal than just not serving request to the troubled node, so the best thing will be to use the local preference to avoid this issue. 

This will probably also increase performance noticeably since the local will usually be faster that the round-robin.

This should be fixed in 6.15.8

**Comment by GlennRicaud** [comment]
Done for 7.2, 7.1 and 6.15
