### ISSUE TITLE
Content lib - getOutboundDependencies

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7577]
https://discuss.enonic.com/t/proper-way-of-getting-outbound-dependencies/2011/2

Expose getOutboundDependencies in content library

Example of usage:
```
const contentIds = contentLib.getOutboundDependencies({
    key: '/path/to/mycontent'
});
````

**Comment by alansemenov** [comment]
The result should be the same as in the "outbound" part of the Dependencies widget when selecting the content item:

![image](https://user-images.githubusercontent.com/11612490/68215602-d18d5080-ffdf-11e9-89a3-631bbb83df52.png)
