### ISSUE TITLE
Heap error when reprocessing migration draft branch

### ISSUE THREAD

**Issue by poi33** [enonic/xp#7655]
Running reporcess command (from toolbox) on the draft branch of a migrated dump causes a java heap error. 

Sendt the dump files to Glenn for debugging.
The last command in [Migration script](https://github.com/enonic/cms2xp)

**Comment by GlennRicaud** [comment]
If I remember correctly, this was due to a heap size with an extremely low value for this machine

**Comment by poi33** [comment]
This is / was the default heapsize when starting a java application. 
You changed a bash script (server.bat?) file to initilize the server with a bigger heap size

**Comment by rymsha** [comment]
@poi33 let me know when you run into this issue again. Currently there is no work do about it.
