### ISSUE TITLE
Reduce number of issue email notifications

### ISSUE THREAD

**Issue by pmi** [enonic/xp#7664]
**Case 1:** 
User A creates an issue, but doesn’t assign it to anyone.

_Expected behaviour:_
No email is sent

**Case 2:** 
User A creates an issue and assigns it to user B during creation.

_Expected behaviour:_
System sends an email with subject “You were assigned…”
_From_: User A
_To_: User B

**Case 3:**
Any user assigns an existing issue to user B

_Expected behaviour:_
System sends an email with subject “You were assigned…” (even if it was user B who assigned the issue to himself)

_From_: modifier
_To_: User B

**Case 4:**
Any user adds a comment to an issue

_Expected behaviour:_
System sends an email “A new comment is posted”

_From_: modifier (the one who left a comment)
_To_: creator + all assignees - modifier

**Case 5:**
Any user closes or reopens the issue

_Expected behaviour:_
System sends an email “The issue was closed” or “The issue was reopened”

_From_: modifier
_To_: creator + all assignees - modifier

**Case 6:**
Any user changes issue title or modifies the list of content items

_Expected behaviour:_
No email is sent

**Case 7:**
Any user publishes an issue or a publish request (which then closes)

_Expected behaviour:_
System sends an email “X published and closed the issue...”

_From_: modifier
_To_: creator + all assignees - modifier

**NB!**
There are certain cases when email should not be sent at all. For example, when creator, assignee and modifier is the same user. Or when creator changes an issue and there are no assignees.

**Comment by GlennRicaud** [comment]
See comment in PR https://github.com/enonic/xp/pull/7665#issuecomment-563230530

**Comment by GlennRicaud** [comment]
Thanks @alansemenov 

If I understood correctly:
```
Common rules:
  No copy recipients
  Do not sent mail if the list of recipients is empty

##############
Issue Created

Subject: "You were assigned…"
From: Creator
To: Assignees - Creator
Copy: -

##############
Issue Updated

If new assignees (no filtering)
  Subject: "You were assigned…"
  From: Modifier
  To: New assignees
  Copy: -

If issue opened / closed
  Subject: "The issue was closed" / "The issue was reopened"
  From: Modifier
  To: Creator + all assignees - modifier
  Copy: -

##############
Issue Commented

  Subject: "A new comment is posted"
  From: Commenter
  To: Creator + Assignees - Commenter
  Copy: -

##############
Issue Published

  No email sent anymore
```

**Comment by alansemenov** [comment]
```
##############
Issue Published

  No email sent anymore
```

Turns out we had a special email template for this case. Added case 7 describing this.
