### ISSUE TITLE
Portal Lib - URL generation for content with special characters

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7674]
Have a content with a norwegian character.
Generate an idprovider URL from this content (test with assetUrl also).
These URL should not contain the content path but they do.

Reproduce and investigate why

Fix in 6.15 also

Example:

1) Content has path "_features_":

IdProviderUrl: `/site/default/draft/_/idprovider/system`

2) Content has path "_featuresåøæ_":

IdProviderUrl: `/site/default/draft/features%C3%A5%C3%B8%C3%A6/_/idprovider/system` (the `features%C3%A5%C3%B8%C3%A6` part should not be in the URL)

**Comment by alansemenov** [comment]
@GlennRicaud What should there be if not path? From what I see it's the same for all urls generated with portalLib

![image](https://user-images.githubusercontent.com/11612490/69709484-c2d91b80-10fd-11ea-9891-527ea9b79b94.png)

**Comment by GlennRicaud** [comment]
Asset URL is wrong there
