### ISSUE TITLE
Reprocess Content - Out of Memory

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7675]
@poi33 reported an Out of Memory error on content reprocessing.
Reproduce and try to improve the process to not be dependant on the ammount of data

**Comment by GlennRicaud** [comment]
The default max heap size is very low on @poi33 computer: 256 mib (on a computer with 16GiB ram)
We were setting it untill [6.4](https://github.com/enonic/xp/commit/73be3b4a5e7cbf5da3c1dc1a992fea1d71b1a494#diff-a5e88d35f66bb2b2376449017e1597da) but not anymore. And I think it is better in most cases to use the default value. 

Closing this issue

**Comment by poi33** [comment]
Computer why you no set higher heap size 💻 😢
