### ISSUE TITLE
Translate missing language phrases to Spanish

### ISSUE THREAD

**Issue by jsi** [enonic/xp#7680]
The following phrases in ´modules/app/app-system/src/main/resources/i18n/´ are missing a Spanish translation:
 - base.folder.description
 - base.shortcut.description
 - issue.email.closed
 - issue.email.commented
 - issue.email.created
 - issue.email.issue
 - issue.email.latestCommentTitle
 - issue.email.publishRequest
 - issue.email.published
 - issue.email.reopened
 - issue.email.showDetailsCaption
 - portal.page-template.description
 - portal.template-folder.description

**Comment by Blask0** [comment]
I can help you with that.

**Comment by diegopasten** [comment]
@Blask0 If you want to do this task, go for it :)

**Comment by Blask0** [comment]
> @Blask0 If you want to do this task, go for it :)
https://github.com/Blask0/xp/pull/1

**Comment by jsi** [comment]
Hi @Blask0 !

Thanks for your work!  We are very grateful.  I have just merged it from your fork, and it is now a part of the core XP!

Would you be able to help us with the other projects in the product as well?  Here are the tasks we have created to do so.  The issue for app-contentstudio is really big.  The other three should be quick:
https://github.com/enonic/lib-admin-ui/issues/1102
https://github.com/enonic/app-applications/issues/110
https://github.com/enonic/app-contentstudio/issues/1240
https://github.com/enonic/app-admin-home/issues/77
