### ISSUE TITLE
Get Page Template - Improve performance

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7690]
Apply following changes to get rid on an unnecessary getById on site and retrieval of all templates:

```
ContentServiceImpl:findByParent  //Add possibility to have additional Filters
  ...
  GetPageTemplateBySiteCommand //Add possibility to specify the site path (To not have this getById)    AND     Add possibility to specify content type that have to be supported
    ...
    GetDefaultPageTemplateCommand //Add possibility to specify path   AND pass the content type to the GetPageTemplateBySiteCommand
      PageTemplateServiceImpl.getDefault // Add posibility to specify path
        ...
        RenderHandlerWorker.getDefaultPageTemplate //Use path instead of site ID
```

**Comment by GlennRicaud** [comment]
Before:
<img width="1676" alt="Screenshot 2019-11-29 at 15 18 30" src="https://user-images.githubusercontent.com/12030113/69877464-928eaa00-12c2-11ea-861a-6f4047c03b7b.png">

After:
<img width="1678" alt="Screenshot 2019-11-29 at 16 05 36" src="https://user-images.githubusercontent.com/12030113/69877470-96223100-12c2-11ea-9cad-0578b7ce8fee.png">

**Comment by GlennRicaud** [comment]
Reimplemented for 7.3.
Added size parameter
Before:
![Screenshot 2020-02-03 at 13 34 27](https://user-images.githubusercontent.com/12030113/73658100-fc954800-4693-11ea-8cbf-29cab9542c86.png)
After:
![Screenshot 2020-02-03 at 14 36 16](https://user-images.githubusercontent.com/12030113/73658110-06b74680-4694-11ea-961b-fddd218c9641.png)

**Comment by sigdestad** [comment]
Nice
