### ISSUE TITLE
Script Event Listener invalidation

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7700]
Event listeners are removed when they should not.
There are invalidations done on the application registry but there are different cases of invalidation.

Things impacted by application registry invalidation
  Application cache (Recomputable cache)
  Resource cache. (Recomputable cache)
  Script executor (Kind of a recomputable cache. But it also calls the disposers)
    IMO: The disposers should only be called as the result of bundle event, the same way as the main.js execution is called...
  Locales (Recomputable cache)
  Script event listeners (This should only be called on bundle events also IMO)

In order to make the least impact in a bug fix version, I will only impact "Script event listeners" for the ApplicationConfigReloader reactivation and update.

A bigger refactoring is necessary in 7.3 to fix the lifecycle of apps: bundle, main.js, app config, event listeners, tasks that are currently never stopped, ...

**Comment by sigdestad** [comment]
Glenn, does this mean that you will not "kill" listeners in the case of app "reloads"?

**Comment by GlennRicaud** [comment]
They will still be removed on app stop or start. This invalidation is called at 5 different place. Just that the event listener should at least not be removed on config change (or cluster state passing to red in our case).

**Comment by sigdestad** [comment]
+1
