### ISSUE TITLE
XP does not handle X-Forwarded-Host correctly

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#7708]
When proxying XP through apache, it can happen that the `X-Forwarded-Host` header is a list of hosts.

The [Apache documentation states](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers):
> Be careful when using these headers on the origin server, since they will contain more than one (comma-separated) value if the original request already contained one of these headers. 

XP does not account for this so if the header is set to `X-Forwarded-Host: "host.a.com, host.b.com"` it will in some cases throw an exception. It was observed in the ADFS provider:

```
2019-12-09 12:38:52,363 DEBUG com.enonic.app.adfsidprovider - (/lib/adfs-id-provider/oauth2.js) redirectToAuthorizationUrl({
    "method": "GET",
    "scheme": "https",
    "host": "host.a.com, host.b.com",
    "port": 443,
    "path": "/xp/admin/tool",
    "rawPath": "/admin/tool",
    "url": "https://host.a.com, host.b.com/xp/admin/tool",
    "remoteAddress": "185.55.107.196",
    "mode": "admin",
    "webSocket": false,
    "repositoryId": "com.enonic.cms.default",
    "branch": "draft",
    "params": {},
    "headers": {
        "Cookie": "enonicXpReturnToUrl=https://host.b.com/xp/admin/tool",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0",
        "X-Forwarded-Host": "host.a.com, host.b.com",
        "X-Forwarded-Proto": "https",
        "Connection": "keep-alive",
        "Host": "host.a.com",
        "Accept-Encoding": "gzip, deflate, br",
        "DNT": "1",
        "Cache-Control": "max-age=0",
        "Upgrade-Insecure-Requests": "1",
        "X-Forwarded-For": "185.55.107.196",
        "Accept-Language": "en-US,en;q=0.5",
        "X-Forwarded-Server": "host.b.com"
    },
    "cookies": {
        "enonicXpReturnToUrl": "https://host.b.com/xp/admin/tool"
    }
})
```

**Comment by rymsha** [comment]
`"url": "https://host.a.com, host.b.com/xp/admin/tool"` is certainly invalid
`"host": "host.a.com, host.b.com"` also invalid

I'm a bit confused why `"Cookie": "enonicXpReturnToUrl=https://host.b.com/xp/admin/tool"`. It maybe a bug in adfsidprovider itself?

**Comment by gbbirkisson** [comment]
Yeah i would assume so: https://github.com/enonic/app-adfs-idprovider/blob/7b18e47f99e0cd69153c6702250bc80aaf2a7441/src/main/resources/lib/adfs-id-provider/portal.js#L99
