### ISSUE TITLE
Default project language

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7835]
Suggestion for design of storing default language of a project/base layer:

```
 "branches": [
    "master",
    "draft"
  ],
  "data": {
    "com-enonic-cms": {
      "displayName": "Default",
      "icon": {
      },
      layers: [{
        name: "base",
        displayName: "",
        parentLayers: [],
        languages: ["en", "no"]
      }, {
        name: "no",
        displayName: "Norwegian content",
        parentLayers: ["base"],
        languages: ["no"]
      }]
    }
  }
```

**Comment by GlennRicaud** [comment]
This seems layer specific to me (except if specifications have changed since).
Please put in appropriate epic

**Comment by rymsha** [comment]
Why multiple languages per layer?

**Comment by sigdestad** [comment]
It is basically a filter of languages that can be used within the layer. The default list is very very long

**Comment by rymsha** [comment]
In the example macrolanguage is used `no` which is a macro for individual languages `nb` and `nn` . Is it intentional, so it is a shortcut for two languages?

Number of languages is not so big (about 200), maybe you meant locales instead of languages?

**Comment by sigdestad** [comment]
True, this is a list of locales

**Comment by rymsha** [comment]
Then I suggest to call field "locales"

Some questions still remain:
- how to create locale independent layer? 
- what would empty array mean?
- will for example `no` macrolnguage resolve to `nb_NO` `nn_NO` locales, or all unique must be provided? If first is true than `en` language will automatically bring ~100 locales into layer. If second is true, will we still expand macro languages?

**Comment by rymsha** [comment]
If it is just cosmetic maybe it would be enough to call it preferred_locales and show them first in the list- then most of my questions are not relevant.
