### ISSUE TITLE
Uninstall app via server.deploy

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#7836]
It i possible to install applications via server.deploy.cfg but not possible to uninstall

One way to do it is to have a special character sequence `!!` which XP will interpret as uninstallation command.

update documentation with server.deploy.cfg when done.

**Comment by rymsha** [comment]
server.deploy.cfg is undocumented feature.
And it is quite problematic one as it installs a Global application.

Maybe remove installation via file server.deploy.cfg @sigdestad ?

**Comment by sigdestad** [comment]
Skeptical about adding more smartness into this one, why not simply uninstall via regular API's?

**Comment by rymsha** [comment]
I'm skeptical, too. I don't want to add more functionality 
I ask instead if we can remove deployment via server.deploy.cfg file

**Comment by sigdestad** [comment]
Personally, I think it is a pretty cool feature, where you don't have to download and prebundle stuff. Any reason explicit reasons to remove it?

**Comment by rymsha** [comment]
1. It is asymmetric. You can install, but can't uninstall. Even if you uninstall next restart will resurrect the app.
2. It installs apps globally while comfig file is local. It causes issues like this #7837 .
3. From ops perspective it is better to mount file into docker image or to script it via curl/wget 
4. It is less secure as it is hard to know what is behind the URL (and it gets download silently without use action)
5. Code is messy :( Doesn't consider a few corner cases. I really don't want to support it.

**Comment by sigdestad** [comment]
1. A "don't install if it already exists" would be interesting
2. Global deployment is generally fine, if I just want local, once can use deploy folder, or provide more options. The multiple restart site-effect is definetly not desired!
3. Yes, but this feature does not prevent once from doing that
4. True
5. Mess can be cleaned, so it's more a discussion of if we want it or not.

Conclusion. We can drop it.

Let's focus on getting full app management capabilities via management API instead!

**Comment by rymsha** [comment]
see #8420
