### ISSUE TITLE
server.deploy.cfg triggers too many application redeploys

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#7837]
We observed a lot of install/uninstall applications when server.deploy.cfg file gets changed.
related to #7836

**Comment by rymsha** [comment]
This happens because each node in cluster "installs" global application seen in server.deploy.config
This doesn't seem correct. We may need to change behavior - install application locally.

**Comment by sigdestad** [comment]
Local installs can also be done via docker image builds

**Comment by rymsha** [comment]
We need to decide what to do with these deploy.cfg apps.
Current implementation is quite useless
- global apps should be installed via endpoint
- local apps should be provided Al local jars

IMO, this functionality must be deprecated/removed. It only caused trouble and confusion

BTW, it is not documented anyhow

**Comment by gbbirkisson** [comment]
Docker image builds is an anti-pattern. You should not have to build a new image when bootstrapping XP. In fact that is not an option in Kubernetes.

Besides, this is a feature of XP and has nothing to do with docker. Do we not want people who choose not to use docker to have this option?

Local install of apps in the deploy.cfg file seems reasonable to me.

**Comment by rymsha** [comment]
I mostly referred to functionality that deploys Global application from `deploy.cfg`. 

Installing local app (as I wrote in first comment) is what could be reasonable.

**Comment by rymsha** [comment]
see #8420
