### ISSUE TITLE
configuration to prohibit global app installation on specific instances

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#7838]
`globalApps = false`

**Comment by sigdestad** [comment]
Is this supposed to go into system.properties?

**Comment by rymsha** [comment]
It is closer to cluster configuration, but I'm not sure either

**Comment by rymsha** [comment]
With current implementation It may come with shortcomings:
- Such nodes can't be frontend nodes, as application gets installed on a frontend node first, then gets distributed as "stored" application.
- currently all master nodes must have global/stored app installed. Users send a global event to cluster from an up and then check isMaster() in a received node. In master doesn't have app installed, event won't be processed by any node.

**Comment by sigdestad** [comment]
Could we implement this as a filter instead? I.e. Allow/deny?

**Comment by rymsha** [comment]
There is another issue for this #7839 but yeah, this one can be replicated if #7839 is implemented correctly.
