### ISSUE TITLE
Revert the removal of layer from Admin Rest URLs

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7863]
- Revert the URL modifications done in https://github.com/enonic/xp/commit/1904d9dd7cf68845e8c02e54efc30b79a0a63cbc

The goal here is to have the possibility to set layer later. We will ignore this value for now in the backend.
But Content Studio should send "base" for now.

**Comment by sigdestad** [comment]
Hmm... How does this relate to the context? Shouldn't we simply use the context (repo/branch)?
