### ISSUE TITLE
No check for project permissions in ContentService

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7868]
There are currently no checks for project permissions in content API - for example, content from Default project can be fetched by user who doesn't have any permissions for this project. Please create tasks to fix this (or replace this description with correct specs).

**Comment by sigdestad** [comment]
Hmm.. Not so sure about this task..
The project permissions are primarily related to accessing projects (i.e. through content studio, issues etc). If groups, or uses have access to content, this is not related to the project permissions IMHO. For instance, how do you intend to make content available to "everyone" when "everyone" are not listed in the project access list?

**Comment by alansemenov** [comment]
We talked about using `cms.cm.app` role to give access to everyone who's supposed to have access to content. So this role can be used to give access to content from all projects. 

It's not right that users with no access to any projects can do whatever they want with content across all projects. Content Project should not be just a Content Studio feature.

**Comment by sigdestad** [comment]
Think about this once more Alan... This will not fly.

**Comment by sigdestad** [comment]
At least not without some more changes, and potentially migration scripts

**Comment by alansemenov** [comment]
Will this be solved when we implement setting CRUD permissions on root (`/content`) inside a project?

**Comment by sigdestad** [comment]
It will be better, but still - people may currently give permissions to groups/users/roles that do not have access to the project - and they still need to i.e. "everyone can read".

**Comment by GlennRicaud** [comment]
As Thomas said, Content API does not deal with ProjectPermissions. Actually Content API does not deal with permissions at all, that is done in Node layer.

But so with the current design, the blurriness here is that there was a mention of rights different from the project rights to set on the root. Should we do that now?

**Comment by sigdestad** [comment]
If this is to be done 100% - We would need to limit which idProvider / principals can be used per project. I think the default permissons is a different thing

**Comment by sigdestad** [comment]
It would definetly be interesting and useful if we could "limit" selectable "principals" within a project ( in terms of permissions etc)

**Comment by alansemenov** [comment]
Closing this until we decide how/when/if we want to check project permissions in content service
