### ISSUE TITLE
Archived dumps

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7871]
Proposed by @diegopasten. Supported by @mortyeriksen 

We use too much space with moving around dumps. As Diego said, we use 3 times the data: (Index/Blob + Dump + Archive of the dump in order to transfer it somewhere)
Proposition: The dumps could be directly archived (tar?)  (Actually parts of the dumps are already archived as tar) as the logical step after is to transfer it somewhere

I set this with milestone 8.0 and add it to the 8.0 wishlist

**Comment by rymsha** [comment]
related #7312 ?

**Comment by GlennRicaud** [comment]
Very related :+1: 

The idea of the process is that there is a PAB every 2 weeks and to dedicate some time before PAB meetings to handle "New Issues".

Was not done for the last PAB in september and there has not been any PAB since, so the new issues have started to pile up.
I will try to look at them before the end of the month

**Comment by sigdestad** [comment]
Imho this is nor really breaking. Think dumps should be streamed directly to/from an archive by default (or with a flag to use uncompressed)

**Comment by sigdestad** [comment]
Also, we had pab in December https://discuss.enonic.com/t/roadmap-update-december-2019/2043

And another in januar where roadmap was unchanged.

**Comment by GlennRicaud** [comment]
I do not remember being at these meetings. Must be my memory then.

True that it is not really breaking. Good then. I let you choose the priority

**Comment by rymsha** [comment]
dupliate #7312
