### ISSUE TITLE
MediaSelector doesn't respect <allowContentTypes>

### ISSUE THREAD

**Issue by tajakobsen** [enonic/xp#7889]
This issue has been found in Enonic XP 7.2.1 on Ubuntu.

I have the following xml:

```xml
<input name="reports" type="MediaSelector">
  <label>Related reports and documents</label>
  <occurrences minimum="0" maximum="50" />

  <config>
    <allowContentTypes>media:document</allowContentTypes>
    <treeMode>true</treeMode>
    <showStatus>true</showStatus>
    <hideToggleIcon>true</hideToggleIcon>
  </config>
</input>
```
I wanted to only be able to select content of type `media:document`.

But when adding content, Images (of type `media:image`) show up in the picker, and I can select the images.

**Comment by alansemenov** [comment]
Looks like a bug. Thanks for reporting this.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/doc-xp #121](https://github.com/enonic/doc-xp/issues/121) via [**ZenHub**](https://www.zenhub.com/)
