### ISSUE TITLE
Content Layer - Step3 - LayeredNodeService

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7893]
- The goal is to create a service wrapping the NodeService and used by ContentService.
  - Create this service in core-content module
- Call the Node service methods
  - For calls that modify node (create/update/move/...), sets the node tag: ``com.enonic.cms.layer={layerName}`` before forwarding the call to the node service

**Comment by sigdestad** [comment]
Any reason why this is not implemented directly in content service layer? i.e. Is it likely that any other code would use layers directly?
