### ISSUE TITLE
Content Layer - Step2 - Node tags

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7894]
- Create a new field on Node
  - tags: NodeTags
- A NodeTag has the following field:
  - value: String
- NodeTag value format: [A-Za-z0-9\.-_]+

- Adapt the storage of Node
- Node tags will also be stored in the branch and version ES documents
- Adapt the Node API
- Include node tags in NodeComparison

**Comment by sigdestad** [comment]
Hmm, is this nodetags or versiontags? Also, why would we index them in branch?
