### ISSUE TITLE
Exception when current user has no permissions for a newly created project

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7896]
1. Log in as super admin and create a user who has permissions for the Default project, but is not a sys.admin or cms.admin
2. Open a new browser window, log in as that new user and open Content Studio. Context is now Default project.
3. In the first window (where you are logged in as super admin) go to Content Studio settings page and select "New"
4. Fill in the form for the new project and make sure that the user from step 2 does NOT have permissions for the new project
5. Save the project

There's an exception in the log and error popup in the 2nd window saying that user doesn't have permissions for the new project. Apparently we're trying to refresh the project selector, but if current user doesn't have permissions for the new project then simply nothing should happen and no errors/notifications given.

![image](https://user-images.githubusercontent.com/11612490/75046623-bf1f2000-54c5-11ea-9f16-84cd13a2d087.png)

![image](https://user-images.githubusercontent.com/11612490/75046432-5a63c580-54c5-11ea-998d-496a705ea0fc.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio #1527](https://github.com/enonic/app-contentstudio/issues/1527) via [**ZenHub**](https://www.zenhub.com/)
