### ISSUE TITLE
Content Layer - Step4 - Create/Update/Delete layer

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#7914]
* In Project Service, for the method createLayer
  * Create branches "draft-{layerName}" and "master-{layerName}"
  * Push all current contents (not the issues, so basically everything under /content) from the parent to the new draft child branch
    * Inspiration: https://github.com/enonic/xp/blob/epic-contentlayer/modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/repository/RepositoryServiceImpl.java#L150
* In Project Service, for the method deleteLayer
  * A layer with a child layer cannot be deleted
  * Delete branches "draft-{layerName}" and "master-{layerName}"

**Comment by sigdestad** [comment]
Maybe (LAYER)-draft / master would be smarter? Listing branches would group them together?
