### ISSUE TITLE
Delete launcher-ui

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#7927]
there is a swing application in XP which could run XP from UI. "Nobody"  knows about it but it is full of legacy code.

Should be deleted.

**Comment by sigdestad** [comment]
Go for it :-)

**Comment by rymsha** [comment]
To eliminate confusions:
launcher-ui is similar to ordinary launcher, except that it starts a **desktop application** to "control" XP startup. It doesn't seem to work properly either: it doesn't read jetty port properly (always falls back to 8080). It also assumes that jetty binds on localhost.

**Comment by rymsha** [comment]
![image](https://user-images.githubusercontent.com/2891483/76200069-445a4280-61f1-11ea-8459-eb9bff9d736a.png)
