### ISSUE TITLE
Implement special handling of permissions for the default project

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7942]
We now check project permissions to determine read/modify access to projects (according to [this](https://github.com/enonic/xp/issues/7840)). We should exclude the default project from this check, as it will have special handling of permissions:

* **create**: not relevant (default project always exists)
* **delete**: not allowed
* **modify**: `system.admin` OR `cms.admin`
* **get**: `system.admin` OR `cms.admin` OR `cms.cm.app`
* **list**: `system.admin` OR `cms.admin` OR `cms.cm.app`

**Comment by vbradnitski** [comment]
implemented in #7970
