### ISSUE TITLE
Check project permissions via project roles

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7944]
We now store permissions in project meta-data:

![image](https://user-images.githubusercontent.com/11612490/76078050-2f3ba480-5fa2-11ea-8c7a-e76ef69bba89.png)

Since we will now store permissions by [assigning principals](https://github.com/enonic/xp/issues/7943) to project roles, we should change how we check permissions to verifying if the principal has correct role instead.

For example, if user has a role `cms.project.<project-name>.contributor`, he's the **contributor** of the project and can _get_, _list_. If user has a role `cms.project.<project-name>.owner`, he's an owner and can _get_, _list_, _modify_ and _delete_.

After that, clean up storing `permissions {}` in project meta-data.

**Comment by rymsha** [comment]
> After that, clean up storing permissions {} in project meta-data.

The idea was to try out both approaches during development to see if there is no performance and functional degradation

**Comment by alansemenov** [comment]
We already have current implementation in the master, if we want to compare. But I guess we can wait with the cleanup.

**Comment by vbradnitski** [comment]
implemented in #7970
