### ISSUE TITLE
Management of READ access to project

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7945]
* If the project has **Private** READ access, remove permissions for `system.everyone` on `/content` node and remove all principals from the `cms.project.<project-name>.viewer` role
* If the project has **Public** READ access, give READ permissions to `system.everyone` on `/content` node and remove all principals from the `cms.project.<project-name>.viewer` role
* If the project has **Custom** READ access, remove permissions for `system.everyone` on `/content` node and add selected principals to the `cms.project.<project-name>.viewer` role

See description of the frontend task [here](https://github.com/enonic/app-contentstudio/issues/1586) 

NB! This doesn't affect default project.

**Comment by rymsha** [comment]
Strictly speaking, number 2 can be simplified to:
 - If the project has Public READ access, give READ permissions to system.everyone on /content node

Because we are using permissive model here,
it is actually more consistent.
And in this case taking back public access (if it was given by misstake) gives back previously set custom access.

**Comment by alansemenov** [comment]
I'm not so sure about that. We can do that but this will require special handling in the UI. 

Here's a case:
1. Project is set to Custom access with one user allowed access
2. Project is changed to "Public" and saved. We are keeping permissions for the user as you suggest.
3. A month later someone changes "Public" to "Custom" and suddenly the user pops up as selected option, no one will have any idea why.

If backend handles it so that whenever the project has `everyone` then no principals for the `viewer` role are returned in the data object, then it will work but I'm not sure if that is a right thing to do. We should store current state of the saved project.

**Comment by rymsha** [comment]
Custom vs Private is a UI concept. On the backend side there will be no difference!

Actually, same goes with public vs non-public: on backend side there is no such concept either. Beckend already supports setting up `Everyone` to have READ permissions on /content

We may introduce shortcuts in Admin API, if our strategy is a logic-less UI.

**Comment by sigdestad** [comment]
I think Alan is right on this one, no need to "save" the list of people that "used to" have access at one point, will only cause confusion. What we should store is this:

Public: Everyone + Project visitors (empty)
Private: Project visitors (empty)
Custom: Project visitors (with users)
