### ISSUE TITLE
Replace all Set usages of Project by List

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#7972]
make Projects.java to be a List and the other places.
check all equals/hashCode methods for Project classes (params, jsons, etc.)

**Comment by rymsha** [comment]
Most important part is to review public API classes, so we don't endup with frozen but broken API.

**Comment by rymsha** [comment]
For domain objects in XP (like Project is) defining equality is impossible without context.
 - In one case two instances are equal if all fields are equal.
- In another they are equal if their ID fields are equal.

But without well defined equality one cannot add a class instance into a HashSet (or keys of HashMap)
If one can't compare two objects (to tell which project is less then another one) without context it is not possible to add them to TreeSet.

So, one almost never (if ever) need to write equals/hashcode for such classes.
And don't out them into Set. Use List.

But ProjectId, for ex., is another story: one must define equals/hashcode and make class final.
