### ISSUE TITLE
Set correct display name on project roles

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7973]
When a new project is created or an existing project is modified, we should set correct display name on project roles so that they are understandable in the UI. As of now, display name is the same as project path.

`cms.project.projectName.owners`: "`<Project display name>` _- Owners_" (for example _"My Project - Owners"_)
`cms.project.projectName.editors` - "`<Project display name>` _-Editors_" (for example _"My Project - Editors"_)

and so on.

If display name of an existing project changes, display names of its roles should be updated as well.

![image](https://user-images.githubusercontent.com/11612490/77525079-bf298b80-6e88-11ea-8345-5f990735a1bb.png)

**Comment by sigdestad** [comment]
Do we want to include quotes in the middle of the text? How about "My project - Editor" instead. Also, we could use special icons for these roles

**Comment by alansemenov** [comment]
Project's display name can contain any kind of weird characters. Quotes are a good way to wrap it. Dash can work too I guess, but we should expect roles like "Tine - NO - Editors", "Tine - SE - Editors" etc.
