### ISSUE TITLE
Update language property on /content node when project is created/modified

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7975]
When a project is created or modified, update `language` property on `/content` node of the project (`draft` branch) with selected value. If value is empty, remove the property.

**Comment by rymsha** [comment]
don't we call this property `locale` ?

**Comment by alansemenov** [comment]
No, it's called `language`

<img width="1029" alt="Screenshot 2020-03-26 at 16 57 14" src="https://user-images.githubusercontent.com/11612490/77667854-04ca7f00-6f83-11ea-8ca0-68c72ba04f8b.png">

**Comment by rymsha** [comment]
Oh , I see this property exists for ages now.
