### ISSUE TITLE
Default project language

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7977]
We will enable selecting default language for a project. Selected language will be stored as a property of `/content` node. If a default language is set, a new content created in the root (child content of `/content` node) will be automatically assigned this language.

**Comment by rymsha** [comment]
I really missed discussion of it.
- It should be locale, not language (if you want to put values like `no-NO` there)
- Isn't it a layer functionality do define locale?

**Comment by alansemenov** [comment]
> It should be locale, not language (if you want to put values like no-NO there)

We cannot rename existing property, it will break stuff. And it's always been called "Language" in the UI too.

![image](https://user-images.githubusercontent.com/11612490/77670573-ae5f3f80-6f86-11ea-8fc0-516e6475b2c5.png)
