### ISSUE TITLE
Allow creation of issues for project roles

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#7986]
We seem to require `role:cms.cm.app` to create issues. This is ok for default project but for other projects we should instead require at least one role of the current project (of course `system.admin` and `cms.admin` should still be able to create issues).

To reproduce:
1. Create a user with `system.admin.login` role
2. Create a project (or open an existing one) and give this user any project permission (f.ex. Author)
3. Log in and open Content Studio
4. Create a folder in the root, mark it as ready
5. Click "Request Publishing" in the toolbar
6. Complete the wizard

![image](https://user-images.githubusercontent.com/11612490/78002827-0d7ed480-7338-11ea-8186-d70a640256c2.png)

![image](https://user-images.githubusercontent.com/11612490/78002939-3606ce80-7338-11ea-9fd5-01112be1dac0.png)

**Comment by rymsha** [comment]
If I remember right `viewer` should not be able to create issues. It was the only difference from contributor currently.

**Comment by rymsha** [comment]
TBD :

Management of permissions on /issues node inside a project will be done via management of Project Permissions with exception of the Default project/repo which will keep current permissions for its /issues node.

When a new project is created, the system will automatically create 5 new roles:
cms.project.<project-name>.viewer
cms.project.<project-name>.contributor
cms.project.<project-name>.author
cms.project.<project-name>.editor
cms.project.<project-name>.owner

After that, permissions for these roles will be added to /issues node of the newly created project like this:

.viewer role
"READ"

.contributor role,
.author role
"READ"
"CREATE",
"MODIFY",
"DELETE"

.editor role,
.owner role
"READ",
"CREATE",
"MODIFY",
"DELETE",
"PUBLISH",
"READ_PERMISSIONS",
"WRITE_PERMISSIONS"

Project owner (or admins) can then manage content permissions by adding users/groups to these roles without having to update the /issues node for every change in permissions.

**Comment by sigdestad** [comment]
Why not simply handle this programmatic ally? Viewers should not have any access to issues, all other have full access?

**Comment by alansemenov** [comment]
In UI it's already like that. It's the server that prevents creation of an issue.

**Comment by rymsha** [comment]
I'm little bit confused why `contributor` and `author` should have "READ_PERMISSIONS", "WRITE_PERMISSIONS" on /issues @sigdestad

**Comment by rymsha** [comment]
> Why not simply handle this programmatic ally?

In practice that would mean that one with `contributor` role could use node-lib to modify issues.

**Comment by sigdestad** [comment]
Basically, anyone with a "project role" should be able to fully manage issues, and I don't think we should use node-level permissions for this, just handle via issues API.

**Comment by rymsha** [comment]
@sigdestad 

> Basically, anyone with a "project role" should be able to fully manage issues

does "viewer" role fall into "project role" ?
