### ISSUE TITLE
Set project language for new content items with no language

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8008]
When a new content is created, it inherits language from its parent content. If the parent doesn't have language it won't be set for the child either. Fix it so that if parent doesn't have language but current project does, then the project language is used for the new child content.

**Comment by rymsha** [comment]
IMO, this is a break of "Law of Dementer".
Why do we need this surprising requirement?

**Comment by alansemenov** [comment]
What requirement? We don't require anything. We implemented default project language so that users wouldn't have to remember to set it every time for new content.

**Comment by sigdestad** [comment]
Missing language has been a problem for a while now. Setting it improves indexing with stemming amongst others

**Comment by rymsha** [comment]
"Set project language for new content items with no language" - is a "functional requirement", so yes we do require it, in a way :)

Enough "Casuistry". What I wanted to argue about is that for all repositories with we already set language on `/content` #7977 . So, in most cases language will be effectively set when Project is created from scratch.

**Comment by sigdestad** [comment]
Indeed, so this is a "fix" for default repo when someone actually sets a language

**Comment by rymsha** [comment]
In default repository most affected content is existing one, not new. So, when we set language on default repository we should ask if this should be applied on all content without language. Similarly how we do it with "Everyone" principal.

**Comment by sigdestad** [comment]
Yes, but this is a much nigger task

**Comment by alansemenov** [comment]
I hope it's a typo 😂

**Comment by rymsha** [comment]
> Yes, but this is a much bigger task

Not big enough to introduce a "hack":
1. "Law of Demeter" is violated because when language is not set "create_content" method need to ask a Project of its language. Well, it could be implemented as a traversal to a `/content` node, but it is still a violation of the same "law".

2. "Principle of least astonishment" is violated as well, in my opinion: if content `is new` and `no language provided` and `parent has no language` and `content root node has language` then get language from...

And it doesn't solve existing content language-less problem - probably the most important case for existing users.

**Comment by alansemenov** [comment]
I don't really understand what this discussion is about... 

We are implementing a default project language to make sure that users don't have to remember to set language for every new content. This is a new feature which will obviously affect the way content is created - that's why we have implemented it, to simplify procedure of content creation for web editors. If content's parent doesn't have language it's only natural that it will fallback to default language of the project. 

Should we then also not preset language for new content in the default project's root - because people are used to that new content in root doesn't have language?

**Comment by rymsha** [comment]
If you need to web editors user experience - implement it only for web editors. In gui. Don't spoil content API

**Comment by alansemenov** [comment]
It doesn't say anywhere that the API should be changed. It's perfectly fine if it happens only in CS.

**Comment by rymsha** [comment]
If it is CS only (which I prefer), then issue should be in a different repository. 

It also should be emphasized in the "New dialog" that language is selected from the Project
> because people are used to that new content in root doesn't have language

**Comment by alansemenov** [comment]
No, it should be here. It's not CS that will set the language (because create content + set language will result in 2 versions instead of one). It's the `/create` call from CS that will create a content **with** language and serve it to the client. Content API (like `contentLib.create`) should probably work as before, since we agreed that projects are CS-specific feature.

**Comment by rymsha** [comment]
aren't we talking about this one?
![image](https://user-images.githubusercontent.com/2891483/78656562-e0966880-78c7-11ea-9519-faa89e35eea4.png)

so, GUI can pre-select language. And no need to generate two versions.

**Comment by alansemenov** [comment]
Postponing this until later
