### ISSUE TITLE
Edit Permissions dialog does not open after deleting a project role

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#8032]
1. Create a project 
2. Navigate to just created project and add a folder .
3. Go to Users and delete a role that was created with the project.
4. Go to CS , select the folder and click on `Edit Permission`  

BUG:  Edit Permissions dialog does not open, warning message appears

![image](https://user-images.githubusercontent.com/3728712/79747012-9ffd0d00-8313-11ea-8942-030eecfd9120.png)

**Comment by rymsha** [comment]
What is an expected behavior?
IMO this one is quite expected.

related to #8031

**Comment by alansemenov** [comment]
@rymsha Expected behaviour is the same as when deleting regular (non-project) role - that dialog opens without errors but permissions for the deleted role are not shown. @vbradnitski has more details on this one.
