### ISSUE TITLE
Rename zip to archive for dump/load

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8038]
#7312 implemented zipped dumps/loads. But "zip" as an endpoint parameter is not the best choice.
Change it to "archive"

**Comment by sigdestad** [comment]
Sergey, also curious if "load" needs to take this parameter. Can't it just load from what is available, and poritize zip if it exists?

**Comment by rymsha** [comment]
Reasons to do it like it was done:
- nothing stops people from calling a folder `dump-123.zip` . So checking just filename is not sufficient. 
- `dump-123` folder and `dump-123.zip` file can coexist in `data/dump` folder. So I would have to introduce preferences. And zip file won't be winning for backwards compatibility.
- I was hoping to make `archive` and `dumpName` mutually exclusive. But bumped into a sad fact: datatoolbox creates archives with folder inside called after `dumpName` (`dump-123.zip` contains `dump-123` folder as a first entry). So, I replicated the same structure for new zip archives as well.
- it is symmetric for dump/load.
- dump/load endpoints are not for end consumers. One must have GUI or CLI to call them. Some "smartness" could be put there instead.

All in all, the simplest and unambiguous solution was to leave `dumpname` parameter and introduce one more parameter called `archive`.


Others do the same. For example mongodb: https://docs.mongodb.com/manual/reference/program/mongorestore/#cmdoption-mongorestore-archive
