### ISSUE TITLE
localhost:8080/hello-world returns 404

### ISSUE THREAD

**Issue by nilankamanoj** [enonic/xp#8047]
I have created enonic project **hello-world** site. the content studio shows site URL as **/hello-world**
But when browser calls **localhost:8080/hello-world** it returns 404 error log from enonic server.

How to fix this issue?

**Comment by sigdestad** [comment]
Hi, this is not a bug, please post your questions on our forum https://discuss.enonic.com. Correct URL is probably http://localhost:8080/site/default/draft/hello-world
