### ISSUE TITLE
Deep pagination fails for repositories with more that 8M versions

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#8051]
Response error: ` {
{
  "status": 500,
  "message": "Search request failed after [30s], query: [{\n  \"from\" : 8122000,\n  \"size\" : 1000,\n  \"query\" : {\n    \"filtered\" : {\n      \"query\" : {\n        \"match_all\" : { }\n      },\n      \"filter\" : {\n        \"range\" : {\n          \"timestamp\" : {\n            \"from\" : null,\n            \"to\" : \"2020-04-23T09:14:57.236Z\",\n            \"include_lower\" : true,\n            \"include_upper\" : true\n          }\n        }\n      }\n    }\n  },\n  \"explain\" : false,\n  \"fields\" : [\"versionid\", \"timestamp\", \"nodepath\", \"nodeid\"]\n}]",
  "context": {
    "authenticated": true,
    "principals": [
      "role:system.admin",
      "role:system.admin.login",
      "role:system.authenticated",
      "role:system.everyone",
      "user:system:su"
    ]
  }
}`

**Comment by rymsha** [comment]
in 7.x it was addressed by #7139
