### ISSUE TITLE
Content Studio with a lot of content is unstable on Hazelcast Cluster 

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8064]
When there is a lot of content requesting more and more nodes in content tree freezes (showing spinner). There is an error in browser console.

**Comment by rymsha** [comment]
k8s cluster has request rate limit set on ingress.
As soon as it is removed this issue cannot be reproduced.

**Comment by sigdestad** [comment]
So, solution is to have this as a configurable option for "routes" - or rewrite CS?

**Comment by rymsha** [comment]
Solution was do disable (as it is by default) rate limits on ingress.
