### ISSUE TITLE
Possible to upload an attachment of unallowed type in selectors

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8075]
In ImageSelector and MediaSelector we define file extensions that are allowed to be selected in the native file browser dialog. It's possible to work around this restriction by switching from "Customized Files" to "All files" and select ANY file, which will then be uploaded even though it might be of incorrect type, not supported by this selector.

Since we cannot do anything about this behaviour in the native dialog, we should have an additional check/filter on the server which will verify uploaded file against allowed types for the input type.

![image](https://user-images.githubusercontent.com/11612490/81684561-5c4f7c00-9457-11ea-8f4d-04fd4360bbbc.png)

![image](https://user-images.githubusercontent.com/11612490/81684944-c23c0380-9457-11ea-8816-70c5b139a896.png)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #1345](https://github.com/enonic/lib-admin-ui/issues/1345) via [**ZenHub**](https://www.zenhub.com/)
