### ISSUE TITLE
Audit logs appear to always be created as "anonymous" user

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#8079]
https://enonic-community.slack.com/archives/C73JLM8E7/p1587987894074000

Investigations seem to confirm this. This is a major error and should be corrected as soon as possible.

**Comment by sigdestad** [comment]
Apparently, user seems to be correct for latest 7.3 build. Verify if this has been fixed for 7.3

**Comment by alansemenov** [comment]
Relevant for 7.3-B1 at least

![image](https://user-images.githubusercontent.com/11612490/82561506-cb258700-9b73-11ea-8700-7862f1e1fb71.png)
