### ISSUE TITLE
change to mavenCentral

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8087]
Currently we use only jcenter only. When it is down artifacts don't get downloaded.

There are better options:
1. Add mavenCentral as well as a second choice (or first ) - the simplest option
2. Use our our own artifactory as a mirror - this may give the best performance, but quite complicated to setup.

**Comment by rymsha** [comment]
we could not create a new release because jcenter kept returning 502 (Bad Gateway) error

**Comment by alansemenov** [comment]
@jsi check if we are using Maven as fallback for JCenter for XP release.

**Comment by rymsha** [comment]
we don't

**Comment by jsi** [comment]
I have not done this task yet, but I can do it right away.  It is really simple.  Should I do it for all apps as well?

**Comment by rymsha** [comment]
Please, don't rush. We had only one incident so far.

**Comment by jsi** [comment]
Ok.

**Comment by rymsha** [comment]
Second time jcenter returns bad gateway

**Comment by rymsha** [comment]
RIP JCenter
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

We need to change to mavenCentral everywhere

**Comment by rymsha** [comment]
asciidoctor plugin used in our doc repos (the version we use) exists only in jcenter.
