### ISSUE TITLE
Wrong message when insufficient permissions to change project access mode

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#8129]
**Case 1  - User is Editor**
1. Create a project(Private access mode) and create new user(Administration Console Login) 
2. Select in the project new created user as `Editor` 

this user has 2 roles now : 
![image](https://user-images.githubusercontent.com/3728712/83856720-a9570300-a722-11ea-8ab1-7c17eeec71f5.png)

3. Log in with the user and open this project 
4. Update access mode to public
5. Save button is disabled - OK
6. Click on close icon and try to close  the project wizard. Confirmation Dialog appears - click on Yes button

BUG:  Access mode is updated after Yes was clicked in Confirmation Dialog  

![image](https://user-images.githubusercontent.com/3728712/83857204-4fa30880-a723-11ea-8e63-6c145d545c8e.png)

**Case 2 - User is Contributor**

Do steps from Case 1 , but with `contributor` user
BUG: Access mode is not updated , but  error notification message appears:

![image](https://user-images.githubusercontent.com/3728712/83857705-0a330b00-a724-11ea-8fcf-69a1d9072ef2.png)

**Case 3 - Login with user that has Author role**
- Open the project and update a language.
- Click on Close icon  then click on Yes butoon

**BUG: User with Author role should not update the language**

**Comment by rymsha** [comment]
Partially (about confirmation dialog) it is a GUI bug in CS @alansemenov

**Comment by alansemenov** [comment]
Confirmation dialog will be solved in https://github.com/enonic/app-contentstudio/issues/1916

**Comment by vbradnitski** [comment]
All these issues are not actually bugs, this kind of behavior is expected, but there is a wrong message in case 2, will be fixed.
