### ISSUE TITLE
Link to issue details is missing project context

### ISSUE THREAD

**Issue by ashklianko** [enonic/xp#8132]
@alansemenov commented on [Fri Jun 05 2020](https://github.com/enonic/app-contentstudio/issues/1918)

When an issue is created we send out an email with issue details which contains a link to open the issue in the browser. This link is now missing the project context and user has to choose one after clicking the link.

**Comment by rymsha** [comment]
Isn't it breaking change? Because now old CS won't find issues. Also all previously sent emails are invalid...

**Comment by sigdestad** [comment]
Which is why we call it CS 3 (and everyone should use it from xp 7.3 and newer
