### ISSUE TITLE
Content Layers

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8158]
To be PRed to branch `epic-subproject`

As a **system or CMS administrator** or **owner of a project**, I can create a sub-project inside a project. Every sub-project will have its own repository, a set of project roles and other properties of a regular project. Upon creation, a sub-project will inherit all of the content items of the parent project (separate epic). I should see a visual feedback (a progress bar or a spinner) while the sub-project and inherited content inside are being created. 

I should be able to copy properties (language, read access mode, project permissions) of the parent project into a child project in the project settings GUI.

In the GUI, projects should be represented in a tree-structure to visualise the inheritance chain.

Auto-inheritance of parent project properties will not be done in this revision.
Here are the tasks for this (not for the UI yet):
https://github.com/enonic/xp/issues/8155
https://github.com/enonic/xp/issues/8156

**Comment by rymsha** [comment]
Probably needs clarification:

> a sub-project can inherit all or selected properties

In first version "inherited" properties (default language, roles, read access) are copied to sub-project properties. After successful sub-project creation modifications of parent project properties do not affect sub-project properties.
