### ISSUE TITLE
lib-portal serviceUrl needs protocol parameter for ws:// and wss://

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#8160]
https://repo.enonic.com/public/com/enonic/xp/docs/6.15.9/docs-6.15.9-libdoc.zip!/module-portal.html#.serviceUrl
https://repo.enonic.com/public/com/enonic/xp/docs/7.3.0/docs-7.3.0-libdoc.zip!/module-portal.html#.serviceUrl
https://developer.enonic.com/docs/xp/stable/api/lib-portal#serviceurl

Perhaps name it scheme, like here:
https://developer.enonic.com/docs/xp/stable/framework/http#http-request

**Comment by ComLock** [comment]
I thought there used to be some parameter for http and https, but I guess that is automatic from context?

**Comment by rymsha** [comment]
https://discuss.enonic.com/t/give-portallib-serviceurl-option-to-create-websocket-urls-too/2372/2

**Comment by sigdestad** [comment]
I guess customising protocol should be an option for all URL functions, so make this task cover all of them.

**Comment by rymsha** [comment]
There are only 4 schemas portal supports `http`, `https`, `ws`, `wss`

And if page is on `https://` , websocket should be `wss://`
I can't imagine a (non academical) case where `https://` page would want to provide a link to `http` or `ws`  especially when we are dealing with the same site.

There is an optional `type` parameter already. we can extend it with `websocket` value - that would generate a `ws(s)` absolute url.
