### ISSUE TITLE
lib-websocket.getGroupSize('groupName')

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#8163]
I have an event listener which pushes data over a websocket group whenever some specific nodes are created, updated or deleted. It would be nice to skip doing any work inside the event callback if there are no "subscribers" in the websocket group. Thus beeing able to get how many "members" there are in a websocket group would be useful.

Another option would be to get a list of sessionId's in a group but there might be security implications with that?

**Comment by ComLock** [comment]
@alansemenov mentioned that this NPM has clients.size https://github.com/websockets/ws

**Comment by rymsha** [comment]
calculating size of a group has a linear cost from total number of sockets.
Consider using this method only if building a message is a resource consuming operation, overwise it is better to simply `sendToGroup`
