### ISSUE TITLE
Application display name does not support ØÆÅ only \u00E6\u00E6\u00F8\u00E5\u00E6\u00F8\u00E5

### ISSUE THREAD

**Issue by poi33** [enonic/xp#8164]
Application display name:
![image](https://user-images.githubusercontent.com/3340349/85112206-927dd980-b215-11ea-8577-95ccb1483524.png)

Gradle properties:
![image](https://user-images.githubusercontent.com/3340349/85112250-a1648c00-b215-11ea-9bbd-9b511fcc681a.png)

**Comment by rymsha** [comment]
have you tried `appDisplayName = \u00E6\u00E6\u00F8\u00E5\u00E6\u00F8\u00E5` ?

**Comment by poi33** [comment]
Do i have to do unicode encoding and decoding by hand?

**Comment by alansemenov** [comment]
I hoped it was a joke...

**Comment by rymsha** [comment]
> Do i have to do unicode encoding and decoding by hand?

You don't have to if:
- your IDE does it for you
- or you know how to configure Gradle to do it for you

Welcome to the world of legacy.

**Comment by rymsha** [comment]
@poi33 have you tried it? Does it fix the issue?

**Comment by rymsha** [comment]
This is what Gradle does. Don't store app name in properties file, or encode symbols according to properties file format.
