### ISSUE TITLE
Repository attachments get lost after loading a dump

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8208]
Similar to #8191 but less critical an not as easy to fix.

Root cause of an issue: dump-load and import jobs use high level API RepositoryService to recreate repositories, but has to bypass a few constraints RepositoryService has:

There is no method in RepositoryService to create a repository with an attachment. It can only be added to exiting repository.
When one has a repository she can provide a BinaryAttachment - and repository gets updated with it.

Dump load doesn't have BinaryAttachments. All it can operate with is Nodes (which have AttachedBinaries instead).

Correct fix of this issue would be to NOT call RepositoryService from DumpService and work on a lower level there.

It would be beneficial as it would allow to implement features like #8188

**Comment by jsi** [comment]
This error is very obvious when moving data from production to QA:

<img width="324" alt="Screenshot 2020-07-27 14 33 59" src="https://user-images.githubusercontent.com/477453/88545575-75f66d80-d01b-11ea-9074-8da1c179363c.png">

Four out of five project logos are not present after dumping all data from production and reloading them into QA.

**Comment by alansemenov** [comment]
@rymsha @vbradnitski we have to fix this bug for the 7.5 release, it's now all over the place.
