### ISSUE TITLE
Improve error message when XP cannot find a submitted task

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8275]
We had a bug in the docs of the Tasks engine where "`tasks`" folder was named "`task`":
![Screenshot 2020-08-12 at 11 55 34](https://user-images.githubusercontent.com/11612490/90002374-ded41b80-dc92-11ea-81b0-c46fd4a67411.png)

 If you follow this, name the folder "`task`", create a task there and try to submit a named task, you'll get an exception that looks like this:

```
2020-08-12 11:33:59,331 ERROR c.e.xp.lib.task.SubmitTaskHandler - Error executing task [f095533e-af4d-4dd3-b07d-eb7557b3fba8] '': java.lang.IllegalArgumentException: No mapping defined for property hostname with value https://collicare.fotoware.cloud
jdk.nashorn.internal.runtime.ECMAException: java.lang.IllegalArgumentException: No mapping defined for property hostname with value https://collicare.fotoware.cloud

```

Instead of giving a message that says something like "`Task <task-name> is not found`" the engine complains about failed mapping of the task config. This is very confusing for the user who thinks the problem lies in the incorrect XML config scheme.

**Comment by rymsha** [comment]
#8486 fixed it.
