### ISSUE TITLE
Unable to modify content of media type

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#8281]
Error: Value of type [com.enonic.xp.data.PropertySet] cannot be converted to [Reference]

The modify
https://github.com/enonic/app-fotoware/blob/master/src/main/resources/tasks/syncSite/syncSite.es#L282-L295

The error actually occurs before the xdata has been applied, but here is the xdata anyway.
https://github.com/enonic/app-fotoware/blob/master/src/main/resources/site/x-data/fotoWare/fotoWare.xml

**Comment by ComLock** [comment]
[Freight from LT to NO.pdf](https://github.com/enonic/xp/files/5084315/Freight.from.LT.to.NO.pdf)

**Comment by alansemenov** [comment]
Fails on [this SVG](https://github.com/enonic/xp/files/5084326/Collicare.-.web.symboler-13.zip) as well (download, change extension from .zip to .svg)

**Comment by alansemenov** [comment]
@ComLock A quickfix is to wrap field names inside quotes:

```javascript
content.x[X_APP_NAME] = {
  'fotoWare': {
    'metadata': metadataObj
  }
};
```

We are investigating why it doesn't work without quotes.

**Comment by ComLock** [comment]
So I assume since the comment is gone, you have discovered the workaround don't work? Cause it don't work for me.

**Comment by alansemenov** [comment]
Apparently that was not the (only) case, no. Investigating further...

**Comment by ComLock** [comment]
I have verified this fixed in a SNAPSHOT build of Enonic XP 7.5.0

**Comment by sigdestad** [comment]
Can we get this merged into the layers branch?

**Comment by anatol-sialitski** [comment]
> Can we get this merged into the layers branch?

this commit already exists in the epic-subproject branch.
