### ISSUE TITLE
API for fetching projects containing specified item Id

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8285]
We need an API which will return the list of projects containing specific item Id. This will be used for building the tree of projects/layers for a selected content item in the UI. As of now we have to traverse the entire project tree and call "`contentsExist`" for each level to collect all the data we need.

Data fields we need:
1) project Id
2) Id of the parent project
3) project display name
4) project/layer icon
5) project/layer language
6) item's display name
7) item's path
8) item's language
9) item's validity and workflow status
10) inherited flag

Item fields (6-10) are project-specific.
If 3-5 are problematic, they can be omitted (we'll use project info in the UI to get them), but we do need the rest of the fields.

**Comment by rymsha** [comment]
I believe it is implemented already @vbradnitski ?

**Comment by alansemenov** [comment]
Not with content data for each item.

**Comment by rymsha** [comment]
It would be better to fetch item content independently and asynchronously.
```
get projects --->
<---
get content by id 1 --->
get content by id 2 --->
get content by id 3 --->
<---
<---
<---
```
I see no benefits implementing it server side (I Consider GraphQL  )

**Comment by alansemenov** [comment]
Well, there's definitely a benefit of sending one request instead of multiple.
In the UI we will show the entire (always expanded) tree of content data in all projects and layers. Making a request for each layer will not be efficient, especially for complex structures (and we are not using graphQL in CS yet).

**Comment by alansemenov** [comment]
We concluded to not do this. Client will send one request to fetch the project/layer structure and then several parallel requests to fetch content data for each level.
