### ISSUE TITLE
Implement API for updating inherit settings of a content item

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8303]
We need a new API to be able to update inherit options on a specific content item in a specific project, so it needs the following arguments:
1) `contentId`
2) `project`
3) `inherit` (array of inherit options)

**Comment by rymsha** [comment]
Directly manipulating flags would be to permissive (if logic is actually in XP, not in CS)
It should be an API to reset inherit flags (set them back to inherit)

**Comment by sigdestad** [comment]
Indeed, this must be part of content api.

**Comment by alansemenov** [comment]
However/whatever you do it, guys. But in order to do this we need an API to be able to remove/add "_SORT_" from "`inherit`" (not reset the entire field yet - but this I guess we'll also need in the future)

**Comment by alansemenov** [comment]
I agree that directly manipulating flags is not a good idea. So if we could have APIs for `/inheritance/add`, `/inheritance/remove` and `/inheritance/reset` that would do the trick, I guess.

**Comment by sigdestad** [comment]
It would be nice to see a design for this API (javascript level) before we actually implement it. It must be somewhat flexible to support future requirements imho

**Comment by vbradnitski** [comment]
use `resetInherit` endpoint in ContentResource to get removed types back.
