### ISSUE TITLE
lib-portal.imageUrl() doesn't convert to specified image format

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8307]
By using `format` argument of `lib-portal.imageUrl()` you can specify a different format to convert the image to, see [here](https://developer.enonic.com/docs/xp/stable/api/lib-portal#imageurl).

[According to customer](https://enonic.zendesk.com/agent/tickets/3945), this stopped working after a recent release.

For example, on Enonic site PNG images are supposed to be converted to JPEG but returned format is still PNG:

<img width="693" alt="Screenshot 2020-08-27 at 14 55 17" src="https://user-images.githubusercontent.com/11612490/91444839-9bbe9e80-e875-11ea-85cb-620bf9940e59.png">

**Comment by rymsha** [comment]
Probably a regression after fix for #8004

**Comment by anatol-sialitski** [comment]
@alansemenov very important to clear cache for images before start to use it.
