### ISSUE TITLE
Dumps don't include the project icons

### ISSUE THREAD

**Issue by poi33** [enonic/xp#8363]
<img src="https://user-images.githubusercontent.com/3340349/93073543-5d055280-f683-11ea-9c23-6c00b1fb4e33.png" width="400px" />

Creating a system dump does not include the project icons/images. 
Got an error on doing the export, might be they are saved in a location the dump does not copy?

**Comment by sigdestad** [comment]
Hmm. I thought this was fixed? Maybe we need 7.4.1?

**Comment by alansemenov** [comment]
https://github.com/enonic/xp/issues/8208

**Comment by poi33** [comment]
Okay we allready have an issue on. Closing

**Comment by alansemenov** [comment]
I don't think it should be in the Backlog (aka the Black Hole) though. It's a very obvious bug which we'll have lots of complaints about when people start using the feature.
