### ISSUE TITLE
Cleanup deleted content in child layers

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8368]
When content item is deleted in parent project/layer, we should try to delete it in child layers as well.

Conditions for deleting the item in child layer are:
1. The item should be inheriting `content`.
2. The item should not have any inbound references.

**Comment by rymsha** [comment]
> The item should be inheriting data.

we don't have `data` anymore. Do you mean `content`?

**Comment by alansemenov** [comment]
> we don't have `data` anymore. Do you mean `content`?

yes, corrected

**Comment by sigdestad** [comment]
What about Child items?
