### ISSUE TITLE
Image service sets "private" cache header even for "everyone can read" images

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#8400]
Correct header in this scenario is "public". "private" shall only be used when everyone role does _not_ have read permissions.

Bug reproduced on both enonic.com (7.4.1) and 7.2.x - other customer.
This is effectively overriding CF caching.

Should be prioritized and released in both 7.4.2 + 7.5.0

**Comment by sigdestad** [comment]
NOTE: This problem might also affect attachment service. Please verify.

**Comment by rymsha** [comment]
I cannot reproduce it.
Every time image has `everyone` role read access, Cache-Control becomes public.

It looks like a content right misconfiguration:
if `user:system:anonymous` has read access, image will be available only for anonymous uses. But Cache-Control is private.

**Comment by rymsha** [comment]
Docs https://developer.enonic.com/docs/content-studio/stable/permissions#public_content are misleading

> Content without the Everyone role can only be seen by users who are logged in and have read access to it through one of the content’s principals.

There is a way to show content to _almost_ everyone - by giving anonymous access
