### ISSUE TITLE
Support configuring initial user permissions in config files

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#8406]
In the cloud, we need to set the creator of instance to be admin, regardless of what id provider we use.

**Comment by rymsha** [comment]
We don't need it anymore, do we? @gbbirkisson

**Comment by rymsha** [comment]
Id provider, as an app, does not know the id provider name (generally speaking). 
Bootstrapping can be done in a separate app,

**Comment by gbbirkisson** [comment]
I guess not
