### ISSUE TITLE
Return related projects layers in /getTree API

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8413]
We have an issue with building project/layer tree in the frontend if current user lacks access to some of the nodes. In the settings grid the tree is completely [broken](https://github.com/enonic/app-contentstudio/issues/2337), in the Layer selection dialog the tree becomes a [flat list](https://github.com/enonic/app-contentstudio/issues/2293). Both are wrong.

We need to fix the `/list` API so that it always returns all items, but for each item also returns permissions for user in the current context. We'll add an additional check in the frontend to make sure that user with no permissions cannot switch to this project/layer in the CS.

**Comment by rymsha** [comment]
What kind of security is this, if only fronted limits access?

**Comment by alansemenov** [comment]
It's not access, it's the list. In the content API we'll still have the current permissions check. We can also avoid having permissions for each item and simply have something like "hasAccess: true/false"

**Comment by rymsha** [comment]
Do you mean that user has access to see the project, but doesn't have rights to one of the content items and it results in an error?

**Comment by alansemenov** [comment]
Yes, all api requests under the project he doesn't have access to will result in an error (like now).

**Comment by rymsha** [comment]
When user can see the project in the list is described it #7840


We either:
rethink model described in #7840, 

For instance by allowing anyone `permissions.*` on any project to list the project. (it is similar to not-yet-implemented "materialized roles" feature where role would be dynamically calculated based on other conditions)

or 

fix UI so it does not break when it cannot render full tree.

For "select layer" dialog leave it as is - it is not that bad, if we don't know that projects are not connected to flatten them.

For settings grid implement flattening as well.



IMO, UI improvements would be sufficient and we don't compromise a feature where customers would want to have "secret" projects.

**Comment by alansemenov** [comment]
Fixing UI is not an option unfortunately, otherwise that's what we would've done. We have at least two places in the UI where we need this.
1. Project tree in the Settings grid. We are using TreeGrid component which will simply not work if you don't feed it the correct tree. We can disable nodes you don't have access too but we cannot avoid rendering them.
2. The Layers widget and the modal dialog where we show status of the item in all projects. The whole idea of this one is to show a user the status of this specific item in ALL layers, which he may not have access to. For example, a user working in Collicare-China should be able to see whether the item is in progress/ready/published in sibling or parent layers.

We should then implement a new "hidden" type of permissions which we will use only for these two **admin** APIs (building the tree of layers and getting content data in a specific layer).

**Comment by rymsha** [comment]
> We should then implement a new "hidden" type of permissions
A Backdoor? :) 
No, we won't agree on that.

**Comment by rymsha** [comment]
We will try to do the following:

in addition to layers `/list` endpoint we will introduce a new layers `/graph` endpoint.
- accepts projectId 
- Verifies that user has any permissions for the project (see #7840)
- if project does not exist or user has no permissions, returns 404?
- if project exists, returns entire graph [projectId -> [parentProjectId]] of this project. (mind multi-inheritance)

This is an extension to current permissions model: if user has any permissions to the project it gets the right to read dependencies graph of this project.
