### ISSUE TITLE
responseProcessors and filters break cookies

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8418]
Cookie handling in XP is broken. There is no way to properly set anything except for simple key=value cookies through XP at the moment.

"Complex" cookies have all their properties stripped, and these properties are never sent to the client

**Comment by sigdestad** [comment]
Isn't it possible to set cookies via standard headers?

**Comment by rymsha** [comment]
Yesit is, but only one cookie.
There is another bug #8404

**Comment by rymsha** [comment]
I can't reproduce it.

**Comment by rymsha** [comment]
> *ANY* response processor will cause all cookies to revert to "simple cookies" instead of "complex cookies". Even just a response processor that returns immediately:
> 
> exports.responseProcessor = function (req, res) {
> log.info(req);
> return req;
> };

**Comment by rymsha** [comment]
Filters are also affected
