### ISSUE TITLE
Moved content cannot be unpublished

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8435]
Reported in [support case](https://enonic.zendesk.com/agent/tickets/3998)

Steps to reproduce:

1. Publish a content
2. Move the content
3. Unpublish the content

Server will respond with "_Nothing to unpublish_".

Correct behaviour is to find the published version at "old" path in the master and unpublish it.

**Comment by rymsha** [comment]
related to #8559

**Comment by rymsha** [comment]
currently it looks like bug origins from CS:
There are two problems:
- For moved items it requests `getDescendantsOfContents` with empty paths
- Even if path would not be empty, moved content descendants must be enquired from master branch by contentId instead.

**Comment by rymsha** [comment]
Duplicate of #8435

**Comment by rymsha** [comment]
waiting for https://github.com/enonic/app-contentstudio/issues/2756
