### ISSUE TITLE
Add job to clean up audit log

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#8439]
Add job that cleans audit logs that are older than X days. Retention set in configuration files.

**Comment by rymsha** [comment]
We never run periodical tasks (cron like) in XP core before. Even vacuum doesn't run automatically.

It is a good app candidate that would use lib-cron.
There are some challenges:
- flexible configuration when to run (potentially heavy) cleanup job.
- implement correct "delete-by-query" mechanics (Elasticsearch 2.4 doesn't have this feature out of the box). It is OutOfMemory prone.

**Comment by alansemenov** [comment]
We have added this to our Roadmap. Has to be thoroughly analysed before we begin. Putting this to Backlog and assigning to @rymsha so that it doesn't get lost.

**Comment by rymsha** [comment]
depend on #8596

**Comment by rymsha** [comment]
- initial jobs are defined in `com.enonic.xp.sheduler.cfg` file
- if job is not in scheduler repository, new job is created, and period is read from config file (only elected master config is effective)
- if job is in scheduler repository, neither of config files is effective.

- audit-log-cleanup task descriptor should be located in app-system

**Comment by rymsha** [comment]
Implementation notes:
- audit-log-cleanup task descriptor should be located in app-system
