### ISSUE TITLE
Better errorhandling when page template is missing

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#8441]
With the new default errorpage, user only gets a 404 Doh when requesting an item that is published, but where the page template is not published. There is nothing in the logs indicating there is a problem either.

I propose we change the error-code in this case from 404 to 501 (or possibly 500), and also write a nice log entry: "Unable to render item, missing page template: <full request URL>." or similar.

**Comment by rymsha** [comment]
Related to #6844

**Comment by rymsha** [comment]
It should be general 500 error. Only log message should explain what is wrong.
