### ISSUE TITLE
Extend Management with App events

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8451]
A continuation of #8118
Implement SSE endpoint to receive global application events (started/stopped/installed/uninstalled)

endpoint should be `/app/events`

Prefer to reuse what Jetty already provides. Or, JAX.RS (Resteasy), if it speeds up development.

**Comment by anatol-sialitski** [comment]
@gbbirkisson Could you please to specify the list of properties which should be returned in the DTO when a client was subscribed to the SSE endpoint (app list)?

**Comment by gbbirkisson** [comment]
> @gbbirkisson Could you please to specify the list of properties which should be returned in the DTO when a client was subscribed to the SSE endpoint (app list)?

As you told me on slack, this has been decided. Im happy with the result.
