### ISSUE TITLE
highlight fragmentSize and numberOfFragments fails with parseInt

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#8462]
Normal int works, and int via parseInt fails with:

class java.lang.Double cannot be cast to class java.lang.Integer (java.lang.Double and java.lang.Integer are in module java.base of loader 'bootstrap')

Reproduced in all versions from 7.2.0 unto 7.5.0

**Comment by rymsha** [comment]
In a few places Java code expects Integer where JS can easily provide Double. parseInt is one of the examples where JS returns Double (despite method name)

**Comment by rymsha** [comment]
Bugs are in lib-node / lib-content 
So applications must be recompiled with newer lib versions in order to get problem fixed
