### ISSUE TITLE
xmlns in <site ...> (site.xml) forces <x-data ...> elements to be before the opening <form> element.

### ISSUE THREAD

**Issue by espen42** [enonic/xp#8501]
Using `xmlns="urn:enonic:xp:model:1.0"` inside the `<site ...>` opening element in site.xml enforces the order of the x-data element(s) within, it seems to only work if placed before `<form>`. This conflicts with recommendations in other docs.

For example (collapsed code content for clarity, in the `<form>` and `<mappings`> elements):

![image](https://user-images.githubusercontent.com/5279775/100098187-f7d99480-2e5d-11eb-9a4b-4d701fd0e777.png)
...works, while...
![image (1)](https://user-images.githubusercontent.com/5279775/100098200-0031cf80-2e5e-11eb-88a7-8665f1c49996.png)
...does not.

If the `xmlns` part is removed, the order doesn't cause any IDE warning or runtime error.

**This is not just a linting thing.** When marked red as above, it builds just fine, but then, when editing the site in Content Studio, a wild runtime error appears:

![image (2)](https://user-images.githubusercontent.com/5279775/100098342-3707e580-2e5e-11eb-868a-f6c506fb06b7.png)

**Comment by espen42** [comment]
First seen in app-superhero-blog when adding lib-menu. Reproduced by @poi33 in the enonic.com app.

**Comment by rymsha** [comment]
There are multiple x-data elements allowed according to schema:
```
  <xs:complexType name="site">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="x-data" type="xdata"/>
      <xs:element minOccurs="0" name="form" type="form"/>
      <xs:element minOccurs="0" name="processors" type="processors"/>
      <xs:element minOccurs="0" name="mappings" type="mappings"/>
    </xs:sequence>
  </xs:complexType>
```
And as soon as you are done specifying x-data elements you may specify form.

This is how things are. If documentation suggests different, let's fix the documentation.
