### ISSUE TITLE
A hint message in case of 404 on site engine

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8540]
In addition to 404  `D'oh` write a simple hint "Did you forget to publish your site?" in cases where route points to `/site/.../master/...`.

**Comment by rymsha** [comment]
@alansemenov I need a simple design suggestion

**Comment by alansemenov** [comment]
![image](https://user-images.githubusercontent.com/11612490/101907815-60917280-3bbb-11eb-863b-081f0377802d.png)

**Comment by alansemenov** [comment]
`<body><h1>D'oh!</h1><h3>404 - Not Found</h3><h4>Tip: Did you remember to publish the site?</h4></body>`
