### ISSUE TITLE
Incorrect language of a local child item created under inherited non-localised parent

### ISSUE THREAD

**Issue by ashklianko** [enonic/xp#8576]
@alansemenov commented on [Tue Dec 22 2020](https://github.com/enonic/app-contentstudio/issues/2681)

When a new child content is created under existing content, we set language of the parent on this child content.
This behaviour should be different when a child content is created under **inherited non-localised** content. In this case we should set language of the current layer on the child content.

**Comment by ashklianko** [comment]
To be fixed in `CreateContentCommand.getDefaultLanguage()`
Also I think we need CreateContentJson to also have 'language' parameter so language could be set from create request; note that `CreateContentHandler` in lib-content has language as param

**Comment by ashklianko** [comment]
If task is OK with everyone then can assign on me

**Comment by rymsha** [comment]
Too easy to break layers sync. Leave it for @vbradnitski

**Comment by vbradnitski** [comment]
> To be fixed in `CreateContentCommand.getDefaultLanguage()`
> Also I think we need CreateContentJson to have 'language' parameter so language could be set from create request; note that `CreateContentHandler` in lib-content has language as param

We can't force all lib users to set language field in every such request.
