### ISSUE TITLE
Cut seconds to zero in publish info

### ISSUE THREAD

**Issue by ashklianko** [enonic/xp#8601]
@sgauruseu commented on [Wed Nov 04 2020](https://github.com/enonic/app-contentstudio/issues/2474)

1. Open `Published` folder.
2. Press Tab key - focus set in `Online from` input

BUG: Save button gets enabled and content is modified after  tab navigation to   `Online from` input

![image](https://user-images.githubusercontent.com/3728712/98095267-65b42100-1e9b-11eb-94e5-96ccebc509af.png)

**Comment by ashklianko** [comment]
Publishing is being scheduled up to hours and minutes, but not seconds, however when publishing content without scheduling it is being saved with publish info including seconds. 
It leasds to a situation when comparing content with the same (visually) data we get unequal contents because of persisted content has publish info including seconds and viewed content has seconds part set to zero.
Please, cut seconds when saving publish info on the backend.

**Comment by rymsha** [comment]
Changing it on backend won't fix all existing data.
We concluded that the easiest is to fix it on frontend instead.
