### ISSUE TITLE
Per-asset fingerprint

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8612]
Currently assets are not fingerprinted. It is done on application level instead
`company.com/_/asset/com.company.app:235293024/path/to/asset.css`

This is a waste of resources, when assets actually don't change between application redeploy/new application version

Fingerprint could be applied on asset level:
`company.com/_/asset/com.company.app/path/to/asset.2c52a3024.css`

We can even keep old structure, but calculate has from asset

`company.com/_/asset/com.company.app:2c52a3024/path/to/asset.css`

This may require semi-breaking change on `assetUrl` function, currently it can be abused with path (required parameter) to be specified as empty string to get "base url". This should not be allowed, as we need full path to get an asset and compute its hash.

**Comment by sigdestad** [comment]
Is this task still relevant, given lib-static and other optimisations done?

**Comment by rymsha** [comment]
It depends.
lib-static does not exist, so issue is relevant until it is proved that lib-static is simply better.
"other optimizations" solve other problems really.

**Comment by sigdestad** [comment]
Hi - with lib-static live, can we close this?
