### ISSUE TITLE
Expose NamePrettyfier using a library method

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/xp#8616]
We must have the ability to use the functionality of [NamePrettyfier](https://github.com/enonic/xp/blob/master/modules/core/core-api/src/main/java/com/enonic/xp/name/NamePrettyfier.java) at many places (lib, apps and etc), therefore we should expose this functionality for instance in lib-content.

**Comment by alansemenov** [comment]
We have [sanitize]( https://developer.enonic.com/docs/xp/stable/api/lib-common#sanitize) method in `lib-common`. We should probably check what it does to see if it covers our needs. If not, we can implement a new method (`prettify`?) in the same lib.

**Comment by anatol-sialitski** [comment]
Thanks, Alan. That is enough. will close issue.
