### ISSUE TITLE
Unpublished content may become published again

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8630]
Affects version 6.15.x (latest)
https://enonic.zendesk.com/agent/tickets/4349

**Comment by rymsha** [comment]
This may happen due to vacuum.

**Comment by rymsha** [comment]
Cannot reproduce. waiting for more info

**Comment by alansemenov** [comment]
The case was most likely that an unpublished content got accidentally published as a dependency of a newer content. The logic of dependency resolution has been improved in XP7+ and it's now much easier to exclude dependencies as well. The customer who reported the case is working on upgrade to XP7.
