### ISSUE TITLE
The shebang line in scripts (sh) is not generic enough

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#8652]
Currently the shebang line expects bash in a certain location: https://github.com/enonic/xp/blob/f850ff1eb8de1c83d25fa4ba8983200b34f98e94/modules/runtime/src/bin/server.sh#L1

This does not work on irregular distributions (such as NixOS).

This should be changed to `#!/usr/bin/env bash` to be more generic. Or better yet `#!/usr/bin/env sh` to cover distrobutions that do not have bash (such as alpine). We need to make sure the script does not contain any bash specific things if we do that.

This applies to all scripts containing a shebang line.

**Comment by rymsha** [comment]
`#!/usr/bin/env sh` would require changes in script itself - for instance because "dash" does not understand subshell calls.
we stick to `#!/usr/bin/env bash`
