### ISSUE TITLE
Personal tokens support

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8668]
Personal tokens are passwords that are not intended for humans to memorize.
They are secure-random generated on demand, and shown only once to a user - when generated.
 
They can't be used for normal login, but should be used on management port for authentication.

**Comment by sigdestad** [comment]
We probably need to support it in lib-auth I guess, so any IDprovier may choose to support that?

**Comment by rymsha** [comment]
Starting from XP7.15 system-id-provider supports Bearer authentication. It is a bit more complicated and at the same time more secure.
It also protects management endpoint
