### ISSUE TITLE
The CKEditor 5 plugin track change feature. Will XP Content Studio support the plugin?

### ISSUE THREAD

**Issue by thrdcircle** [enonic/xp#8680]
Here is the documentation for the Integration but will XP allow the plugin integration with Content Stuido App?

https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/track-changes-integration

https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes-integration.html#track-changes-api

Thanks

**Comment by alansemenov** [comment]
@thrdcircle Content Studio is using CKE 4. Upgrade to CKE 5 is not possible for us at the moment due to their licensing model but we will consider this in the future.

**Comment by alansemenov** [comment]
@thrdcircle Also, feel free to leave your feature requests at [our forum](discuss.enonic.com).
