### ISSUE TITLE
Don't serve asset for webapp

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8686]
This functionality ~is not documented~ and has a few implementations issues:

- assets can easily take over request handling from webapp service, so some requests never rich `webapp.get`
- there is no control on headers (like cache, etag, etc)

Upcoming `lib-static` solves these problems and allows to customize the behavior

**Comment by sigdestad** [comment]
Well it is documented in a way: https://developer.enonic.com/guides/my-first-webapp#js_controller
In this guide, we use it directly!

**Comment by sigdestad** [comment]
Actually, it has been a request from developers to directly serve index.html files like this as well.

Perhaps a solution is a library that enables this kind of functionality, and deprecate the current model? We could easily include this library in a starter anyway.

**Comment by rymsha** [comment]
wait for XP8

**Comment by espen42** [comment]
Since it's undocumented, what's the exact asset-serving path?

**Comment by rymsha** [comment]
Webapps can also use `/_/asset/<app-name>` instead
