### ISSUE TITLE
Handle `contentType` parameter in PartDescriptorResource.getByApplications

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8691]
[PartDescriptorResource.getByApplications](https://github.com/enonic/xp/blob/a1533a8f95a152761214c3f2a6e341c7d7685039/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/page/part/PartDescriptorResource.java#L90) should support an optional parameter `contentType`. If specified, the list of parts should be filtered based on whether each part is allowed for this `contentType`.

**Comment by rymsha** [comment]
#8706 fixes it differently
