### ISSUE TITLE
Handle `contentType` parameter in LayoutDescriptorResource.getByApplications

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8692]
[LayoutDescriptorResource.getByApplications](https://github.com/enonic/xp/blob/a1533a8f95a152761214c3f2a6e341c7d7685039/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/page/layout/LayoutDescriptorResource.java#L71) should support an optional parameter `contentType`. 

If specified, the list of layouts should be filtered based on whether each layouts is allowed for this `contentType`.

**Comment by rymsha** [comment]
#8706 fixes it differently
