### ISSUE TITLE
Widget admin endpoint

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8732]
Our documentation [says](https://developer.enonic.com/docs/xp/stable/runtime/engines/admin-engine) that widget endpoint is at `/admin/widget/<app-name>/<widget-name>`. 

However, this is not true ([this](https://qa.enonic.com/admin/widget/com.enonic.app.contentviewer/contentviewer) doesn't work). Currently the endpoint is `/admin/site/admin/<project-name>/<branch-name>/<app-name>/<widget-name>` ([this](
https://qa.enonic.com/admin/site/admin/default/draft/_/widgets/com.enonic.app.contentviewer/contentviewer) works). 

Admin tool endpoint is still the same as in the docs.

What was the reason the widget endpoint was changed? `admin/site/admin` looks strange (I didn't find any other admin endpoints with this pattern) and there's no reason to have it under `<project-name>/<branch-name>` since we pass repositoryId and branch as parameters to a widget.

**Comment by rymsha** [comment]
It was maybe true for XP 6.15 what documentation describes (widgets was experimental feature), but in XP 7 widgets migrated under `/admin/site` So what documentation describes was never true for XP7


extra `admin` in path is a "render mode". Certainly confusing, but hard to avoid without breaking anything.


Widgets are not useful without data. "repository/branch" is a common way (in XP endpoints) to select data root.
So, the endpoint we have now makes them different from admin tools, otherwise widgets would be just another way of writing admin tools.


My conclusion: it is a documentation bug.

**Comment by alansemenov** [comment]
> extra admin in path is a "render mode". Certainly confusing, but hard to avoid without breaking anything.

Why would we have such a special url (/admin/site/admin) **only** for widgets? Having this under `/site/` is 100% wrong because widgets don't have anything to do with sites specifically.
And what is "render mode"? We are not using this type of url for anything else, as far as I can see. Preview (which is also rendering) is using a different url. Page editor is also using a different url.

> Widgets are not useful without data. "repository/branch" is a common way (in XP endpoints) to select data root.

As I mentioned, we pass repository and branch to widgets via url arguments, we don't need this to be in the context.

**Comment by rymsha** [comment]
such behavior is since year 2015. Even if it is 100% wrong changing it would break many widgets. 
It was an attempt to correct things a bit, but it was abandoned #5203

**Comment by sigdestad** [comment]
The widget path should be /admin/_/widget/<appname>/<widgetname>

Technically widgets should be able to use any prefix before /_ to provide optional context.

I can explain in a meeting

**Comment by alansemenov** [comment]
We already provide a widget with info about contentId, branch and repository so I don't see why the endpoint should be under `/site`. But if it's always been like that, fine. Closing this.
