### ISSUE TITLE
lib-task submitTask/executeFunction method rename

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8752]
`submitTask` substitutes and deprecates `submitNamed`
`name` (in `submitNamed`)-> `descriptor` (in `submitTask`)

`submit` -> `executeFunction`

**Comment by rymsha** [comment]
Consider `runFunction` instead of `runLocal`

**Comment by sigdestad** [comment]
Will it run any "function", or only "tasks"?

**Comment by sigdestad** [comment]
If it only runs tasks, and if it is part of task API, why not simply call it "run"?

**Comment by vbradnitski** [comment]
We used to call it task, but it's actually just a js-function can be set there:
 `setTask( final Function<Void, Void> taskFunction )`

**Comment by rymsha** [comment]
> Will it run any "function", or only "tasks"?

**Comment by alansemenov** [comment]
@sigdestad this is becoming a blocker. can we agree on the name here?

**Comment by sigdestad** [comment]
So, it will run any function, and it only runs on the local node?

submitTask() submits task for execution in cluster
Here are my suggestions for the Background task/function executor
Detach() 
Async() 
Execute() 
Run()

**Comment by sigdestad** [comment]
Since this is already in the task lib, maybe we could name "submitTask()" simply submit() also?

**Comment by sigdestad** [comment]
And go for run() for the local version?

**Comment by rymsha** [comment]
> submitTask()" simply submit()

**Comment by rymsha** [comment]
> submitTask()" simply submit()

Not possible. `submit` is already occupied with what we are trying to give a better name.

"Local/clustered" - words are confusing, as it is not always an XP cluster
"Detach" - "C++" term for threads, but means a different thing.
"Async" - will be sooo confusing for JS developers, because behavior is totally different.
"Run" - gives headache for Java developers, as they used to see `Thread.run` (and it differs from `Executor.execute`)
"Execute" - might be a good candidate, actually, but why would we call one `execute` and another `submitTask`...?

We also have to consider how Java API looks like (and hopefully we can make two APIs look more similar)

```
public interface TaskService
{
    TaskId submitTask( RunnableTask runnable, String description ); <--- in JS "submit" wraps it, but does a lot of conversion as well.

    TaskId submitTask( DescriptorKey key, PropertyTree config ); <--- in JS "submitNamed" (yey! we rename it to submitTask in JS)
```

This is why `submitFunction` more or less fits:
- it still starts with "submit" word - similar to "submitTask"
- it hints that function is one of the arguments, that will be converted to a task
