### ISSUE TITLE
expose lib-Content modify/update Media function in javascript api

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#8754]
Everytime metadata is changed on the FotoWare side, they change the image binary by writing the metadata into it.
There I need to update the binary on the Enonic side quite often.
Currently I have to use deleteAttachment and addAttachment, which does not update image metadata.

**Comment by sigdestad** [comment]
This functionality appears to be available in the Java layer, as it is already possible to upload new binaries to existing media, and metadata is automatically updated.
