### ISSUE TITLE
Changing elasticsearch cluster.name will "wipe" XP index

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#8802]
Well it wont wipe the index, but it will change the index location on disk, so it looks like all data is lost.

Not much we can do about this in XP7 but going forward, you should not be able to "wipe" XP by changing 1 config parameter.

**Comment by rymsha** [comment]
There are many of such "destructive" parameters. `xp.home`, `path.data`,  blobstore `basedir`
`path.repo` and `snapshots.dir` change can be very annoying.
ah, and don't forget about  `rm -rf .` 

BTW is inherited behavior from Elasticsearch and there is not much (if at all) we can do.

**Comment by sigdestad** [comment]
This was surprising to me that cluster name has anything to do with the indexes? How are these related?

**Comment by rymsha** [comment]
Elasticsearch calls folder with indices after cluster name.

**Comment by sigdestad** [comment]
Interesting

**Comment by gbbirkisson** [comment]
It might be worth documenting this. It is not trivial in this case to know why the XP index is gone, as oppose to if you change `path.repo`.
