### ISSUE TITLE
You can only have one "set" of should filters

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#8887]
https://developer.enonic.com/docs/xp/stable/storage/filters#boolean

Since boolean is an object, not an array, it's not possible to have more than one "set" of should filters.

That's at least how the doc looks.

It would be cool if this was possible:

```
const filters = { // ((a or b) AND (c or d))
	boolean: [
		{
			should: [{
				exists: {
					field: 'a'
				}
			},{ // or
				exists: {
					field: 'b'
				}
			}]
		}, // and
		{
			should: [{
				exists: {
					field: 'c'
				}
			},{ // or
				exists: {
					field: 'd'
				}
			}]
		}
	]
};
```

**Comment by rymsha** [comment]
Have your tried to wrap two `should` into `must` ?

**Comment by ComLock** [comment]
@rymsha I'm not certain what you are saying, you cannot nest one boolean inside another...?

**Comment by rymsha** [comment]
according to docs boolean filter is a filter. Are you saying that documentation is incorrect, and one cannot chain filters?

**Comment by ComLock** [comment]
Well, since there are no examples of such, if it's even possible, it has thus far escaped my mind... so I don't believe it before I've tried it. And if it does work, chances are it gone past other people too...

**Comment by ComLock** [comment]
And if it's possible, there are more changes to turn slow queries into quick nested filters...

**Comment by rymsha** [comment]
It is possible to do by by chaining filters
If documentation is not clear, make a PR with clarifications in https://github.com/enonic/doc-xp repository

**Comment by ComLock** [comment]
Works: https://github.com/ComLock/enonic-xp-app-test-should/blob/main/src/main/resources/main.es#L124
