### ISSUE TITLE
NPE after deleting a content type and trying to fetch the list

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#8901]
In **Content Studio 3.3** with the ability to control List title using expressions, it is possible to set Content Studio into a mode with eternal looping error messages. You don't need to use List title expressions anywhere, you just need to create a content using your app, then delete that content type from the app. Content Studio is after that unable to render this content and any content after it in the tree. It will spawn error messages in the log about null pointer exception, forever. Also the red little toast message bar will try and show it self every second, empty.

Let me know if more info is needed =)

**Comment by rymsha** [comment]
There is no check for contentType existence in ContentListTitleResolver
Fix is to fallback to displayName when contentType is currently unknown.
