### ISSUE TITLE
Layer Inheritance sometimes get significantly delayed

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#8954]
For a customer with a fairly large dataset 20+ layers, 4 levels deep, ca 5k items per layer - inheritance is "randomly" slow or delayed. Customer has reported that it may take several hours for the items to sync across all layers:

I have been able to reproduce the following quite easily:
* Create content in a parent layer -> immediately inherited to all child layers
* Delete the same content -> Only immediately deleted in direct child layer, level 2 child items only removed after a few minutes.

Instance is single node, so this is not related to clustering problems

Suggested initial approach:
Provide access to customer instance to export and use customer data to setup a similar environment locally:
NB! There is a significant amount of binary data in the repos. Avoid exporting those.

PM me when you start looking at this for a demo and access

**Comment by rymsha** [comment]
A layer sync was done for entire tree structure in case of _any_ node deletion. Fixed by narrowing sync only to deleted subtree
