### ISSUE TITLE
Need date/time stamp of when an item was archived 

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8974]
We now use `content/resolveByIds` to resolve items to be displayed in the Archive UI, whose response is obviously missing the date/time stamp of when the item was archived. 

So we either need a separate API that will return this field for a specified id (which is probably too much overhead for getting one value), or - better - archive's own `archive/resolveByIds` where this field is present.

Another option is adding it to the response of `archive/list`.

**Comment by vbradnitski** [comment]
second option implemented in #8970
