### ISSUE TITLE
Extend lib-auth to include user authentication 

### ISSUE THREAD

**Issue by poi33** [enonic/xp#8987]
Currently its not possible to check if a user has a valid username + password without loging into the system. 

Can we create a javascript function that will do this? 

The use case for it is 2step authenticaton of users, where they first have to send in a username and password, then a second step to login to the system.

**Comment by rymsha** [comment]
We can trivially implement it extending login function with `scope=NONE` 
in this scope login either fails with exception or succeeds (bud does not persist the login fact anyhow)

**Comment by sigdestad** [comment]
That is a quickfix we can live with. Can you make sure this gets into XP 7.8 @rymsha ?
