### ISSUE TITLE
Investigate how to properly to work with numbers in GraalJS

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/xp#9011]
Investigate how to properly to work with numbers in GraalVM JS

**Comment by rymsha** [comment]
https://github.com/oracle/graaljs/issues/234

**Comment by rymsha** [comment]
With a simple code
```
if ( source.isNumber() )
        {
            return source.as( Number.class );
        }
```

we allow Graal to decide how to interpret the Number
- if it was Java type - it will be kept as is
- if it was from JS - it will be either `Integer` or `Double`
