### ISSUE TITLE
Increase timeout for initialization

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#9013]
When operations use manual procedure to start cluster nodes, it is often not sufficient to have a 30 seconds system repository bootstrap timeout.

- [ ] Make it configurable
- [ ] Make it longer by default

**Comment by rymsha** [comment]
@gbbirkisson what would be a good value when you use k8s readiness check?

**Comment by gbbirkisson** [comment]
That is hard to say. Depends on the amount of resources the pod gets.

**Comment by rymsha** [comment]
Currently, it is 30 seconds.
There are possibilities we can increase the default value to several minutes.
Would it be problematic?

**Comment by gbbirkisson** [comment]
No I dont think it would be a problem. Are you going to make this number configurable?
