### ISSUE TITLE
index for fulltext per language

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#9025]
Let's say we have a property named "title" with valueType: String.

We have two nodes:
In node A the title property is norwegian, so it gets stemmed to title._stemmed_no
In node B the title property is english, so it gets stemmed to title._stemmed_en

Which is all cool because now I can execute stemmed queries which will only find hits in the language I want.

The "problem" is that stemming gives worse results than fulltext.
For instance both "biler" and "billig" has the stem "bil" so doing a stemmed search gives poor results.

What I want is an index for fulltext per language too. (ngram too?)
title._fulltext_no
title._fulltext_en

Thus I can execute a fulltext('billig','no') which will only search the norwegian index. 

This might be useful when dealing with synonyms too.

**Comment by sigdestad** [comment]
For this you can simply do AND language = "no" afaik?

**Comment by ComLock** [comment]
In our case, yes, if we assume all fields within a node have the same language. So that should work in most cases.
As such the added complexity of support this might not be worth it.

**Comment by sigdestad** [comment]
Closing issue
