### ISSUE TITLE
Test JS framework differs from prod

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#9039]
When JS code is executed in production, some of the ES6+ features, default function parameters `(foo = 'bar') => {}` work. But they are not supported in JS that is passed to `ScriptTestSupport.runScript()`.
Features like `let`, `const`, `() => {}` works fine both in production and during tests.

**Comment by anatol-sialitski** [comment]
JFYI: No issue on GraalJS. I've tested it on Graal JS and it works fine.

**Comment by rymsha** [comment]
`AssignSymbols.enterBlock` has a line of code
```
449                // Don't bother descending into it, it must be empty anyway.
450                assert block.getStatements().isEmpty();
```

JVM `-ea` is added by gradle when tests are run. (other test executors also turn assertions on)
When XP is run, this flag is absent thus code on line 450 never executes.


Known fact: Nashorn does not fully support ES6 syntax.
In order for your code to work with and without `-ea` flag use https://babeljs.io/
