### ISSUE TITLE
Configuration to prevent default content repository to be created

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#9062]
Default content repository gets deprecated.
We plan to remove default content repository in XP 8.
It should be possible to disable automatic creation of default content repository on XP startup.

**Comment by rymsha** [comment]
If default repository does not exist, XP does not work AT ALL.
Current bumper is `.../status`  endpoint that needs default repository!

There are a few other places (Vacuum, Dump/Restore, DeleteRepositoryHandler) where existence of default repository is assumed

Also there are places where correct behavior for repositories is only guaranteed for default repository (for instance DeleteBranchHandler )

**Comment by sigdestad** [comment]
Ha, atleast this prooves it is good to solve this now rather than with xp8

**Comment by alansemenov** [comment]
How does that prove that fixing this in so many places now in a feature version is better than in XP8 when we are actually supposed to do structural changes?

**Comment by rymsha** [comment]
Default repository is an important part of XP 7.x We'll likely remove it in XP 8. But for now we'll disable it visually only:
https://github.com/enonic/app-contentstudio/issues/3655
