### ISSUE TITLE
Filter causes duplication of query parameters

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#9100]
`site.xml`:
```XML
  <mappings>
    <mapping filter="/site/mappings/filter.js">
      <pattern>/filter</pattern>
    </mapping>
  </mappings>
</site>
```

`/site/mappings/filter.js`:
```Javascript
exports.filter = function (req, next) {
    log.info(JSON.stringify(req.params, null, 4));
    return next(req);
};
```

A part added to the default site's template:
```Javascript
exports.get = function (req, next) {
    log.info(JSON.stringify(req.params, null, 4));
    return {
        contentType: 'text/html',
        body: body
    };
};
```

This setup will output the following in the XP log for url `http://localhost:8080/admin/site/preview/default/draft/features/filter?q=1`:

```
16:18:35.280 INFO  com.enonic.app.features - (/site/mappings/filter.js) {
    "q": "1"
}
16:18:35.289 INFO  com.enonic.app.features - (/site/parts/my-part/my-part.js) {
    "q": [
        "1",
        "1"
    ]
}
```

After going through the filter, `q` parameter becomes an array with duplicated value.

**Comment by rymsha** [comment]
It appeared after #8210 (although, it is not a regression)

Interestingly enough we are not the first who face such issue https://github.com/eclipse/jetty.project/issues/2074

**Comment by rymsha** [comment]
prams from filter result are appended to params with the same name - that is causing bug in cases where filter uses `next` as a return value.

To do a fix we decided to changes the behavior:
prams with the same name in filter result _replace_ params in the original request.
