### ISSUE TITLE
Problems giving external users access to a single content item in XP

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#9112]
To reproduce:

1 - create a vhost pointing to a site/master branch
2 - Remove "everyone can read" permissions from the site and entire tree
3 - Add "everyone can read" permissions to a subset of the site (i.e. a page)
4 - Publish everything

Going directly to the content now gives a 404 (using the site's error handler at least).
Expected behaviour, page should render - showing at least the content user has access to.

Giving everyone read access to the site (just site content) will make the page work - so for some reason, not having access to the main site content seems to prevent the leaf content from being delivered.

Also (possibly related) - in the scenario above, I  ave a mapping /api at the site root. This also returned 404 when user did not have read-permissions for the site itself. Expected behaviour - user should have read access to mapping regardless of content/site permissions.

**Comment by ellenbakksjo** [comment]
Hi, do you know approximately when this issue will be fixed? We are considering whether we should implement a workaround in the meantime.

**Comment by rymsha** [comment]
There is no ETA yet. You could open Support Case if you need more help with this issue.
