### ISSUE TITLE
OccurrenceValidator: validation error property path is build incorrectly

### ISSUE THREAD

**Issue by ashklianko** [enonic/xp#9190]
On this line https://github.com/enonic/xp/blob/ed5c3412c3875b410061c1e6f9d966cb500652fa/modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/validate/OccurrenceValidator.java#L143
in case when parent data set is empty we use form item's path as parent path, that leads to a situation on next line that validation property path is build two times from property name. 
This to be replaced with 
`.orElseGet( () -> PropertyPath.from( formItem.getPath().getParent().toString() ) )`

**Comment by rymsha** [comment]
essential for #9055, but was not important before, so tests were never verifying that aspect
