### ISSUE TITLE
Unexpected nameRequired validation message

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#9202]
To reproduce:
1. Create under the Features site a new content of type "Text Line" which has a required input
2. Fill out display name (note that name/path is auto-generated)
3. Save
4. Open Data Toolbox and check the content JSON

There are two errors in `validationErrors`: one is `system:cms.occurrencesInvalid` (correct, since the required input is empty) and another is `system:cms.validation.nameRequired` which is incorrect since name is not empty. If you now fill out the required input and save again, then **both** messages will be gone.

<img width="656" alt="Screenshot 2021-11-10 at 16 29 34" src="https://user-images.githubusercontent.com/11612490/141148934-c73c9814-c1db-4cdf-848b-d15cadae5423.png">

**Comment by rymsha** [comment]
Good catch. It only happens when there is at least one extra validation error, because `RenameContentCommand` does not bother updating invalid state to another invalid state
```
        if ( content.isValid() == validationErrors.hasErrors() )
        {
            return updateValidState( content );
        }
```
