### ISSUE TITLE
Focal point no longer works in image service

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#9244]
Requesting image URLs using the Portal Lib 7.6 and 7.7 doesn't return image with focal point within the cropping section after upgrading to *XP 7.8 B1*. Going back to XP 7.7.3 solves the issue.

* Upload a giraffe image
* Set focal point on the head
* Save
* Use this image somewhere were the controller code uses `imageUrl({ scale: 'block(300,100)' })` or similar, which should force cropping.

Result: You get the foot of the giraffe, not even the middle point.
Expected: Get the head since you added a focal point there.

![Skjermbilde 2021-11-29 kl  11 30 03](https://user-images.githubusercontent.com/1465598/143852484-607e64f5-b4d5-42fd-a3a3-c5751b4152c8.png)
![Skjermbilde 2021-11-29 kl  11 30 29](https://user-images.githubusercontent.com/1465598/143852493-b9ab46ae-7966-4849-b64a-049d74991582.png)

**Comment by poi33** [comment]
@Bellfalasch i see we are still using giraffes to test focal point 🦒

**Comment by Bellfalasch** [comment]
> @Bellfalasch i see we are still using giraffes to test focal point 🦒

Same pic as in good old 101 training. Did it just for this issue ❤️

**Comment by tajakobsen** [comment]
I can confirm this issue.

**Comment by rymsha** [comment]
it is a regression of #8851

**Comment by alansemenov** [comment]
@Bellfalasch @tajakobsen the fix has been issued in XP 7.8.0-B3. can you check that behaviour is back to normal now?

**Comment by Bellfalasch** [comment]
@alansemenov Looks like it works fine now. Just tried it on a few photos and some `block` scaling. Using B3 of XP, but still on B1 for CS but I guess CS doesn't intercept anything here.

**Comment by tajakobsen** [comment]
Hey @alansemenov . It works in frontend and edit-preview now, but not in tree-view-preview.

**Comment by alansemenov** [comment]
Hmm, are you sure it's not cached somehow? Did you try in a new instance of XP?

**Comment by tajakobsen** [comment]
I tested a bit more, and it appears to be caching of the old image crop that was the problem.

So ignore the comment above.
