### ISSUE TITLE
Add function updateMedia

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#9261]
In the FotoWare integration, when I receive a assetModified webhook, in which the asset has been renamed, I have to rename the attachment in Enonic. The only way I've been able to do this now is in 3 operations.

Remove Attachment
Add Attachment
Modify content and update data.media.attachment
This works but creates 3 versions, of which 2 are "invalid"

Instead a renameMedia function which only creates a single version would be better, but then again it would be even better if I could renameMedia and update other content data in a single function call updateMedia.

So if createContent and modifyContent could do everything regarding media and attachments in addition to what it does not, that would be another option.

**Comment by rymsha** [comment]
Isn't it a duplicate of #8754 ?

**Comment by sigdestad** [comment]
Yes, but in addition - it mentions "rename". But, that is maybe a separate task anyway?

**Comment by rymsha** [comment]
Duplicates #8754
