### ISSUE TITLE
Do not store binaryReference together with blobKey

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#9262]
It should be enough to modify content and change data.media.attachment and attachments[filename]. But xp content studio, data toolbox etc uses the binaryReference string rather than the blobKey when downloading the image.

There should be no need for binaryReference to be stored or used for anything?

**Comment by rymsha** [comment]
BinaryReference decouples internal blob storage (and sha1 as a key) from node API. 
Yes, this decupling is broken in Attachment/Image service, but not severely.

Technically BinaryReference  allows to have two distinct attachments with different names, but same content. It could have been done differently, but this is how it is.
