### ISSUE TITLE
Task api submitNamed fails

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#9266]
Although this function is deprecated, it is still in use in some places. It is calling a method on the bean that does not exist:

https://github.com/enonic/xp/blob/a457a29a59ce8ab1e61f6d0468984f2263cde2cc/modules/lib/lib-task/src/main/resources/lib/xp/task.js#L110

**Comment by vbradnitski** [comment]
and one more:
https://github.com/enonic/xp/blob/a457a29a59ce8ab1e61f6d0468984f2263cde2cc/modules/lib/lib-task/src/main/resources/lib/xp/task.js#L58
