### ISSUE TITLE
portal-lib processHtml Does not support pixel density

### ISSUE THREAD

**Issue by poi33** [enonic/xp#9289]
Srcset

One or more strings separated by commas, indicating possible image sources for the user agent to use. Each string is composed of:
  1. A URL to an image
  2. Optionally, whitespace followed by one of:
    - A width descriptor (a positive integer directly followed by w). The width descriptor is divided by the source size given in the sizes attribute to calculate the effective pixel density.
    - A pixel density descriptor (a positive floating point number directly followed by x).

We only support widths so its not possible to get the images to render properly on devices with dpr (display pixel ratio) of more then 1x.

**Comment by rymsha** [comment]
According to 
https://ericportis.com/posts/2014/srcset-sizes/ x-desciptors are not needed. `sizes` are simply  superior.

**Comment by rymsha** [comment]
https://techblog.holidaycheck.com/post/2017/12/22/responsive-images-srcset-and-sizes it called  antipatten even

**Comment by sigdestad** [comment]
Yup, browser will determine optimal image based on its own knowledge of dpr, bandwith etc. Devs do have to provide enough sizes though.
