### ISSUE TITLE
Content Api modify() removes First Published

### ISSUE THREAD

**Issue by ktriekp** [enonic/xp#9291]
`contentLib.modify` removes `publish.first` from node, `publish.from` remains the same 

```
function editor(c) {
    c.displayName = 'Modified';
    c.language = 'en';
    c.data.myCheckbox = false;
    return c;
}

// Modify content by path
var result = contentLib.modify({
    key: '/a/b/mycontent',
    editor: editor
});
```

I get the same result when explicitly specifying the `publish.first`
```
function editor(c) {
    c.displayName = 'Modified';
    c.language = 'en';
    c.data.myCheckbox = false;
    c.publish.first = "2016-11-03T10:01:34Z";
    return c;
}
```
---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: bbfa3acb2d6af5413366d9e3c8974343780cf346
* Document: Content library
* Document path: /developer/docs/xp/stable/api/lib-content

**Comment by alansemenov** [comment]
@ktriekp what version of XP are you on? we couldn't reproduce it in XP 7.8 at least.  if you are still experiencing this issue, try removing the line that modifies `data.myCheckbox` and see if that makes a difference.

**Comment by ktriekp** [comment]
We are using version 7.6. 
Thank you @alansemenov for testing this out. I will try this again when we upgrade to 7.8

**Comment by vbradnitski** [comment]
@ktriekp Hi, app have to be rebuilt with a new xp version as well, the bug was in the content lib.
