### ISSUE TITLE
Image component rendering causes 404 page if referenced image is not available

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#9301]
Customer struggled with a front page showing 404, even if everything seemed normal - and the page was published. It turned out the error was caused by the image component (no info in logs etc). The linked image had (due to a different bug) wrong permissions, and was thus not accessible from the live front-end.

Solution: Image component must be able to handle "null" for the referenced image "silently" by not rendering the image. It should not fail.

Also investigate how/why the page returned 404? Can a part override the errorcode of the entire page? Should this even be possible? It was hard to debug and figure out this one.

**Comment by rymsha** [comment]
Isn't Image component deprecated?

**Comment by sigdestad** [comment]
Yes, but still in use by many. This should be a very simple "if null" check that we seem to be missing now.

**Comment by alansemenov** [comment]
@rymsha wouldn't this be solved after your changes in rendering error handling?

**Comment by rymsha** [comment]
No.
