### ISSUE TITLE
node.connect doesn't throw error on non-existing repo

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#9328]
```
import {connect} from '/lib/xp/node';
const connection = connect({
  branch: 'master',
  repoId:'com.non.existant'
}); // No error!!!
log.info('connection:%s', connection);
const queryRes = connection.query({
  query:''
}); // com.enonic.xp.repository.RepositoryNotFoundException: Repository with id [com.non.existant] not found
log.info('queryRes:%s', queryRes);
```

The error only appears when executing functions on the connection...

**Comment by ComLock** [comment]
principals probably plays some role.

connection is an object with functions, executing those functions fail.

**Comment by rymsha** [comment]
Why is this an issue? Is there any docs that say - exception should be thrown?

**Comment by alansemenov** [comment]
No, but it would make sense if there was some kind of indication that connection failed. For example, if `connect` would return `null` instead of connection object.

**Comment by rymsha** [comment]
`connect` is a misleading name. It does create any connection: no state, no session, no id no need to disconnect.

Besides this would require a extra check inside connect - that is almost useless in most of the cases. And there is no guarantee either: repository can be removed at any time wile connection is "open", leading to `Repository with id [com.non.existant] not found` anyway.

There is a method to check repository existence: https://developer.enonic.com/docs/xp/stable/api/lib-repo#get
There is no need to mix them up.
