### ISSUE TITLE
Remove LICENCE_AL.txt

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#9334]
For some reason, the repo now contains both GPL and apache license, the Apache license must be removed asap.

**Comment by rymsha** [comment]
our libs are Apache licensed 
related to https://github.com/enonic/xp/issues/8124

**Comment by sigdestad** [comment]
We have added a text in our license description - saying that we are GPL with linking exception. 
So, maybe we should add the same in the top of NOTICE.txt, and then we can drop the Apache file?

https://developer.enonic.com/licensing
