### ISSUE TITLE
Rename `query` param to `searchString` for text DSL expressions

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#9389]

**Comment by rymsha** [comment]
we are changing 
```
lib_node.query({
			query: {fulltext : {query: "fisk"}}
		});
```
to 

```
lib_node.query({
			query: {fulltext : {searchString: "fisk"}}
		});
```

After a second thought I realize - it is a mistake: "searchString" may be confusing. There is nothing wrong with "query" as an argument for "fulltext". 

Instead 
`lib_node.query` should be `lib_node.search`, but I guess, it is too late to rename it.


What bothers me more is that we use "ngram" with query.

Also, this discussion revealed irregularities between "fulltext" and "stemmed".
