### ISSUE TITLE
Webapp controller portal.url throws URI out of scope

### ISSUE THREAD

**Issue by poi33** [enonic/xp#9423]
In my webapp controller i call:

`var startUrl = portalLib.url({ path: "/", type: "absolute" });` 

I expected it to return the URL to the site https://mywebapp.rocks. 
But instead it retruns an error page and throw an error "Uri out of scope"

**Comment by rymsha** [comment]
The correct way of calling this method from webapp would be 

`var startUrl = portalLib.url({ path: "/webapp/your.app.name.here", type: "absolute" });`

Recently XP was changed to throw an exception instead of generating a misleading url #8583.
