### ISSUE TITLE
Add lib-event type definitions

### ISSUE THREAD

**Issue by edloidas** [enonic/xp#9435]
* [x] Replace `event.js` with `event.ts`.
* [x] Add type definitions.
* [ ] Add tasks to transpile code to JS and generate DTS files.
* [ ] Make sure tests work with TS code (must be transpiled first).
* [ ] Move tests to TS. Leave a single test to test JS?
* [ ] Make sure transpiled JS code works.

**Comment by alansemenov** [comment]
> Move tests to TS. Leave a single test to test JS?

I'm not so sure about this one. I'd prefer keeping current tests but making sure they pass on transpiled JS. This will also make sure we haven't broken anything during migration.
