### ISSUE TITLE
Project app must be visible after data node has been changed

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#9504]
When data is changed directly via node API in system repository, project metadate is not updated

**Comment by vbradnitski** [comment]
The issue involves repository cache changing and most likely implementing a new one on the branch index level. To be discussed.

**Comment by rymsha** [comment]
Anything changed in a project via node level won't be immediately visible to to cache in ProjectService
The only way to properly change project settings is via ProjectService API
