### ISSUE TITLE
Modify workflow via JS API

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#9511]
It seems there's currently no way to modify workflow via Javascript API. It doesn't work when trying to do it via modify API

```Javascript
function editor(c) {
    c.workflow.state = 'READY';
    return c;
}

var result = contentLib.modify({
    key: '/a/b/mycontent',
    editor: editor
});
```

See discussion here: https://enonic-community.slack.com/archives/C73JLM8E7/p1652707523428529

**Comment by vbradnitski** [comment]
It looks like it's already implemented, following code works for me:


```
var contentLib = require('/lib/xp/content');

    function editor(c) {
        c.workflow.state = 'REJECTED';
        return c;
    }

    var result = contentLib.modify({
        key: '/features/js-libraries/mycontent',
        editor: editor
    });
```

 Context of a run should have permission to edit content.

**Comment by alansemenov** [comment]
Retested - works fine
