### ISSUE TITLE
Icon resolver won't respect admin vhost config

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#9647]
The problem described in https://github.com/enonic/app-contentstudio/issues/4250 has reappeared. The fix applied for that bug is in place, so this must be something else. [Support case](https://enonic.zendesk.com/agent/tickets/5483).

Vhost config:
```groovy
enabled = true

mapping.test.host = localhost
mapping.test.source = /xp/admin
mapping.test.target = /admin
mapping.test.idProvider.system = default
```

![Screenshot 2022-08-17 at 15 56 53](https://user-images.githubusercontent.com/11612490/185152739-cbea20ae-3d9a-49a4-8661-4fb8f0662336.png)

**Comment by rymsha** [comment]
It is a regression bug in 7.0.1 and there is a bug in CS fixed in 4.0.3
Both have similar effect, but different in nature.
