### ISSUE TITLE
node.delete events are not batched like node.published

### ISSUE THREAD

**Issue by pmi** [enonic/xp#9684]
Need to have both of them behave similar, preferably batched

**Comment by rymsha** [comment]
Three is no `node.unpublished` event.

And there can't be, as nodes are never unpublished - this is a ContentAPI concept. 

You can find list of events [here](https://github.com/enonic/xp/blob/master/modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/NodeEvents.java)

**Comment by pmi** [comment]
Correct, what I meant was node.deleted event from master branch, that happens when they are unpublished.

And the main issue here is delete events being not batched when unpublishing, in contrary to publish events.

**Comment by rymsha** [comment]
This is due to how delete is designed: 
node.push - accepts batch of ids - and CS sends all ids found for publishing
node.delete - accepts one id and CS requests deletes one-by one
#9707 could do better
