### ISSUE TITLE
multiRepoConnect with empty sources should throw an error

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#9695]
Yes ElasticSearch has some ways of doing things, and later have added options to avoid how they did things :)

So maybe we can do something "safer" than the default "broken" ElasticSearch behaviour?

**Comment by rymsha** [comment]
There is still one question remaining: is there any code that prevents multiRepoConnect  to search in branch indices?
If so, we may preserve current behavior for backwards compatibility, if not - than it is better to "be safe than sorry" - and empty sources should be rejected.

**Comment by rymsha** [comment]
duplicates #5418
