### ISSUE TITLE
publish.first may be greater than publish.from

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#9810]
`publish.first` may be greater than `publish.from` when scheduled content is re-published before the first publish date

**Comment by rymsha** [comment]
related to #5517

**Comment by sigdestad** [comment]
FYI! As the publish-from field is editable, this has been used as a functionality for some editors when importing existing content from a different system, and they want to control what is presented as the "published" date on their public site. Not ideal, but at least solves their problem.

With CS5, these settings will be "hidden" a bit by moving into the details panel

**Comment by rymsha** [comment]
So, technically `publish.from` and `publish.first` are only slightly related, and it is not a bug.

**Comment by sigdestad** [comment]
I guess it is not a bug per se, but certainly illogical. So a publish operation should probably change publish.first to be == publish.from in these scenarios.
