### ISSUE TITLE
Disallow anonymous access to draft branch

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#9853]
When accessed on `/site` endpoint, all unpublished (draft branch) content should not be accessible anonymously even if anonymous has read rights (public content).

New behavior should be revertable via configuration.

Reason:
Usually draft branch is for not-ready content only and exposing it to public is a mistake. Although when preview rendering is done separately (for instance by nextjs), draft content has to be exposed. Requiring authentication will make sure that "ANONYMOUS" User does not fall into role "EVERYONE", but only for draft content.

**Comment by rymsha** [comment]
Implementation: `/site` controller must check that Context's Principal is not Antonymous when content from draft branch is accessed.

**Comment by sigdestad** [comment]
This is not enough, it must actually check for access to the project.

**Comment by rymsha** [comment]
It may be required to limit draft branch access to the `admin` and `admin.login` roles.
