### ISSUE TITLE
Content library: wrong Permissions type

### ISSUE THREAD

**Issue by edloidas** [enonic/xp#9855]
[Permissions](https://github.com/enonic/xp/blob/master/modules/lib/lib-content/src/main/resources/lib/xp/content.ts#L1368-L1371) type looks like this:
```ts
export interface Permissions {
    inheritsPermissions: boolean;
    permissions?: Permission[];
}
```
Must be like this (see [example](https://github.com/enonic/xp/blob/master/modules/lib/lib-content/src/main/resources/lib/xp/examples/content/getPermissions.js#L19-L30) or [docs](https://developer.enonic.com/docs/xp/stable/api/lib-content#getpermissions)):
```ts
export interface Permissions {
    inheritsPermissions: boolean;
    permissions?: AccessControlEntry[];
}
```

**Comment by rymsha** [comment]
Am also not sure if permissions is optional
