### ISSUE TITLE
add java_opt to use system File Descriptor Limit value on MacOS

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#9932]
add `-XX:-MaxFDLimit` - to stop the Java VM from restricting the number of open files to 10240.

https://stackoverflow.com/questions/16451343/java-file-limit-on-osx-lower-than-in-bash

**Comment by rymsha** [comment]
@vbradnitski we need a bit of documentation, too

**Comment by rymsha** [comment]
We need to revert it. with `-XX:-MaxFDLimit` Java uses soft limit which is 256 on Mac. 

We may set ulimit to 65K https://www.elastic.co/guide/en/elasticsearch/reference/2.4/setup-configuration.html#file-descriptors but we should do it only on MacOS

**Comment by rymsha** [comment]
follow up is here #9938
