### ISSUE TITLE
Store app config on `/content` node

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#9947]
Instead of storing `siteConfig` in system repository, store them in `/content` same way as `siteConfig` is stored for site content

Primary goal is to make import/export to work the same way for entire content as it works of sites

**Comment by rymsha** [comment]
We need to decide how to make siteConfig available on master branch
- push `/content` with any other content publish
- push `/content` node immediately after change
- never push `/content` - switch to draft context to read siteConfig

Currently we prefer first option.
