### ISSUE TITLE
Unable to lib-schema.createSchema on bundled app without any descriptors

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#9981]
<img width="1698" alt="Screenshot 2023-01-23 at 12 12 03" src="https://user-images.githubusercontent.com/118847/214036496-33728b78-fded-432a-a629-e0095790cb67.png">

**Comment by rymsha** [comment]
This is an expected behavior. First `createVirtualApplication` must be called

**Comment by ComLock** [comment]
Why to we have the "augmented" type, if augmentation is not possible?

**Comment by rymsha** [comment]
It is possible. and it is documented https://developer.enonic.com/docs/xp/stable/apps
