### ISSUE TITLE
localTime queries don't work

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#9985]
![Screenshot 2023-01-24 at 10 19 28](https://user-images.githubusercontent.com/118847/214253991-4256a17c-3db7-417a-9d51-078a239ad8bc.png)

**Comment by rymsha** [comment]
Probably duplicate of #9970

**Comment by rymsha** [comment]
Are you sure this bug belongs to XP?

**Comment by ComLock** [comment]
I don't think it's a duplicate of #9970. After all numbers and colon doesn't have "lowercase" variants.

**Comment by ComLock** [comment]
No I'm not certain it's XP, but I've seen the same when using the node layer myself. But I think we landed on "time" NOT working but "localTime" should work. @anatol-sialitski  Maybe value type is not set correctly by lib-guillotine?

**Comment by ComLock** [comment]
https://developer.enonic.com/docs/xp/stable/storage/dsl#time

**Comment by vbradnitski** [comment]
`localTime` query "makes a search for a field indexed as 'string'" according to the docs. It doesn't make any indexed field searches. So you are looking for a string field named "createdTime" with different time strings. But it won't work, because the actual `createdTime` string value is something like: 
```
"createdtime": [
      "2023-01-24T11:15:53.421168Z"
    ] 
```

**Comment by ComLock** [comment]
Yeah I keep forgetting that. It just feels natural for me that when something contains a time, I could be able to query for the time, on any resolution/accuracy that I want. That's what I'm used to with SQL databases...

**Comment by ComLock** [comment]
I will close this as soon as I have a field indexed as time and a query on that field working.

**Comment by ComLock** [comment]
![Screenshot 2023-01-24 at 13 08 38](https://user-images.githubusercontent.com/118847/214287950-a8cc03ed-e857-4028-80e4-8017ef17f0d1.png)
